/** Original author-data proposal tests; no earned mission/source acceptance. */
import test from 'node:test';import assert from 'node:assert/strict';
import '../../my-3d2dge-agent.js';
import * as D from '../../proposals/brass-cutting.js';
import {createRailPath,createConsist,advanceConsist,validateCarSpecs} from '../../src/rail-foundation/rail-consist.js';
import {worldPoint,localPoint,length,sub,worldVector,makeFrame} from '../../src/rail-foundation/rigid-frame.js';
import {validateBodySupport,stepRailBody,worldContact,sweepMovingCover} from '../../src/rail-foundation/moving-support.js';
import {createGangwayPlatforms} from '../../src/rail-foundation/moving-gangways.js';
import {createTrainHuman,prepareTrainPose} from '../../src/train-native/rigs.js';
const E=globalThis.My3D2dge,P=(x=0,y=0,z=0)=>({x,y,z}),clone=v=>JSON.parse(JSON.stringify(v));
const original=await import('../rail-foundation/fixtures/brass-cutting-authoring.mjs');
const setup=cursor=>{const path=createRailPath(D.TRAIN_TRACK),state=createConsist(path,D.TRAIN_CARS,{cursor,speed:85}),motion=advanceConsist(path,D.TRAIN_CARS,state,.01,{},D.TRAIN_MOTION_PROPOSAL);return{path,state,motion};};
test('proposal preserves all car/crew IDs and masses while declaring matched36-unit rails/wheels and a rear cab',()=>{assert.deepEqual(D.TRAIN_CARS.map(c=>[c.id,c.mass]),original.TRAIN_CARS.map(c=>[c.id,c.mass]));assert.deepEqual(D.TRAIN_MOVING_CREW.map(c=>c.id),original.TRAIN_MOVING_CREW.map(c=>c.id));assert.equal(D.TRAIN_TRACK.gauge,36);assert.ok(D.TRAIN_CARS.every(c=>c.wheelY===18&&c.wheelAxles.every(x=>Number.isFinite(x)&&Math.abs(x)+c.wheelRadius<c.length/2)));const engine=D.TRAIN_CARS[0];assert.equal(engine.surfaces.find(s=>s.id==='cab-floor').bounds.max.x,-4);assert.equal(engine.cover.find(v=>v.id==='engine-boiler').bounds.min.x,-2);assert.ok(validateCarSpecs(D.TRAIN_CARS));});
test('all twelve original starting inhabitants retain one valid support and conservative solid clearance after the mirror',()=>{const {motion}=setup(1200),people=[...D.TRAIN_MOVING_CREW,...D.TRAIN_NEW_CAST.filter(a=>a.initialSupport).map(a=>({...a,...a.initialSupport}))];assert.equal(people.length,12);for(const a of people){const p=motion.platforms.find(p=>p.id===a.carId),body=new E.Body({...worldPoint(p.frame,a.local),r:9,height:53,onGround:true});body.support={carId:a.carId,surfaceId:a.surfaceId,local:clone(a.local),relativeVelocity:P()};assert.ok(validateBodySupport(body,motion.platforms),a.id);for(const c of p.cover){if(c.bounds.max.z<=a.local.z)continue;const overlapX=a.local.x+9>c.bounds.min.x&&a.local.x-9<c.bounds.max.x,overlapY=a.local.y+9>c.bounds.min.y&&a.local.y-9<c.bounds.max.y,overlapZ=a.local.z+53>c.bounds.min.z&&a.local.z<c.bounds.max.z;assert.ok(!(overlapX&&overlapY&&overlapZ),`${a.id} does not begin inside ${c.id}`);}}});
test('operator foot approaches are distinct supported positions with reachable actual native hand/tool targets',()=>{const {motion}=setup(1200);for(const [id,approach]of Object.entries(D.TRAIN_OPERATOR_APPROACHES)){const p=motion.platforms.find(p=>p.id===approach.carId),position=worldPoint(p.frame,approach.local),body={id:'mara',...position,hp:100,onGround:true,r:9,facing:Math.atan2(p.frame.x.y,p.frame.x.x)+approach.facingLocal,support:{carId:p.id,surfaceId:approach.surfaceId,local:clone(approach.local),relativeVelocity:P()}};assert.ok(validateBodySupport(body,motion.platforms),id);const target=worldContact(p,id),h=createTrainHuman(E,body);h.rig.update(0,{...body,z:0});const pose=prepareTrainPose(E,h,body,p,{contacts:[{side:approach.hand,target,kind:id}]});const hand=pose.diagnostics.find(c=>c.kind===id);assert.ok(hand.reachable,`${id} is physically in native arm reach`);assert.ok(hand.error<1e-5);assert.ok(length(sub(position,target))>1,'foot approach is not the hand target');pose.restore();}});
test('eighteen moving gangway/pad supports derive from both real cars and span their actual deck joins',()=>{const {motion}=setup(2400),bridges=createGangwayPlatforms(motion.platforms,D.TRAIN_GANGWAYS);assert.equal(bridges.length,18);assert.equal(new Set(bridges.map(p=>p.id)).size,18);for(const def of D.TRAIN_GANGWAYS){const bridge=bridges.find(p=>p.id===def.id);for(const ref of[def.forward,def.rear]){const parent=motion.platforms.find(p=>p.id===ref.carId),anchor=worldContact(parent,ref.contactId),local=localPoint(bridge.frame,anchor);assert.ok(Math.abs(local.z)<1e-5);assert.ok(local.x>bridge.surfaces[0].bounds.min.x+3&&local.x<bridge.surfaces[0].bounds.max.x-3,'lap has positive foot overlap');}assert.notDeepEqual(bridge.previousFrame.origin,bridge.frame.origin,'the bridge itself moves with the train');}});
test('same-level car transfer traverses actual moving laps/pads under native walking with no car-selection shortcut',()=>{const path=createRailPath(D.TRAIN_TRACK);let state=createConsist(path,D.TRAIN_CARS,{cursor:1200,speed:85});const seed=advanceConsist(path,D.TRAIN_CARS,state,0),p=seed.platforms.find(p=>p.id==='morrow-stores-coach'),local=P(55,0,26),body=new E.Body({...worldPoint(p.frame,local),r:9,height:53,onGround:true});body.support={carId:p.id,surfaceId:'stores-floor',local:clone(local),relativeVelocity:P()};const seen=new Set();for(let n=0;n<70;n++){const motion=advanceConsist(path,D.TRAIN_CARS,state,.01,{},D.TRAIN_MOTION_PROPOSAL),bridges=createGangwayPlatforms(motion.platforms,D.TRAIN_GANGWAYS),all=[...motion.platforms,...bridges],forward=worldVector(motion.platforms[0].frame,P(60));stepRailBody(body,all,.01,{relativeVelocity:forward,inputSpace:'world'});seen.add(body.support?.carId||'air');state=motion.state;if(body.support?.carId==='morrow-tool-wagon')break;}assert.ok([...seen].some(id=>id.startsWith('morrow-gangway-4')),'real bridge support is observed');assert.equal(body.support?.carId,'morrow-tool-wagon');});
test('a physically unattainable gap rejects rather than moving deck contacts together',()=>{const {motion}=setup(1200),defs=clone(D.TRAIN_GANGWAYS);defs[0].maxSpan=1;assert.throws(()=>createGangwayPlatforms(motion.platforms,defs),/span/);});

test('operator foot approaches retain real native reach throughout idle breathing and clear the actual cab solids',()=>{
 const {motion}=setup(1200);
 for(const [id,a]of Object.entries(D.TRAIN_OPERATOR_APPROACHES)){
  const p=motion.platforms.find(p=>p.id===a.carId),body={id:'mara',...worldPoint(p.frame,a.local),hp:100,onGround:true,r:9,facing:Math.atan2(p.frame.x.y,p.frame.x.x)+a.facingLocal,support:{carId:p.id,surfaceId:a.surfaceId,local:clone(a.local),relativeVelocity:P()}};
  assert.ok(validateBodySupport(body,motion.platforms),id);
  const b=p.surfaces.find(s=>s.id===a.surfaceId).bounds;assert.ok(a.local.x-9>=b.min.x&&a.local.x+9<=b.max.x&&a.local.y-9>=b.min.y&&a.local.y+9<=b.max.y,`${id} has full9-unit standing footprint`);
  for(const c of p.cover){const b=c.bounds,v=a.local;assert.ok(!(v.x+9>b.min.x&&v.x-9<b.max.x&&v.y+9>b.min.y&&v.y-9<b.max.y&&v.z+53>b.min.z&&v.z<b.max.z),`${id} clears ${c.id}`);}
  const target=worldContact(p,id),h=createTrainHuman(E,body);
  for(let phase=0;phase<=20;phase+=.25){h.rig.t=phase;h.rig.update(0,{...body,z:0});const pose=prepareTrainPose(E,h,body,p,{contacts:[{side:a.hand,target,kind:id}]});try{const hand=pose.diagnostics.find(c=>c.kind===id);assert.ok(hand.reachable&&hand.error<1e-5,`${id} reaches at idle phase ${phase}: ${hand.error}`);for(const foot of pose.diagnostics.filter(c=>c.kind==='deck-foot')){const v=localPoint(p.frame,foot.hit);assert.ok(v.x>=b.min.x-1e-6&&v.x<=b.max.x+1e-6&&v.y>=b.min.y-1e-6&&v.y<=b.max.y+1e-6,`${id} native foot stays on deck at ${phase}`);}}finally{pose.restore();}}
 }
});
test('the former cab-brake foot point exposes the actual idle reach regression without moving its hand target',()=>{
 const {motion}=setup(1200),p=motion.platforms.find(p=>p.id==='morrow-engine'),local=P(-40,12,32),body={id:'mara',...worldPoint(p.frame,local),hp:100,onGround:true,facing:Math.atan2(p.frame.x.y,p.frame.x.x)+Math.PI,support:{carId:p.id,surfaceId:'cab-floor',local,relativeVelocity:P()}},h=createTrainHuman(E,body);
 h.rig.t=.75;h.rig.update(0,{...body,z:0});const target=worldContact(p,'cab-brake'),pose=prepareTrainPose(E,h,body,p,{contacts:[{side:'R',target,kind:'cab-brake'}]});try{const hand=pose.diagnostics.find(c=>c.kind==='cab-brake');assert.equal(hand.reachable,false);assert.ok(hand.error>.04&&hand.error<.06);assert.deepEqual(p.contacts.find(c=>c.id==='cab-brake').local,P(-43,12,56));}finally{pose.restore();}
});

test('all twelve starting inhabitants stay on their actual moving surfaces through native accepted-step simulation',()=>{
 const path=createRailPath(D.TRAIN_TRACK);let state=createConsist(path,D.TRAIN_CARS,{cursor:2400,speed:85});const seed=advanceConsist(path,D.TRAIN_CARS,state,0),people=[...D.TRAIN_MOVING_CREW,...D.TRAIN_NEW_CAST.filter(a=>a.initialSupport).map(a=>({...a,...a.initialSupport}))],bodies=people.map(a=>{const p=seed.platforms.find(p=>p.id===a.carId),body=new E.Body({...worldPoint(p.frame,a.local),r:9,height:53,onGround:true});body.id=a.id;body.support={carId:a.carId,surfaceId:a.surfaceId,local:clone(a.local),relativeVelocity:P()};return body;});
 for(let step=0;step<12;step++){const m=advanceConsist(path,D.TRAIN_CARS,state,1/120,{},D.TRAIN_MOTION_PROPOSAL);for(const body of bodies){const result=stepRailBody(body,m.platforms,1/120,{relativeVelocity:P()});assert.equal(result.kind,'supported',body.id);assert.ok(validateBodySupport(body,m.platforms),body.id);}state=m.state;}
 assert.equal(new Set(bodies.map(b=>b.id)).size,12);
});

test('explicit native circular footprints fit a rotated20-unit lane while nearby actual wall intersections still block',()=>{
 const frame=makeFrame(P(),P(1,1)),box=(y0,y1)=>({min:P(-100,y0,0),max:P(100,y1,60)}),p={id:'rotated-lane',frame,previousFrame:frame,surfaces:[],cover:[{id:'left-wall',bounds:box(-13,-10),bodySolid:true,projectileSolid:true},{id:'right-wall',bounds:box(10,13),bodySolid:true,projectileSolid:true}]},from=worldPoint(frame,P(0,0,26.5)),clear=worldPoint(frame,P(1,0,26.5)),collision=worldPoint(frame,P(1,2,26.5));
 assert.ok(sweepMovingCover(from,clear,[p],.01,{radius:9,height:53,mode:'body'}),'the original conservative world-square remains available and wider in this rotation');
 assert.equal(sweepMovingCover(from,clear,[p],.01,{radius:9,height:53,mode:'body',footprint:'circle'}),null);
 const hit=sweepMovingCover(from,collision,[p],.01,{radius:9,height:53,mode:'body',footprint:'circle'});assert.equal(hit.volumeId,'right-wall');assert.ok(Math.abs(hit.u-.5)<1e-5,'actual circular footprint contacts the wall after one unit lateral motion');
 assert.throws(()=>sweepMovingCover(from,clear,[p],.01,{footprint:'unsupported'}),/shape/);
});

test('gangway pad/core laps hold a full18-unit standing footprint, and the former short lap exposes a real fall',()=>{
 for(const d of D.TRAIN_GANGWAYS)assert.ok(d.overlap+d.padOut>=20,'minimum pad/core overlap at maxSpan leaves18-unit footprint plus2unit travel interval');
 const path=createRailPath(D.TRAIN_TRACK);let state=createConsist(path,D.TRAIN_CARS,{cursor:1200,speed:85}),seed=advanceConsist(path,D.TRAIN_CARS,state,0),p=seed.platforms.find(p=>p.id==='morrow-stores-coach'),local=P(55,0,26),body=new E.Body({...worldPoint(p.frame,local),r:9,height:53,onGround:true});body.support={carId:p.id,surfaceId:'stores-floor',local,relativeVelocity:P()};const short=clone(D.TRAIN_GANGWAYS);for(const d of short)d.overlap=6;
 for(let n=0;n<70;n++){const m=advanceConsist(path,D.TRAIN_CARS,state,.01,{},D.TRAIN_MOTION_PROPOSAL),all=[...m.platforms,...createGangwayPlatforms(m.platforms,short)];stepRailBody(body,all,.01,{relativeVelocity:worldVector(m.platforms[0].frame,P(60)),inputSpace:'world'});state=m.state;}
 assert.equal(body.support,null,'r9 cannot stay on the former narrow lap');assert.ok(body.z<25,'native gravity records actual loss of deck support');
});
