/** Pure finite-volume and explicitly STAGED native hinge fixtures.
 * No inventory, mission, handoff, fuse, Save or earned placement acceptance. */
import test from 'node:test';import assert from 'node:assert/strict';import '../../my-3d2dge-agent.js';
import {makeFrame,worldPoint,localPoint,worldVector,sub,dot} from '../../src/rail-foundation/rigid-frame.js';
import {createHeldBox,compileHeldSolidSet,heldBoxContacts,createHeldBoxMotion,sampleHeldBoxMotion,sweepHeldBox,compileHeldWorld,heldBoxWorldContacts,validateHeldWorldSnapshot} from '../../src/train-held-volume.js';
import {createTrainTerrain,createWorldQuery,worldCoverSolids,raycastWorldCoverAt} from '../../src/train-terrain.js';
import {createTrainConsist,trainGeometry} from '../../src/train-motion.js';
import {TRAIN_TRACK,TRAIN_CARS,TRAIN_GANGWAYS,TRAIN_MOTION_PROPOSAL,TRAIN_CHARGE_APPROACHES} from '../../content/campaign/brass-cutting.js';
import {TRAIN_CHARGE_HALF_EXTENTS} from '../../content/campaign/train-equipment.js';
import {createRailPath,compileCarSpecs,createConsist,advanceConsist} from '../../src/rail-foundation/rail-consist.js';
import {createAcceptedStepContext} from '../../src/rail-foundation/accepted-step-context.js';
import {createGangwayPlatforms} from '../../src/rail-foundation/moving-gangways.js';
import {stepRailBody,validateBodySupport,worldContact} from '../../src/rail-foundation/moving-support.js';
import {createTrainHuman,prepareTrainPose,rigWorldPoint} from '../../src/train-native/rigs.js';
const E=My3D2dge,P=(x=0,y=0,z=0)=>({x,y,z}),F=(p=P(),yaw=0)=>makeFrame(p,P(Math.cos(yaw),Math.sin(yaw),0)),clone=v=>JSON.parse(JSON.stringify(v)),faces=[[0,3,2,1],[4,5,6,7],[0,1,5,4],[1,2,6,5],[2,3,7,6],[3,0,4,7]];
function solid(id,a,b){return{id,vertices:[P(a.x,a.y,a.z),P(b.x,a.y,a.z),P(b.x,b.y,a.z),P(a.x,b.y,a.z),P(a.x,a.y,b.z),P(b.x,a.y,b.z),P(b.x,b.y,b.z),P(a.x,b.y,b.z)],faces};}
const box=(p=P(),h=P(1,1,1),yaw=0,id='held')=>createHeldBox({id,frame:F(p,yaw),halfExtents:h}),set=s=>compileHeldSolidSet(s,{id:'explicit-component-fixture'});
test('finite SAT distinguishes1e-6 gap, tangency and real penetration without resizing',()=>{const s=set([solid('wall',P(0,-5,-5),P(1,5,5))]);assert.equal(heldBoxContacts(box(P(-1.000001)),s).length,0);const touch=heldBoxContacts(box(P(-1)),s);assert.equal(touch.length,1);assert.equal(touch[0].interiorOverlap,false);const inside=heldBoxContacts(box(P(-.999999)),s);assert.equal(inside.length,1);assert.equal(inside[0].interiorOverlap,true);assert.ok(inside[0].penetration>9e-7);assert.ok(Object.isFrozen(touch[0].axis));assert.throws(()=>{touch[0].axis.x=0;});});
test('thin wall crossed only between safe endpoints blocks the whole translating box',()=>{const s=set([solid('thin',P(0,-3,-3),P(.00001,3,3))]),a=box(P(-4)),b=box(P(4)),m=createHeldBoxMotion(a,b);assert.equal(heldBoxContacts(a,s).length,0);assert.equal(heldBoxContacts(b,s).length,0);const hit=sweepHeldBox(m,s);assert.equal(hit.clear,false);assert.equal(hit.solidId,'thin');assert.ok(Math.abs(hit.interval[0]-.375)<1e-6);});
test('constant-frame sweep can certify no interior while retaining exact endpoint touch',()=>{const s=set([solid('door',P(0,-4,-4),P(1,4,4))]),m=createHeldBoxMotion(box(P(-4)),box(P(-1)));assert.equal(sweepHeldBox(m,s).clear,false);assert.equal(sweepHeldBox(m,s,{contactMode:'interior'}).clear,true);assert.equal(heldBoxContacts(m.to,s)[0].interiorOverlap,false);});
test('edge-cross axes reject diagonally separated corners at multiple headings',()=>{for(let n=0;n<8;n++){const angle=n*Math.PI/4,frame=F(P(100,200,30),angle),h=P(2,3,6),a=createHeldBox({id:'held',frame,halfExtents:h}),raw=solid('corner',P(3,4,-1),P(4,5,1));raw.vertices=raw.vertices.map(p=>worldPoint(frame,p));assert.equal(heldBoxContacts(a,set([raw])).length,0);raw.vertices=solid('corner',P(1,2,-1),P(4,5,1)).vertices.map(p=>worldPoint(frame,p));assert.equal(heldBoxContacts(a,set([raw]))[0].interiorOverlap,true);}});
test('stationary-centre rotation catches a maximal corner between safe endpoint angles',()=>{const s=set([solid('angular-panel',P(2.15,-.02,-1),P(2.16,.02,1))]),a=box(P(),P(2,1,.5),-Math.PI/4),b=box(P(),P(2,1,.5),Math.PI/4),m=createHeldBoxMotion(a,b);assert.equal(heldBoxContacts(a,s).length,0);assert.equal(heldBoxContacts(b,s).length,0);const q=sweepHeldBox(m,s);assert.equal(q.clear,false);assert.equal(q.solidId,'angular-panel');assert.ok(q.interval[0]>0&&q.interval[1]<1);assert.ok(q.status==='contact'||q.status==='unresolved');});
test('large box with tiny rotation cannot lose its corner motion through acos rounding',()=>{const a=box(P(),P(100000,1,1),0),b=box(P(),P(100000,1,1),1e-9),m=createHeldBoxMotion(a,b),s=set([solid('tiny-angle-panel',P(99999,.00004,1.00001),P(100001,.00006,2))]);const q=sweepHeldBox(m,s);assert.equal(typeof q.clear,'boolean');const wall=set([solid('tiny-angle-real',P(99999,1.00004,-.2),P(100001,1.00006,.2))]);assert.equal(heldBoxContacts(a,wall).length,0);assert.equal(sweepHeldBox(m,wall).clear,false);});
test('simultaneous translation and rotation, and exhausted proof budget, never silently clear',()=>{const s=set([solid('edge',P(-.02,-.02,-2),P(.02,.02,2))]),m=createHeldBoxMotion(box(P(-4,0,0),P(2,.1,.5),-.7),box(P(4,0,0),P(2,.1,.5),.7));assert.equal(sweepHeldBox(m,s).clear,false);const limited=sweepHeldBox(m,s,{maxIntervals:1});assert.equal(limited.clear,false);assert.equal(limited.status,'unresolved');});
test('complete convex geometry retains triangulated caps and tapered lower footprints',()=>{const tri=solid('split',P(0,0,0),P(10,10,10));tri.faces=[...faces.map(f=>[...f])];tri.faces[1]=[4,5,6];tri.faces.push([4,6,7]);const s=set([tri]);assert.equal(heldBoxContacts(box(P(-.999999,8,5)),s)[0].interiorOverlap,true);const taper=solid('taper',P(0,0,0),P(10,10,100));taper.vertices[0].x=-.000002;taper.vertices[3].x=-.000002;assert.equal(heldBoxContacts(box(P(-.999999,5,5)),set([taper]))[0].interiorOverlap,true);});
test('invalid, reflected, open and concave geometry refuses; snapshots and motion stay immutable',()=>{const raw={id:'held',frame:F(),halfExtents:P(2,3,6)},a=createHeldBox(raw);raw.frame.origin.x=100;assert.equal(a.frame.origin.x,0);assert.throws(()=>createHeldBox({...raw,halfExtents:P(NaN,3,6)}));const reflected=F();reflected.x=P(-1,0,0);assert.throws(()=>createHeldBox({...raw,frame:reflected}));const skew=F();skew.y.x=.01;assert.throws(()=>createHeldBox({...raw,frame:skew}));const open=solid('bad',P(),P(2,2,2));open.faces=faces.slice(0,-1);assert.throws(()=>set([open]));const concave=solid('bad',P(),P(2,2,2));concave.vertices[6]=P(.5,.5,.5);assert.throws(()=>set([concave]));assert.throws(()=>set([]));assert.throws(()=>heldBoxContacts(a,{}));assert.throws(()=>sampleHeldBoxMotion({},.5));const m=createHeldBoxMotion(a,box(P(5),P(2,3,6)));assert.throws(()=>{m.to.frame.origin.x=100;});assert.equal(sampleHeldBoxMotion(m,.5).frame.origin.x,2.5);assert.throws(()=>sweepHeldBox({...m},set([solid('wall',P(10),P(12,2,2))])));});
test('changing accessors are snapshotted before actual geometry validation',()=>{let reads=0;const value={id:'held',frame:F(),get halfExtents(){reads++;return reads===1?P(NaN,3,6):P(2,3,6);}};assert.throws(()=>createHeldBox(value));assert.equal(reads,1);});
test('world snapshots require complete current world authority and expose frozen actual covers',()=>{const terrain=createTrainTerrain(),world=createWorldQuery(trainGeometry(createTrainConsist()),terrain),before=JSON.stringify(world),snapshot=worldCoverSolids(world),compiled=compileHeldWorld(world);assert.ok(snapshot.solids.length>663);assert.ok(Object.isFrozen(snapshot.solids[0].vertices[0]));assert.equal(validateHeldWorldSnapshot(compiled,world),true);const other=createWorldQuery(trainGeometry(createTrainConsist()),terrain);assert.equal(validateHeldWorldSnapshot(compiled,other),false);for(const invalid of[null,{}, {...world}])assert.throws(()=>compileHeldWorld(invalid));assert.throws(()=>worldCoverSolids(world,{fraction:NaN}));assert.throws(()=>heldBoxWorldContacts(null,box()));assert.equal(JSON.stringify(world),before);});

function stagedHinge(cursor,actorId){const path=createRailPath(TRAIN_TRACK),specs=compileCarSpecs(TRAIN_CARS),motion=advanceConsist(path,specs,createConsist(path,specs,{cursor,speed:0,brakePressure:1}),1/120,{brake:1},TRAIN_MOTION_PROPOSAL),cars=createAcceptedStepContext(motion.platforms,1/120),query=createAcceptedStepContext([...cars.platforms,...createGangwayPlatforms(cars,TRAIN_GANGWAYS)],1/120),socket=actorId==='mara'?'private-hinge-a':'private-hinge-b',approach=TRAIN_CHARGE_APPROACHES[socket],car=query.platforms.find(p=>p.id===approach.carId),plate=query.platforms.find(p=>p.id===approach.supportId),base=worldPoint(car.previousFrame,P(approach.referenceLocalXY.x,approach.referenceLocalXY.y)),z=dot(plate.previousFrame.z,sub(plate.previousFrame.origin,base))/dot(plate.previousFrame.z,car.previousFrame.z),local=localPoint(plate.previousFrame,worldPoint(car.previousFrame,P(approach.referenceLocalXY.x,approach.referenceLocalXY.y,z)));local.z=0;const body=new E.Body({...worldPoint(plate.previousFrame,local),id:actorId,r:9,height:53,hp:100,onGround:true,facing:Math.atan2(car.previousFrame.x.y,car.previousFrame.x.x)+approach.facingLocal,toolHeld:actorId==='mara'?'quarry-sealed-charge-2':'quarry-sealed-charge-3',toolHand:approach.hand,...actorId==='juno'?{injured:true,handInjury:{side:'right',recovered:false}}:{}});body.support={carId:plate.id,surfaceId:'gangway-deck',local,relativeVelocity:P()};stepRailBody(body,query,1/120,{relativeVelocity:P()});assert.ok(validateBodySupport(body,query));return{query,car,plate,body,socket,approach};}
test('STAGED stopped curved/gangway native MaraR and JunohealthyL hinge poses retain finite2/3/6 car-aligned boxes',()=>{for(const cursor of[1600,2400,3600])for(const actorId of['mara','juno']){const f=stagedHinge(cursor,actorId),before=JSON.stringify(f.body),h=createTrainHuman(E,f.body);for(let i=0;i<24;i++)h.rig.update(1/120,{...f.body,z:0,pose:f.approach.pose==='kneel'?'kneel':null});const target=worldContact(f.car,f.socket),pose=prepareTrainPose(E,h,f.body,f.plate,{contacts:[{side:f.approach.hand,target,kind:f.socket,usesHeldTool:f.body.toolHeld}]});try{assert.ok(pose.diagnostics.find(c=>c.kind===f.socket).reachable);assert.ok(Math.hypot(...Object.values(sub(rigWorldPoint(h.rig,pose.root,'hand'+f.approach.hand),target)))<1e-5);const aligned=createHeldBox({id:f.body.toolHeld,frame:{...f.car.frame,origin:target},halfExtents:TRAIN_CHARGE_HALF_EXTENTS}),world=createWorldQuery(f.query,createTrainTerrain()),contacts=heldBoxWorldContacts(world,aligned);assert.ok(contacts.some(c=>c.solidId==='private-iron-door'));assert.ok(contacts.every(c=>!c.interiorOverlap));if(actorId==='juno'){const wrong=createHeldBox({id:f.body.toolHeld,frame:F(target,f.body.facing),halfExtents:TRAIN_CHARGE_HALF_EXTENTS});assert.ok(heldBoxWorldContacts(world,wrong).some(c=>c.solidId==='private-iron-door'&&c.interiorOverlap));const blocked=prepareTrainPose(E,h,f.body,f.plate,{contacts:[{side:'R',target,kind:'wrong-hand',usesHeldTool:f.body.toolHeld}]});assert.equal(blocked.diagnostics.find(c=>c.kind==='wrong-hand').blocked,'injured-hand');blocked.restore();}}finally{pose.restore();}assert.equal(JSON.stringify(f.body),before);}});

test('STAGED stopped hinge work rotates at a clear outboard native hand and seats without finite penetration',()=>{for(const cursor of[1100,1600,2000,2400,3000,3600,4200,4800,5200])for(const actorId of['mara','juno']){const f=stagedHinge(cursor,actorId),world=createWorldQuery(f.query,createTrainTerrain()),solids=compileHeldWorld(world),bodyBefore=JSON.stringify(f.body),target=worldContact(f.car,f.socket),localTarget=localPoint(f.car.frame,target),outboard=worldPoint(f.car.frame,P(89.5,localTarget.y<0?-27:27,localTarget.z)),initial=createHeldBox({id:f.body.toolHeld,frame:F(outboard,f.body.facing),halfExtents:TRAIN_CHARGE_HALF_EXTENTS}),aligned=createHeldBox({id:f.body.toolHeld,frame:{...f.car.frame,origin:outboard},halfExtents:TRAIN_CHARGE_HALF_EXTENTS}),final=createHeldBox({id:f.body.toolHeld,frame:{...f.car.frame,origin:target},halfExtents:TRAIN_CHARGE_HALF_EXTENTS}),rotation=createHeldBoxMotion(initial,aligned,{duration:1.2}),seating=createHeldBoxMotion(aligned,final,{duration:1.1});assert.equal(heldBoxContacts(initial,solids).length,0);const rotational=sweepHeldBox(rotation,solids);assert.equal(rotational.clear,true,cursor+'/'+actorId+' '+JSON.stringify(rotational));assert.equal(sweepHeldBox(seating,solids,{contactMode:'interior'}).clear,true);assert.equal(sweepHeldBox(seating,solids).clear,false,'the real final door contact is retained');const h=createTrainHuman(E,f.body);for(let i=0;i<24;i++)h.rig.update(1/120,{...f.body,z:0,pose:f.approach.pose==='kneel'?'kneel':null});for(const path of[rotation,seating])for(let n=0;n<=12;n++){const sample=sampleHeldBoxMotion(path,n/12);h.rig.t=.25+n/12;h.rig.update(0,{...f.body,z:0,pose:f.approach.pose==='kneel'?'kneel':null});const pose=prepareTrainPose(E,h,f.body,f.plate,{contacts:[{side:f.approach.hand,target:sample.frame.origin,kind:'staged-held-centre',usesHeldTool:f.body.toolHeld}]});try{const hand=pose.diagnostics.find(c=>c.kind==='staged-held-centre');assert.ok(hand.reachable&&hand.error<1e-5);const bones=['sh','elbow','hand'].map(j=>rigWorldPoint(h.rig,pose.root,j+f.approach.hand));for(let i=1;i<bones.length;i++)assert.equal(raycastWorldCoverAt(world,bones[i-1],bones[i],{mode:'body'}),null,'native arm segment stays outside cover');assert.ok(pose.diagnostics.filter(c=>c.kind==='deck-foot').every(c=>c.reachable));}finally{pose.restore();}}assert.deepEqual(final.halfExtents,{x:2,y:3,z:6});assert.equal(JSON.stringify(f.body),bodyBefore);}});
test('instant moving-world fractions differ and invalidate fixed-snapshot bindings',()=>{const path=createRailPath(TRAIN_TRACK),specs=compileCarSpecs(TRAIN_CARS),motion=advanceConsist(path,specs,createConsist(path,specs,{cursor:2400,speed:85}),.1,{},TRAIN_MOTION_PROPOSAL),cars=createAcceptedStepContext(motion.platforms,.1),geometry=createAcceptedStepContext([...cars.platforms,...createGangwayPlatforms(cars,TRAIN_GANGWAYS)],.1),world=createWorldQuery(geometry,createTrainTerrain()),car=geometry.platforms.find(p=>p.id==='morrow-custody-coach'),target=worldContact(car,'private-hinge-b',0),b=createHeldBox({id:'explicit-staged-charge',frame:{...car.previousFrame,origin:target},halfExtents:TRAIN_CHARGE_HALF_EXTENTS}),at0=compileHeldWorld(world,{fraction:0});assert.ok(heldBoxContacts(b,at0).some(c=>c.solidId==='private-iron-door'));assert.equal(validateHeldWorldSnapshot(at0,world,{fraction:1}),false);assert.equal(validateHeldWorldSnapshot(at0,world,{fraction:0,mode:'projectile'}),false);const before=worldCoverSolids(world,{fraction:0}).solids.find(s=>s.id==='private-iron-door'),after=worldCoverSolids(world,{fraction:1}).solids.find(s=>s.id==='private-iron-door');assert.notDeepEqual(before.vertices,after.vertices);assert.ok(!heldBoxWorldContacts(world,b,{fraction:1}).some(c=>c.solidId==='private-iron-door'));});

test('STAGED Mara rotation at unsafe x90 outboard has safe endpoints but cannot bypass the neighbouring vestibule',()=>{const f=stagedHinge(2400,'mara'),world=createWorldQuery(f.query,createTrainTerrain()),solids=compileHeldWorld(world),point=worldPoint(f.car.frame,P(90,-28,45)),a=createHeldBox({id:f.body.toolHeld,frame:F(point,f.body.facing),halfExtents:TRAIN_CHARGE_HALF_EXTENTS}),b=createHeldBox({id:f.body.toolHeld,frame:{...f.car.frame,origin:point},halfExtents:TRAIN_CHARGE_HALF_EXTENTS}),m=createHeldBoxMotion(a,b);assert.equal(heldBoxContacts(a,solids).length,0);assert.equal(heldBoxContacts(b,solids).length,0);const hit=sweepHeldBox(m,solids);assert.equal(hit.clear,false);assert.equal(hit.solidId,'vestibule-left-wall');assert.equal(hit.ownerId,'morrow-vestibule-coach');assert.ok(hit.interval[0]>.49&&hit.interval[0]<.51);});
test('a freely rotating finite box obtains a whole-interval separation proof',()=>{const m=createHeldBoxMotion(box(P(),P(2,3,6),-2),box(P(),P(2,3,6),1.8)),s=set([solid('distant',P(30,30,30),P(31,31,31))]),q=sweepHeldBox(m,s);assert.equal(q.clear,true);assert.equal(q.scope,'fixed-solids');});

test('near-rigid accepted endpoint matrices retain their actual finite corners through the motion',()=>{const skew=F();skew.y.x=1e-8;const a=createHeldBox({id:'actual-matrix-box',frame:skew,halfExtents:P(1000000,1000000,1)}),b=createHeldBox({id:'actual-matrix-box',frame:F(P(),1e-9),halfExtents:P(1000000,1000000,1)}),wall=set([solid('matrix-residual-wall',P(1000000.005,999999,-.5),P(1000000.02,1000001,.5))]);assert.equal(heldBoxContacts(a,wall)[0].interiorOverlap,true);assert.equal(sampleHeldBoxMotion(createHeldBoxMotion(a,b),0),a);assert.equal(sweepHeldBox(createHeldBoxMotion(a,b),wall).clear,false);assert.throws(()=>createHeldBoxMotion(a,box(P(),P(1000000,1000000,1),0,'other')));assert.throws(()=>createHeldBoxMotion(box(),box(P(),P(2,1,1))));});
