/** Real accepted-frame velocity regressions; original fixture bytes are never
 * patched into positive body, stock, watch or elapsed outcomes. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {gunzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import {Journey,trainRecord} from '../helpers/train-preparation-route.mjs';
import {capturePreparationBodyBounds,validatePreparationBodyBounds} from '../../src/train-preparation-layout.js';
import {preparationNativeBodyParts} from '../../src/train-preparation-body-geometry.js';
const RIVAL='snowbound-the-names-they-took',point=a=>({x:a.x,y:a.y,z:a.z??0}),sha=b=>createHash('sha256').update(b).digest('hex'),copy=structuredClone;
function load(name,expected){const bytes=gunzipSync(readFileSync(new URL(`../fixtures/${name}.json.gz`,import.meta.url)));assert.equal(sha(bytes),expected);const raw=bytes.toString(),s=Journey.restoreCampaign(raw);assert.ok(s,'the unchanged entire earned graph restores');assert.equal(Journey.serializeCampaign(s),raw,'restore never clears historical velocity or rewrites receipts');return{s,raw};}
const pr9=()=>load('train-preparation-pr9-mask-owned-bring','2c3aa5309166cbb316838f5b2332165057671df8be8839d95424c5968d3bb76c');
const facts=s=>copy({party:s.party,inventory:s.inventory,weapons:s.weapons,items:s.itemInstances,objects:s.campaign.missions[RIVAL].objects,performance:s.campaign.missions[RIVAL].performance,guardId:s.campaign.missions[RIVAL].captivity.guardId,helperId:s.campaign.missions[RIVAL].captivity.helperId,restraint:s.campaign.missions[RIVAL].captivity.restraint,care:s.campaign.missions[RIVAL].captivity.care});
const feet=s=>Object.fromEntries(Object.entries(s.entities).map(([id,a])=>[id,point(a)]));

test('unchanged earned PR9 idle frame settles inherited free-NPC velocities after controllers without changing feet, guard or custody',()=>{const{s,raw}=pr9(),before=feet(s),history=copy(trainRecord(s).train.preparation.campSetup),authority=facts(s),elapsed=s.elapsed,timer=trainRecord(s).timers.elapsed,clock=s.time,levi=copy(s.entities.levi),neri=copy(s.entities.neri),refs=new Map(Object.entries(s.entities));const prior=capturePreparationBodyBounds(s);for(const id of['bastian','hob']){assert.ok(Math.hypot(s.entities[id].vx,s.entities[id].vy)>1);assert.ok(preparationNativeBodyParts(prior.find(r=>r.id===id),prior).some(p=>p.id==='stride'));}assert.equal(s.entities.ruth.vx,0);assert.equal(s.entities.ruth.vy,0);Journey.stepCampaign(s,.05);assert.deepEqual(feet(s),before);for(const id of['bastian','hob','ruth','inez','tomas']){assert.equal(s.entities[id],refs.get(id));assert.equal(s.entities[id].vx,0,id);assert.equal(s.entities[id].vy,0,id);}assert.equal(s.entities.levi.vx,levi.vx,'attached Levi keeps attachment/transport authority');assert.equal(s.entities.levi.vy,levi.vy);assert.deepEqual(s.entities.levi.attachment,levi.attachment);assert.deepEqual(s.entities.neri,neri,'dead actor is not given new velocity fields');assert.deepEqual(facts(s),authority);assert.deepEqual(trainRecord(s).train.preparation.campSetup,history);assert.ok(Math.abs(s.elapsed-elapsed-.05)<1e-9);assert.ok(Math.abs(trainRecord(s).timers.elapsed-timer-.05)<1e-9);assert.ok(s.time>clock);const after=capturePreparationBodyBounds(s);for(const id of['bastian','hob']){const row=after.find(r=>r.id===id),parts=preparationNativeBodyParts(row,after);assert.ok(!parts.some(p=>p.id==='stride'));assert.equal(parts.find(p=>p.id==='root-foot').halfExtents.x,9);}assert.equal(trainRecord(s).train.preparation.copperRecovery,undefined);const saved=Journey.serializeCampaign(s);assert.notEqual(saved,raw,'only a real accepted frame changes current state/time');assert.ok(Journey.restoreCampaign(saved));assert.equal(Journey.serializeCampaign(Journey.restoreCampaign(saved)),saved);});

test('genuine pending holding request retains controller-derived velocity when a called NPC really moves in the accepted frame',()=>{const{s}=load('train-preparation-pending-holding-native','fd6e31e8268df0009cba8ba861b812e8e24aa993994e31f3443a7136568a9957'),authority=facts(s),guard=point(s.entities.bastian),horse=point(s.entities.copper);assert.equal(s.entities.copper.following,false);assert.equal(trainRecord(s).train.preparation.exchange.kind,'holding');let moved=false;for(let i=0;i<4&&!moved;i++){const old=Object.fromEntries(['hob','inez'].map(id=>[id,{body:s.entities[id],point:point(s.entities[id])}])),elapsed=s.elapsed;Journey.stepCampaign(s,.05);assert.ok(s.elapsed>elapsed);for(const id of['hob','inez']){const a=s.entities[id],p=old[id].point,d=Math.hypot(a.x-p.x,a.y-p.y);assert.equal(a,old[id].body);if(d>1e-7){assert.ok(d<=95*.05+1e-7);assert.ok(Math.abs(a.vx-(a.x-p.x)/.05)<1e-7,`${id} vx must describe the actual accepted displacement`);assert.ok(Math.abs(a.vy-(a.y-p.y)/.05)<1e-7,`${id} vy must describe the actual accepted displacement`);assert.ok(Math.hypot(a.vx,a.vy)>0,'frame-end settlement must not erase real controller motion');moved=true;}}}assert.ok(moved,'a genuine called NPC earns finite movement, without patched actors');assert.deepEqual(point(s.entities.bastian),guard);assert.deepEqual(point(s.entities.copper),horse);assert.deepEqual(facts(s),authority);assert.equal(trainRecord(s).train.preparation.completed.some(e=>e.kind==='holding'),false,'movement is not fabricated hearing/watch completion');const raw=Journey.serializeCampaign(s);assert.ok(Journey.restoreCampaign(raw));assert.equal(Journey.serializeCampaign(Journey.restoreCampaign(raw)),raw);});

test('derived native volume roundoff preserves supplied numbers while material bounds, roots, shapes and rig changes still refuse',()=>{const{s,raw}=pr9(),rows=capturePreparationBodyBounds(s),rounded=copy(rows),mara=rounded.find(r=>r.id==='mara');mara.volumes[0].min.z+=3.552713678800501e-15;const supplied=JSON.stringify(rounded);assert.equal(validatePreparationBodyBounds(s,rounded),true,'component probe matches the observed few-ULP cross-engine scale');assert.equal(JSON.stringify(rounded),supplied,'validation retains the original supplied scalar');for(const mutate of[r=>r.volumes[0].min.z+=1e-6,r=>r.volumes[0].max.x-=1e-6,r=>r.volumes[0].max.x=NaN,r=>r.volumes[0].extra=1,r=>r.volumes.pop(),r=>r.point.x+=1e-10,r=>r.radius+=Number.EPSILON*9,r=>r.pose.rig={}]){const bad=copy(rows);mutate(bad.find(r=>r.id==='mara'));const before=JSON.stringify(bad);assert.equal(validatePreparationBodyBounds(s,bad),false);assert.equal(JSON.stringify(bad),before);}assert.equal(Journey.serializeCampaign(s),raw,'pure derived-bound checks never rewrite source/history or current bodies');});
