import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {gunzipSync} from 'node:zlib';
import {Journey,moveNative,trainRecord} from '../helpers/train-preparation-route.mjs';
import {beginPreparationCopperRecovery,stepPreparationCopperRecovery,validatePreparationCopperRecovery,currentPreparationCopperRecovery} from '../../src/train-preparation-copper-recovery.js';
import {capturePreparationBodyBounds} from '../../src/train-preparation-layout.js';
import {preparationNativeBodyParts,preparationNativeBodyContacts} from '../../src/train-preparation-body-geometry.js';
import {followPreparationOwnedMount,stepPreparationMounted} from '../../src/train-preparation-navigation.js';
import {getTrainCampHorseInteractions,interactTrainCampHorse} from '../../src/train-camp-horse-actions.js';
import {emitCampaignPresentation} from '../../src/campaign.js';
const input=new URL('../fixtures/train-preparation-pr9-mask-owned-bring.json.gz',import.meta.url),original=()=>gunzipSync(readFileSync(input)).toString(),ctx={worldFor:Journey.worldForCampaign,present:emitCampaignPresentation},P=a=>({x:a.x,y:a.y,z:a.z??0}),prep=s=>trainRecord(s).train.preparation;
let calledBytes,prefixBytes,clearBytes;
function artifact(name,s){const dir=process.env.TRAIN_COPPER_ARTIFACT_DIR;if(!dir)return;mkdirSync(dir,{recursive:true});writeFileSync(`${dir}/${name}.json`,Journey.serializeCampaign(s));}
function called(){if(calledBytes){const s=Journey.restoreCampaign(calledBytes);assert.ok(s);return s;}const raw=original(),s=Journey.restoreCampaign(raw);assert.ok(s);assert.equal(Journey.serializeCampaign(s),raw,'unchanged genuine PR9 historical bytes');assert.equal(prep(s).copperRecovery,undefined);const start=P(s.horse);moveNative(s,{x:600,y:1330,z:0});assert.deepEqual(P(s.horse),start,'walking Mara does not relocate an uncalled horse');Journey.whistleCampaign(s);if(!prep(s).copperRecovery)assert.equal(beginPreparationCopperRecovery(s,ctx),true);assert.equal(prep(s).copperRecovery.steps.length,0);assert.equal(prep(s).copperRecovery.startedAt,s.elapsed);assert.ok(validatePreparationCopperRecovery(s,prep(s).copperRecovery));calledBytes=Journey.serializeCampaign(s);assert.ok(Journey.restoreCampaign(calledBytes));return s;}
function advance(s,n=1){for(let i=0;i<n;i++){const old=P(s.horse),elapsed=s.elapsed;Journey.stepCampaign(s,.05);if(currentPreparationCopperRecovery(s)&&prep(s).copperRecovery.lastAdvancedAt<s.elapsed)stepPreparationCopperRecovery(s,.05,ctx);assert.ok(s.elapsed>elapsed);const d=Math.hypot(s.horse.x-old.x,s.horse.y-old.y);assert.ok(d<=95*.05+1e-7);assert.equal(followPreparationOwnedMount(s,.05,ctx),0,'generic follow shares this accepted frame budget');assert.deepEqual(P(s.horse),{x:old.x,y:old.y+d,z:old.z});assert.equal(stepPreparationCopperRecovery(s,.05,ctx),false,'same clock has no second movement allowance');}}
function toMinimum(s){for(let i=0;s.horse.y<prep(s).copperRecovery.initial.from.y+23.75&&i<10;i++)advance(s);return s;}
function prefix(){if(prefixBytes){const s=Journey.restoreCampaign(prefixBytes);assert.ok(s);return s;}const s=called();toMinimum(s);assert.equal(s.horse.y,prep(s).copperRecovery.initial.from.y+23.75);assert.equal(prep(s).copperRecovery.status,'recovering');artifact('02-local-minimum-prefix',s);prefixBytes=Journey.serializeCampaign(s);assert.ok(Journey.restoreCampaign(prefixBytes),'original episode is whole-Save compatible at the local energy minimum');return s;}
function clear(){if(clearBytes){const s=Journey.restoreCampaign(clearBytes);assert.ok(s);return s;}const s=prefix();for(let i=0;prep(s).copperRecovery.status!=='clear'&&i<24;i++)advance(s);assert.equal(prep(s).copperRecovery.status,'clear');clearBytes=Journey.serializeCampaign(s);assert.ok(Journey.restoreCampaign(clearBytes));artifact('03-cleared',s);return s;}
const preserved=s=>structuredClone({plover:s.entities.plover,cinder:s.entities.cinder,moth:s.entities['tomas-mount'],skein:s.entities.skein,items:s.itemInstances,inventory:s.inventory,weapons:s.weapons,rival:{objects:s.campaign.missions['snowbound-the-names-they-took'].objects,performance:s.campaign.missions['snowbound-the-names-they-took'].performance,captivity:Object.fromEntries(['guardId','helperId','restraint','care'].map(k=>[k,s.campaign.missions['snowbound-the-names-they-took'].captivity[k]]))}});

test('genuine PR9 owned mask→ordinary walk/call→finite complete Copper exit preserves original episode across whole Save/Continue',()=>{const s=called(),before=preserved(s),from=P(s.horse);toMinimum(s);const r=prep(s).copperRecovery,originalLimits=structuredClone(r.initial.certificate.depthLimits);assert.equal(r.steps.filter(step=>step.motion).length,5);assert.equal(s.horse.y,from.y+23.75);const raw=Journey.serializeCampaign(s),continued=Journey.restoreCampaign(raw);assert.ok(continued);assert.equal(Journey.serializeCampaign(continued),raw);assert.deepEqual(prep(continued).copperRecovery.initial.certificate.depthLimits,originalLimits);for(let i=0;prep(continued).copperRecovery.status!=='clear'&&i<24;i++)advance(continued);assert.deepEqual(P(continued.horse),{...from,y:from.y+100});assert.equal(continued.horse.vx,0);assert.equal(continued.horse.vy,0);assert.equal(prep(continued).copperRecovery.steps.filter(step=>step.motion).length,22);assert.deepEqual(preserved(continued),before,'no companion horse, source, custody or stock was rewritten');assert.ok(validatePreparationCopperRecovery(continued,prep(continued).copperRecovery));const rows=capturePreparationBodyBounds(continued),h=rows.find(r=>r.id==='copper');for(const moving of[false,true]){const A=preparationNativeBodyParts({...h,pose:{...h.pose,vx:moving?1:0,vy:0}},rows);for(const other of rows.filter(r=>r.id!=='copper'&&r.regionId==='snowbound'))assert.equal(preparationNativeBodyContacts(A,preparationNativeBodyParts(other,rows)).length,0,`${moving?'walking':'rest'} clear of ${other.id}`);}const saved=Journey.serializeCampaign(continued);assert.ok(Journey.restoreCampaign(saved));assert.equal(Journey.serializeCampaign(Journey.restoreCampaign(saved)),saved);});

test('original caps/old-body identities/accepted clock and contact episode cannot be replaced in a restored prefix',()=>{const s=prefix(),good=prep(s).copperRecovery;for(const mutate of[r=>r.initial.certificate.depthLimits[0]+=1,r=>r.initial.certificate.oldBodyIds.push('tomas-mount'),r=>r.initial.target.x+=1,r=>r.startedAt-=1,r=>r.steps[0].finish+=.001,r=>r.steps.at(-1).motion=null,r=>r.clearedBodyIds=['plover'],r=>r.initial.bodyBounds.find(b=>b.id==='plover').point.x+=100]){const bad=structuredClone(good);mutate(bad);const before=JSON.stringify(s);assert.equal(validatePreparationCopperRecovery(s,bad),false);assert.equal(JSON.stringify(s),before,'pure negative query never repairs geometry or actors');}});

test('missing/substituted world, absent call and a newly occupying body refuse rather than becoming old contacts',()=>{const raw=original(),uncalled=Journey.restoreCampaign(raw),before=Journey.serializeCampaign(uncalled);assert.equal(beginPreparationCopperRecovery(uncalled,ctx),false);assert.equal(Journey.serializeCampaign(uncalled),before);for(const world of[null,{id:'snowbound',width:1800,height:1400,obstacles:[]}]){const s=called();delete prep(s).copperRecovery;const snapshot=JSON.stringify(s);assert.equal(beginPreparationCopperRecovery(s,{worldFor:()=>world}),false);assert.equal(JSON.stringify(s),snapshot);}const first=called();delete prep(first).copperRecovery;Object.assign(first.entities.neri,{x:first.horse.x,y:first.horse.y,z:0,hidden:true});assert.equal(beginPreparationCopperRecovery(first,ctx),false,'new corpse at first call is never inherited herd');const s=called(),h=s.horse;Object.assign(s.entities.neri,{x:h.x,y:h.y+45,z:0,hidden:true});const body=structuredClone(s.entities.neri),start=P(h);Journey.stepCampaign(s,.05);assert.deepEqual(P(h),start,'registered corpse newly crossing the complete exit cancels motion');assert.deepEqual(s.entities.neri,body);assert.ok(validatePreparationCopperRecovery(s,prep(s).copperRecovery),'staged obstruction records a typed wait; this is not an earned route or whole-Save provenance');assert.equal(prep(s).copperRecovery.steps.at(-1).motion,null);});

test('genuine cleared Copper offers canonical mount, clears ground crouch, whole Saves, earns native rider/horse motion and dismounts',()=>{let s=clear();moveNative(s,{x:s.horse.x+28,y:s.horse.y,z:0});Journey.stepCampaign(s,.05);artifact('04-approached',s);assert.ok(getTrainCampHorseInteractions(s,ctx).some(o=>o.id==='train:mount-copper'),JSON.stringify({p:{...P(s.player),mounted:s.player.mounted,crouch:s.player.crouch},h:{...P(s.horse),facing:s.horse.facing,vx:s.horse.vx,vy:s.horse.vy}}));Journey.campaignAction(s,'crouch');assert.equal(s.player.crouch,true);assert.equal(interactTrainCampHorse(s,'train:mount-copper',ctx),true);assert.equal(s.player.crouch,false);assert.equal(s.player.mounted,true);assert.deepEqual(P(s.player),P(s.horse));artifact('05-actual-mounted',s);const mounted=Journey.serializeCampaign(s);s=Journey.restoreCampaign(mounted);assert.ok(s);assert.equal(Journey.serializeCampaign(s),mounted);const start=P(s.horse);for(let i=0;i<35;i++)Journey.stepCampaign(s,.05,{mx:0,my:1});assert.ok(s.horse.y>start.y+20,'actual bounded yaw then full-native translation earns a ride');assert.deepEqual(P(s.player),P(s.horse));artifact('06-actual-ridden',s);const ridden=Journey.serializeCampaign(s);assert.ok(Journey.restoreCampaign(ridden));assert.equal(stepPreparationMounted(s,.05,{mx:0,my:1},125,ctx),0,'ride has no duplicate frame allowance');Journey.stepCampaign(s,.05);assert.equal(interactTrainCampHorse(s,'train:dismount-copper',ctx),true);assert.equal(s.player.mounted,false);artifact('07-actual-dismounted',s);assert.ok(Journey.restoreCampaign(Journey.serializeCampaign(s)));});


test('unchanged genuinely generated v1/60-unit prefix restores exact original bytes and continues its own original endpoint',()=>{const raw=gunzipSync(readFileSync(new URL('../fixtures/train-preparation-copper-recovery-v1-prefix.json.gz',import.meta.url))).toString(),s=Journey.restoreCampaign(raw);assert.ok(s);assert.equal(Journey.serializeCampaign(s),raw);assert.equal(prep(s).copperRecovery.routeVersion,undefined);const from=prep(s).copperRecovery.initial.from.y;for(let i=0;prep(s).copperRecovery.status!=='clear'&&i<12;i++)advance(s);assert.equal(s.horse.y,from+60);assert.equal(prep(s).copperRecovery.routeVersion,undefined);assert.ok(Journey.restoreCampaign(Journey.serializeCampaign(s)));});
