import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {gunzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import {Journey,trainRecord} from '../helpers/train-preparation-route.mjs';
import {validatePreparationCopperRecovery} from '../../src/train-preparation-copper-recovery.js';
const file=new URL('../fixtures/train-preparation-copper-recovery-webkit-v2-pending.json.gz',import.meta.url),provenance=JSON.parse(readFileSync(new URL('../fixtures/train-preparation-copper-recovery-webkit-v2-pending.provenance.json',import.meta.url))),packed=readFileSync(file),raw=gunzipSync(packed).toString('utf8'),sha=b=>createHash('sha256').update(b).digest('hex');
let cached;
function observed(){assert.equal(sha(packed),provenance.gzipSHA256);assert.equal(sha(raw),provenance.originalRawSHA256);if(!cached){cached=Journey.restoreCampaign(raw);assert.ok(cached,'unaltered real WebKit pending Save must pass the V8 owning decoder');}return cached;}
const episode=s=>trainRecord(s).train.preparation.copperRecovery;

test('unaltered performed WebKit recovery Save preserves its original bounds and partition telemetry across V8 whole-Save restore',()=>{const s=observed(),r=episode(s);assert.equal(Journey.serializeCampaign(s),raw);assert.equal(r.status,'recovering');assert.ok(r.steps.length>0&&r.steps.every(step=>step.motion));assert.equal(r.initial.certificate.rest.bodies[1].axisIntervals,133);assert.equal(r.initial.certificate.walking.bodies[1].axisIntervals,151);assert.equal(r.initial.bodyBounds.find(b=>b.id==='levi').volumes[1].min.z,-0.9720038545337601);assert.ok(validatePreparationCopperRecovery(s,r));assert.equal(Journey.serializeCampaign(s),raw,'validation preserves stored platform telemetry and every original byte');});

test('malformed diagnostic counts and extra or missing proof keys reject through the owning recovery validator',()=>{const s=observed(),good=episode(s),mutations=[r=>r.initial.certificate.rest.bodies[1].axisIntervals=-1,r=>r.initial.certificate.rest.bodies[1].axisIntervals=1.5,r=>r.initial.certificate.rest.bodies[1].axisIntervals=Number.MAX_SAFE_INTEGER+1,r=>r.initial.certificate.rest.bodies[1].axisIntervals='133',r=>delete r.initial.certificate.rest.bodies[1].axisIntervals,r=>r.initial.certificate.rest.bodies[1].invented=true,r=>r.initial.certificate.mountedParkingTurn.intervals=Infinity,r=>delete r.initial.certificate.mountedParkingTurn.intervals,r=>r.steps[0].motion.walking.bodies[0].axisIntervals=-1,r=>r.steps[0].motion.walking.bodies[0].axisIntervals=null,r=>r.steps[0].motion.unknown=0];for(const mutate of mutations){const bad=structuredClone(good);mutate(bad);assert.equal(validatePreparationCopperRecovery(s,bad),false);}assert.equal(Journey.serializeCampaign(s),raw);});

test('physical authority remains exact: caps, IDs, roots, target, ordering, array length and safety outcome cannot borrow diagnostic compatibility',()=>{const s=observed(),good=episode(s),mutations=[r=>r.initial.certificate.depthLimits[0]+=1e-12,r=>r.initial.certificate.rest.bodies[1].exitFraction+=Number.EPSILON,r=>r.initial.certificate.rest.bodies[1].maximumDepth-=1e-12,r=>r.initial.certificate.mountedParkingTurn.toFacing+=1e-12,r=>r.initial.certificate.mountedParkingTurn.clear=false,r=>r.initial.certificate.oldBodyIds.reverse(),r=>r.initial.certificate.remainingBodyIds.pop(),r=>r.initial.certificate.rest.bodies.length++,r=>r.initial.target.x+=1e-8,r=>r.initial.from.y+=1e-8,r=>r.steps[0].motion.depthLimits[1]+=1e-12,r=>r.steps[0].motion.walking.bodies[1].limit+=1e-12];for(const mutate of mutations){const bad=structuredClone(good);mutate(bad);assert.equal(validatePreparationCopperRecovery(s,bad),false);}assert.equal(Journey.serializeCampaign(s),raw);});

test('the same observed WebKit pending Save continues through ordinary V8 accepted time without replacing its original episode or caps',()=>{const s=Journey.restoreCampaign(raw);assert.ok(s);const before=s.entities.copper.y,initial=structuredClone(episode(s).initial),count=episode(s).steps.length;Journey.stepCampaign(s,.05);assert.ok(s.entities.copper.y>before,'real accepted recovery advances after a cross-engine load');assert.ok(s.entities.copper.y-before<=95*.05+1e-7);assert.ok(episode(s).steps.length>count);assert.deepEqual(episode(s).initial,initial,'original stored JSCore bounds, caps and telemetry remain untouched');const saved=Journey.serializeCampaign(s),continued=Journey.restoreCampaign(saved);assert.ok(continued);assert.equal(Journey.serializeCampaign(continued),saved);});
