import test from 'node:test';
import assert from 'node:assert/strict';
import '../../my-3d2dge-agent.js';
import {createConsist,createRailPath,advanceConsist} from '../../src/rail-foundation/rail-consist.js';
import {worldPoint,sub,length,makeFrame} from '../../src/rail-foundation/rigid-frame.js';
import {createTrainHuman,prepareTrainPose,rigWorldPoint,TRAIN_PROFILES,physicalProjection,RivetRig,createTrainMount,prepareTrainMountedPose} from '../../src/train-native/rigs.js';
import {createTrainRenderer} from '../../src/train-native/renderer.js';
import {TRAIN_CARS,TRAIN_TRACK,TRAIN_NEW_CAST,TRAIN_OPERATOR_APPROACHES} from '../../proposals/brass-cutting.js';
const E=globalThis.My3D2dge,P=(x=0,y=0,z=0)=>({x,y,z}),clone=v=>JSON.parse(JSON.stringify(v));
const context=()=>new Proxy({globalAlpha:1,globalCompositeOperation:'source-over',measureText:s=>({width:s.length*5})},{get:(o,k)=>k in o?o[k]:()=>{},set:(o,k,v)=>(o[k]=v,true)});
function scene(){const track=createRailPath(TRAIN_TRACK),consist=createConsist(track,TRAIN_CARS,{cursor:2400,speed:85}),motion=advanceConsist(track,TRAIN_CARS,consist,.05),car=motion.platforms.find(p=>p.id==='morrow-engine'),local=clone(TRAIN_OPERATOR_APPROACHES['cab-brake'].local),mara={id:'mara',name:'Mara Vale',...worldPoint(car.frame,local),hp:100,onGround:true,holstered:true,facing:Math.atan2(car.frame.x.y,car.frame.x.x)+Math.PI,r:9,support:{carId:car.id,surfaceId:'cab-floor',local,relativeVelocity:P()}};return{track,consist:motion.state,platforms:motion.platforms,actors:[mara],viewerId:'mara',actions:[{actorId:'mara',contacts:[{carId:car.id,contactId:'cab-brake',side:'R',kind:'brake-grip'}]}]};}
function render(s,reduced=false,view=E.VIEWS.threequarter,inspect=null){s.reduceMotion=reduced;const renderer=createTrainRenderer(E,{},{cars:TRAIN_CARS}),pending=[],r={view,w:(x,y,z=0)=>view.p(x,y,z),visible:()=>true,queue:(x,y,z,fn,o)=>pending.push({k:view.order(x,y,z)+(o?.bias||0),fn})};renderer.update(.05,s);const before=JSON.stringify(s),style=JSON.stringify(E.style);renderer.draw(r,s);pending.sort((a,b)=>a.k-b.k);const g=context();for(const p of pending)p.fn(g);assert.equal(JSON.stringify(s),before,'rendering never writes authoritative positions/support/motion');assert.equal(JSON.stringify(E.style),style,'native physical projection restores engine preferences');const result=renderer.inspect();inspect?.(result,renderer);return result;}

test('the original train cast has distinct native profiles and Rig IDs',()=>{const bodies=['nell','abel','harlan','etta','conrad','odo','jana','faber'].map(id=>TRAIN_NEW_CAST.find(b=>b.id===id)),rigs=bodies.map(b=>createTrainHuman(E,b));assert.equal(new Set(rigs.map(r=>r.id)).size,8);assert.equal(new Set(rigs.map(r=>r.colors.coat)).size,8);assert.equal(new Set(rigs.map(r=>r.rig.o.size)).size,8);assert.equal(rigs.find(r=>r.id==='nell').profile.accessory,'riveter-stitch');assert.ok(rigs.every(r=>r.rig instanceof E.Humanoid));});
test('actual native world hand contacts remain camera-independent on rotated and graded bodies',()=>{for(const id of['nell','abel','harlan','etta','conrad','odo'])for(const yaw of[0,.5,Math.PI/2,Math.PI]){const body={id,x:100,y:200,z:40,hp:100,facing:yaw,onGround:true},h=createTrainHuman(E,body);h.rig.update(0,{...body,z:0});const original=rigWorldPoint(h.rig,body,'handR'),target={x:original.x+1,y:original.y,z:original.z+1},pose=prepareTrainPose(E,h,body,null,{contacts:[{side:'R',target,kind:'handle'}]});assert.ok(pose.diagnostics[0].reachable);assert.ok(pose.diagnostics[0].error<1e-6);pose.restore();}});
test('a distant requested target cannot stretch a body or count as a reached contact',()=>{const body={id:'nell',x:0,y:0,z:0,hp:100},h=createTrainHuman(E,body);h.rig.update(0,body);const before=JSON.stringify(body),pose=prepareTrainPose(E,h,body,null,{contacts:[{target:P(200,0,80),side:'R'}]});assert.equal(pose.diagnostics[0].reachable,false);assert.ok(pose.diagnostics[0].error>100);assert.equal(JSON.stringify(body),before);pose.restore();});
test('rendered moving geometry and actor contacts preserve the exact authoritative world and unique body',()=>{const s=scene(),result=render(s);assert.deepEqual(result.actors.map(a=>a.id),['mara']);assert.ok(result.geometry.length>20);assert.ok(result.geometry.every(g=>g.world.every(p=>Object.values(p).every(Number.isFinite))));const brake=result.contacts.find(c=>c.kind==='brake-grip');assert.ok(brake.reachable);assert.ok(brake.error<1e-5);assert.ok(result.cutaways.some(c=>c.carId==='morrow-engine'));assert.ok(result.cutaways.every(c=>c.collisionUnchanged));});
test('normal and reduced motion retain actual rail/car/wheel movement and reachable native contacts',()=>{const normal=render(scene(),false),reduced=render(scene(),true);assert.deepEqual(normal.wheels,reduced.wheels);assert.ok(normal.wheels.some(w=>Math.abs(w.angle)>0));for(const result of[normal,reduced])assert.ok(result.contacts.every(c=>c.reachable&&c.error<1e-5));});
test('geometry comes from moving cover even when the roof is cut away; no static interior or painted window is invented',()=>{const s=scene(),result=render(s);const p=s.platforms.find(p=>p.id==='morrow-engine'),geometry=result.geometry.find(g=>g.carId===p.id&&g.id==='engine-boiler');assert.ok(geometry);for(const vertex of geometry.world){const d=length(sub(vertex,p.frame.origin));assert.ok(d<100);}assert.equal(result.geometry.filter(g=>g.kind==='cover').length,s.platforms.reduce((n,p)=>n+p.cover.length,0));assert.ok(!result.geometry.some(g=>/window/.test(g.id)));});
test('duplicate bodies and invalid supported actor world positions are rejected instead of being repaired by drawing',()=>{const s=scene(),renderer=createTrainRenderer(E,{},{cars:TRAIN_CARS}),r={view:E.VIEWS.threequarter,w:(...p)=>E.VIEWS.threequarter.p(...p),queue:()=>{},visible:()=>true};assert.throws(()=>renderer.draw(r,{...s,actors:[s.actors[0],s.actors[0]]}));s.actors[0].x+=3;assert.throws(()=>renderer.draw(r,s));});
test('Rivet has her own compact native animal rig and right-eye crescent rather than Copper’s identity',()=>{const rig=new RivetRig(E),body={id:'rivet',kind:'horse',x:0,y:0,z:0,facing:0,hp:100};rig.update(.1,body,false);const result=rig.draw(context(),{view:E.VIEWS.threequarter,w:(...p)=>E.VIEWS.threequarter.p(...p)},body);assert.equal(rig.id,'rivet');assert.equal(result.mark,'right-eye-crescent');assert.ok(rig.world(body,'head')[0]<37);});
test('Juno’s existing injured right hand cannot silently perform a required manipulation',()=>{const body={id:'juno',x:0,y:0,z:0,hp:100,injured:true,handInjury:{side:'right',fingers:2}},h=createTrainHuman(E,body);h.rig.update(0,body);const pose=prepareTrainPose(E,h,body,null,{contacts:[{target:rigWorldPoint(h.rig,body,'handR'),side:'R'}]});assert.equal(pose.diagnostics[0].reachable,false);assert.equal(pose.diagnostics[0].blocked,'injured-hand');pose.restore();});

test('holding a different tool cannot be hidden by a simultaneous control grip, and nonfinite wheel geometry rejects',()=>{const body={id:'harlan',x:0,y:0,z:0,hp:100,toolHeld:'shovel',toolHand:'R'},h=createTrainHuman(E,body);h.rig.update(0,body);const pose=prepareTrainPose(E,h,body,null,{contacts:[{target:rigWorldPoint(h.rig,body,'handR'),side:'R'}]});assert.equal(pose.diagnostics[0].blocked,'hand-holds-other-tool');assert.equal(pose.diagnostics[0].reachable,false);pose.restore();const bad=clone(TRAIN_CARS);bad[0].wheelAxles=[NaN];assert.throws(()=>createTrainRenderer(E,{},{cars:bad}));});


test('native queue ordering keeps floor actors above their support but below opaque overhead cover',()=>{const s=scene();s.viewerId='outside';s.actions=[];const result=render(s),order=result.drawOrder;assert.ok(order.every((x,i)=>!i||x.key>=order[i-1].key-1e-8));const actor=order.findIndex(x=>x.kind==='actor'&&x.id==='mara'),floor=order.findIndex(x=>x.kind==='surface'&&x.carId==='morrow-engine'&&x.id==='cab-floor'),roof=order.findIndex(x=>x.kind==='cover'&&x.carId==='morrow-engine'&&x.id==='engine-cab-roof');assert.ok(floor<actor,'actual floor precedes its supported actor');assert.ok(actor<roof,'the opaque overhead cover can occlude the interior actor');});

test('graded-deck balancing reaches actual feet without moving the authoritative actor or creating a second body',()=>{const frame=makeFrame(P(100,200,20),P(1,0,.3)),local=P(0,0,26),platform={id:'slope',previousFrame:frame,frame,surfaces:[{id:'floor',bounds:{min:P(-40,-20,26),max:P(40,20,26)},oneWay:true}],cover:[]},body={id:'nell',...worldPoint(frame,local),hp:100,onGround:true,facing:0,support:{carId:'slope',surfaceId:'floor',local,relativeVelocity:P(60)}};const h=createTrainHuman(E,body);h.rig.update(.25,{...body,z:0,vx:60,vy:0});const before=JSON.stringify(body),pose=prepareTrainPose(E,h,body,platform);assert.equal(pose.diagnostics.length,2);assert.ok(pose.diagnostics.every(c=>c.reachable&&c.error<1e-5));assert.equal(JSON.stringify(body),before);pose.restore();});

test('charge placement draws the same registered child once at its real moving local point, without a loot grant or duplicate shadow',()=>{const s=scene();s.actions=[];s.objects=[{id:'quarry-sealed-charge-2',kind:'sealed-charge',owner:'mara',location:{type:'car',carId:'morrow-custody-coach',local:P(84,-28,45)}}];const before=JSON.stringify(s.objects),result=render(s),p=s.platforms.find(p=>p.id==='morrow-custody-coach');assert.equal(result.objects.length,1);assert.equal(result.objects[0].id,s.objects[0].id);assert.ok(length(sub(result.objects[0].world,worldPoint(p.frame,P(84,-28,45))))<1e-6);assert.equal(JSON.stringify(s.objects),before);s.objects.push(clone(s.objects[0]));assert.throws(()=>render(s));});
test('rear cab step and named handhold use physical limb targets on the actual moving car',()=>{const s=scene(),p=s.platforms.find(p=>p.id==='morrow-engine'),body=s.actors[0];body.crouch=true;body.support.local=P(-54,0,32);Object.assign(body,worldPoint(p.frame,body.support.local));s.actions=[{actorId:'mara',contacts:[{carId:p.id,contactId:'engine-rear-step',side:'R',hand:false,kind:'cab-foot-step'}]}];const result=render(s),foot=result.contacts.find(c=>c.kind==='cab-foot-step');assert.ok(foot.reachable);assert.ok(foot.error<1e-5);});

test('Nell and the same Rivet mount keep real stirrup/rein contacts in eight headings without changing world bodies',()=>{for(let i=0;i<8;i++){const s=scene(),horse={id:'rivet',kind:'horse',name:'Rivet',x:100,y:200,z:0,hp:100,facing:i*Math.PI/4,vx:0,vy:0},nell={id:'nell',name:'Nell Sarto',x:100,y:200,z:0,hp:100,mounted:true,mountId:'rivet',facing:horse.facing,holstered:true};s.actors=[nell,horse];s.viewerId='nell';s.actions=[];const result=render(s,i%2===0);assert.equal(result.actors.filter(a=>a.id==='nell').length,1);assert.equal(result.actors.filter(a=>a.id==='rivet').length,1);assert.equal(result.contacts.filter(c=>c.kind==='mounted-stirrup').length,2);assert.ok(result.contacts.every(c=>c.reachable&&c.error<1e-5));assert.deepEqual(result.actors.find(a=>a.id==='nell').world,P(100,200,0));}});

test('actors on the same real deck retain native depth order when authoritative input order is reversed',()=>{
 const s=scene(),p=s.platforms[0],a=s.actors[0],local=P(-28,-10,32),b={...a,id:'tomas',...worldPoint(p.frame,local),support:{...a.support,local}};s.actors=[a,b];s.viewerId='outside';s.actions=[];
 const first=render(s),second=render({...s,actors:[b,a]}),ids=r=>r.drawOrder.filter(x=>x.kind==='actor').map(x=>x.id);assert.deepEqual(ids(first),ids(second));
 for(const body of[a,b])assert.equal(first.drawOrder.find(x=>x.kind==='actor'&&x.id===body.id).key,E.VIEWS.threequarter.depth(body.x,body.y,body.z));
 assert.notEqual(first.drawOrder.find(x=>x.id===a.id&&x.kind==='actor').key,first.drawOrder.find(x=>x.id===b.id&&x.kind==='actor').key);
});
test('a mounted manipulation releases its selected rein and every reported contact matches the final native pose',()=>{
 const horse={id:'rivet',kind:'horse',x:100,y:200,z:0,hp:100,facing:0},body={id:'nell',...horse,mounted:true,mountId:'rivet'};body.id='nell';delete body.kind;const h=createTrainHuman(E,body),mount=createTrainMount(E,horse);mount.update(0,horse);h.rig.update(0,{...body,z:0});let pose=prepareTrainMountedPose(E,h,body,horse,mount),target={...pose.diagnostics.find(c=>c.kind==='mounted-rein'&&c.side==='R').target};pose.restore();target.x+=2;
 pose=prepareTrainMountedPose(E,h,body,horse,mount,{contacts:[{side:'R',target,kind:'signal-grip'}]});try{assert.equal(pose.diagnostics.filter(c=>c.kind==='mounted-rein').length,1);assert.ok(pose.diagnostics.every(c=>c.reachable&&c.error<1e-5));for(const c of pose.diagnostics)assert.ok(length(sub(c.hit,rigWorldPoint(h.rig,pose.root,(c.leg?'foot':'hand')+c.side)))<1e-6);}finally{pose.restore();}
 assert.throws(()=>prepareTrainMountedPose(E,h,body,horse,mount,{contacts:[{side:'R',target},{side:'R',target:{...target,x:target.x+1}}]}),/simultaneous/);
 assert.throws(()=>prepareTrainPose(E,h,body,null,{contacts:[{side:'R',target},{side:'R',target}]}),/simultaneous/);
});
test('mounted required manipulation uses the same injury, held-tool and free-hand guards as a standing actor',()=>{
 const horse={id:'rivet',kind:'horse',x:100,y:200,z:0,hp:100,facing:0},mount=createTrainMount(E,horse);mount.update(0,horse);
 for(const [extra,blocked,freeHands]of[[{id:'juno',injured:true,handInjury:{side:'right',fingers:2}},'injured-hand',true],[{id:'harlan',toolHeld:'shovel',toolHand:'R'},'hand-holds-other-tool',true],[{id:'nell'},'hands-occupied',false]]){
  const body={x:100,y:200,z:0,hp:100,mounted:true,mountId:'rivet',...extra},h=createTrainHuman(E,body);h.rig.update(0,{...body,z:0});const target=P(100,200,48),before=JSON.stringify(body),pose=prepareTrainMountedPose(E,h,body,horse,mount,{freeHands,contacts:[{side:'R',target,kind:'required-control'}]});try{const c=pose.diagnostics.find(c=>c.kind==='required-control');assert.equal(c.blocked,blocked);assert.equal(c.reachable,false);assert.ok(!pose.diagnostics.some(c=>c.kind==='mounted-rein'&&c.side==='R'));assert.equal(JSON.stringify(body),before);}finally{pose.restore();}
 }
});
test('mounted Nell outfit strokes follow her private saddle drawroot while authoritative actor remains at horse ground',()=>{
 const s=scene();s.actors=[{id:'nell',x:100,y:200,z:0,hp:100,mounted:true,mountId:'rivet',facing:0,holstered:true},{id:'rivet',kind:'horse',x:100,y:200,z:0,hp:100,facing:0}];s.actions=[];s.viewerId='nell';const strokes=[],old=E.px.line;E.px.line=(...a)=>{if(a[5]==='#d1b679')strokes.push(a.slice(1,5));return old(...a);};
 try{render(s,false,E.VIEWS.threequarter,(result,renderer)=>{const n=result.actors.find(a=>a.id==='nell'),sh=rigWorldPoint(renderer.humanRig('nell'),n.drawRoot,'shC'),at=E.VIEWS.threequarter.p(sh.x,sh.y,sh.z);assert.equal(strokes.length,1);assert.ok(Math.hypot(strokes[0][0]-(at[0]-8),strokes[0][1]-(at[1]+1))<1e-5);assert.ok(n.drawRoot.z>0);assert.deepEqual(n.world,P(100,200,0));});}finally{E.px.line=old;}
});
