import test from 'node:test';
import assert from 'node:assert/strict';
import '../../my-3d2dge-agent.js';
import {makeFrame,worldPoint,localPoint,interpolateFrame,validFrame,pointVelocity,length,sub} from '../../src/rail-foundation/rigid-frame.js';
import {sweepLanding,sweepMovingCover,stepRailBody,jumpFromSupport,validateBodySupport,validPlatforms,sweepMovingContact,worldContact} from '../../src/rail-foundation/moving-support.js';
import {createRailPath,sampleRail,validateCarSpecs,createConsist,advanceConsist,validateConsist,placeConsist} from '../../src/rail-foundation/rail-consist.js';
const E=globalThis.My3D2dge,P=(x=0,y=0,z=0)=>({x,y,z}),near=(a,b,e=1e-5)=>assert.ok(Math.abs(a-b)<e,`${a} ~= ${b}`),same=(a,b,e=1e-5)=>['x','y','z'].forEach(k=>near(a[k],b[k],e));
const F=(x=0,y=0,z=0,yaw=0,grade=0)=>makeFrame(P(x,y,z),P(Math.cos(yaw),Math.sin(yaw),grade));
const box=(x0,x1,y0,y1,z0,z1)=>({min:P(x0,y0,z0),max:P(x1,y1,z1)});
const deck=(id='roof',bounds=box(-30,30,-10,10,10,10))=>({id,bounds,oneWay:true});
const platform=(id='car',a=F(),b=a,surfaces=[deck()],cover=[])=>({id,previousFrame:a,frame:b,surfaces,cover});
const volume=(id,bounds)=>({id,bounds,bodySolid:true,projectileSolid:true,material:'iron'});
const car=(id='engine',mass=10000)=>({id,length:80,width:40,mass,wheelRadius:10,couplerGap:8,frontCoupler:P(40,0,10),rearCoupler:P(-40,0,10),surfaces:[deck('roof',box(-40,40,-20,20,30,30))],cover:[volume('boiler',box(-10,10,-12,12,0,20))],contacts:[{id:'cab-step',kind:'step',local:P(20,-20,15)}]});
const straight=(grade=0)=>createRailPath({id:'main',segments:[{id:'straight',kind:'line',from:P(),to:P(10000,0,grade*10000),maxSpeed:200}]});
const clone=v=>JSON.parse(JSON.stringify(v));

test('native V3 frames invert world/local points on arbitrary yaw and grade',()=>{for(const yaw of[0,.3,Math.PI/2,Math.PI-1e-5])for(const g of[-.3,0,.2]){const f=F(123,45,9,yaw,g),local=P(-11,7,14);assert.ok(validFrame(f));same(localPoint(f,worldPoint(f,local)),local,1e-7);}});
test('rigid interpolation retains an orthonormal 45-degree midpoint and point velocity includes rotation',()=>{const a=F(),b=F(0,0,0,Math.PI/2),m=interpolateFrame(a,b,.5);assert.ok(validFrame(m));same(worldPoint(m,P(10,0,0)),P(Math.sqrt(50),Math.sqrt(50),0));same(pointVelocity(a,b,P(10,0,0),.1),P(-50*Math.PI,0,0),.01);});
test('nonfinite and degenerate frames are rejected',()=>{assert.throws(()=>makeFrame(P(NaN),P(1)));assert.throws(()=>makeFrame(P(),P()));assert.throws(()=>makeFrame(P(),P(0,0,1)));assert.equal(validFrame({...F(),x:P(2)}),false);});
test('fast moving roofs can be landed on between two outside endpoint footprints',()=>{const p=platform('roof',F(-50),F(50),[deck('roof',box(-5,5,-5,5,10,10))]);const hit=sweepLanding(P(0,0,20),P(0,0,0),[p],.1,{footRadius:1});assert.ok(hit);near(hit.u,.5);same(hit.world,P(0,0,10));same(hit.local,P(0,0,10));});
test('upward and missed-edge crossings cannot attach an actor to the nearest car',()=>{const p=platform();assert.equal(sweepLanding(P(0,0,0),P(0,0,20),[p],.1),null);assert.equal(sweepLanding(P(40,0,20),P(40,0,0),[p],.1),null);assert.equal(sweepLanding(P(29.5,0,20),P(29.5,0,0),[p],.1,{footRadius:1}),null);});
test('landing uses the actual intermediate rotated deck, not either end pose',()=>{const p=platform('rotating',F(),F(0,0,0,Math.PI/2),[deck('roof',box(-15,15,-2,2,10,10))]),x=Math.sqrt(50),hit=sweepLanding(P(x,x,20),P(x,x,0),[p],.1);assert.ok(hit);near(hit.u,.5);same(hit.local,P(10,0,10),1e-4);});
test('translated moving cover and projectile share one relative-motion hit point',()=>{const p=platform('car',F(),F(10),[],[volume('plate',box(-1,1,-2,2,0,10))]),hit=sweepMovingCover(P(-20,0,5),P(20,0,5),[p],.1);assert.ok(hit);near(hit.u,19/30);same(hit.local,P(-1,0,5));same(hit.world,P(16/3,0,5));});
test('thin moving iron crosses a stationary projectile without endpoint tunnelling',()=>{const p=platform('car',F(-50),F(50),[],[volume('thin',box(-.1,.1,-2,2,0,10))]),hit=sweepMovingCover(P(0,0,5),P(0,0,5),[p],.1);assert.ok(hit);near(hit.u,.499);});
test('rotating cover hits at its swept face rather than the static starting box',()=>{const p=platform('car',F(),F(0,0,0,Math.PI/2),[],[volume('door',box(10,20,-1,1,0,10))]),hit=sweepMovingCover(P(0,15,5),P(0,15,5),[p],.1);assert.ok(hit);near(hit.u,Math.acos(1/15)/(Math.PI/2),1e-4);});
test('free native body gravity remains equivalent when there are no moving surfaces',()=>{const a=new E.Body({x:0,y:0,z:30,vx:10,vy:2,vz:-100,onGround:false,gravity:700,r:0}),b=new E.Body({...a});a.update(.1);stepRailBody(b,[],.1);same(a,b);near(a.vz,b.vz);assert.equal(a.onGround,b.onGround);});
test('a real swept landing is carried by subsequent motion and native jump inherits platform velocity once',()=>{const body=new E.Body({x:0,y:0,z:12,vz:-40,onGround:false,gravity:0,r:0});const p=platform('car',F(),F(2));const event=stepRailBody(body,[p],.1);assert.equal(event.kind,'landed');assert.equal(body.support.carId,'car');near(body.x,0);const q=platform('car',F(2),F(4));stepRailBody(body,[q],.1,{relativeVelocity:P()});near(body.x,2);assert.equal(jumpFromSupport(body,[q],.1,220),true);near(body.vx,20);near(body.vz,220);assert.equal(body.support,null);assert.equal(body.onGround,false);});
test('walking across a real gap falls even when the endpoint lies over the next roof',()=>{const a=platform('a',F(),F(),[deck('roof',box(-10,10,-10,10,10,10))]),b=platform('b',F(25),F(25),[deck('roof',box(-10,10,-10,10,10,10))]),body=new E.Body({x:9,y:0,z:10,r:0,gravity:700,onGround:true});body.support={carId:'a',surfaceId:'roof',local:P(9,0,10),relativeVelocity:P()};stepRailBody(body,[a,b],.1,{relativeVelocity:P(100)});assert.equal(body.support,null);assert.equal(body.onGround,false);near(body.x,19);assert.ok(body.z<10);});
test('continuous connected gangway contact transfers support without a car-selection command',()=>{const a=platform('a',F(),F(),[deck('roof',box(-10,10,-10,10,10,10))]),b=platform('b',F(20),F(20),[deck('roof',box(-10,10,-10,10,10,10))]),body=new E.Body({x:9,y:0,z:10,r:0,gravity:700,onGround:true});body.support={carId:'a',surfaceId:'roof',local:P(9,0,10),relativeVelocity:P()};stepRailBody(body,[a,b],.1,{relativeVelocity:P(100)});assert.equal(body.support.carId,'b');near(body.x,19);near(body.z,10);});
test('actual moving body cover stops walking before a closed volume',()=>{const p=platform('car',F(),F(),[deck()],[volume('wall',box(5,6,-10,10,10,60))]),body=new E.Body({x:0,y:0,z:10,r:1,height:20,onGround:true});body.support={carId:'car',surfaceId:'roof',local:P(0,0,10),relativeVelocity:P()};const hit=stepRailBody(body,[p],.1,{relativeVelocity:P(100)});assert.equal(hit.kind,'cover');assert.ok(body.x<=4);assert.equal(body.hitWall,true);});
test('pure support validation rejects duplicate, floating, stale and horse-attached bodies',()=>{const p=platform(),body=new E.Body({x:0,y:0,z:10,r:1,onGround:true});body.support={carId:'car',surfaceId:'roof',local:P(0,0,10),relativeVelocity:P()};assert.equal(validateBodySupport(body,[p]),true);for(const mutate of[b=>{b.supports=[b.support,b.support];},b=>{b.support.local.z=20;},b=>{b.x=2;},b=>{b.attachment={type:'passenger',targetId:'copper'};},b=>{b.support.local.x=Infinity;},b=>{b.support.carId='missing';}]){const bad=clone(body);mutate(bad);assert.equal(validateBodySupport(bad,[p]),false);}assert.equal(validPlatforms([p,p]),false);});
test('rail arc sampling honours variable Bezier parameter speed and a real grade',()=>{const path=createRailPath({id:'curve',segments:[{id:'b',kind:'bezier',from:P(),c1:P(1),c2:P(2),to:P(100),maxSpeed:100}]});near(sampleRail(path,50).frame.origin.x,50,.01);const g=sampleRail(straight(.1),Math.sqrt(101)*10);same(g.frame.origin,P(100,0,10));});
test('disconnected, kinked, duplicate and nonfinite authored track is rejected',()=>{for(const segments of[[{id:'a',kind:'line',from:P(),to:P(100),maxSpeed:100},{id:'b',kind:'line',from:P(101),to:P(200),maxSpeed:100}],[{id:'a',kind:'line',from:P(),to:P(100),maxSpeed:100},{id:'b',kind:'line',from:P(100),to:P(100,100),maxSpeed:100}],[{id:'a',kind:'line',from:P(),to:P(Infinity),maxSpeed:100}],[{id:'a',kind:'line',from:P(),to:P(100),maxSpeed:100},{id:'a',kind:'line',from:P(100),to:P(200),maxSpeed:100}]])assert.throws(()=>createRailPath({id:'bad',segments}));});
test('consist placement keeps unique car IDs and exact physical coupler gaps',()=>{const p=straight(),cars=[car('engine'),car('tender'),car('coach')],s=createConsist(p,cars,{cursor:1000,speed:85});assert.ok(validateConsist(p,cars,s));same(s.cars[1].frame.origin,P(912));same(s.cars[2].frame.origin,P(824));for(let i=1;i<s.cars.length;i++)near(length(sub(s.cars[i].frontCoupler,s.cars[i-1].rearCoupler)),8);assert.throws(()=>createConsist(p,cars,{cursor:10}));assert.equal(validateCarSpecs([cars[0],cars[0]]),false);});
test('85 worldunits per second brakes by actual 150t mass and 90kN force, not an arrival label',()=>{const p=straight(),cars=[car('engine',150000)];let s=createConsist(p,cars,{cursor:1000,speed:85,brakePressure:1});for(let i=0;i<70;i++)s=advanceConsist(p,cars,s,.1,{brake:1},{brakeResponseSeconds:0}).state;near(s.speed,0);near(s.cursor,1000+85*85/(2*15),1e-5);near(s.cars[0].wheelAngle,(s.cursor-1000)/10);assert.equal(s.mission,undefined);assert.equal(s.arrived,undefined);});
test('double mass halves force-derived deceleration and brake response cannot stop an unbraked frame instantly',()=>{const p=straight(),a=[car('a',150000)],b=[car('b',300000)];const sa=createConsist(p,a,{cursor:1000,speed:85,brakePressure:1}),sb=createConsist(p,b,{cursor:1000,speed:85,brakePressure:1});near(advanceConsist(p,a,sa,.1,{brake:1},{brakeResponseSeconds:0}).state.speed,83.5);near(advanceConsist(p,b,sb,.1,{brake:1},{brakeResponseSeconds:0}).state.speed,84.25);const loose=createConsist(p,a,{cursor:1000,speed:85});const r=advanceConsist(p,a,loose,.1,{brake:1},{brakeResponseSeconds:1});near(r.state.brakePressure,1-Math.exp(-.1));assert.ok(r.state.speed>84.9&&r.state.speed<85);assert.ok(r.physics.travel>8.49);});
test('grade and restart change actual acceleration and cursor without resetting the stopped location',()=>{const p=straight(.1),cars=[car('engine',150000)],s=createConsist(p,cars,{cursor:1000,speed:85,brakePressure:1}),r=advanceConsist(p,cars,s,.1,{brake:1},{brakeResponseSeconds:0});near(r.state.speed,85+(-15-9.81*25*.1/Math.sqrt(1.01))*.1);const flat=straight(),stopped=createConsist(flat,cars,{cursor:1234,speed:0});const next=advanceConsist(flat,cars,stopped,.1,{throttle:1},{brakeResponseSeconds:0});near(next.state.cursor,1234+.5*20*.1*.1);near(next.state.speed,2);});
test('curve articulation preserves anchor distance and fixed local supports follow the real curved car',()=>{const k=.5522847498307936,path=createRailPath({id:'bend',segments:[{id:'q',kind:'bezier',from:P(1000,0),c1:P(1000,1000*k),c2:P(1000*k,1000),to:P(0,1000),maxSpeed:200}]}),cars=[car('engine'),car('tender'),car('coach')];const initial=createConsist(path,cars,{cursor:800,speed:85}),r=advanceConsist(path,cars,initial,.1);assert.ok(validateConsist(path,cars,r.state));for(let i=1;i<3;i++)near(length(sub(r.state.cars[i].frontCoupler,r.state.cars[i-1].rearCoupler)),8,1e-5);const platform=r.platforms[1],local=P(5,0,30),world=worldPoint(platform.previousFrame,local),body=new E.Body({...world,onGround:true,r:1});body.support={carId:'tender',surfaceId:'roof',local,relativeVelocity:P()};stepRailBody(body,r.platforms,.1);same(body,worldPoint(platform.frame,local));assert.ok(Math.abs(body.vx)>1&&Math.abs(body.vy)>1);assert.ok(validateBodySupport(body,r.platforms));});
test('train snapshot validation rejects forged poses, duplicated cars and nonfinite movement',()=>{const p=straight(),cars=[car('engine'),car('tender')],s=createConsist(p,cars,{cursor:1000,speed:85});for(const mutate of[q=>{q.cars[1].id='engine';},q=>{q.cars[1].frame.origin.x+=1;},q=>{q.speed=Infinity;},q=>{q.cars[1].cursor=q.cars[0].cursor;}]){const bad=clone(s);mutate(bad);assert.equal(validateConsist(p,cars,bad),false);}assert.throws(()=>advanceConsist(p,cars,s,1));});

test('a side volume blocks forward boarding before the remaining fall lands safely on the near roof',()=>{const p=platform('car',F(),F(),[deck('roof',box(-20,20,-10,10,10,10))],[volume('front-wall',box(-5,-4,-10,10,0,40))]),body=new E.Body({x:-10,y:0,z:20,vx:200,vz:-200,gravity:0,r:0,height:10,onGround:false});const hit=stepRailBody(body,[p],.1);assert.equal(hit.kind,'cover');assert.equal(hit.contact.volumeId,'front-wall');near(hit.contact.u,.25);assert.equal(hit.after.kind,'landed');assert.ok(body.x<-5,'the full body remains outside the wall');near(body.vx,0);near(body.z,10);assert.equal(body.support.surfaceId,'roof');assert.equal(validateBodySupport(body,[p]),true);});
test('an upward jump hits the same moving roof volume from below and cannot be snapped aboard',()=>{const p=platform('car',F(),F(),[deck('roof',box(-30,30,-10,10,20,20))],[volume('roof',box(-30,30,-10,10,18,20))]),body=new E.Body({x:0,y:0,z:0,vz:200,gravity:0,r:0,height:10,onGround:false});const hit=stepRailBody(body,[p],.1);assert.equal(hit.kind,'cover');assert.equal(body.support,undefined);assert.ok(body.z<=8+1e-4);near(body.vz,0);});
test('a supporting roof does not become a false wall under an upright body on graded rail',()=>{const a=F(0,0,0,0,.1),b=F(2,0,.2,0,.1),p=platform('car',a,b,[deck()],[volume('roof',box(-30,30,-10,10,8,10))]),local=P(0,0,10),body=new E.Body({...worldPoint(a,local),r:1,height:20,onGround:true});body.support={carId:'car',surfaceId:'roof',local,relativeVelocity:P()};const result=stepRailBody(body,[p],.1,{relativeVelocity:P(10)});assert.equal(result.kind,'supported');same(body,worldPoint(b,P(1,0,10)));});

test('paused accepted time preserves complete body/consist bytes even when brake controls change',()=>{const p=straight(),cars=[car('engine')],state=createConsist(p,cars,{cursor:1000,speed:85}),before=JSON.stringify(state),result=advanceConsist(p,cars,state,0,{brake:1},{brakeResponseSeconds:0});assert.equal(JSON.stringify(result.state),before);assert.equal(JSON.stringify(state),before);const body=new E.Body({x:0,y:0,z:50,landed:true,hitWall:true}),raw=JSON.stringify(body);assert.equal(stepRailBody(body,[],0).kind,'paused');assert.equal(JSON.stringify(body),raw);});


test('moving hand contacts require actual world intersection, never a remote requested control ID',()=>{const p=platform('car',F(),F(10));p.contacts=[{id:'brake',kind:'control',local:P(5,0,20)}];assert.equal(sweepMovingContact(P(-100,0,20),P(-90,0,20),[p],.1,{contactId:'brake'}),null);const hit=sweepMovingContact(P(5,0,20),P(5,0,20),[p],.1,{radius:1,contactId:'brake'});assert.ok(hit);near(hit.u,0);assert.ok(hit.distance<=1);same(worldContact(p,'brake'),P(15,0,20));assert.equal(sweepMovingContact(P(5,0,20),P(5,0,20),[p],.1,{contactId:'other'}),null);});
test('native departure inherits grade and rotational point velocity rather than only the car centre velocity',()=>{const theta=Math.atan(.2),a=F(),b=F(5,0,1,0,.2),p=platform('car',a,b),local=P(10,0,10),body=new E.Body({...worldPoint(a,local),onGround:true,r:0});body.support={carId:'car',surfaceId:'roof',local,relativeVelocity:P()};stepRailBody(body,[p],.1);assert.equal(jumpFromSupport(body,[p],.1,220),true);near(body.vx,50-10*(Math.sin(theta)+Math.cos(theta))*theta/.1,.002);near(body.vz,10+10*(Math.cos(theta)-Math.sin(theta))*theta/.1+220,.002);});

const authored=await import('./fixtures/brass-cutting-authoring.mjs');
test('isolated original authoring declares one coherent seven-car 150t consist and twelve geometrically legal initial inhabitants',()=>{
 const path=createRailPath(authored.TRAIN_TRACK),cars=authored.TRAIN_CARS,state=createConsist(path,cars,{cursor:1200,speed:authored.TRAIN_MOTION_PROPOSAL.approachSpeed});assert.equal(cars.length,7);assert.equal(cars.reduce((n,c)=>n+c.mass,0),150000);assert.equal(new Set(cars.map(c=>c.id)).size,7);
 const initial=[...authored.TRAIN_MOVING_CREW,...authored.TRAIN_NEW_CAST.filter(a=>a.initialSupport).map(a=>({...a,...a.initialSupport}))];assert.equal(initial.length,12);
 const motion=advanceConsist(path,cars,state,.1,{brake:1},authored.TRAIN_MOTION_PROPOSAL);for(const actor of initial){const p=motion.platforms.find(p=>p.id===actor.carId),body=new E.Body({...worldPoint(p.previousFrame,actor.local),r:9,height:53,onGround:true});body.support={carId:actor.carId,surfaceId:actor.surfaceId,local:{...actor.local},relativeVelocity:P()};assert.ok(validateBodySupport(body,motion.platforms,{previous:true}),actor.id);stepRailBody(body,motion.platforms,.1,{relativeVelocity:P()});assert.ok(validateBodySupport(body,motion.platforms),actor.id);}
 assert.equal(authored.TRAIN_AUTHORING_STATUS,'isolated_original_authoring_runtime_unimplemented');assert.equal(state.mission,undefined);
});

test('a translating wall collision resolves the remaining accepted time instead of leaving a body inside its future pose',()=>{const p=platform('car',F(-10),F(10),[],[volume('wall',box(-1,1,-3,3,0,20))]),body=new E.Body({x:0,y:0,z:0,r:0,height:10,gravity:0,onGround:true});const event=stepRailBody(body,[p],.1);assert.equal(event.kind,'cover');assert.ok(body.x>=11-1e-5);near(body.vx,200,.01);});
test('extremely slow outward edge motion cannot repeatedly reattach to the same zero-time boundary',()=>{const p=platform('car',F(),F(),[deck('roof',box(-10,10,-10,10,10,10))]),body=new E.Body({x:10,y:0,z:10,r:0,onGround:true,gravity:700});body.support={carId:'car',surfaceId:'roof',local:P(10,0,10),relativeVelocity:P()};stepRailBody(body,[p],.1,{relativeVelocity:P(.00001)});assert.equal(body.support,null);assert.equal(body.onGround,false);assert.ok(body.z<10);});
test('attached bodies are never independently integrated and nonfinite contact geometry fails pure validation',()=>{const body=new E.Body({x:0,y:0,z:25});body.attachment={type:'carried',targetId:'mara'};const before=JSON.stringify(body);assert.throws(()=>stepRailBody(body,[],.1));assert.equal(JSON.stringify(body),before);const p=platform();p.contacts=[{id:'bad',kind:'control',local:P(Infinity)}];assert.equal(validPlatforms([p]),false);});

test('finite inputs cannot hide overflowed geometry/mass, and infinite controls cannot become a full regulator',()=>{assert.throws(()=>createRailPath({id:'huge',segments:[{id:'h',kind:'line',from:P(-1e308),to:P(1e308),maxSpeed:100}]}));assert.equal(validateCarSpecs([car('a',1e308),car('b',1e308)]),false);const p=straight(),cars=[car()],s=createConsist(p,cars,{cursor:1000,speed:85});const raw=JSON.stringify(s);for(const controls of[{throttle:Infinity},{brake:-Infinity},{throttle:'1'}])assert.throws(()=>advanceConsist(p,cars,s,.1,controls));assert.equal(JSON.stringify(s),raw);assert.throws(()=>advanceConsist(p,cars,s,.1,{throttle:1},{tractionForceN:1e308,worldUnitsPerMeter:1e308}));});
test('reaching an unauthored track end cannot silently relocate or declare the consist stopped',()=>{const path=createRailPath({id:'short',segments:[{id:'s',kind:'line',from:P(),to:P(1000),maxSpeed:200}]}),cars=[car()],state=createConsist(path,cars,{cursor:959,speed:85}),before=JSON.stringify(state);assert.throws(()=>advanceConsist(path,cars,state,.1),/endpoints|path/);assert.equal(JSON.stringify(state),before);});

test('brake release finds the first stop even if the final unconstrained velocity becomes positive again',()=>{const p=straight(),cars=[car('engine',150000)],state=createConsist(p,cars,{cursor:1000,speed:.001,brakePressure:.6}),r=advanceConsist(p,cars,state,.1,{throttle:1,brake:0},{tractionForceN:52000,maxBrakeForceN:90000,brakeResponseSeconds:.6,rollingResistanceN:0});const turn=-.6*Math.log((52000/150000*25)/9);near(r.physics.restartTime,turn,1e-9);assert.ok(r.physics.stopTime>0&&r.physics.stopTime<turn);let previous=1000;for(let n=0;n<=100;n++){const x=r.platforms[0].frameAt(n/100).origin.x;assert.ok(x>=previous-1e-9,'no hidden reverse interval in collision/support poses');previous=x;}const delta=.1-turn,A=52000/150000*25,B=-9,expected=.5*A*delta*delta+B*.6*(Math.exp(-turn/.6)*delta-.6*(Math.exp(-turn/.6)-Math.exp(-.1/.6)));assert.ok(r.physics.travel>=expected&&r.physics.travel-expected<.00001);assert.ok(r.state.speed>0);});
test('a held zero-speed train restarts within the step at the actual force change, without a whole-step freeze',()=>{const p=straight(),cars=[car('engine',150000)],state=createConsist(p,cars,{cursor:1000,speed:0,brakePressure:.6}),r=advanceConsist(p,cars,state,.1,{throttle:1,brake:0},{tractionForceN:52000,maxBrakeForceN:90000,brakeResponseSeconds:.6,rollingResistanceN:0});const turn=-.6*Math.log((52000/150000*25)/9);near(r.physics.stopTime,0);near(r.physics.restartTime,turn);near(r.platforms[0].frameAt(turn/.1/2).origin.x,1000,1e-9);assert.ok(r.state.cursor>1000&&r.state.speed>0);});
test('malformed null geometry is rejected by pure validators without an exception or mutation',()=>{const p=platform(),bad=clone(p);bad.surfaces=[null];assert.equal(validPlatforms([bad]),false);const spec=car();spec.cover=[null];assert.equal(validateCarSpecs([spec]),false);});

test('render/query fractions cannot sample invented future motion outside the accepted step',()=>{const p=straight(),cars=[car()],s=createConsist(p,cars,{cursor:1000,speed:85}),r=advanceConsist(p,cars,s,.1);assert.throws(()=>r.platforms[0].frameAt(2));assert.throws(()=>worldContact({...r.platforms[0],contacts:[{id:'b',local:P()}]},'b',NaN));assert.equal(s.cursor,1000);});
