/** Classification-cache tests use a small async transaction protocol stub.
 * Native IndexedDB durability/abort behavior remains the browser suite's job. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {createSaveRepository,SAVE_DATABASE_STORE,SAVE_DATABASE_LAST_SLOT} from '../src/save-database.js';
import {LEGACY_SAVE_KEY,CAMPAIGN_SAVE_KEY,MERCY_SAVE_KEY} from '../src/save-slots.js';
const raw=(mode,n=0)=>JSON.stringify({mode,payload:{n}});
function storage(entries=[]){const values=new Map(entries);return{values,getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,String(v)),removeItem:k=>values.delete(k)};}
function codec(){const calls=new Map(),states=[];return{calls,states,restore(bytes){calls.set(bytes,(calls.get(bytes)||0)+1);const s=JSON.parse(bytes);if(!s||!['campaign','mercy'].includes(s.mode)||!s.payload)return null;states.push(s);return s;},modeOf:s=>s.mode};}
function memoryDatabase(entries=[]){const db={records:new Map(entries),objectStoreNames:{contains:name=>name===SAVE_DATABASE_STORE},close(){},transaction(name,mode){assert.equal(name,SAVE_DATABASE_STORE);const tx=new EventTarget(),view=new Map(db.records);let pending=0,finished=false;const finish=()=>setImmediate(()=>{if(finished||pending)return;finished=true;if(mode==='readwrite')db.records=view;tx.dispatchEvent(new Event('complete'));});const enqueue=fn=>{pending++;queueMicrotask(()=>{if(finished)return;fn();pending--;finish();});};tx.abort=()=>{if(finished)return;finished=true;tx.dispatchEvent(new Event('abort'));};tx.objectStore=()=>({get(key){const request={};enqueue(()=>{request.result=view.get(key);request.onsuccess?.({target:request});});return request;},put(value,key){enqueue(()=>view.set(key,value));return{};},openCursor(){const request={},items=[...view];let i=0;const step=()=>enqueue(()=>{const entry=items[i++];request.result=entry?{key:entry[0],value:entry[1],continue:step}:null;request.onsuccess?.({target:request});});step();return request;}});finish();return tx;}};return{db,factory:{open(){const request={};queueMicrotask(()=>{request.result=db;request.onsuccess?.({target:request});});return request;}}};}

test('same exact bytes reuse classification across migration, cleanup, requested/last-slot checks and public menu metadata',async()=>{const a=raw('campaign'),b=raw('mercy'),legacy=storage([[CAMPAIGN_SAVE_KEY,a],[MERCY_SAVE_KEY,b],[LEGACY_SAVE_KEY,a]]),backend=memoryDatabase(),c=codec(),repo=createSaveRepository({...c,...backend,legacyStorage:legacy});assert.equal(await repo.ready,true);assert.equal(c.calls.get(a),1);assert.equal(c.calls.get(b),1);assert.deepEqual(repo.candidates('campaign'),[a]);assert.deepEqual(repo.candidates('campaign'),[a]);assert.equal(repo.candidateMode(a),'campaign');assert.equal(c.calls.get(a),1,'slot, last-slot and wanted-slot checks do not restore again');assert.equal(legacy.getItem(CAMPAIGN_SAVE_KEY),null);assert.equal(legacy.getItem(MERCY_SAVE_KEY),null);
 const prior=c.states.find(s=>s.mode==='campaign');prior.mode='mercy';prior.payload.n=99;assert.equal(repo.candidateMode(a),'campaign','only scalar metadata is retained');const candidates=await repo.loadCandidates('campaign'),loaded=c.restore(candidates[0]);assert.equal(c.calls.get(a),2,'actual caller loading still performs a fresh owning restore');assert.notEqual(loaded,prior);assert.deepEqual(loaded,JSON.parse(a));await repo.close();});

test('new/corrupt bytes are validated and cached classifications never turn stale database bytes into authority',async()=>{const a=raw('campaign'),b=raw('mercy'),backend=memoryDatabase([[CAMPAIGN_SAVE_KEY,a],[MERCY_SAVE_KEY,b],[SAVE_DATABASE_LAST_SLOT,CAMPAIGN_SAVE_KEY]]),c=codec(),repo=createSaveRepository({...c,...backend,legacyStorage:storage()});await repo.ready;assert.deepEqual(repo.candidates('campaign'),[a]);const changed=raw('campaign',1);backend.db.records.set(CAMPAIGN_SAVE_KEY,changed);assert.deepEqual(await repo.loadCandidates('campaign'),[changed]);assert.equal(c.calls.get(changed),1);backend.db.records.set(CAMPAIGN_SAVE_KEY,'{corrupt');assert.deepEqual(await repo.loadCandidates('campaign'),[]);assert.equal(c.calls.get('{corrupt'),1);assert.deepEqual(repo.candidates('campaign'),[]);assert.equal(c.calls.get('{corrupt'),1,'an exact corrupt result can be reused only as null');assert.equal(repo.candidateMode(a),'campaign','metadata remains distinct from actual slot authority');assert.deepEqual(repo.candidates('campaign'),[]);
 backend.db.records.set(CAMPAIGN_SAVE_KEY,b);assert.equal(repo.candidateMode(b),'mercy');assert.deepEqual(await repo.loadCandidates('campaign'),[],'valid other-mode bytes in the wrong canonical slot are refused');assert.deepEqual(repo.candidates('mercy'),[b]);await assert.rejects(repo.save(CAMPAIGN_SAVE_KEY,b),/valid owned save/);await repo.close();});

test('cross-mode candidate order and recovery copies retain their exact classification without sharing decoded states',async()=>{const a=raw('campaign'),b=raw('mercy'),older=raw('campaign',-1),backend=memoryDatabase([[CAMPAIGN_SAVE_KEY,a],[MERCY_SAVE_KEY,b],[SAVE_DATABASE_LAST_SLOT,CAMPAIGN_SAVE_KEY],['recovery:campaign:older',older]]),c=codec(),repo=createSaveRepository({...c,...backend,legacyStorage:storage()});await repo.ready;assert.deepEqual(repo.candidates('mercy'),[b,a],'existing last-world candidate order is preserved for the caller mode policy');assert.equal(repo.candidateMode(b),'mercy');assert.equal(repo.candidateMode(a),'campaign');const recovery=repo.recoveries();assert.deepEqual(recovery,[{key:'recovery:campaign:older',slot:CAMPAIGN_SAVE_KEY,raw:older}]);assert.deepEqual(repo.recoveries(),recovery);assert.equal(c.calls.get(older),1);recovery[0].raw='replaced outside';assert.equal(repo.recoveries()[0].raw,older);assert.equal(c.calls.get(a),1);assert.equal(c.calls.get(b),1);await repo.close();});

test('four-entry per-repository LRU evicts old raw keys, treats distinct bytes separately and never persists validation metadata',async()=>{const c=codec(),legacy=storage(),repo=createSaveRepository({...c,factory:null,legacyStorage:legacy});assert.equal(await repo.ready,false);const values=Array.from({length:5},(_,n)=>raw('campaign',n));for(const value of values.slice(0,4))assert.equal(repo.candidateMode(value),'campaign');assert.equal(repo.candidateMode(values[0]),'campaign');assert.equal(repo.candidateMode(values[4]),'campaign');assert.equal(repo.candidateMode(values[1]),'campaign');assert.equal(c.calls.get(values[1]),2,'least recently used raw key was evicted');const whitespace=' '+values[4];assert.equal(repo.candidateMode(whitespace),'campaign');assert.equal(c.calls.get(whitespace),1,'new exact bytes require their own codec validation');for(const value of[null,{},undefined])assert.equal(repo.candidateMode(value),null);assert.deepEqual([...legacy.values],[],'no disk/legacy cache is written');const second=createSaveRepository({...c,factory:null,legacyStorage:null});await second.ready;assert.equal(second.candidateMode(values[4]),'campaign');assert.equal(c.calls.get(values[4]),2,'a new repository has no inherited validation authority');await repo.close();await second.close();});

test('fallback rejects corrupt or cross-slot canonical bytes while preserving a valid legacy other-world candidate',async()=>{const a=raw('campaign'),b=raw('mercy'),legacy=storage([[CAMPAIGN_SAVE_KEY,b],[LEGACY_SAVE_KEY,a]]),c=codec(),repo=createSaveRepository({...c,factory:null,legacyStorage:legacy});await repo.ready;assert.deepEqual(repo.candidates('campaign'),[a]);assert.equal(c.calls.get(b),1);legacy.setItem(LEGACY_SAVE_KEY,'bad');assert.deepEqual(repo.candidates('campaign'),[]);assert.deepEqual(repo.recoveries(),[{key:CAMPAIGN_SAVE_KEY,slot:MERCY_SAVE_KEY,raw:b}],'valid misfiled bytes remain explicit recovery material');assert.equal(c.calls.get('bad'),1);await repo.close();});
