/** Explicit v4 component evidence. Layout/default3, actors, routes and Save
 * markers are not upgraded by these tests or the pure geometry API. */
import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import{gunzipSync}from'node:zlib';
import '../my-3d2dge-agent.js';
import{capturePreparationBodyBounds,DEFAULT_PREPARATION_BODY_GEOMETRY_VERSION}from'../src/train-preparation-layout.js';
import{preparationNativeBodyParts,preparationNativeLocomotionParts,preparationNativeTorsoParts}from'../src/train-preparation-body-geometry.js';
import{createTrainHuman,rigWorldPoint}from'../src/train-native/rigs.js';
import{captureNativeGroundLocomotion}from'../src/train-native/locomotion-state.js';
import{createHeldBox,compileHeldBoxSet,heldBoxContacts}from'../src/train-held-volume.js';
import{makeFrame,localPoint,sub,length}from'../src/rail-foundation/rigid-frame.js';
const E=globalThis.My3D2dge,P=(x=0,y=0,z=0)=>({x,y,z}),axes=['x','y','z'],copy=structuredClone,root=P(600,900),zeroPoses=()=>({cheer:0,cast:0,guard:0,kneel:0,crouch:0,wave:0,hips:0,block:0});
const raw=()=>JSON.parse(gunzipSync(readFileSync(new URL('./fixtures/train-preparation-pr9-mask-owned-bring.json.gz',import.meta.url))).toString());
const inside=(p,b)=>{const q=localPoint(b.frame,p);return axes.every(k=>Math.abs(q[k])<=b.halfExtents[k]+1e-7);},covered=(p,parts)=>parts.some(b=>inside(p,b));
function rigFor(id='inez'){const r=createTrainHuman(E,{id}).rig;r.t=0;r.phase=0;r.spW=1;r.mv=[1,0];r.facing=0;r._cheat=0;r.o.cheat=0;r.downW=0;r.poseW=zeroPoses();r._pose();return r;}
// Independent finite bone-box reconstruction, including all eight corners.
function bone(rig,a,b){const x=rigWorldPoint(rig,root,a),y=rigWorldPoint(rig,root,b),d=sub(y,x),n=length(d),radius=Math.max(2,rig.o.limbW)*rig.o.size;return createHeldBox({id:a+b,frame:n<1e-7?makeFrame(x,P(1,0,0)):makeFrame(P(...axes.map(k=>(x[k]+y[k])/2)),d,Math.abs(d.z/n)>.95?P(0,1,0):P(0,0,1)),halfExtents:n<1e-7?P(radius,radius,radius):P(n/2+radius,radius,radius)});}
function drawVertices(rig){const o=rig.o,J=rig.J,a=(rig.downW||0)*Math.PI/2*.96,at=(q,f=0,r=0,z=0)=>rigWorldPoint(rig,root,[q[0]+f*Math.cos(a)-z*Math.sin(a),q[1]+r,q[2]+f*Math.sin(a)+z*Math.cos(a)]),mix=(x,y)=>P(...axes.map(k=>(x[k]+y[k])/2)),shL=at(J.shL,0,-.4),shR=at(J.shR,0,.4),vertices=[shL,shR,mix(at(J.hipR,0,.2),shR),at(J.hipR,0,.25,.5),at(J.hipL,0,-.25,.5),mix(at(J.hipL,0,-.2),shL),at(J.hipC,0,0,.8),at(J.shC,0,0,-.4)];if(['coat','tunic','robe'].includes(o.outfit)){const hz=Math.max(J.hipL[2],J.hipR[2])+.9,len=o.outfit==='robe'?hz-.6:o.outfit==='coat'?hz*.62:hz*.42,fl=o.outfit==='robe'?1.55:1.3,dep=o.torsoW*.7,tail=o.outfit==='coat'?-1.2-2.2*Math.min(1,rig.spW):0;vertices.push(...[[J.hipC[0],-o.hipHalf*1.25,hz],[J.hipC[0],o.hipHalf*1.25,hz],[J.hipC[0]+tail*.5,o.hipHalf*1.25*fl,hz-len],[J.hipC[0]+tail*.5,-o.hipHalf*1.25*fl,hz-len],[J.hipC[0]+dep,0,hz],[J.hipC[0]+(o.outfit==='coat'?dep*.3:dep*fl),0,hz-len*(o.outfit==='coat'?.45:1)],[J.hipC[0]-dep*fl+tail,0,hz-len],[J.hipC[0]-dep,0,hz]].map(q=>at(q)));}for(const side of['L','R'])vertices.push(at(J['foot'+side],1.9,0,.3));return vertices;}
function checkRig(rig,label){const before=JSON.stringify({o:rig.o,J:rig.J,t:rig.t,phase:rig.phase,mv:rig.mv,spW:rig.spW,sq:rig.sq}),parts=preparationNativeLocomotionParts(rig,root);assert.ok(parts.every(p=>Object.isFrozen(p)&&p.vertices.every(Object.isFrozen)));for(const key of['hipL','hipR','kneeL','kneeR','footL','footR','shL','shR','elbowL','elbowR','handL','handR','head'])assert.ok(covered(rigWorldPoint(rig,root,key),parts),label+' joint '+key);for(const side of['L','R'])for(const[a,b]of[['hip','knee'],['knee','foot'],['sh','elbow'],['elbow','hand']])for(const p of bone(rig,a+side,b+side).vertices)assert.ok(covered(p,parts),label+' finite '+a+b+side);for(const p of drawVertices(rig))assert.ok(covered(p,parts),label+' native draw vertex');for(const part of preparationNativeTorsoParts(rig,root,{moving:true}))for(const p of part.vertices)assert.ok(covered(p,parts),label+' finite torso '+part.id);assert.equal(JSON.stringify({o:rig.o,J:rig.J,t:rig.t,phase:rig.phase,mv:rig.mv,spW:rig.spW,sq:rig.sq}),before,'enclosure never edits native motion or dimensions');return parts;}

test('explicit v4 covers the actual Inez sideways foot miss while exact historical v3 remains unchanged',()=>{const s=raw(),before=JSON.stringify(s),rows=capturePreparationBodyBounds(s,{geometryVersion:3}),original=rows.find(r=>r.id==='inez'),r3={...original,pose:{...original.pose,facing:0,vx:0,vy:65}},r4={...r3,geometryVersion:4},old=preparationNativeBodyParts(r3,[r3]),legacy=JSON.stringify(old),next=preparationNativeBodyParts(r4,[r4]),rig=rigFor();rig.phase=-Math.PI/2;rig.mv=[0,1];rig._pose();const point=original.point;for(const side of['L','R']){const foot=rigWorldPoint(rig,point,'foot'+side);assert.equal(covered(foot,old),false,'original v3 counterexample stays genuinely reproduced');assert.equal(covered(foot,next),true,'v4 encloses the real sideways foot');const panel=createHeldBox({id:'real-side-foot-'+side,frame:makeFrame(foot,P(1,0,0)),halfExtents:P(.001,.001,.001)}),set=compileHeldBoxSet([{box:panel,ownerId:'component-panel'}],{id:side});assert.ok(next.some(p=>heldBoxContacts(p,set).some(h=>h.interiorOverlap)));assert.ok(old.every(p=>heldBoxContacts(p,set).length===0));}assert.deepEqual(next.filter(p=>!p.id.startsWith('locomotion-')),old,'v4 adds coverage without shrinking/replacing a historical primitive');assert.equal(JSON.stringify(preparationNativeBodyParts(r3,[r3])),legacy);assert.equal(next.find(p=>p.id==='root-foot').halfExtents.x,9);assert.equal(DEFAULT_PREPARATION_BODY_GEOMETRY_VERSION,3,'component support is not a live/default or Save migration');assert.equal(JSON.stringify(s),before);});

test('analytical bands cover native joints, finite bone corners and torso/coat vertices across adversarial phases, all relative movement headings and squash',()=>{let count=0;for(const id of['inez','hob'])for(let heading=0;heading<8;heading++)for(let direction=0;direction<8;direction++)for(const phase of[-Math.PI/2,0,Math.PI/4,1.23456789]){const rig=rigFor(id),n=count++;rig.facing=heading*Math.PI/4+.03;rig.mv=[Math.cos(direction*Math.PI/4),Math.sin(direction*Math.PI/4)];rig.phase=phase;rig.t=n*.37;rig.spW=[0,.37,1,1.25][(heading+direction+Math.round((phase+Math.PI)*10))%4];rig.sq=[-.3,0,.3][(heading+direction)%3];rig.poseW.crouch=[0,.5,1][(heading+2*direction+n)%3];rig._pose();checkRig(rig,`${id}/${heading}/${direction}/${phase}`);}assert.equal(count,512);});

test('valid custom profiles, advanced pose/down fallback and tiny-target IK receive conservative bounds or explicit refusal',()=>{for(const profile of[{size:.8,legUpper:12,legLower:3,hipZ:7,armUpper:8,armLower:2,torsoW:8,hipHalf:4,shoulderHalf:2,lean:.35,hunch:.4},{size:2.1,legUpper:4,legLower:11,hipZ:6,armUpper:2,armLower:9,torso:12,stride:10,footSpread:4,torsoW:5,outfit:'robe'},{size:1.1,torso:30,torsoW:25,lean:1.2,outfit:'tunic'},{size:1.3,hipZ:100,torso:100,legUpper:2,legLower:2,armUpper:2,armLower:2,headR:.25,neck:.2,hipHalf:.5,shoulderHalf:.5,torsoW:.25,stride:3,lift:.5,outfit:'shirt'}]){const rig=new E.Humanoid({...profile,weapon:null,cheat:0});rig.poseW=zeroPoses();rig.downW=0;rig.facing=.7;rig.spW=1;rig.mv=[.6,.8];rig.phase=2.3;for(const sq of[-.3,0,.3]){rig.sq=sq;rig._pose();checkRig(rig,'custom/'+sq);}}for(const down of[0,.25,1])for(const sq of[-.3,0,.3])for(const pose of['guard','kneel','cheer','cast','wave','hips','block']){const rig=rigFor();rig.poseW[pose]=.5;rig.downW=down;rig.sq=sq;rig.mv=[0,-1];rig.phase=-1.3;rig._pose();checkRig(rig,`advanced/${pose}/${down}`);}for(const mutate of[r=>r.o.legUpper=NaN,r=>r.o.size=0,r=>r.o.armUpper=1e200,r=>r.o.cape={len:6},r=>r.atkW=.1,r=>r.airW=.1,r=>r.mv=[2,0],r=>r.spW=NaN,r=>r.phase=Infinity,r=>r.poseW={}]){const rig=rigFor(),before=JSON.stringify(rig.J);mutate(rig);assert.throws(()=>preparationNativeLocomotionParts(rig,root));assert.equal(JSON.stringify(rig.J),before);}});

test('explicit native motion record retains braking gait coverage at zero body velocity without rewriting actor/history',()=>{const s=raw(),rows=capturePreparationBodyBounds(s,{geometryVersion:3}),old=rows.find(r=>r.id==='inez'),r4={...old,geometryVersion:4,point:root,sourcePoint:root,pose:{...old.pose,facing:0,vx:0,vy:0}},rig=rigFor();rig.spW=.6;rig.mv=[0,1];rig.phase=-Math.PI/2;rig.t=3;rig._pose();const locomotion=JSON.parse(JSON.stringify(captureNativeGroundLocomotion(rig))),before=JSON.stringify({r4,locomotion}),without=preparationNativeBodyParts(r4,[r4]),parts=preparationNativeBodyParts(r4,[r4],{locomotion});assert.ok(!without.some(p=>p.id.startsWith('locomotion-')),'velocity-only reconstruction cannot invent lost braking state');assert.ok(parts.some(p=>p.id==='locomotion-lower'));assert.ok(['L','R'].some(side=>!covered(rigWorldPoint(rig,root,'foot'+side),without)),'the real retained braking foot is absent from velocity-only reconstruction');for(const side of['L','R'])assert.ok(covered(rigWorldPoint(rig,root,'foot'+side),parts));assert.equal(JSON.stringify({r4,locomotion}),before);const bad=copy(locomotion);bad.profile.size+=.001;assert.throws(()=>preparationNativeBodyParts(r4,[r4],{locomotion:bad}));assert.throws(()=>preparationNativeBodyParts({...r4,geometryVersion:3},[r4],{locomotion}));assert.throws(()=>preparationNativeBodyParts(r4,[r4],{locomotion:{...locomotion,facing:.1}}));});

test('tall short-arm profile keeps positive lower bands conservative at negative squash',()=>{const rig=new E.Humanoid({size:1.3,hipZ:100,torso:100,legUpper:2,legLower:2,armUpper:2,armLower:2,headR:.25,neck:.2,hipHalf:.5,shoulderHalf:.5,torsoW:.25,stride:3,lift:.5,outfit:'shirt',weapon:null,cheat:0});rig.poseW=zeroPoses();rig.downW=0;rig.facing=0;rig.spW=1;rig.mv=[0,1];rig.phase=-Math.PI/2;rig.sq=-.3;rig._pose();const parts=checkRig(rig,'tall negative squash'),upper=parts.find(p=>p.id==='locomotion-upper'),hand=rigWorldPoint(rig,root,'handR');assert.ok(upper.frame.origin.z-upper.halfExtents.z<hand.z,'positive lower height uses .7size, not the1.3size upper scale');assert.ok(inside(hand,upper),'actual sideways high hand belongs to its upper band');});

test('the separate bound-prone transform refuses an unowned moving v4 claim while historical3 remains intact',()=>{const s=raw(),rows=capturePreparationBodyBounds(s,{geometryVersion:3}),original=rows.find(r=>r.id==='levi'),r3={...original,binding:{type:'free',regionId:'snowbound'},rootId:'levi',pose:{...original.pose,vx:10,vy:0}},r4={...r3,geometryVersion:4},before=JSON.stringify({r3,r4});assert.ok(preparationNativeBodyParts(r3,[r3]).length>0);assert.throws(()=>preparationNativeBodyParts(r4,[r4]),/separate native motion owner/);assert.equal(JSON.stringify({r3,r4}),before);});
