import {followPreparationGuideNative} from './helpers/train-preparation-route.mjs';
import test from 'node:test';import assert from 'node:assert/strict';
import {Journey,acceptedBriefingNative,moveNative,trainRecord} from './helpers/train-preparation-route.mjs';
import {interactNative,chooseNative} from './helpers/train-clinic-route.mjs';
import {createTrainCampPresentation,activePreparationCampWorkPose,ownsTrainCampActor,ownsPreparationCampProp,createPreparationMaterialDetail} from '../src/train-camp-presentation.js';
import {watchDiscussionNative,beginWatchReliefNative} from './helpers/train-watch-route.mjs';
import {getPreparationWorkPose,preparationPlayerApproach} from '../src/train-preparation-work.js';
import * as Camp from '../content/campaign/train-preparation-camp.js';
import {TRAIN_MASK_ID,TRAIN_MASK_APPROACHES,TRAIN_MASK_FOLDED_CENTER} from '../content/campaign/train-gear-data.js';
const E=globalThis.My3D2dge,RIVAL='snowbound-the-names-they-took',prep=s=>trainRecord(s).train.preparation,powder=s=>trainRecord(s).train.powder;
function wait(s,predicate,max=800){for(let i=0;!predicate()&&i<max;i++)Journey.stepCampaign(s,.05);assert.ok(predicate(),'actual native prerequisite/work completes');}
function begin(){const s=acceptedBriefingNative();moveNative(s,{x:790,y:1205});interactNative(s,'train:prepare-call');moveNative(s,Camp.TRAIN_STORE_MARA);interactNative(s,'train:prepare-talk:store');wait(s,()=>!!s.dialog);while(s.dialog)chooseNative(s,'train-prepare-next');wait(s,()=>!!prep(s).campSetup.sites['quarry-charge-worktop']);return s;}
const context=()=>new Proxy({globalAlpha:1,globalCompositeOperation:'source-over',measureText:s=>({width:s.length*5})},{get:(o,k)=>k in o?o[k]:()=>{},set:(o,k,v)=>(o[k]=v,true)});
function render(s,sharedIds=[],view=E.VIEWS.threequarter){const p=createTrainCampPresentation(E),pending=[],g=context(),r={view,w:(...args)=>view.p(...args),visible:()=>true,shadow:()=>{},queue:(x,y,z,fn,o)=>pending.push({key:view.order(x,y,z)+(o?.bias||0),fn})},before=JSON.stringify(s),humans=sharedIds.map(id=>{const e=getPreparationWorkPose(s,id);assert.ok(e);return{id,e,update:e.human.rig.update,joints:structuredClone(e.human.rig.J),time:e.human.rig.t};});
 for(const row of humans)row.e.human.rig.update=()=>{throw Error('Drawing must not advance the real physics human again');};
 try{p.update(.05,s);p.draw(r,s);pending.sort((a,b)=>a.key-b.key);for(const item of pending)item.fn(g);const result=p.inspect();assert.equal(JSON.stringify(s),before);assert.deepEqual(result.errors,[]);for(const row of humans){assert.deepEqual(row.e.human.rig.J,row.joints);assert.equal(row.e.human.rig.t,row.time);const actor=result.actors.find(a=>a.id===row.id),contact=result.contacts.find(c=>c.actorId===row.id&&c.kind.startsWith('preparation-'));assert.equal(result.actors.filter(a=>a.id===row.id).length,1);assert.equal(actor.physicsHuman,true);assert.deepEqual(actor.contactHint,row.e.contactHint);assert.ok(Math.hypot(...['x','y','z'].map(k=>actor.elbow[k]-row.e.joints[1][k]))<1e-7);assert.ok(Math.hypot(...['x','y','z'].map(k=>contact.hit[k]-row.e.joints[2][k]))<1e-7);}assert.ok(Journey.restoreCampaign(Journey.serializeCampaign(s)));return result;}finally{for(const row of humans)row.e.human.rig.update=row.update;}
}
function approachMask(s){moveNative(s,{x:390,y:1180});const target=TRAIN_MASK_APPROACHES.mara;for(let i=0;i<100&&Math.hypot(s.player.x-target.x,s.player.y-target.y)>.2;i++){const d=Math.hypot(s.player.x-target.x,s.player.y-target.y);Journey.stepCampaign(s,.005,{mx:(target.x-s.player.x)/d,my:(target.y-s.player.y)/d});}assert.ok(Math.hypot(s.player.x-target.x,s.player.y-target.y)<.3);}

test('real activated store draws the same open tray/four wrapped children/tin, and borrows the exact live hinted physics humans',()=>{
 const unstarted=acceptedBriefingNative();assert.ok(!render(unstarted).objects.some(o=>o.siteId),'metadata alone displays no new site/object');assert.equal(ownsPreparationCampProp(unstarted,{id:'ruth-charge-store'}),false);
 const s=begin(),skein=JSON.stringify(s.entities.skein);interactNative(s,'train:prepare-inspect:quarry-sealed-charge-1');followPreparationGuideNative(s);wait(s,()=>powder(s).pending.some(w=>w.acceptedSeconds>0));for(const id of ['mara','ruth'])assert.equal(activePreparationCampWorkPose(s,s.entities[id]).kind,'preparation');const result=render(s,['mara','ruth']);
 for(const id of ['quarry-charge-worktop','charge-crate','cap-tin',...Object.keys(Camp.TRAIN_CHILD_CONTACTS)])assert.equal(result.objects.filter(o=>o.id===id).length,1,id);
 for(const[id,slot]of Object.entries(Camp.TRAIN_CHILD_CONTACTS))assert.deepEqual(result.objects.find(o=>o.id===id).world,slot.center);
 assert.deepEqual(result.objects.find(o=>o.id==='charge-crate').halfExtents,Camp.TRAIN_CRATE_SHAPE);assert.equal(result.objects.find(o=>o.id==='cap-tin').opened,false);assert.ok(!result.objects.some(o=>/^quarry-primer-/.test(o.id)));assert.ok(!result.objects.some(o=>o.siteId==='ruth-wiring-case-stand'));assert.equal(ownsPreparationCampProp(s,{id:'ruth-charge-store'}),true);assert.equal(ownsPreparationCampProp(s,{id:'ruth-cap-store'}),true);assert.equal(ownsPreparationCampProp(s,{id:'levi-holding-anchor'}),false);assert.equal(JSON.stringify(s.entities.skein),skein,'rendering neither clears nor conceals the actual blocker');
});
test('only an actual waiting work request guides Mara to the owning approach, without changing the world or retaining a marker during work',()=>{
 const unstarted=acceptedBriefingNative();assert.equal(preparationPlayerApproach(unstarted),null);assert.deepEqual(render(unstarted).guidance,[]);
 const s=begin();assert.equal(preparationPlayerApproach(s),null);interactNative(s,'train:prepare-inspect:quarry-sealed-charge-1');assert.equal(prep(s).work.workId,null);const before=JSON.stringify(s),approach=preparationPlayerApproach(s);
 assert.deepEqual(approach,{siteId:'quarry-charge-worktop',point:{x:Camp.TRAIN_INSPECTION_V3_MARA_APPROACH.x,y:Camp.TRAIN_INSPECTION_V3_MARA_APPROACH.y,z:Camp.TRAIN_INSPECTION_V3_MARA_APPROACH.z||0},facing:Camp.TRAIN_INSPECTION_V3_MARA_APPROACH.facing});
 const result=render(s);assert.equal(result.at,s.elapsed);assert.deepEqual(result.guidance,[{kind:'player-approach',siteId:approach.siteId,world:approach.point,facing:approach.facing,radius:3,label:'Stand here'}]);approach.point.x+=100;assert.deepEqual(preparationPlayerApproach(s).point,result.guidance[0].world,'read-only getter returns detached guidance');assert.equal(JSON.stringify(s),before);
 followPreparationGuideNative(s);wait(s,()=>powder(s).pending.some(w=>w.acceptedSeconds>0));assert.equal(preparationPlayerApproach(s),null);const active=render(s,['mara','ruth']);assert.equal(active.at,s.elapsed);assert.deepEqual(active.guidance,[]);wait(s,()=>prep(s).work===null);assert.deepEqual(render(s).guidance,[]);
});
test('foreground foliage fades for the actual worker and elevated hand even when it does not cover Mara’s feet',async()=>{
 const s=begin();interactNative(s,'train:prepare-inspect:quarry-sealed-charge-1');followPreparationGuideNative(s);wait(s,()=>powder(s).pending.some(w=>w.acceptedSeconds>0));const before=JSON.stringify(s),[{trainCampWorkContext},{shouldFadeSnowboundTree}]=await Promise.all([import('../src/train-camp-work-view.js'),import('../src/snowbound-renderer.js')]),work=trainCampWorkContext(s),hand=getPreparationWorkPose(s,'ruth').contact,view=E.VIEWS.threequarter,screen=view.p(hand.x,hand.y,hand.z),[x,y]=view.toGround(screen[0],screen[1]+24),tree={x,y,size:1},playerFoot={x:s.player.x,y:s.player.y,z:0};
 assert.ok(work.points.some(p=>Math.hypot(p.x-hand.x,p.y-hand.y,p.z-hand.z)<1e-7));
 for(const offset of [[0,0],[270,-120]]){const r={w:(...p)=>view.p(...p).map((v,i)=>v-offset[i])};assert.equal(shouldFadeSnowboundTree(r,tree,[playerFoot]),false,'the old player-only fade leaves Ruth’s hand behind this foreground silhouette');assert.equal(shouldFadeSnowboundTree(r,tree,[playerFoot,...work.points]),true);assert.equal(shouldFadeSnowboundTree(r,tree,[]),false);assert.equal(shouldFadeSnowboundTree(r,{...tree,x:x+200},[playerFoot,...work.points]),false,'unrelated foliage stays opaque');}
 assert.equal(JSON.stringify(s),before);assert.ok(Journey.restoreCampaign(Journey.serializeCampaign(s)));
});
test('the same tin reveals only actual receipted nested units after native opening; no old task pose or second tin remains',()=>{
 let s=begin();interactNative(s,'train:prepare-open-tin');wait(s,()=>powder(s).pending.some(w=>w.kind==='open-tin'&&w.acceptedSeconds>0));render(s,['ruth']);s=Journey.restoreCampaign(Journey.serializeCampaign(s));assert.ok(s);wait(s,()=>prep(s).work===null);assert.ok(s.campaign.missions[RIVAL].objects['cap-tin'].openingEventId);assert.equal(activePreparationCampWorkPose(s,s.entities.ruth),null);
 const result=render(s),units=result.objects.filter(o=>/^quarry-primer-/.test(o.id));assert.equal(result.objects.filter(o=>o.id==='cap-tin').length,1);assert.equal(result.objects.find(o=>o.id==='cap-tin').opened,true);assert.equal(units.length,6);assert.equal(new Set(units.map(o=>o.id)).size,6);for(const unit of units)assert.deepEqual(unit.world,Camp.TRAIN_PRIMER_SLOTS[unit.id].center);
});
test('the real worktop and all four rails retain their bounds while higher numbered wrappers and actual opened units survive global face painting',()=>{
 const s=begin();interactNative(s,'train:prepare-open-tin');wait(s,()=>prep(s).work===null);assert.equal(s.campaign.missions[RIVAL].objects['cap-tin'].primers.length,6);
 const inside=(p,polygon)=>{const cross=polygon.map((a,i)=>{const b=polygon[(i+1)%polygon.length];return(b[0]-a[0])*(p[1]-a[1])-(b[1]-a[1])*(p[0]-a[0]);});return cross.every(n=>n>=-1e-7)||cross.every(n=>n<=1e-7);};
 for(const view of [E.VIEWS.threequarter,new E.View('boosted-regression','Actual projection',0,55,2,1.7)]){
  const result=render(s,[],view),surfaces=result.surfaces,lastAt=world=>{const pixel=view.p(world.x,world.y,world.z);return surfaces.filter(face=>inside(pixel,face.world.map(p=>view.p(p.x,p.y,p.z)))).at(-1);};
  for(const board of Camp.TRAIN_CRATE_SOLIDS){const drawn=surfaces.filter(face=>face.partId===board.id);assert.ok(drawn.length,board.id);for(const face of drawn)for(const p of face.world)assert.ok(p.x>=board.x&&p.x<=board.x+board.w&&p.y>=board.y&&p.y<=board.y+board.h&&p.z>=board.z&&p.z<=board.z+board.height,'actual solid is neither moved nor resized');}
  for(const[id,slot]of Object.entries(Camp.TRAIN_CHILD_CONTACTS)){const painted=lastAt({...slot.center,z:slot.center.z+6});assert.equal(painted.id,id,'worktop/front rail cannot repaint a physically visible wrapped top');assert.equal(painted.face,'top');assert.equal(painted.number,Number(id.slice(-1)));}
  for(const[id,slot]of Object.entries(Camp.TRAIN_PRIMER_SLOTS)){assert.equal(lastAt({...slot.center,z:slot.center.z+slot.halfExtents.z}).id,id,'actual counted unit remains visible through the opened top');}
  assert.ok(!surfaces.some(face=>face.id==='cap-tin'&&face.face==='top'),'only the actual opened lid is absent');
 }
});
test('the explicit material close-up magnifies only the same current objects, retains every rail and reveals no units before real opening',()=>{
 const s=begin(),detail=createPreparationMaterialDetail(E),before=JSON.stringify(s),update=E.Humanoid.prototype.update,draw=E.Humanoid.prototype.draw;E.Humanoid.prototype.update=E.Humanoid.prototype.draw=()=>{throw Error('Material detail must never update or draw a second actor');};
 try{const closed=detail.draw(context(),s,{width:320,height:200});assert.equal(closed.view,'material-closeup');assert.deepEqual(closed.actors,[]);assert.equal(closed.objects.filter(o=>o.id.startsWith('quarry-sealed-charge-')).length,4);assert.ok(!closed.objects.some(o=>o.id.startsWith('quarry-primer-')));assert.equal(JSON.stringify(s),before);assert.equal(detail.draw(context(),acceptedBriefingNative(),{width:320,height:200}),null);}finally{E.Humanoid.prototype.update=update;E.Humanoid.prototype.draw=draw;}
 interactNative(s,'train:prepare-open-tin');wait(s,()=>prep(s).work===null);const openedBefore=JSON.stringify(s),opened=detail.draw(context(),s,{width:320,height:200});assert.equal(opened.objects.filter(o=>o.id.startsWith('quarry-primer-')).length,6);assert.ok(opened.scale>6,'sub-unit objects receive a readable magnified viewport');for(const board of Camp.TRAIN_CRATE_SOLIDS)assert.ok(opened.surfaces.some(face=>face.partId===board.id));assert.deepEqual(opened.actors,[]);assert.equal(JSON.stringify(s),openedBefore);assert.ok(Journey.restoreCampaign(Journey.serializeCampaign(s)));
});
test('Look closely opens and closes a labelled material-only region without inspection credit and resets after actual owning restore',async()=>{
 const {createTrainCampWorkView}=await import('../src/train-camp-work-view.js'),s=begin(),before=JSON.stringify(s),elements=new Map(),classes=new Set();
 const element=(tag,rect={left:0,right:0,top:0,bottom:0})=>({tag,hidden:false,dataset:{},attributes:{},listeners:{},children:[],setAttribute(k,v){this.attributes[k]=v;},addEventListener(k,v){this.listeners[k]=v;},append(...els){this.children.push(...els);for(const el of els)if(el.id)elements.set('#'+el.id,el);},closest:()=>null,getBoundingClientRect:()=>rect,getContext:()=>context(),focus(){this.focused=true;}});
 elements.set('.objective',element('section',{left:12,right:204,top:105,bottom:235}));const doc={querySelector:id=>elements.get(id)||null,createElement:tag=>element(tag),body:{classList:{toggle(name,on){on?classes.add(name):classes.delete(name);}}}},screen={W:320,H:568,S:1,dpr:1,OX:0,OY:0,canvas:{getBoundingClientRect:()=>({left:0,top:0})}},view=createTrainCampWorkView(doc);view.sync(s,{screen});const button=elements.get('#camp-store-detail-toggle'),panel=elements.get('#camp-store-detail');assert.equal(button.hidden,false);assert.equal(panel.hidden,true);assert.equal(button.attributes['aria-controls'],panel.id);button.listeners.click();assert.equal(button.attributes['aria-expanded'],'true');assert.equal(panel.hidden,false);assert.equal(panel.attributes.role,'region');const canvas=panel.children.find(el=>el.tag==='canvas'),receipt=JSON.parse(canvas.dataset.renderReceipt);assert.equal(receipt.view,'material-closeup');assert.deepEqual(receipt.actors,[]);assert.equal(receipt.objects.filter(o=>o.id.startsWith('quarry-sealed-charge-')).length,4);assert.equal(JSON.stringify(s),before,'looking awards no accepted work or inspection event');panel.children.find(el=>el.tag==='button').listeners.click();assert.equal(panel.hidden,true);button.listeners.click();view.sync(Journey.restoreCampaign(Journey.serializeCampaign(s)),{screen});assert.equal(panel.hidden,true);assert.equal(button.attributes['aria-expanded'],'false');assert.equal(JSON.stringify(s),before);
});
test('activated mending source and live Ada/Mara hands use authored geometry, then the one issued stowed mask leaves no basket proxy',()=>{
 const s=begin();approachMask(s);wait(s,()=>!!prep(s).campSetup.sites['ada-mending-worktop']);interactNative(s,'train:prepare-mask-issue');wait(s,()=>powder(s).pending.some(w=>w.kind==='issue-mask'&&w.acceptedSeconds>0));const result=render(s,['mara','ada']),cloth=result.objects.filter(o=>o.id===TRAIN_MASK_ID);assert.equal(cloth.length,1);assert.deepEqual(cloth[0].world,TRAIN_MASK_FOLDED_CENTER);assert.equal(cloth[0].source,true);assert.equal(s.itemInstances[TRAIN_MASK_ID],undefined);
 wait(s,()=>prep(s).work===null);assert.equal(s.itemInstances[TRAIN_MASK_ID].location.type,'carried');const after=render(s);assert.equal(after.objects.filter(o=>o.id===TRAIN_MASK_ID).length,0,'ordinary stowed inventory is not a fabricated idle hand object');assert.equal(activePreparationCampWorkPose(s,s.entities.ada),null);assert.equal(s.campaign.missions[RIVAL].rival.continuation.events.filter(e=>e.kind==='issue-mask').length,1);
});
async function assertSnowboundWorkers(s,actorIds){
 const before=JSON.stringify(s),entries=actorIds.map(id=>getPreparationWorkPose(s,id)),rigIds=new WeakMap(entries.map(e=>[e.human.rig,e.body.id])),draws={},updates={},oldDocument=globalThis.document,update=E.Humanoid.prototype.update,draw=E.Humanoid.prototype.draw;
 globalThis.document={createElement:()=>({getContext:()=>context()})};E.Humanoid.prototype.update=function(dt,body){rigIds.set(this,body.id);if(actorIds.includes(body.id))updates[body.id]=(updates[body.id]||0)+1;return update.call(this,dt,body);};E.Humanoid.prototype.draw=function(...args){const id=rigIds.get(this);if(actorIds.includes(id))draws[id]=(draws[id]||0)+1;return draw.apply(this,args);};
 try{const{createSnowboundRenderer}=await import('../src/snowbound-renderer.js'),game={reduceMotion:false,cam:{x:0,y:0},view:E.VIEWS.threequarter},renderer=createSnowboundRenderer(game),pending=[],g=context(),view=game.view,base={game,ctx:g,view,H:800,W:1280,bw:1280,bh:800,ix:0,iy:0,w:(...args)=>view.p(...args),visible:()=>true,queue:(x,y,z,fn,o)=>pending.push({key:view.order(x,y,z)+(o?.bias||0),fn}),actor:(x,y,z,fn)=>pending.push({key:view.order(x,y,z),fn:g=>fn(g,...view.p(x,y,z))}),overlay:fn=>pending.push({key:Infinity,fn}),shadow:()=>{},sky:()=>{},box:()=>{}};renderer.update(.05,s);renderer.draw(new Proxy(base,{get:(o,k)=>k in o?o[k]:()=>{}}),s);pending.sort((a,b)=>a.key-b.key);for(const item of pending)item.fn(g);assert.deepEqual(updates,{});assert.deepEqual(draws,Object.fromEntries(actorIds.map(id=>[id,1])));const result=renderer.inspectTrainCampAnimation();for(const id of actorIds)assert.equal(result.actors.filter(a=>a.id===id).length,1);assert.equal(JSON.stringify(s),before);assert.ok(Journey.restoreCampaign(Journey.serializeCampaign(s)));return result;}finally{E.Humanoid.prototype.update=update;E.Humanoid.prototype.draw=draw;if(oldDocument===undefined)delete globalThis.document;else globalThis.document=oldDocument;}
}
test('full Snowbound composition draws each actual preparation worker once with no competing legacy rig update',async()=>{
 const s=begin();interactNative(s,'train:prepare-inspect:quarry-sealed-charge-1');followPreparationGuideNative(s);wait(s,()=>powder(s).pending.some(w=>w.acceptedSeconds>0));const result=await assertSnowboundWorkers(s,['mara','ruth']);assert.equal(result.objects.filter(o=>o.id==='charge-crate').length,1);
});
test('actual watch handover owns only its live native participants and draws each keeper once without ambient takeover',async()=>{
 let s=watchDiscussionNative();for(const id of ['bastian','inez','hob'])assert.equal(ownsTrainCampActor(s,s.entities[id]),false,'hearing alone gives no work draw ownership');
 for(const to of ['inez','hob']){
  beginWatchReliefNative(s,to);const opIds=['mara',to==='inez'?'bastian':'inez',to],workId=prep(s).work.workId;
  for(const id of opIds){const entry=activePreparationCampWorkPose(s,s.entities[id]);assert.ok(entry,id);assert.equal(entry.workId,workId);assert.equal(entry.operationKind,'guard-handover');assert.equal(activePreparationCampWorkPose(s,{...s.entities[id]}),null,'unregistered lookalike cannot own the native pose');}
  const outside=['bastian','inez','hob'].find(id=>!opIds.includes(id));assert.equal(activePreparationCampWorkPose(s,s.entities[outside]),null);assert.equal(ownsTrainCampActor(s,s.entities[outside]),false);
  render(s,opIds);const composition=await assertSnowboundWorkers(s,opIds);for(const id of opIds)assert.equal(composition.actors.find(a=>a.id===id).workId,workId);
  wait(s,()=>prep(s).work===null);for(const id of ['bastian','inez','hob'])assert.equal(ownsTrainCampActor(s,s.entities[id]),false,'a completed handover retains no stale native ownership');s=Journey.restoreCampaign(Journey.serializeCampaign(s));assert.ok(s);
 }
});
