import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {gunzipSync} from 'node:zlib';
import '../my-3d2dge-agent.js';
import {createTrainHuman,rigWorldPoint} from '../src/train-native/rigs.js';
import {TRAIN_ID} from '../content/campaign/brass-cutting.js';
import {TRAIN_STABLE_CARE as CARE} from '../content/campaign/train-stable-care-data.js';
import {trainStableCareApproach,trainStableCareTarget,prepareTrainStableCarePose,inspectTrainStableCareContact,inspectTrainStableCareWindow,beginTrainStableCare,stepTrainStableCare,getTrainStableCareInteractions,validateTrainStableCare,currentTrainStableCare,completeTrainStableCare} from '../src/train-stable-care.js';
import {capturePreparationBodyBounds} from '../src/train-preparation-layout.js';
import {preparationNativeBodyParts,preparationNativeBodyContacts} from '../src/train-preparation-body-geometry.js';
import {preparationStableWorldGeometry} from '../src/train-preparation-stable.js';
const source=()=>JSON.parse(gunzipSync(readFileSync(new URL('./fixtures/train-preparation-pr9-mask-owned-bring.json.gz',import.meta.url))));
function detached(kind){const old=source(),s={...old,entities:{...old.entities,skein:{...old.entities.skein,x:620,y:1318,facing:Math.PI/2,vx:0,vy:0}}};s.entities.inez={...old.entities.inez,...trainStableCareApproach(s,kind),vx:0,vy:0,holstered:true};return s;}

test('unchanged earned mask prefix cannot invent stable care, tools, food, water or completion',()=>{const s=source(),before=JSON.stringify(s);assert.equal(s.campaign.missions[TRAIN_ID].train.preparation.stableCare,undefined);assert.deepEqual(getTrainStableCareInteractions(s,{worldFor:()=>null}),[]);for(const kind of ['tack','coat','brush','water'])assert.equal(beginTrainStableCare(s,kind,{worldFor:()=>null}),false);assert.equal(stepTrainStableCare(s,.05,{worldFor:()=>null}),false);assert.equal(currentTrainStableCare(s),null);assert.equal(validateTrainStableCare(s,{schema:1,completed:['tack','coat']}),false);assert.equal(completeTrainStableCare(s),false);assert.equal(JSON.stringify(s),before);});

test('detached actual glove contact fits both existing components without changing feet or condition; walking envelopes also clear the same mare',()=>{for(const kind of ['tack','coat']){const s=detached(kind),before=JSON.stringify(s),rows=capturePreparationBodyBounds(s),r=rows.find(r=>r.id==='inez'),mare=preparationNativeBodyParts(rows.find(r=>r.id==='skein'),rows),moving=preparationNativeBodyParts({...r,pose:{...r.pose,vx:1,vy:0}},rows);assert.deepEqual(preparationNativeBodyContacts(moving,mare),[],'station must admit the full unshrunk walking skeleton');for(let i=0;i<=32;i++){const hit=inspectTrainStableCareContact(s,kind,i/32);assert.ok(hit);assert.ok(Math.hypot(...['x','y','z'].map(k=>hit.hand[k]-hit.target[k]))<1e-5);assert.deepEqual(hit.glove,CARE.glove);assert.ok(Math.abs(Math.hypot(...['x','y','z'].map(k=>hit.hand[k]-hit.componentPoint[k]))-hit.palmRadius)<1e-6,'finite native glove reaches the actual material while wrist stays outside');}assert.equal(JSON.stringify(s),before);assert.equal(s.campaign.missions[TRAIN_ID].train.preparation.stableDuty,null,'detached kinematics cannot earn the lead');}});

test('detached continuous contact windows certify real IK movement; obstructing the actual hand blocks credit',()=>{for(const kind of ['tack','coat']){const s=detached(kind),rows=capturePreparationBodyBounds(s),geometry=preparationStableWorldGeometry(s),fromTarget=trainStableCareTarget(s,kind,0),toTarget=trainStableCareTarget(s,kind,.05),before=JSON.stringify(s);assert.ok(inspectTrainStableCareWindow(s,{kind,fromTarget,toTarget,bodyBounds:rows,geometry}));const blocked={...s,entities:{...s.entities,ruth:{...s.entities.ruth,x:fromTarget.x,y:fromTarget.y,z:0,vx:0,vy:0}}};assert.equal(inspectTrainStableCareWindow(blocked,{kind,fromTarget,toTarget,bodyBounds:capturePreparationBodyBounds(blocked),geometry}),null,'a real registered body occupying the hand target blocks the certified motion');const panel={id:'blocking-contact-panel',x:fromTarget.x-.1,y:fromTarget.y-.1,z:fromTarget.z-.1,w:.2,h:.2,height:.2};assert.equal(inspectTrainStableCareWindow(s,{kind,fromTarget,toTarget,bodyBounds:rows,geometry:[...geometry,panel]}),null,'unrecognized world substitutions cannot authorize contact');assert.equal(inspectTrainStableCareWindow(s,{kind:'water',fromTarget,toTarget,bodyBounds:rows,geometry}),null);assert.equal(JSON.stringify(s),before);}});

test('an injured or occupied actual right hand cannot perform the gloved contact',()=>{for(const kind of ['tack','coat'])for(const facts of [{handInjury:{side:'right',recovered:false},injured:true},{toolHeld:'other-tool'},{mounted:true},{holstered:false},{hp:0,dead:true}]){const s=detached(kind);Object.assign(s.entities.inez,facts);assert.equal(inspectTrainStableCareContact(s,kind,.5),null);assert.equal(completeTrainStableCare(s),false);}});

test('detached whole reach and withdrawal certify every accepted hand interval from the original idle elbow pole',()=>{for(const kind of ['tack','coat']){const s=detached(kind),before=JSON.stringify(s),h=createTrainHuman(My3D2dge,s.entities.inez),pose=prepareTrainStableCarePose(My3D2dge,h,s.entities.inez,null),rest=rigWorldPoint(h.rig,pose.root,'handR');pose.restore();const first=trainStableCareTarget(s,kind,0),rows=capturePreparationBodyBounds(s),geometry=preparationStableWorldGeometry(s),at=u=>Object.fromEntries(['x','y','z'].map(k=>[k,rest[k]+(first[k]-rest[k])*u]));for(let i=0;i<16;i++){const a=at(i/16),b=at((i+1)/16);assert.ok(inspectTrainStableCareWindow(s,{kind,fromTarget:a,toTarget:b,bodyBounds:rows,geometry}),kind+' actual reach interval '+i);assert.ok(inspectTrainStableCareWindow(s,{kind,fromTarget:b,toTarget:a,bodyBounds:rows,geometry}),kind+' actual withdrawal interval '+i);}assert.equal(JSON.stringify(s),before);}});

test('the native care pose borrows a previously walking Human without retaining its gait or mutating its private animation state',()=>{const s=detached('coat'),h=createTrainHuman(My3D2dge,s.entities.inez),rig=h.rig;rig.update(.05,{...s.entities.inez,vx:55,vy:0,crouch:true});rig.t=123;rig.phase=2;const before=structuredClone({J:rig.J,t:rig.t,phase:rig.phase,spW:rig.spW,poseW:rig.poseW}),target=trainStableCareTarget(s,'coat',.5),pose=prepareTrainStableCarePose(My3D2dge,h,s.entities.inez,target);assert.equal(rig.spW,0);assert.equal(rig.t,0);assert.ok(pose.diagnostics[0].reachable);pose.restore();assert.deepEqual({J:rig.J,t:rig.t,phase:rig.phase,spW:rig.spW,poseW:rig.poseW},before);});
