import test from 'node:test';import assert from 'node:assert/strict';import '../my-3d2dge-agent.js';
import {makeFrame,worldPoint} from '../src/rail-foundation/rigid-frame.js';
import {createAcceptedStepContext} from '../src/rail-foundation/accepted-step-context.js';
import {sweepMovingCover} from '../src/rail-foundation/moving-support.js';
import {raycastCoverAt} from '../src/train-terrain.js';
const P=(x=0,y=0,z=0)=>({x,y,z}),frame=x=>makeFrame(P(x),P(1)),wall=(x0=0,x1=2)=>({id:'door',bounds:{min:P(x0,-5,0),max:P(x1,5,20)},bodySolid:true,projectileSolid:true});
const platform=(previous=frame(0),current=previous)=>({id:'car',previousFrame:previous,frame:current,surfaces:[],cover:[wall()],contacts:[]});
test('instant current-frame rays work at restored dt0 without pretending a sweep advanced time',()=>{const c=createAcceptedStepContext([platform(frame(10))],0),before=JSON.stringify(c),hit=raycastCoverAt(c,P(0,0,10),P(20,0,10));assert.equal(hit.volumeId,'door');assert.equal(hit.rayU,.5);assert.equal(hit.world.x,10);assert.equal(sweepMovingCover(P(0,0,10),P(20,0,10),c,0),null);assert.equal(JSON.stringify(c),before);});
test('instant fractions query separate real moving poses and do not use a swept corridor',()=>{const c=createAcceptedStepContext([platform(frame(0),frame(10))],.1);assert.equal(raycastCoverAt(c,P(-5,0,10),P(5,0,10),{fraction:0}).rayU,.5);assert.equal(raycastCoverAt(c,P(-5,0,10),P(5,0,10),{fraction:1}),null);assert.equal(raycastCoverAt(c,P(0,0,10),P(20,0,10),{fraction:.5}).world.x,5);});
test('thin shielding, inside sources, endpoint contact and solid flags remain explicit',()=>{const p=platform();p.cover=[wall(1,1.001)];const c=createAcceptedStepContext([p],0);assert.equal(raycastCoverAt(c,P(0,0,10),P(2,0,10)).world.x,1);assert.equal(raycastCoverAt(c,P(0,0,10),P(1,0,10)).rayU,1);const inside=raycastCoverAt(c,P(1.0005,0,10),P(3,0,10));assert.equal(inside.rayU,0);assert.equal(inside.startsInside,true);p.cover[0].projectileSolid=false;const transparent=createAcceptedStepContext([p],0);assert.equal(raycastCoverAt(transparent,P(0,0,10),P(2,0,10)),null);assert.ok(raycastCoverAt(transparent,P(0,0,10),P(2,0,10),{mode:'body'}));});
test('curved/graded car coordinates and actual closed-door shielding share one world model',()=>{const f=makeFrame(P(100,200,30),P(1,1,.1)),p=platform(f);p.cover=[wall(82,85)];p.cover[0].bounds.min.y=-32;p.cover[0].bounds.max.y=32;p.cover[0].bounds.min.z=26;p.cover[0].bounds.max.z=86;const c=createAcceptedStepContext([p],0),outside=worldPoint(f,P(87,0,45)),worker=worldPoint(f,P(0,0,45)),hit=raycastCoverAt(c,outside,worker);assert.equal(hit.volumeId,'door');assert.ok(Math.abs(hit.local.x-85)<1e-6);assert.equal(raycastCoverAt(c,worldPoint(f,P(97,0,45)),outside),null);assert.equal(raycastCoverAt(c,worldPoint(f,P(84,0,45)),worker).startsInside,true);});
test('instant rays reject invalid inputs and cannot inherit forged context trust',()=>{const c=createAcceptedStepContext([platform()],0);for(const fraction of[-1,2,NaN])assert.throws(()=>raycastCoverAt(c,P(),P(10),{fraction}));assert.throws(()=>raycastCoverAt(c,P(NaN),P()));assert.throws(()=>raycastCoverAt(c,P(),P(),{mode:'invented'}));assert.throws(()=>raycastCoverAt({...c},P(),P()));});

import {TRAIN_TERRAIN_DATA} from '../content/campaign/train-terrain-data.js';
import {createTrainConsist,trainGeometry} from '../src/train-motion.js';
import {createTrainTerrain,terrainFloorAt,createWorldQuery,raycastWorldCoverAt,actorWorldPoint,traceGroundSegment,sweepTerrainBody,sweepTerrainLanding,stepTerrainBody,jumpTerrainBody} from '../src/train-terrain.js';
const E=My3D2dge,terrain=createTrainTerrain(),dt=1/120,clone=v=>JSON.parse(JSON.stringify(v));
function prism(id,x0,x1,y0,y1,z0,z1,walkable=true){return{id,vertices:[P(x0,y0,z0),P(x1,y0,z0),P(x1,y1,z0),P(x0,y1,z0),P(x0,y0,z1),P(x1,y0,z1),P(x1,y1,z1),P(x0,y1,z1)],faces:[[0,3,2,1],[4,5,6,7],[0,1,5,4],[1,2,6,5],[2,3,7,6],[3,0,4,7]],bodySolid:true,projectileSolid:true,...walkable?{walkableFace:1}:{}};}
function fixture(meshes,offset=0){return{schema:1,regionId:'brass-cutting',bounds:{min:P(offset,0,-64),max:P(offset+400,200,300)},meshes:[prism('base',offset,offset+400,0,200,-32,0),...meshes],fixedContacts:{},trainCarIds:[],gangwayIds:[]};}
function galleryPoint(){const m=TRAIN_TERRAIN_DATA.meshes.find(m=>m.id==='brass-boarding-deck'),[a,b,,d]=m.vertices.slice(4);return P(a.x+(b.x-a.x)/3+(d.x-a.x)*14/52,a.y+(b.y-a.y)/3+(d.y-a.y)*14/52,20);}
function follower(route,{r=9,height=53,speed=76,trace=false}={}){const body=new E.Body({...route[0],r,height,hp:100,onGround:true}),rows=[],hits=[],contactChecks=[],traceBlocks=[];let grounded=true,steps=0,traceLength=0,maxSpacing=0;for(let i=1;i<route.length;i++){const target=route[i];for(let n=0;n<1000&&Math.hypot(target.x-body.x,target.y-body.y)>1e-6;n++){const dx=target.x-body.x,dy=target.y-body.y,d=Math.hypot(dx,dy),from=P(body.x,body.y,body.z),result=stepTerrainBody(terrain,body,Math.min(dt,d/speed),{vx:dx/d*speed,vy:dy/d*speed}),after=P(body.x,body.y,body.z);steps++;hits.push(...result.hits);grounded&&=body.onGround===true&&!!terrainFloorAt(terrain,body,{radius:r,step:0});for(const hit of result.hits){const mesh=TRAIN_TERRAIN_DATA.meshes.find(m=>m.id===hit.volumeId),single=createTrainTerrain({...TRAIN_TERRAIN_DATA,trainCarIds:[],gangwayIds:[],meshes:[mesh]});contactChecks.push({volumeId:hit.volumeId,u:hit.u,normal:hit.normal,grounded:body.onGround===true,outside:sweepTerrainBody(single,after,after,{radius:r,height})===null});}if(trace&&Math.hypot(after.x-from.x,after.y-from.y,after.z-from.z)>1e-7){const q=traceGroundSegment(terrain,from,after,{radius:r,height});if(!q.clear)traceBlocks.push(q.hit);traceLength+=q.length3d;for(let j=1;j<q.groundPoints.length;j++){const a=q.groundPoints[j-1],b=q.groundPoints[j];maxSpacing=Math.max(maxSpacing,Math.hypot(b.x-a.x,b.y-a.y,b.z-a.z));}}}rows.push({distance:Math.hypot(target.x-body.x,target.y-body.y),z:body.z,guideZ:target.z});if(rows.at(-1).distance>1e-6)break;}return{body,rows,hits,contactChecks,grounded,steps,traceBlocks,traceLength,maxSpacing};}
test('compiled terrain rejects open/nonfinite solids and snapshots the actual accepted geometry',()=>{const input=fixture([prism('floor',50,150,50,150,-16,20)]),t=createTrainTerrain(input);input.meshes[1].vertices[4].z=999;assert.equal(terrainFloorAt(t,P(100,100,20),{radius:9}).height,20);assert.ok(Object.isFrozen(t.meshes[1].vertices[4]));const open=clone(input);open.meshes[1].faces.pop();assert.throws(()=>createTrainTerrain(open));const bad=fixture([prism('floor',50,150,50,150,-16,20)]);bad.meshes[1].vertices[0].x=NaN;assert.throws(()=>createTrainTerrain(bad));bad.meshes[1].vertices[0].x=50;bad.meshes.push(clone(bad.meshes[1]));assert.throws(()=>createTrainTerrain(bad));assert.throws(()=>terrain.groundAt(1980,1450,9),'current feet height is mandatory');});
test('full circular feet cross coplanar unions at translated seams while meaningful gaps and narrow strips reject',()=>{for(const offset of[0,2000,4000]){const joined=createTrainTerrain(fixture([prism('a',offset+20,offset+150,30,170,-16,20),prism('b',offset+150,offset+300,30,170,-16,20)],offset));assert.equal(terrainFloorAt(joined,P(offset+150,100,20),{radius:9,step:0}).height,20);const gap=createTrainTerrain(fixture([prism('a',offset+20,offset+149.999,30,170,-16,20),prism('b',offset+150.001,offset+300,30,170,-16,20)],offset));assert.equal(terrainFloorAt(gap,P(offset+150,100,20),{radius:9,step:0}).height,0);const narrow=createTrainTerrain(fixture([prism('strip',offset+20,offset+300,91.005,108.995,-16,20)],offset));assert.equal(terrainFloorAt(narrow,P(offset+150,100,20),{radius:9,step:0}).height,0);const partial=terrainFloorAt(narrow,P(offset+150,100,20),{radius:9,step:0,requireFull:false});assert.equal(partial.height,20);assert.equal(partial.fullFootprint,false);assert.equal(terrainFloorAt(joined,P(offset+150,100,20),{radius:9,step:0,requireFull:false}).fullFootprint,true);}});
test('real ridge neck stays94 until actual incline and never raises feet from a valley query',()=>{const [a,b]=TRAIN_TERRAIN_DATA.routes.boardingRun,n=Math.hypot(b.x-a.x,b.y-a.y),body=new E.Body({...a,r:9,height:53,hp:100,onGround:true});for(let i=0;i<64;i++){const q=stepTerrainBody(terrain,body,dt,{vx:(b.x-a.x)/n*76,vy:(b.y-a.y)/n*76});assert.equal(q.hits.length,0);assert.equal(body.onGround,true);assert.ok(terrainFloorAt(terrain,body,{radius:9,step:0}));if(i<63)assert.ok(Math.abs(body.z-94)<1e-7);}assert.ok(body.z>94&&body.z<94.1);assert.equal(terrainFloorAt(terrain,P(a.x,a.y,0),{radius:9,step:2}).height,0);});
test('gallery20, slab underside104 and deck112 remain separate real layers and instant shielding',()=>{const p=galleryPoint(),world=createWorldQuery(trainGeometry(createTrainConsist()),terrain);assert.equal(terrainFloorAt(terrain,P(p.x,p.y,20),{radius:9,step:0}).height,20);assert.equal(terrainFloorAt(terrain,P(p.x,p.y,112),{radius:9,step:0}).height,112);const underside=raycastWorldCoverAt(world,P(p.x,p.y,80),P(p.x,p.y,120));assert.equal(underside.volumeId,'brass-boarding-deck');assert.ok(Math.abs(underside.world.z-104)<1e-7);const top=raycastWorldCoverAt(world,P(p.x,p.y,130),P(p.x,p.y,80));assert.equal(top.volumeId,'brass-boarding-deck');assert.ok(Math.abs(top.world.z-112)<1e-7);assert.equal(world.regionId,'brass-cutting');assert.equal(world.fixedContact('ridge-detonator').z,48);assert.throws(()=>createWorldQuery(trainGeometry(createTrainConsist()).platforms.slice(0,1),terrain));assert.throws(()=>createWorldQuery(trainGeometry(createTrainConsist()),{}));assert.throws(()=>raycastWorldCoverAt({...world},P(),P(1)));});
test('actual sloped top earns downward centre-foot landing across shifted fall phases, never early toe support',()=>{const a=TRAIN_TERRAIN_DATA.routes.boardingRun[1],b=TRAIN_TERRAIN_DATA.routes.boardingRun[2],p=P((a.x+b.x)/2,(a.y+b.y)/2,(a.z+b.z)/2);for(const offset of[.1,.3,3.8,8.8,12]){const body=new E.Body({...p,z:p.z+offset,r:9,height:53,hp:100,onGround:false});let firstLanding=null;for(let i=0;i<70;i++){const q=stepTerrainBody(terrain,body,dt);firstLanding??=q.hits.find(h=>h.kind==='landing');}assert.equal(body.onGround,true);assert.ok(Math.abs(body.z-p.z)<1e-7);assert.ok(firstLanding?.fullFootprint);assert.equal(firstLanding.volumeId,'brass-boarding-walk-1');assert.ok(Math.abs(firstLanding.world.z-p.z)<1e-7);}const before=new E.Body({...p,z:p.z+.1,r:9,height:53,gravity:0,vz:-1,onGround:false}),q=stepTerrainBody(terrain,before,dt);assert.equal(before.onGround,false);assert.ok(before.z>p.z);assert.equal(q.hits.length,0);assert.equal(sweepTerrainLanding(terrain,P(p.x,p.y,p.z+.1),P(p.x,p.y,p.z+.09)),null);});
test('finite cliff wall, roof underside and insufficient-foot edge remain blocking',()=>{const t=createTrainTerrain(fixture([prism('cliff',150,220,20,180,-16,80)])),body=new E.Body({x:135,y:100,z:0,r:9,height:53,hp:100,onGround:true});const q=stepTerrainBody(t,body,.1,{vx:100,vy:0});assert.ok(q.hits.some(h=>h.volumeId==='cliff'));assert.ok(body.x<=141+1e-6);assert.equal(body.z,0);assert.equal(body.onGround,true);const p=galleryPoint(),under=sweepTerrainBody(terrain,P(p.x,p.y,40),P(p.x,p.y,70));assert.equal(under.volumeId,'brass-boarding-walk-4');assert.ok(under.normal.z<-.9,'actual sloped bridge underside blocks the full body before the point-ray deck');const edge=createTrainTerrain(fixture([prism('narrow',100,180,90,107.9,10,20)]));assert.equal(sweepTerrainLanding(edge,P(130,99,30),P(130,99,10),{radius:9}),null);});
test('native jumps require an accepted grounding receipt and actual ceiling response limits the body',()=>{const t=createTrainTerrain(fixture([prism('floor',20,380,20,180,-16,20),prism('ceiling',20,380,20,180,105,115,false)])),body=new E.Body({x:100,y:100,z:20,r:9,height:53,hp:100,onGround:true});assert.equal(jumpTerrainBody(t,body),false);stepTerrainBody(t,body,dt);const before=JSON.stringify(body);for(const speed of[0,-1,NaN,Infinity]){assert.equal(jumpTerrainBody(t,body,speed),false);assert.equal(JSON.stringify(body),before);}assert.equal(jumpTerrainBody(t,body),true);assert.equal(body.vz,220);let apex=body.z,hit=false;for(let i=0;i<100;i++){const q=stepTerrainBody(t,body,dt);apex=Math.max(apex,body.z);hit||=q.hits.some(h=>h.volumeId==='ceiling');}assert.equal(hit,true);assert.ok(apex+53<=105+1e-6);assert.equal(body.onGround,true);assert.equal(body.z,20);});
test('uphill native run jump inherits real slope velocity and meets the real upper lintel',()=>{const a=TRAIN_TERRAIN_DATA.routes.boardingRun[1],b=TRAIN_TERRAIN_DATA.routes.boardingRun[2],dx=b.x-a.x,dy=b.y-a.y,n=Math.hypot(dx,dy),u=1-25/Math.hypot(dx,dy,b.z-a.z),body=new E.Body({x:a.x+dx*u,y:a.y+dy*u,z:a.z+(b.z-a.z)*u,r:9,height:53,hp:100,onGround:true}),move=stepTerrainBody(terrain,body,dt,{vx:dx/n*160,vy:dy/n*160});assert.ok(move.groundVelocity.z>70);assert.equal(jumpTerrainBody(terrain,body),true);assert.ok(body.vz>290);let first=null;for(let i=0;i<60;i++){const q=stepTerrainBody(terrain,body,dt);first??=q.hits[0];}assert.equal(first.volumeId,'brass-cutting-roof');assert.ok(Math.abs(first.normal.z)<1e-7,'actual side contact; no blanket ceiling clearance claim');assert.ok(Number.isFinite(body.z));});
test('real wire ground trace preserves endpoints, finite human clearance and measured slack below420',()=>{const route=TRAIN_TERRAIN_DATA.routes.wireLay;let total=0;for(let i=1;i<route.length;i++){const q=traceGroundSegment(terrain,route[i-1],route[i]);assert.equal(q.clear,true,JSON.stringify(q.hit));assert.deepEqual(q.groundPoints[0],route[i-1]);assert.deepEqual(q.groundPoints.at(-1),route[i]);let sum=0;for(let j=1;j<q.groundPoints.length;j++){const a=q.groundPoints[j-1],b=q.groundPoints[j],d=Math.hypot(b.x-a.x,b.y-a.y,b.z-a.z);assert.ok(d>0&&d<=4);sum+=d;}assert.ok(Math.abs(sum-q.length3d)<1e-9);total+=q.length3d;}assert.ok(total>340&&total<360);assert.ok(total<420);assert.equal(traceGroundSegment(terrain,route[0],route[0]).clear,false);assert.throws(()=>traceGroundSegment(terrain,route[0],route[1],{maxSpacing:5}));});
test('one real native body walks the entire wire corridor with full feet and no supplied Z movement',()=>{const q=follower(TRAIN_TERRAIN_DATA.routes.wireLay,{trace:true});assert.equal(q.traceBlocks.length,0);assert.ok(q.traceLength>340&&q.traceLength<360&&q.traceLength<420);assert.ok(q.maxSpacing>0&&q.maxSpacing<=4);assert.equal(q.grounded,true);assert.equal(q.rows.length,TRAIN_TERRAIN_DATA.routes.wireLay.length-1);assert.ok(q.steps>400);for(const row of q.rows){assert.ok(row.distance<1e-6);assert.ok(Math.abs(row.z-row.guideZ)<1e-6);}assert.equal(q.body.hp,100);assert.ok(!q.hits.some(h=>h.kind==='landing'),'the carrier never jumps or falls across an unsupported join');});
test('fresh body validation, attachments and incomplete world providers never become a clear default',()=>{const world=createWorldQuery(trainGeometry(createTrainConsist()),terrain),body=new E.Body({x:1980,y:1450,z:94,r:9,height:53,hp:100});assert.deepEqual(actorWorldPoint(body,world),P(1980,1450,94));body.attachment={kind:'passenger',parentId:'rivet'};assert.throws(()=>actorWorldPoint(body,world));assert.throws(()=>stepTerrainBody(terrain,body,dt));delete body.attachment;for(const duration of[NaN,-1,.2])assert.throws(()=>stepTerrainBody(terrain,body,duration));body.support={carId:'missing',surfaceId:'floor',local:P(),relativeVelocity:P()};assert.throws(()=>actorWorldPoint(body,world));});

test('exact prism refinement retains full circular corners at8headings and swept vertex contact',()=>{for(let n=0;n<8;n++){const angle=n*Math.PI/4,rotate=p=>P(110+(p.x-110)*Math.cos(angle)-(p.y-110)*Math.sin(angle),110+(p.x-110)*Math.sin(angle)+(p.y-110)*Math.cos(angle),p.z),wall=prism('corner',100,120,100,120,10,80),data=fixture([wall]);wall.vertices=wall.vertices.map(rotate);data.meshes.shift();const t=createTrainTerrain(data),clear=rotate(P(92,92,0)),overlap=rotate(P(100-8.99/Math.SQRT2,100-8.99/Math.SQRT2,0));assert.equal(sweepTerrainBody(t,clear,clear),null,'the r9 circle has cleared the sharp outset corner');const hit=sweepTerrainBody(t,overlap,overlap);assert.equal(hit.volumeId,'corner');assert.ok(hit.startsInside&&hit.depth>.009&&hit.depth<.011,'nearby actual circle intersection still blocks');const moving=sweepTerrainBody(t,rotate(P(80,80,0)),rotate(P(95,95,0)));assert.ok(Math.abs(moving.u-(20-9/Math.SQRT2)/15)<1e-7);const tangent=rotate(P(100-9/Math.SQRT2,100-9/Math.SQRT2,0));assert.equal(sweepTerrainBody(t,{...tangent,z:-60},{...tangent,z:20}),null,'vertical corner grazing never becomes a false ceiling');assert.equal(sweepTerrainBody(t,{...overlap,z:-60},{...overlap,z:20}).normal.z,-1);}});
test('native terrain routes and actual r14/90 mounted envelope traverse all static junctions without falls or Z input',()=>{const apron=TRAIN_TERRAIN_DATA.routes.lowerRecovery.findIndex(p=>p.x===2105&&p.y===1660),cases=[['boarding',TRAIN_TERRAIN_DATA.routes.boardingRun,{}],['footPreparation',TRAIN_TERRAIN_DATA.routes.upperFootPath,{}],['gallery',TRAIN_TERRAIN_DATA.routes.galleryAccess,{}],['mountedRecovery',TRAIN_TERRAIN_DATA.routes.lowerRecovery.slice(0,apron+1),{r:14,height:90,speed:125}],['mountedService',TRAIN_TERRAIN_DATA.routes.serviceMountApproach,{r:14,height:90,speed:125}],['mountedThawRide',TRAIN_TERRAIN_DATA.routes.thawRide,{r:14,height:90,speed:125}]];for(const[name,route,options]of cases){const q=follower(route,options);assert.equal(q.grounded,true,name);assert.equal(q.rows.length,route.length-1,name);assert.equal(q.hits.length,0,name);for(const row of q.rows){assert.ok(row.distance<1e-6,name);assert.ok(Math.abs(row.z-row.guideZ)<1e-6,name);}assert.equal(q.body.hp,100);}});
test('the same native full feet can physically return along wire and preparation paths',()=>{for(const route of[TRAIN_TERRAIN_DATA.routes.wireLay,TRAIN_TERRAIN_DATA.routes.upperFootPath]){const q=follower([...route].reverse());assert.equal(q.grounded,true);if(route===TRAIN_TERRAIN_DATA.routes.wireLay){assert.equal(q.contactChecks.length,1);const contact=q.contactChecks[0];assert.equal(contact.volumeId,'brass-wire-path-7');assert.equal(contact.u,0);assert.ok(Math.abs(contact.normal.z)<1e-7);assert.equal(contact.outside,true,'the current full cylinder is outside the actual contacted mesh');assert.equal(contact.grounded,true);}else assert.equal(q.hits.length,0);assert.equal(q.rows.length,route.length-1);for(const row of q.rows){assert.ok(row.distance<1e-6);assert.ok(Math.abs(row.z-row.guideZ)<1e-6);}}});

test('compiled normals and private ground-jump receipts cannot be changed through public query results',()=>{const t=createTrainTerrain(fixture([prism('floor',20,380,20,180,-16,20)])),body=new E.Body({x:100,y:100,z:20,r:9,height:53,hp:100,onGround:true,vx:100,friction:2}),q=stepTerrainBody(t,body,.1),velocity=100*Math.exp(-.2);assert.ok(Math.abs(body.vx-velocity)<1e-9);assert.ok(q.observedVelocity.x>velocity);const floor=terrainFloorAt(t,body,{radius:9,step:0});assert.ok(Object.isFrozen(floor.normal));assert.throws(()=>{floor.normal.z=0;});const twin=createTrainTerrain(fixture([prism('floor',20,380,20,180,-16,20)]));assert.equal(jumpTerrainBody(twin,body),false);q.to.x=999;q.groundVelocity.x=999;assert.equal(jumpTerrainBody(t,body),true);assert.ok(Math.abs(body.vx-velocity)<1e-9);assert.equal(body.vz,220);});

test('a valid triangulated cap cannot narrow the complete solid west-wall footprint',()=>{const wall=prism('triangulated-box',0,10,0,10,0,10);wall.faces[1]=[4,5,6];wall.faces.push([4,6,7]);const data=fixture([wall]);data.meshes.shift();const t=createTrainTerrain(data);for(const y of[2,8]){const hit=sweepTerrainBody(t,P(-5,y,0),P(5,y,0),{radius:1,height:5});assert.equal(hit?.volumeId,'triangulated-box');assert.ok(Math.abs(hit.u-.4)<1e-7,'r1 reaches the real west wall at x-1 in either cap triangle');assert.ok(Math.abs(hit.world.x+1)<1e-7);assert.deepEqual(hit.normal,P(-1,0,0));}assert.equal(sweepTerrainBody(t,P(-5,12,0),P(5,12,0),{radius:1,height:5}),null,'nearby full-cylinder clearance remains clear');});

test('near-vertical tapered geometry never narrows to the smaller top cap',()=>{const wall=prism('slightly-tapered',0,10,0,10,0,100);wall.vertices[0].x=-.000002;wall.vertices[3].x=-.000002;const data=fixture([wall]);data.meshes.shift();const t=createTrainTerrain(data),hit=sweepTerrainBody(t,P(-5,5,0),P(-1.000001,5,0),{radius:1,height:5});assert.equal(hit?.volumeId,'slightly-tapered','side normalz2e-8 must retain the real lower footprint');assert.ok(Math.abs(hit.world.x-(-1.000002))<1e-9);assert.ok(hit.u>0&&hit.u<1);assert.equal(sweepTerrainBody(t,P(-5,5,0),P(-1.000003,5,0),{radius:1,height:5}),null,'nearby real1e-6 clearance remains clear');});
