import test from 'node:test';import assert from 'node:assert/strict';
import {Journey,trainRecord,moveNative} from './helpers/train-preparation-route.mjs';
import {interactNative} from './helpers/train-clinic-route.mjs';
import {TRAIN_MASK_ID,TRAIN_MASK_FIT_V2} from '../content/campaign/train-gear-data.js';
import {readFileSync} from 'node:fs';import {gunzipSync} from 'node:zlib';import {createHash} from 'node:crypto';
import {getPreparationMaskPose,getPreparationWornMaskPose} from '../src/train-preparation-mask.js';
import {createTrainCampPresentation,currentPreparationMaskPose,activePreparationCampWorkPose,currentPreparationMaskMount,currentPreparationStableWork,currentPreparationCareWork,ownsTrainCampActor} from '../src/train-camp-presentation.js';
import {TRAIN_STORE_MARA} from '../content/campaign/train-preparation-camp.js';
const E=globalThis.My3D2dge,prep=s=>trainRecord(s).train.preparation;
function wait(s,predicate,max=600){for(let i=0;!predicate()&&i<max;i++)Journey.stepCampaign(s,.05);assert.ok(predicate(),'actual native mask work completes');}
/** Unchanged genuinely earned PR9 issue history. These tests perform CURRENT
 * wear/removal only; they do not accept the separate fresh body-v2 issue lane. */
function ownedMask(){const bytes=readFileSync(new URL('./fixtures/train-preparation-pr9-mask-owned-bring.json.gz',import.meta.url)),raw=gunzipSync(bytes).toString('utf8'),provenance=JSON.parse(readFileSync(new URL('./fixtures/train-preparation-pr9-mask-owned-bring.json.provenance.json',import.meta.url),'utf8')),sha=b=>createHash('sha256').update(b).digest('hex');assert.equal(sha(bytes),provenance.gzipSHA256);assert.equal(sha(raw),provenance.originalRawSHA256);const s=Journey.restoreCampaign(raw);assert.ok(s);assert.equal(Journey.serializeCampaign(s),raw);return s;}
function wornOnCopper(){
 const s=ownedMask();interactNative(s,'train:prepare-mask-wear');wait(s,()=>prep(s).work===null);
 // The historical herd begins overlapped. The real call earns separation;
 // neither the renderer nor this test relocates Copper or another mount.
 moveNative(s,{x:600,y:1330,z:0});Journey.whistleCampaign(s);const horse=s.entities.copper;
 for(let i=0;i<100&&(Math.hypot(s.player.x-horse.x,s.player.y-horse.y)>82.1||Math.hypot(horse.vx||0,horse.vy||0)>.01);i++)Journey.stepCampaign(s,.05);
 moveNative(s,{x:horse.x+28,y:horse.y,z:0});interactNative(s,'train:mount-copper');assert.equal(s.player.mounted,true);assert.equal(s.player.mountId,'copper');Journey.getCampaignInteractions(s);return s;
}
const context=()=>new Proxy({globalAlpha:1,globalCompositeOperation:'source-over',measureText:s=>({width:s.length*5})},{get:(o,k)=>k in o?o[k]:()=>{},set:(o,k,v)=>(o[k]=v,true)});
const close=(a,b)=>assert.ok(Math.hypot(...['x','y','z'].map(k=>a[k]-b[k]))<1e-7);
function fittedFace(head,rig,facing,fitVersion){const radius=rig.o.headR*rig.o.size,distance=fitVersion===2?radius*TRAIN_MASK_FIT_V2.forwardHeadRadius:radius+.15,z=fitVersion===2?radius*TRAIN_MASK_FIT_V2.verticalHeadRadius:-4;return{x:head.x+Math.cos(facing)*distance,y:head.y+Math.sin(facing)*distance,z:head.z+z};}
function render(s){
 const p=createTrainCampPresentation(E),entry=currentPreparationMaskPose(s,s.player),chosen=entry?.kind==='mask-fitting'?entry:activePreparationCampWorkPose(s,s.player)||entry,rig=chosen?.human.rig,old=rig?.update,joints=rig&&structuredClone(rig.J),time=rig?.t,geometry=entry&&structuredClone(entry.geometry),sourceJoints=entry&&structuredClone(entry.human.rig.J),sourceTime=entry?.human.rig.t,mount=entry?.mountRig,mountUpdate=mount?.update,mountPose=mount?.pose,mountBefore=mount&&structuredClone({J:mount.J,clock:mount.clock,phase:mount.phase,speed:mount.speed,fear:mount.fear}),before=Journey.serializeCampaign(s),pending=[],view=E.VIEWS.threequarter,r={view,w:(...args)=>view.p(...args),visible:()=>true,shadow:()=>{},queue:(x,y,z,fn,o)=>pending.push({key:view.order(x,y,z)+(o?.bias||0),fn})};
 if(rig)rig.update=()=>{throw Error('Presentation must not advance the actual clothing physics Human');};
 if(mount)mount.update=mount.pose=()=>{throw Error('Presentation must not advance or re-pose the actual physics mount');};
 try{p.update(.05,s);p.draw(r,s);const g=context();pending.sort((a,b)=>a.key-b.key);for(const item of pending)item.fn(g);const result=p.inspect();assert.deepEqual(result.errors,[]);assert.equal(Journey.serializeCampaign(s),before);assert.ok(Journey.restoreCampaign(before));if(mount)assert.deepEqual({J:mount.J,clock:mount.clock,phase:mount.phase,speed:mount.speed,fear:mount.fear},mountBefore);if(entry){assert.deepEqual(rig.J,joints);assert.equal(rig.t,time);assert.deepEqual(entry.geometry,geometry);assert.deepEqual(entry.human.rig.J,sourceJoints);assert.equal(entry.human.rig.t,sourceTime);const actor=result.actors.find(a=>a.id==='mara'),masks=result.objects.filter(o=>o.id===TRAIN_MASK_ID);assert.equal(result.actors.filter(a=>a.id==='mara').length,1);assert.equal(actor.physicsHuman,true);assert.equal(actor.rigUpdateSkipped,true);assert.equal(masks.length,1);assert.equal(masks[0].physicsHuman,true);assert.equal(masks[0].fitVersion,geometry.fitVersion);assert.equal(masks[0].location,s.itemInstances[TRAIN_MASK_ID].location.type);assert.equal(masks[0].getterHumanMatchesDraw,chosen.human===entry.human);assert.equal(masks[0].geometrySource,entry.kind==='mask-fitting'?'active-native-fitting':'drawn-native-pose');if(entry.kind==='mask-fitting')assert.deepEqual(masks[0].world,geometry.center);assert.deepEqual(masks[0].axes,geometry.axes);assert.deepEqual(masks[0].halfExtents,geometry.halfExtents);assert.equal(masks[0].vertices.length,8);for(const vertex of masks[0].vertices)for(const axis of ['x','y','z']){const projected=['x','y','z'].reduce((n,k)=>n+(vertex[k]-masks[0].world[k])*geometry.axes[axis][k],0);assert.ok(Math.abs(Math.abs(projected)-geometry.halfExtents[axis])<1e-7,'drawn finite corners match the actual material envelope');}if(entry.kind==='mask-fitting'){const contact=result.contacts.find(c=>c.actorId==='mara'&&c.kind==='preparation-mask-'+geometry.mode);assert.ok(contact?.reachable);close(contact.hit,geometry.hand);close(actor.elbow,entry.joints[1]);}else{close(masks[0].facePoint,fittedFace(actor.maskHead,rig,s.player.facing,geometry.fitVersion));}}return result;}finally{if(rig)rig.update=old;if(mount){mount.update=mountUpdate;mount.pose=mountPose;}}
}

test('unchanged unmarked fit1 pending save preserves legacy geometry through current restore, native completion and whole renderer composition',async()=>{
 const path=new URL('./fixtures/train-preparation-mask-fit1-pending.json.gz',import.meta.url),packed=readFileSync(path),raw=gunzipSync(packed).toString('utf8'),provenance=JSON.parse(readFileSync(new URL('./fixtures/train-preparation-mask-fit1-pending.provenance.json',import.meta.url),'utf8')),sha=b=>createHash('sha256').update(b).digest('hex');assert.equal(sha(packed),provenance.gzipSHA256);assert.equal(sha(raw),provenance.originalRawSHA256);let s=Journey.restoreCampaign(raw);assert.ok(s);assert.equal(Journey.serializeCampaign(s),raw);assert.equal(prep(s).work.maskFitVersion,undefined);const pending=structuredClone(trainRecord(s).train.powder.pending[0]);assert.ok(pending.acceptedSeconds>0);Journey.getCampaignInteractions(s);const entry=getPreparationMaskPose(s);assert.ok(entry);assert.equal(entry.geometry.fitVersion,1);assert.equal(render(s).objects.find(o=>o.id===TRAIN_MASK_ID).fitVersion,1);wait(s,()=>prep(s).work===null);Journey.getCampaignInteractions(s);assert.equal(getPreparationWornMaskPose(s).geometry.fitVersion,1);assert.equal(render(s).objects.find(o=>o.id===TRAIN_MASK_ID).fitVersion,1);await snowboundComposition(s,getPreparationWornMaskPose(s));const finished=trainRecord(s).train.powder.physicalEvents.find(e=>e.kind==='work-completed'&&e.data.workId===pending.workId);assert.ok(finished);assert.deepEqual(finished.data.intervals.slice(0,pending.intervals.length),pending.intervals);const end=Journey.serializeCampaign(s);s=Journey.restoreCampaign(end);assert.ok(s);assert.equal(Journey.serializeCampaign(s),end);Journey.getCampaignInteractions(s);assert.equal(render(s).objects.find(o=>o.id===TRAIN_MASK_ID).fitVersion,1);
});

test('historically earned original garment renders once through current native wear, mid-work restore, worn head and removal; stowed inventory has no hand proxy',()=>{
 let s=ownedMask();const born=structuredClone(s.itemInstances[TRAIN_MASK_ID]);assert.equal(currentPreparationMaskPose(s,s.player),null);assert.equal(render(s).objects.filter(o=>o.id===TRAIN_MASK_ID).length,0);
 for(const[id,worn]of [['train:prepare-mask-wear',true],['train:prepare-mask-remove',false]]){
  interactNative(s,id);wait(s,()=>!!getPreparationMaskPose(s)&&trainRecord(s).train.powder.pending.some(w=>w.acceptedSeconds>0));const active=getPreparationMaskPose(s);assert.equal(currentPreparationMaskPose(s,s.player).kind,'mask-fitting');assert.equal(active.geometry.fitVersion,2);if(!worn)assert.ok(getPreparationWornMaskPose(s),'active removal wins over the still-owned worn source');const first=render(s);assert.equal(first.objects.find(o=>o.id===TRAIN_MASK_ID).presentation,'mask-fitting');assert.equal(s.itemInstances[TRAIN_MASK_ID].location.type,worn?'carried':'worn','presentation does not commit ownership early');
  const oldWork=active.workId,raw=Journey.serializeCampaign(s);s=Journey.restoreCampaign(raw);assert.ok(s);Journey.stepCampaign(s,.05);assert.equal(getPreparationMaskPose(s).workId,oldWork);render(s);wait(s,()=>prep(s).work===null);Journey.getCampaignInteractions(s);assert.equal(s.itemInstances[TRAIN_MASK_ID].location.type,worn?'worn':'carried');const after=render(s);assert.equal(after.objects.filter(o=>o.id===TRAIN_MASK_ID).length,worn?1:0);assert.equal(currentPreparationMaskPose(s,s.player)?.kind??null,worn?'mask-worn':null);assert.equal(s.itemInstances[TRAIN_MASK_ID].issueEventId,born.issueEventId);assert.equal(s.itemInstances[TRAIN_MASK_ID].issuedAt,born.issuedAt);
 }
 assert.deepEqual({...s.itemInstances[TRAIN_MASK_ID],location:born.location},born);assert.equal(s.campaign.missions['snowbound-the-names-they-took'].rival.continuation.events.filter(e=>e.kind==='issue-mask').length,1);
});

test('actual walking changes the worn native face frame and actual drawing cancels a fit without leaving a rendered garment copy',()=>{
 const s=ownedMask();interactNative(s,'train:prepare-mask-wear');wait(s,()=>prep(s).work===null);Journey.getCampaignInteractions(s);const before=getPreparationWornMaskPose(s).geometry.center,oldY=s.player.y;Journey.stepCampaign(s,.05,{mx:0,my:-1});Journey.getCampaignInteractions(s);assert.ok(s.player.y<oldY,'normal native motion changes the body');const after=render(s),mask=after.objects.find(o=>o.id===TRAIN_MASK_ID);assert.notDeepEqual(mask.world,before);assert.equal(mask.facesCamera,false,'the actual backwards-facing garment draws behind the native head');
 interactNative(s,'train:prepare-mask-remove');wait(s,()=>!!getPreparationMaskPose(s));Journey.campaignAction(s,'draw');assert.equal(getPreparationMaskPose(s),null);Journey.stepCampaign(s,.05);Journey.getCampaignInteractions(s);assert.equal(s.itemInstances[TRAIN_MASK_ID].location.type,'worn');assert.equal(currentPreparationMaskPose(s,s.player).kind,'mask-worn');assert.equal(render(s).objects.filter(o=>o.id===TRAIN_MASK_ID).length,1,'the original still-worn garment remains; the interrupted fit creates no copy');
});

test('genuine wear then crouched walk and immediate standing inspection binds the worn cloth to the selected work Human’s drawn head',()=>{
 const s=ownedMask();interactNative(s,'train:prepare-mask-wear');wait(s,()=>prep(s).work===null);Journey.campaignAction(s,'crouch');for(let i=0;i<6;i++)Journey.stepCampaign(s,.05);assert.equal(s.player.crouch,true);moveNative(s,TRAIN_STORE_MARA);Journey.campaignAction(s,'stand');assert.equal(s.player.crouch,false);interactNative(s,'train:prepare-inspect:quarry-sealed-charge-1');wait(s,()=>!!activePreparationCampWorkPose(s,s.player)&&trainRecord(s).train.powder.pending.some(w=>w.acceptedSeconds>0));
 const work=activePreparationCampWorkPose(s,s.player),idle=getPreparationWornMaskPose(s);assert.ok(idle);assert.notEqual(work.human,idle.human,'different genuine provider histories must be exercised');const itemBefore=structuredClone(s.itemInstances[TRAIN_MASK_ID]),result=render(s),actor=result.actors.find(a=>a.id==='mara'),mask=result.objects.find(o=>o.id===TRAIN_MASK_ID);assert.equal(actor.work,'preparation');assert.equal(mask.geometrySource,'drawn-native-pose');assert.equal(mask.getterHumanMatchesDraw,false);assert.equal(mask.physicsHuman,true);assert.ok(Math.abs(mask.facePoint.z-idle.geometry.face.z)>.5,'standing work and the earlier crouch/walk idle blend genuinely differ');assert.equal(mask.fitVersion,2);close(mask.facePoint,fittedFace(actor.maskHead,work.human.rig,s.player.facing,2));assert.deepEqual(s.itemInstances[TRAIN_MASK_ID],itemBefore);assert.ok(Journey.restoreCampaign(Journey.serializeCampaign(s)));
});

test('genuine wear then walking to Copper and offered mounting uses the actual shared seated Human/mount through whole Save reload',()=>{
 let s=wornOnCopper();const born=structuredClone(s.itemInstances[TRAIN_MASK_ID]);
 for(let pass=0;pass<2;pass++){
  const entry=getPreparationWornMaskPose(s);assert.ok(entry?.mountRig);assert.equal(entry.mountBody,s.entities.copper);assert.equal(currentPreparationMaskMount(s,s.entities.copper)?.human,entry.human);close(s.player,s.horse);const body=structuredClone({x:s.player.x,y:s.player.y,z:s.player.z||0}),horse=structuredClone(s.entities.copper),result=render(s),actor=result.actors.find(a=>a.id==='mara'),mount=result.actors.find(a=>a.id==='copper');assert.equal(result.actors.filter(a=>a.id==='mara').length,1);assert.equal(result.actors.filter(a=>a.id==='copper').length,1);assert.equal(mount.physicsMount,true);assert.equal(mount.rigUpdateSkipped,true);close(actor.drawRoot,entry.mountedRoot);assert.ok(actor.drawRoot.z>body.z+10,'the actual saddle determines the private seated root');const contacts=result.contacts.filter(c=>c.actorId==='mara'&&c.kind.startsWith('mounted-'));assert.equal(contacts.filter(c=>c.kind==='mounted-stirrup').length,2);assert.equal(contacts.filter(c=>c.kind==='mounted-rein').length,2);assert.ok(contacts.every(c=>c.reachable&&c.error<1e-5));for(const c of contacts){const physical=entry.mountedContacts.find(p=>p.kind===c.kind&&p.side===c.side);assert.ok(physical);close(c.hit,physical.hit);close(c.target,physical.target);}assert.deepEqual(s.entities.copper,horse);assert.deepEqual({x:s.player.x,y:s.player.y,z:s.player.z||0},body);assert.deepEqual(s.itemInstances[TRAIN_MASK_ID],born);const raw=Journey.serializeCampaign(s);s=Journey.restoreCampaign(raw);assert.ok(s);assert.equal(Journey.serializeCampaign(s),raw);Journey.getCampaignInteractions(s);
 }
 interactNative(s,'train:dismount-copper');assert.equal(s.player.mounted,false);assert.equal(currentPreparationMaskMount(s,s.entities.copper),null);Journey.getCampaignInteractions(s);assert.equal(getPreparationWornMaskPose(s).mountRig,undefined);assert.equal(render(s).objects.filter(o=>o.id===TRAIN_MASK_ID).length,1);assert.ok(Journey.restoreCampaign(Journey.serializeCampaign(s)));
});

async function snowboundComposition(s,entry){
 const mount=entry.mountRig,oldMountDraw=mount?.draw;let mountDraws=0,legacyAtMount=0;if(mount)mount.draw=function(...args){mountDraws++;return oldMountDraw.apply(this,args);};const before=Journey.serializeCampaign(s),ids=new WeakMap([[entry.human.rig,'mara']]),updates=[],draws=[],oldDoc=globalThis.document,update=E.Humanoid.prototype.update,draw=E.Humanoid.prototype.draw;globalThis.document={createElement:()=>({getContext:()=>context()})};E.Humanoid.prototype.update=function(dt,body){ids.set(this,body.id);if(body.id==='mara')updates.push(body.id);return update.call(this,dt,body);};E.Humanoid.prototype.draw=function(...args){if(ids.get(this)==='mara')draws.push('mara');return draw.apply(this,args);};
 try{const{createSnowboundRenderer}=await import('../src/snowbound-renderer.js'),game={reduceMotion:false,cam:{x:0,y:0},view:E.VIEWS.threequarter},renderer=createSnowboundRenderer(game),pending=[],g=context(),view=game.view,base={game,ctx:g,view,H:800,W:1280,bw:1280,bh:800,ix:0,iy:0,w:(...args)=>view.p(...args),visible:()=>true,queue:(x,y,z,fn,o)=>pending.push({key:view.order(x,y,z)+(o?.bias||0),fn}),actor:(x,y,z,fn)=>{if(mount&&Math.abs(x-entry.mountBody.x)<1e-7&&Math.abs(y-entry.mountBody.y)<1e-7)legacyAtMount++;pending.push({key:view.order(x,y,z),fn:g=>fn(g,...view.p(x,y,z))});},overlay:fn=>pending.push({key:Infinity,fn}),shadow:()=>{},sky:()=>{},box:()=>{}};renderer.update(.05,s);renderer.draw(new Proxy(base,{get:(o,k)=>k in o?o[k]:()=>{}}),s);pending.sort((a,b)=>a.key-b.key);for(const item of pending)item.fn(g);assert.deepEqual(updates,[]);assert.deepEqual(draws,['mara']);if(mount){assert.equal(mountDraws,1);assert.equal(legacyAtMount,0,'the explicit legacy party-horse draw must defer to its actual native owner');const horses=renderer.inspectTrainCampAnimation().actors.filter(a=>a.id==='copper');assert.equal(horses.length,1);assert.equal(horses[0].physicsMount,true);}const masks=renderer.inspectTrainCampAnimation().objects.filter(o=>o.id===TRAIN_MASK_ID);assert.equal(masks.length,1);assert.equal(masks[0].fitVersion,entry.geometry.fitVersion);assert.equal(Journey.serializeCampaign(s),before);assert.ok(Journey.restoreCampaign(before));}finally{E.Humanoid.prototype.update=update;E.Humanoid.prototype.draw=draw;if(mount)mount.draw=oldMountDraw;if(oldDoc===undefined)delete globalThis.document;else globalThis.document=oldDoc;}
}
test('full Snowbound composition draws masked Mara exactly once with no competing legacy or second physics update',async()=>{const s=ownedMask();interactNative(s,'train:prepare-mask-wear');wait(s,()=>!!getPreparationMaskPose(s)&&trainRecord(s).train.powder.pending.some(w=>w.acceptedSeconds>0));await snowboundComposition(s,getPreparationMaskPose(s));});
test('full Snowbound mounted composition draws the actual Copper and Mara once with no competing party-horse callback',async()=>{const s=wornOnCopper();await snowboundComposition(s,getPreparationWornMaskPose(s));});

// Invalid hand-authored records stay outside the dedicated native draw owner.
// This negative fixture does not stand in for genuinely earned stable duty.
test('forged stable duty cannot claim Inez, Skein or a finite rein in the camp renderer',()=>{
 const s=ownedMask(),p=prep(s);for(const duty of [{schema:2,phase:'west',gripSeconds:.8,steps:[]},{schema:2,phase:'grip',startedAt:s.elapsed,lastAdvancedAt:s.elapsed,gripSeconds:.5,watch:{guardId:'hob'},steps:[]}]){p.stableDuty=duty;for(const id of ['inez','skein']){assert.equal(currentPreparationStableWork(s,s.entities[id]),null);assert.equal(ownsTrainCampActor(s,s.entities[id]),false);}}assert.equal(currentPreparationStableWork(s,{...s.entities.inez}),null);
});

test('forged manual care cannot claim the original Inez or Skein presentation or draw a care operation',()=>{const s=ownedMask(),p=prep(s);for(const record of [{schema:1,work:{kind:'tack',phase:'contact',seconds:1},completed:[]},{schema:1,work:{kind:'coat',phase:'reach',seconds:.4},requests:[],steps:[]}]){p.stableCare=record;for(const id of ['inez','skein']){assert.equal(currentPreparationCareWork(s,s.entities[id]),null);assert.equal(ownsTrainCampActor(s,s.entities[id]),false);}}assert.equal(currentPreparationCareWork(s,{...s.entities.inez}),null);});
