/** Original Snowbound opening: authored world and mission data. Distances are world units. */
export const SNOWBOUND_STAGES = [
  'Put on the wool coat, take the starter lantern, and speak with Tomas Reed at the kiln.',
  'Ride the switchback with Tomas. Inspect the severed wire with Inez, then reach the station hitch.',
  'Hitch Juniper outside rifle range. Choose culvert or winch cover while Tomas approaches Voss.',
  'Protect Tomas and Inez. Defeat the gauge guard and coal-chute flanker; Voss may escape.',
  'Search the relay room for blankets, oil, oats, bandages, broth and kindling. Read the optional message log.',
  'Investigate the coal store. Block Pavel, shove and restrain him, recover your weapon and token, then question him.',
  'Holster, approach Copper slowly, speak, calm, pat, and lead her to the station hitch.',
  'Answer Ada’s alarm. Choose a rescue priority, open the relief valve, and bring Ada and Gideon to the safe walkway.',
  'Return to the kiln with the Rusks and Copper. Deposit the recovered supplies in the stove store.',
];

export const CAMPAIGN_ITEMS = {
  tonic: { name: 'Health tonic', description: 'Restores 55 health.' },
  coffee: { name: 'Strong coffee', description: 'Restores 50 focus.' },
  oats: { name: 'Oat sack', description: 'Feed Copper or deliver the remaining oats to camp.' },
  blankets: { name: 'Wool blankets', description: 'Warmth for the kiln community.' },
  oil: { name: 'Lamp oil', description: 'Fuel for the communal lanterns.' },
  bandages: { name: 'Clean bandages', description: 'Restores 35 health; Gideon needs the remaining dressings.' },
  broth: { name: 'Canned broth', description: 'Restores stamina and 15 health, or feeds the community.' },
  kindling: { name: 'Dry kindling', description: 'Lights the communal stove.' },
  logbook: { name: 'Copperglass message log', description: 'Evidence of Silas Orr’s scheduled interception.' },
  token: { name: 'Community token', description: 'Tomas’s mark, recovered after Pavel’s ambush.' },
};

export const SNOWBOUND_WORLD = {
  id: 'snowbound', width: 1800, height: 1400,
  places: [
    { id: 'refuge', name: 'Lime Kiln Refuge', x: 320, y: 1100 },
    { id: 'wire', name: 'Severed Telegraph Wire', x: 760, y: 780 },
    { id: 'station', name: 'Copperglass Station', x: 1330, y: 470 },
    { id: 'hitch', name: 'Traveling Hitch', x: 1100, y: 565 },
    { id: 'relay', name: 'Relay Room', x: 1390, y: 330 },
    { id: 'coalstore', name: 'Coal Store', x: 1180, y: 760 },
    { id: 'pen', name: 'Animal Pen', x: 1530, y: 620 },
    { id: 'walkway', name: 'Stone Service Walkway', x: 1130, y: 430 },
  ],
  trail: [
    { x: 465, y: 1000 }, { x: 610, y: 920 }, { x: 760, y: 780 },
    { x: 875, y: 710 }, { x: 970, y: 640 }, { x: 1100, y: 565 },
  ],
  interiors: [
    { id: 'relay', name: 'Relay room', x: 1300, y: 240, w: 280, h: 180, doors: [{ x: 1390, y: 420 }, { x: 1300, y: 345 }] },
    { id: 'coalstore', name: 'Coal store', x: 1080, y: 710, w: 200, h: 140, doors: [{ x: 1185, y: 710 }, { x: 1280, y: 785 }] },
  ],
  obstacles: [
    { id: 'kiln', x: 225, y: 1015, w: 100, h: 60, kind: 'kiln' },
    { id: 'refuge-tent', x: 400, y: 1080, w: 75, h: 50, kind: 'tent' },
    { id: 'relay-north', x: 1300, y: 230, w: 290, h: 10, kind: 'wall' },
    { id: 'relay-east', x: 1580, y: 240, w: 10, h: 190, kind: 'wall' },
    { id: 'relay-south-west', x: 1300, y: 420, w: 65, h: 10, kind: 'wall' },
    { id: 'relay-south-east', x: 1415, y: 420, w: 175, h: 10, kind: 'wall' },
    { id: 'relay-west-north', x: 1290, y: 230, w: 10, h: 90, kind: 'wall' },
    { id: 'relay-west-south', x: 1290, y: 370, w: 10, h: 60, kind: 'wall' },
    { id: 'coal-north-west', x: 1080, y: 700, w: 75, h: 10, kind: 'wall' },
    { id: 'coal-north-east', x: 1215, y: 700, w: 75, h: 10, kind: 'wall' },
    { id: 'coal-west', x: 1070, y: 700, w: 10, h: 150, kind: 'wall' },
    { id: 'coal-south', x: 1080, y: 850, w: 210, h: 10, kind: 'wall' },
    { id: 'coal-east-north', x: 1280, y: 710, w: 10, h: 45, kind: 'wall' },
    { id: 'coal-east-south', x: 1280, y: 815, w: 10, h: 45, kind: 'wall' },
    { id: 'culvert', x: 1195, y: 555, w: 80, h: 30, kind: 'cover' },
    { id: 'winch', x: 1280, y: 605, w: 55, h: 30, kind: 'cover' },
    { id: 'gauge-cover', x: 1325, y: 495, w: 38, h: 25, kind: 'crate' },
    { id: 'coal-chute', x: 1345, y: 670, w: 100, h: 25, kind: 'chute' },
    { id: 'boiler', x: 1415, y: 450, w: 110, h: 70, kind: 'boiler' },
    { id: 'pen-north', x: 1490, y: 530, w: 200, h: 8, kind: 'fence' },
    { id: 'pen-east', x: 1682, y: 530, w: 8, h: 175, kind: 'fence' },
    { id: 'pen-south', x: 1490, y: 697, w: 200, h: 8, kind: 'fence' },
    { id: 'pen-west-north', x: 1482, y: 530, w: 8, h: 45, kind: 'fence' },
    { id: 'pen-west-south', x: 1482, y: 655, w: 8, h: 50, kind: 'fence' },
  ],
  props: [
    { id: 'coat', kind: 'coat', name: 'Provided wool coat', x: 350, y: 1075 },
    { id: 'lantern', kind: 'lantern', name: 'Starter lantern', x: 375, y: 1080 },
    { id: 'stove-store', kind: 'stove', name: 'Communal stove store', x: 350, y: 1140 },
    { id: 'wire', kind: 'wire', name: 'Severed wire', x: 760, y: 780 },
    { id: 'hitch', kind: 'hitch', name: 'Traveling hitch', x: 1100, y: 565 },
    { id: 'cover-culvert', kind: 'cover-marker', name: 'Culvert cover', x: 1230, y: 605 },
    { id: 'cover-winch', kind: 'cover-marker', name: 'Timber winch cover', x: 1305, y: 660 },
    { id: 'eviction-tag', kind: 'tag', name: 'Copper’s eviction tag', x: 1505, y: 620 },
    { id: 'medical-chair', kind: 'chair', name: 'Overturned medical chair', x: 1370, y: 310 },
    { id: 'torn-sleeve', kind: 'clue', name: 'Gideon’s torn sleeve', x: 1430, y: 340 },
    { id: 'coal-platform', kind: 'platform', name: 'Pavel’s storage platform', x: 1145, y: 810 },
    { id: 'pressure-valve', kind: 'valve', name: 'Pressure relief valve', x: 1270, y: 490 },
    { id: 'speaking-tube', kind: 'tube', name: 'Relay speaking tube', x: 1280, y: 445 },
    { id: 'safe-walkway', kind: 'waypoint', name: 'Safe service walkway', x: 1130, y: 430 },
    { id: 'service-tunnel', kind: 'tunnel', name: 'Voss’s side exit', x: 1090, y: 360 },
    { id: 'telegraph', kind: 'telegraph', name: 'Damaged telegraph', x: 1480, y: 245 },
    { id: 'red-signal-lamp', kind: 'lamp', name: 'Red station lamp', x: 1360, y: 440 },
  ],
  supplies: [
    { id: 'blankets', name: 'Wool blankets', x: 1330, y: 280, amount: 1, essential: true },
    { id: 'oil', name: 'Lamp oil', x: 1430, y: 260, amount: 1, essential: true },
    { id: 'oats', name: 'Oat sack', x: 1515, y: 380, amount: 2, essential: true },
    { id: 'bandages', name: 'Clean bandages', x: 1420, y: 370, amount: 2, essential: true },
    { id: 'broth', name: 'Canned broth', x: 1330, y: 385, amount: 2, essential: true },
    { id: 'kindling', name: 'Dry kindling', x: 1515, y: 285, amount: 1, essential: true },
    { id: 'logbook', name: 'Message log', x: 1480, y: 325, amount: 1, essential: false },
  ],
  rescueRoute: [{ x: 1360, y: 345 }, { x: 1260, y: 345 }, { x: 1220, y: 430 }, { x: 1130, y: 430 }],
  copperRoute: [{ x: 1450, y: 615 }, { x: 1465, y: 735 }, { x: 1320, y: 735 }, { x: 1320, y: 650 }, { x: 1160, y: 650 }, { x: 1100, y: 565 }],
  returnRoute: [{ x: 1000, y: 780 }, { x: 600, y: 970 }, { x: 350, y: 1140 }],
  campHomes: { ada: { x: 330, y: 1165 }, gideon: { x: 305, y: 1175 }, tomas: { x: 310, y: 1115 }, inez: { x: 385, y: 1165 }, pavel: { x: 435, y: 1180 } },
};

export const SNOWBOUND_CAST = [
  { id: 'tomas', name: 'Tomas Reed', role: 'community organizer', x: 305, y: 1115, hp: 100, faction: 'camp' },
  { id: 'inez', name: 'Inez Pike', role: 'stable hand', x: 785, y: 775, hp: 100, faction: 'camp' },
  { id: 'ada', name: 'Ada Rusk', role: 'signal operator', x: 1395, y: 290, hp: 100, faction: 'camp' },
  { id: 'gideon', name: 'Gideon Rusk', role: 'injured station keeper', x: 1430, y: 325, hp: 60, faction: 'camp', injured: true },
  { id: 'pavel', name: 'Pavel Dune', role: 'cornered guard', x: 1150, y: 795, hp: 80, faction: 'company', hidden: true },
  { id: 'neri', name: 'Neri Bell', role: 'the camp’s lost cook', x: 275, y: 1145, hp: 0, faction: 'camp' },
];
