/** Selected native train rendering. Physics/ownership/progression are callers'
 * authority; drawing consumes the SAME car frames and cover volumes as queries. */
import {worldPoint,worldVector,localPoint,add,sub,scale,dot,length,validPoint,cross} from '../rail-foundation/rigid-frame.js';
import {validateBodySupport,worldContact} from '../rail-foundation/moving-support.js';
import {sampleRail,validateCarSpecs} from '../rail-foundation/rail-consist.js';
import {createTrainHuman,createTrainMount,prepareTrainPose,prepareTrainMountedPose,physicalProjection,drawTrainOutfit,rigWorldPoint} from './rigs.js';
const rows=v=>Array.isArray(v)?v:Object.values(v||{}),copy=v=>JSON.parse(JSON.stringify(v));
const palettes={timber:'#8d775a','roof-tin':'#b7b1a0',steel:'#52686a','boiler-iron':'#986d3c','reinforced-iron':'#384d45','safe-iron':'#52615b',coal:'#363c38'};
function vertices(frame,b){const list=[];for(const z of[b.min.z,b.max.z])for(const y of[b.min.y,b.max.y])for(const x of[b.min.x,b.max.x])list.push(worldPoint(frame,{x,y,z}));return list;}
const faces=[[2,3,1,0],[5,7,6,4],[1,5,4,0],[6,7,3,2],[4,6,2,0],[3,7,5,1]];
const centroid=p=>scale(p.reduce((v,p)=>add(v,p),{x:0,y:0,z:0}),1/p.length);
function paintFace(E,r,g,world,color,alpha){E.px.blend(g,alpha,'normal',()=>E.px.poly(g,world.map(p=>r.w(p.x,p.y,p.z)),color));}
function walkMotion(body,platform){return body.support&&platform?worldVector(platform.frame,body.support.relativeVelocity):{x:body.vx||0,y:body.vy||0,z:body.vz||0};}
export function createTrainRenderer(E,game,{cars,track=null,trackGauge=track?.gauge??36}={}){
 if(!validateCarSpecs(cars)||cars.some(c=>c.wheelY!==undefined&&(!Number.isFinite(c.wheelY)||c.wheelY<=0||c.wheelY>c.width/2)||c.wheelAxles!==undefined&&(!Array.isArray(c.wheelAxles)||!c.wheelAxles.length||c.wheelAxles.some(x=>!Number.isFinite(x)||Math.abs(x)+c.wheelRadius>c.length/2+1e-7))))throw new TypeError('Unique authored cars required');
 const railFrames=[];if(track){for(let s=0;s<track.length;s+=12)railFrames.push(sampleRail(track,s).frame);railFrames.push(sampleRail(track,track.length).frame);}
 const humans=new Map(),mounts=new Map();let diagnostics={actors:[],geometry:[],contacts:[],wheels:[],cutaways:[],errors:[],drawOrder:[],objects:[]};
 const human=body=>{if(!humans.has(body.id))humans.set(body.id,createTrainHuman(E,body));return humans.get(body.id);};
 const mount=body=>{if(!mounts.has(body.id))mounts.set(body.id,createTrainMount(E,body));return mounts.get(body.id);};
 function update(dt,scene){
  for(const body of rows(scene.actors)){if(body.hidden)continue;const p=scene.platforms.find(p=>p.id===body.support?.carId),v=walkMotion(body,p);
   if(body.kind==='horse'||body.category==='mount')mount(body).update(dt,body,!!scene.reduceMotion);
   else{const h=human(body);h.rig.update(dt,{...body,z:0,vx:body.mounted?0:v.x,vy:body.mounted?0:v.y,vz:body.mounted?0:v.z,air:!body.mounted&&!body.onGround,pose:body.hp<=0?'die':body.pose||(body.crouch?'crouch':null)});}
  }
 }
 function draw(r,scene){
  const actors=rows(scene.actors);if(new Set(actors.map(a=>a.id)).size!==actors.length)throw new TypeError('A render scene cannot own duplicate actor identities');
  diagnostics={actors:[],geometry:[],contacts:[],wheels:[],cutaways:[],errors:[],drawOrder:[],objects:[]};const q=(x,y,z,fn,tag={})=>{const key=tag.depth??r.view.depth(x,y,z);r.queue(x,y,z,g=>{diagnostics.drawOrder.push({...tag,key});fn(g);},{bias:key-r.view.order(x,y,z),occluder:true});};const byId=new Map(actors.map(a=>[a.id,a])),viewer=byId.get(scene.viewerId||'mara'),viewerPlatform=scene.platforms.find(p=>p.id===viewer?.support?.carId);
  for(let i=1;i<railFrames.length;i++)for(const sign of[-1,1]){const a=worldPoint(railFrames[i-1],{x:0,y:sign*trackGauge/2,z:0}),b=worldPoint(railFrames[i],{x:0,y:sign*trackGauge/2,z:0}),c=centroid([a,b]);if(r.visible&&!r.visible(c.x,c.y,c.z,40,40,40))continue;q(c.x,c.y,c.z,g=>E.px.line(g,...r.w(a.x,a.y,a.z),...r.w(b.x,b.y,b.z),'#697c76',2));}
  for(const car of scene.consist.cars){const spec=cars.find(c=>c.id===car.id),p=scene.platforms.find(p=>p.id===car.id);if(!spec||!p)throw new TypeError('Missing actual car frame');if(r.visible&&!r.visible(p.frame.origin.x,p.frame.origin.y,p.frame.origin.z,spec.length+spec.width,spec.length+spec.width,160))continue;
   const viewerSurface=car.id===viewer?.support?.carId?p.surfaces.find(s=>s.id===viewer.support.surfaceId):null,inside=!!viewerSurface&&!/roof/.test(viewerSurface.id),roofHeight=Math.max(...p.surfaces.map(s=>s.bounds.max.z));
   for(const surface of p.surfaces){const b=surface.bounds,world=[worldPoint(p.frame,{x:b.min.x,y:b.min.y,z:b.max.z}),worldPoint(p.frame,{x:b.max.x,y:b.min.y,z:b.max.z}),worldPoint(p.frame,{x:b.max.x,y:b.max.y,z:b.max.z}),worldPoint(p.frame,{x:b.min.x,y:b.max.y,z:b.max.z})],roof=/roof/.test(surface.id),alpha=inside&&roof?.12:1,center=centroid(world);
    diagnostics.geometry.push({carId:car.id,id:surface.id,kind:'surface',world:copy(world),alpha});q(center.x,center.y,center.z,g=>paintFace(E,r,g,world,roof?'#b7b1a0':'#968568',alpha),{kind:'surface',carId:car.id,id:surface.id,depth:Math.min(...world.map(p=>r.view.depth(p.x,p.y,p.z)))-1e-4});
   }
   for(const cover of p.cover){const b=cover.bounds,world=vertices(p.frame,b),isRoof=/roof/.test(cover.id),thinY=b.max.y-b.min.y<=4,side=(b.min.y+b.max.y)/2,nearWall=thinY&&dot(scale(p.frame.y,Math.sign(side)),{x:r.view.fx,y:r.view.fy,z:0})>0,alpha=inside&&(isRoof||nearWall)?.12:1;
    diagnostics.geometry.push({carId:car.id,id:cover.id,kind:'cover',world:copy(world),alpha,bodySolid:cover.bodySolid,projectileSolid:cover.projectileSolid});if(alpha<1)diagnostics.cutaways.push({carId:car.id,coverId:cover.id,collisionUnchanged:true});
    for(let index=0;index<faces.length;index++){const polygon=faces[index].map(i=>world[i]),normal=cross(sub(polygon[1],polygon[0]),sub(polygon[2],polygon[0]));if(dot(normal,{x:r.view.dx,y:r.view.dy,z:r.view.dz})<=0)continue;const center=centroid(polygon),color=palettes[cover.material]||palettes.timber;q(center.x,center.y,center.z,g=>paintFace(E,r,g,polygon,color,alpha),{kind:'cover',carId:car.id,id:cover.id});}
   }
   for(const contact of p.contacts||[]){if(!['control','climb','hanging-grip','charge-placement'].includes(contact.kind))continue;const target=worldPoint(p.frame,contact.local),base=worldPoint(p.frame,{...contact.local,z:contact.local.z-(contact.kind==='control'?10:3)});q(target.x,target.y,target.z,g=>{E.px.line(g,...r.w(base.x,base.y,base.z),...r.w(target.x,target.y,target.z),contact.kind==='charge-placement'?'#7c8881':'#b5b89d',2);E.px.disc(g,...r.w(target.x,target.y,target.z),2,contact.kind==='control'?'#d2c28a':'#a2b3ab');},{kind:'contact-prop',carId:car.id,id:contact.id});}
   const wheelY=spec.wheelY??trackGauge/2,axles=spec.wheelAxles??(car.id==='morrow-engine'?[-spec.length*.28,-spec.length*.08]:[-spec.length*.3,spec.length*.3]);
   if(spec.wheelY===undefined||spec.wheelAxles===undefined)diagnostics.errors.push({kind:'provisional-wheel-layout',carId:car.id});
   for(const x of axles)for(const side of[-1,1]){const centerLocal={x,y:side*wheelY,z:spec.wheelRadius},center=worldPoint(p.frame,centerLocal),ring=[];for(let n=0;n<24;n++){const a=n*Math.PI/12;ring.push(worldPoint(p.frame,{x:x+Math.cos(a)*spec.wheelRadius,y:side*wheelY,z:spec.wheelRadius+Math.sin(a)*spec.wheelRadius}));}
    diagnostics.wheels.push({carId:car.id,center,angle:car.wheelAngle,radius:spec.wheelRadius});q(center.x,center.y,center.z,g=>{paintFace(E,r,g,ring,'#3b4b49',1);for(let n=0;n<6;n++){const angle=car.wheelAngle+n*Math.PI/3,tip=worldPoint(p.frame,{x:x+Math.cos(angle)*spec.wheelRadius*.85,y:side*wheelY,z:spec.wheelRadius+Math.sin(angle)*spec.wheelRadius*.85});E.px.line(g,...r.w(center.x,center.y,center.z),...r.w(tip.x,tip.y,tip.z),'#9d9c7e',2);}});
   }
   if(car!==scene.consist.cars[0]){const prior=scene.consist.cars[scene.consist.cars.indexOf(car)-1],a=car.frontCoupler,b=prior.rearCoupler,c=centroid([a,b]);q(c.x,c.y,c.z,g=>E.px.line(g,...r.w(a.x,a.y,a.z),...r.w(b.x,b.y,b.z),'#485854',4));}
  }
  for(const p of scene.platforms.filter(p=>p.kind==='gangway'||p.kind==='gangway-pad'))for(const s of p.surfaces){const b=s.bounds,world=[worldPoint(p.frame,{x:b.min.x,y:b.min.y,z:b.max.z}),worldPoint(p.frame,{x:b.max.x,y:b.min.y,z:b.max.z}),worldPoint(p.frame,{x:b.max.x,y:b.max.y,z:b.max.z}),worldPoint(p.frame,{x:b.min.x,y:b.max.y,z:b.max.z})],c=centroid(world);diagnostics.geometry.push({carId:p.id,id:s.id,kind:'gangway',world,alpha:1});q(c.x,c.y,c.z,g=>paintFace(E,r,g,world,'#84918b',1),{kind:'gangway',carId:p.id,id:s.id,depth:Math.min(...world.map(p=>r.view.depth(p.x,p.y,p.z)))-1e-4});}
  const objects=rows(scene.objects);if(new Set(objects.map(o=>o.id)).size!==objects.length)throw new TypeError('Duplicate authoritative render object');
  const heldByActor=new Map();for(const object of objects){if(object.consumed)continue;const location=object.location;if(location?.type==='car'){const p=scene.platforms.find(p=>p.id===location.carId);if(!p||!validPoint(location.local))throw new TypeError('An object requires its actual moving car/local point');const point=worldPoint(p.frame,location.local);q(point.x,point.y,point.z,g=>drawObject(g,object,point),{kind:'object',id:object.id});}else if(location?.type==='carried'){const actorId=location.targetId;if(!heldByActor.has(actorId))heldByActor.set(actorId,[]);heldByActor.get(actorId).push(object);}}
  function drawObject(g,object,point){const at=r.w(point.x,point.y,point.z);if(object.kind==='sealed-charge'||object.kind==='quarry-charge'){E.px.rect(g,at[0]-4,at[1]-3,8,6,'#927650');E.px.line(g,at[0]-3,at[1]-2,at[0]+3,at[1]-2,'#d2bd8b',1);}else if(/document|deed|letter|certificate/.test(object.kind)){E.px.rect(g,at[0]-5,at[1]-4,10,8,'#d4c79d');E.px.line(g,at[0]-3,at[1]-2,at[0]+3,at[1]-2,'#776b53',1);}else return;diagnostics.objects.push({id:object.id,world:{...point},location:object.location.type});}
  for(const body of actors){if(body.hidden||body.departed)continue;if(typeof body.id!=='string'||!body.id.length||!validPoint(body))throw new TypeError('Nonfinite authoritative actor position');if(body.support&&!validateBodySupport(body,scene.platforms))throw new TypeError(`Invalid authoritative support: ${body.id}`);if(r.visible&&!r.visible(body.x,body.y,body.z||0,160,180,160))continue;
   if(body.kind==='horse'||body.category==='mount'){q(body.x,body.y,body.z||0,g=>{const h=mount(body);h.pose(body);h.draw(g,r,body);diagnostics.actors.push({id:body.id,kind:'mount',world:{x:body.x,y:body.y,z:body.z||0}});});continue;}
   const h=human(body),platform=scene.platforms.find(p=>p.id===body.support?.carId),horse=body.mounted?byId.get(body.mountId):null,action=scene.actions?.find(a=>a.actorId===body.id),contacts=[];
   for(const target of action?.contacts||[]){if(target.target){if(!validPoint(target.target)||!target.sourceId)throw new TypeError('A world hand target needs an authoritative source');contacts.push({...target});continue;}const p=scene.platforms.find(p=>p.id===target.carId);if(!p)throw new TypeError('A contact requires its actual moving car');contacts.push({...target,target:worldContact(p,target.contactId)});}
   const actorDepth=r.view.depth(body.x,body.y,body.z||0);
   q(body.x,body.y,body.z||0,g=>physicalProjection(E,()=>{if(body.mounted&&(!horse||horse.hp<=0||body.support||Math.hypot(horse.x-body.x,horse.y-body.y)>1))throw new TypeError('A mounted actor needs its actual live mount');const pose=body.mounted?prepareTrainMountedPose(E,h,body,horse,mount(horse),{contacts,freeHands:body.holstered!==false||!body.equippedWeaponId}):prepareTrainPose(E,h,body,platform,{contacts,freeHands:body.holstered!==false||!body.equippedWeaponId});try{const at=r.w(pose.root.x,pose.root.y,pose.root.z);h.rig.draw(g,...at,r.view);drawTrainOutfit(E,g,r,h,{...body,...pose.root});for(const object of heldByActor.get(body.id)||[]){if(body.toolHeld!==object.id)continue;const side=object.location.hand||body.toolHand||'R';drawObject(g,object,rigWorldPoint(h.rig,pose.root,'hand'+side));}diagnostics.contacts.push(...pose.diagnostics.map(c=>({...c,errorFinite:Number.isFinite(c.error),actorId:body.id,screenTarget:r.w(c.target.x,c.target.y,c.target.z),screenHit:r.w(c.hit.x,c.hit.y,c.hit.z)})));for(const c of pose.diagnostics)if(!c.reachable||!Number.isFinite(c.error)||c.error>1e-4)diagnostics.errors.push({kind:'unreached-native-contact',actorId:body.id,contact:c.kind,blocked:c.blocked||null});diagnostics.actors.push({id:body.id,kind:'human',world:{x:body.x,y:body.y,z:body.z||0},drawRoot:{...pose.root},relativeVelocity:walkMotion(body,platform)});}finally{pose.restore();}}),{kind:'actor',id:body.id,depth:actorDepth});
  }
 }
 return{update,draw,inspect:()=>copy(diagnostics),humanRig:id=>humans.get(id)?.rig};
}
