#!/usr/bin/env python3
"""Complete A Voice Under Ice with visible phone pointers or an emulated Gamepad.

Setup imports an untouched, game-generated version-2/3 completed-opening Save
through the visible Import save file menu and browser file chooser. After setup,
pointer mode uses only mouse-pointer drags on the visible coarse-media joystick,
visible action controls and touchscreen menu/dialog taps. WebKit has no public
Playwright touch-drag API: this is not native multi-touch or iOS hardware proof.

Controller mode writes only a standard-Gamepad input fixture, polled through the
normal game input path. It uses axes/buttons and D-pad/A modal selection, with no
keyboard, mouse or touch fallback. This is not physical-controller evidence.

Evaluations otherwise read camera/UI or Saves made with the normal Save journey
menu. Neither mode writes simulation state, calls game verbs, changes imported
Save contents, places actors or retries failures silently. Artifacts go to /tmp.
This proves rescue continuation after import, not a fresh two-mission journey.
--journal-only is a separate UI check from an untouched completed-rescue Save;
it never claims to complete the rescue again. Browser file upload is setup only.
"""

from campaign_save import observed_save
import argparse
import asyncio
import copy
import json
import math
import os
from pathlib import Path

os.environ.setdefault("PLAYWRIGHT_HOST_PLATFORM_OVERRIDE", "ubuntu24.04-x64")
from playwright.async_api import async_playwright
from campaign_save import normalize_campaign_save

RESCUE = "snowbound-a-voice-under-ice"
OPENING = "snowbound-the-last-warm-light"


async def run(url, output, engine, source_save, case="recover", mode="pointer", device="iPhone SE (3rd gen)", journal_only=False):
    output.mkdir(parents=True, exist_ok=True)
    source = json.loads(source_save.read_text())
    assert source["version"] in (2, 3), "Use an untouched version-2/3 Save generated by ordinary game controls"
    source_opening = source["campaign"]["missions"][OPENING]
    assert source_opening["mission"]["completed"], "The imported opening must already be completed"
    assert source["campaign"]["activeMissionId"] == (RESCUE if journal_only else OPENING), "Choose the opening or completed rescue Save required by this mode"
    if journal_only:
        assert source["campaign"]["missions"][RESCUE]["mission"]["completed"], "The journal-only UI check needs an untouched completed-rescue Save"
    errors, events = [], []
    action_counts = {"joystick_drags": 0, "visible_action_holds": 0, "touchscreen_taps": 0,
        "gamepad_axis_holds": 0, "gamepad_button_holds": 0, "controller_modal_selections": 0, "gamepad_scroll_holds": 0,
        "keyboard_events": 0, "runtime_writes": 0}
    result = {"passed": False, "browser": engine, "url": url, "events": events, "errors": errors,
        "sourceSave": str(source_save.resolve()), "sourceVersion": source["version"], "mode": mode,
        "startMode": "Visible Import save file menu and browser file chooser; untouched game-generated v2 completed rescue" if journal_only else "Visible Import save file menu and browser file chooser; untouched game-generated v2 completed opening",
        "case": case, "inputEvidence": action_counts, "journalOnly": journal_only,
        "fullRescueCompletedInThisRun": False,
        "fileChooserSetup": "Host file chooser uploads the untouched source Save; excluded from gameplay input counts"}
    async with async_playwright() as playwright:
        browser = await getattr(playwright, engine).launch(headless=True)
        if mode == "pointer":
            assert engine != "firefox", "Use Chromium or WebKit for a mobile touch profile"
            profile = playwright.devices[device]
            assert profile["has_touch"], "Choose a touch-device profile"
            context = await browser.new_context(**profile)
            result.update(device=device, viewport=profile["viewport"],
                caveat="Mouse pointer drags on visible coarse-media joystick and action controls; touchscreen taps on menus/dialog. No native multi-touch drag, iOS hardware or fresh two-mission proof. Fire uses the game's normal nearest-hostile targeting.")
        else:
            context = await browser.new_context(viewport={"width": 1440, "height": 1000})
            result.update(device="Desktop with emulated standard Gamepad", viewport={"width": 1440, "height": 1000},
                caveat="Only an isolated standard-Gamepad input fixture is written; all gameplay polls the normal axes/buttons path. No keyboard/mouse/touch fallback, physical controller or fresh two-mission proof. RT uses the game's normal nearest-hostile targeting.")
        page = await context.new_page()
        if mode == "controller":
            await page.add_init_script("""
                window.rescueInputPad={index:0,id:'Automated standard Gamepad input fixture',mapping:'standard',connected:true,
                    axes:[0,0,0,0],buttons:Array.from({length:16},()=>({pressed:false,value:0}))};
                Object.defineProperty(navigator,'getGamepads',{value:()=>[rescueInputPad]});
            """)
        page.on("pageerror", lambda error: errors.append(str(error)))
        page.on("console", lambda message: errors.append(message.text) if message.type == "error" else None)

        async def observe():
            return await page.evaluate("""() => {
              const g=My3D2dge.current;
              return {x:g.cam.tx,y:g.cam.ty+g.H*.1/g.view.by,z:g.cam.tz,
                stage:document.querySelector('#mission-count').textContent,
                mission:document.querySelector('#mission-name').textContent,
                objective:document.querySelector('#objective-text').textContent,
                health:Number(document.querySelector('#health-ring').getAttribute('aria-valuenow')),
                interaction:document.querySelector('#interact').hidden?null:document.querySelector('#interaction-label').textContent,
                dialog:document.querySelector('#conversation').open,
                choices:[...document.querySelectorAll('[data-choice]')].map(el=>el.dataset.choice),
                notices:document.querySelector('#notices').textContent,
                engineErrors:g.errors};
            }""")

        async def pad_button(index, milliseconds=85):
            await page.evaluate("i=>rescueInputPad.buttons[i]={pressed:true,value:1}", index)
            try:
                await page.wait_for_timeout(milliseconds)
            finally:
                await page.evaluate("i=>rescueInputPad.buttons[i]={pressed:false,value:0}", index)
            await page.wait_for_timeout(140)
            action_counts["gamepad_button_holds"] += 1

        async def tap(selector, timeout=18000):
            locator = page.locator(selector)
            await locator.wait_for(state="visible", timeout=timeout)
            if mode == "controller":
                for _ in range(45):
                    if await page.evaluate("sel=>document.activeElement?.matches(sel)", selector):
                        await pad_button(0)
                        action_counts["controller_modal_selections"] += 1
                        return
                    await pad_button(13)
                raise AssertionError(f"Gamepad cannot navigate to {selector}")
            await locator.tap(timeout=timeout)
            action_counts["touchscreen_taps"] += 1

        async def open_menu():
            if mode == "controller":
                await pad_button(8)
            else:
                await tap('[data-panel="menu"]')
            await page.wait_for_timeout(80)

        async def close_panel():
            if mode == "controller":
                await pad_button(8)
            else:
                await tap('#close-panel')
            await page.wait_for_timeout(80)

        async def open_tool(identifier):
            if mode == "controller":
                await open_menu()
                await tap(f'[data-command="panel"][data-id="{identifier}"]')
            else:
                await tap(f'[data-panel="{identifier}"]')
            await page.wait_for_timeout(80)

        async def continue_saved():
            if mode == "controller":
                await open_menu()
                await tap('[data-command="load"]')
            else:
                await tap('#continue-game')
            await page.wait_for_timeout(180)

        async def pointer_hold(selector, milliseconds=80):
            locator = page.locator(selector)
            await locator.wait_for(state="visible")
            rect = await locator.bounding_box()
            assert rect, selector
            await page.mouse.move(rect["x"]+rect["width"]/2, rect["y"]+rect["height"]/2)
            await page.mouse.down()
            try:
                await page.wait_for_timeout(milliseconds)
            finally:
                await page.mouse.up()
            await page.wait_for_timeout(70)
            action_counts["visible_action_holds"] += 1

        async def move_direction(direction, milliseconds, crouch=False):
            if mode == "controller":
                axis, value = {"up": (1,-1), "left": (0,-1), "down": (1,1), "right": (0,1)}[direction]
                await page.evaluate("([axis,value,crouch])=>{rescueInputPad.axes[axis]=value;rescueInputPad.buttons[11]={pressed:crouch,value:crouch?1:0}}", [axis,value,crouch])
                try:
                    await page.wait_for_timeout(milliseconds)
                finally:
                    await page.evaluate("axis=>{rescueInputPad.axes[axis]=0;rescueInputPad.buttons[11]={pressed:false,value:0}}", axis)
                await page.wait_for_timeout(65)
                action_counts["gamepad_axis_holds"] += 1
                return
            rect = await page.locator('#joystick').bounding_box()
            assert rect, "Visible joystick missing"
            cx, cy = rect["x"]+rect["width"]/2, rect["y"]+rect["height"]/2
            radius = rect["width"]/2-14
            dx, dy = {"up": (0,-1), "left": (-1,0), "down": (0,1), "right": (1,0)}[direction]
            await page.mouse.move(cx,cy)
            await page.mouse.down()
            try:
                await page.mouse.move(cx+dx*radius,cy+dy*radius,steps=3)
                await page.wait_for_timeout(milliseconds)
                await page.mouse.move(cx,cy,steps=3)
            finally:
                await page.mouse.up()
            await page.wait_for_timeout(65)
            action_counts["joystick_drags"] += 1

        async def action(identifier, milliseconds=80):
            if mode == "controller":
                await pad_button({"fire":7,"reload":2,"whistle":1,"holster":3}[identifier], milliseconds)
            else:
                await pointer_hold({"fire":'[data-action="shoot"]',"reload":'#reload',
                    "whistle":'[data-action="whistle"]',"holster":'[data-story-action="holster"]'}[identifier], milliseconds)

        async def use_item(identifier):
            await open_tool('satchel')
            await tap(f'[data-command="use"][data-id="{identifier}"]')
            await close_panel()

        async def equip(identifier):
            await open_tool('satchel')
            await tap(f'[data-command="equipment"][data-id="equip:{identifier}"]')
            await close_panel()

        async def interact(expected=None):
            if expected:
                await page.wait_for_function("text=>{const b=document.querySelector('#interact');return !b.hidden&&document.querySelector('#interaction-label').textContent.toLowerCase().includes(text)}", arg=expected.lower(),timeout=5000)
            seen = await observe()
            assert not seen["dialog"], seen
            if expected:
                assert expected.lower() in (seen["interaction"] or "").lower(), seen
            if mode == "controller":
                await pad_button(0)
            else:
                await tap('#interact', timeout=5000)
            await page.wait_for_timeout(110)

        async def choose(identifier="leave"):
            await tap(f'[data-choice="{identifier}"]')
            await page.wait_for_timeout(120)

        async def record(label):
            event = {"label":label,**await observe(),"screenshot":f"{label}.png"}
            await page.screenshot(path=str(output/event["screenshot"]))
            events.append(event)
            print(json.dumps(event),flush=True)

        async def save(label):
            seen=await observe()
            assert not seen["dialog"], seen
            assert not seen["engineErrors"], seen["engineErrors"]
            await open_menu()
            await tap('[data-command="save"]')
            raw=await observed_save(page)
            (output/f"{label}.json").write_text(json.dumps(raw,indent=2)+"\n")
            snapshot=normalize_campaign_save(raw)
            await tap('[data-command="resume"]')
            await page.wait_for_timeout(65)
            assert not snapshot["failure"], snapshot["failure"]
            return snapshot

        async def walk(route,speed=90,tolerance=9,crouch=False):
            if crouch and mode=="pointer":
                await tap('[data-action="crouch"]')
                assert await page.locator('[data-action="crouch"]').get_attribute('aria-pressed')=='true', "The touch crouch toggle must remain active while the joystick moves"
            try:
                for target_x,target_y in route:
                    stuck=0
                    for _ in range(140):
                        before=await observe()
                        assert not before["dialog"], before
                        assert not before["engineErrors"], before["engineErrors"]
                        dx,dy=target_x-before["x"],target_y-before["y"]
                        if math.hypot(dx,dy)<tolerance:
                            break
                        horizontal=abs(dx)>abs(dy)
                        direction=("right" if dx>0 else "left") if horizontal else ("down" if dy>0 else "up")
                        amount=abs(dx) if horizontal else abs(dy)
                        await move_direction(direction,min(550,max(45,amount/speed*1000)),crouch=crouch)
                        after=await observe()
                        stuck=stuck+1 if math.hypot(after["x"]-before["x"],after["y"]-before["y"])<.5 else 0
                        if stuck>=2:
                            other=target_y-after["y"] if horizontal else target_x-after["x"]
                            if abs(other)>tolerance:
                                alternate=("down" if other>0 else "up") if horizontal else ("right" if other>0 else "left")
                                await move_direction(alternate,min(200,max(45,abs(other)/speed*1000)),crouch=crouch)
                                shifted=await observe()
                                if math.hypot(shifted["x"]-after["x"],shifted["y"]-after["y"])>.5:
                                    stuck=0
                        if stuck>=5:
                            raise AssertionError(f"Route blocked toward {target_x},{target_y}: {after}")
                    else:
                        raise AssertionError(f"Route did not reach {target_x},{target_y}: {await observe()}")
            finally:
                if crouch and mode=="pointer":
                    await tap('[data-action="crouch"]')

        async def near_actor(snapshot,identifier,speed=90):
            actor=snapshot["entities"][identifier]
            await walk([(actor["x"],actor["y"])],speed=speed,tolerance=20)

        async def follow_line(target,speed=120):
            start=await observe()
            dx,dy=target[0]-start["x"],target[1]-start["y"]
            steps=max(1,math.ceil(math.hypot(dx,dy)/12))
            for index in range(1,steps+1):
                await walk([(start["x"]+dx*index/steps,start["y"]+dy*index/steps)],speed=speed,tolerance=5)

        async def stage(number):
            await page.wait_for_function("text=>document.querySelector('#mission-count').textContent===text",arg=f"{number:02d} / 10",timeout=6000)
            seen=await observe()
            assert seen["stage"]==f"{number:02d} / 10",seen

        async def fight(wave,label):
            for turn in range(26):
                assert not (await observe())["dialog"], "Combat opened a dialogue or checkpoint failure before Save"
                snapshot=await save(f"{label}-combat-{turn:02d}")
                assert snapshot["mission"]["stage"] in [7,8],snapshot["mission"]
                assert snapshot["flags"]["loadingHandoff"], "Combat unexpectedly reset the loading checkpoint"
                remaining=[wolf for wolf in snapshot["predators"] if wolf["wave"]==wave and wolf["phase"] not in ["dead","fled"]]
                if not remaining:
                    return snapshot
                if snapshot["player"]["hp"]<55 and snapshot["inventory"].get('tonic',0):
                    await use_item('tonic')
                if snapshot["player"]["ammo"]==0:
                    if snapshot["player"]["reserve"]:
                        await action('reload');await page.wait_for_timeout(1900)
                    else:
                        await equip('mara-revolver')
                    continue
                await action('fire',80)
                await page.wait_for_timeout(700)
                assert not (await observe())["dialog"], "Shot opened a checkpoint failure; driver stops without retrying"
            raise AssertionError(f"Wolf wave {wave} remained unresolved: {await observe()}")

        async def inspect_journal():
            await open_tool('journal')
            await tap('[data-command="notebook"]')
            await page.wait_for_timeout(450)
            await page.locator('.journal-illustration svg').wait_for(state="visible")
            assert "Silas" in await page.locator('.journal-illustration svg title').text_content()
            if mode == "controller":
                before = await page.locator('#panel').evaluate('(el)=>el.scrollTop')
                positions = []
                for value in [.8,-.8]:
                    await page.evaluate('v=>rescueInputPad.axes[3]=v',value)
                    try:
                        await page.wait_for_timeout(260)
                    finally:
                        await page.evaluate('()=>rescueInputPad.axes[3]=0')
                    await page.wait_for_timeout(80)
                    positions.append(await page.locator('#panel').evaluate('(el)=>el.scrollTop'))
                    action_counts['gamepad_scroll_holds'] += 1
                assert positions[0] > before+20, f"Right-stick scroll did not move notebook down: {before}, {positions}"
                assert positions[1] < positions[0]-20, f"Right-stick reverse scroll did not read back: {before}, {positions}"
                result['journalScrollEvidence'] = {'before':before,'down':positions[0],'up':positions[1]}
                await tap('[data-command="notebook"]')
                await page.wait_for_timeout(450)
            visible = await page.locator('.journal-illustration svg').evaluate("""el=>{
                const r=el.getBoundingClientRect(),p=document.querySelector('#panel').getBoundingClientRect();
                const height=Math.max(0,Math.min(r.bottom,p.bottom,innerHeight)-Math.max(r.top,p.top,0));
                return {visibleFraction:height/r.height,top:r.top,bottom:r.bottom,panelTop:p.top,panelBottom:p.bottom};
            }""")
            assert visible['visibleFraction'] > .85, f"Notebook drawing remains outside visible panel: {visible}"
            result['journalDrawingViewport'] = visible
            await record('12-notebook-drawing')
            await close_panel()

        try:
            await page.goto(url)
            await page.wait_for_function('globalThis.My3D2dge?.current?._running')
            await open_menu()
            async with page.expect_file_chooser() as chooser_info:
                await tap('[data-command="import"]')
            await (await chooser_info.value).set_files(str(source_save.resolve()))
            await page.locator('#welcome').wait_for(state="hidden")
            await page.wait_for_timeout(180)
            result['setupInputEvidence'] = copy.deepcopy(action_counts)
            for key in action_counts:
                action_counts[key] = 0
            if journal_only:
                imported = await save('00-imported-complete-state')
                assert imported['mission']['completed'] and imported['mission']['id'] == RESCUE
                await record('00-imported-complete')
                await inspect_journal()
                final = await observe()
                assert not errors and not final['engineErrors'], {'errors':errors,'engineErrors':final['engineErrors']}
                result.update(passed=True,final=final,journalUIOnly=True,saveReloadPreserved=None)
            else:
                imported = await save("00-imported-opening-state")
                assert imported["mission"]["completed"]
                historical_opening = copy.deepcopy(imported["campaign"]["missions"][OPENING])
                await record("00-imported-opening")
                await walk([(425, 1230)])
                await interact("Elin"); await choose("accept-rescue"); await stage(2)
                prepared = await save("01-rescue-kit-state")
                await walk([(380,1230),(380,1180)])
                await near_actor(prepared, "tomas"); await interact("Tomas"); await choose()
                prepared = await save("01-after-tomas-state")
                await near_actor(prepared, "inez"); await interact("Inez"); await choose()
                prepared = await save("01-prepared-state")
                await walk([(prepared["horse"]["x"], prepared["horse"]["y"])])
                await interact("Inspect")
                await interact("Mount Copper")
                await walk([(375, 970), (600, 970), (720, 760)], speed=135)
                for _ in range(40):
                    if "northern trail" in ((await observe())["interaction"] or "").lower():
                        break
                    await page.wait_for_timeout(150)
                await interact("northern trail"); await stage(3); await record("02-northern-departure")
                await walk([(390,1450),(530,1350),(600,1350),(650,1190),(760,1080)], speed=135)
                await interact("Dismount")
                for point, label in [((760,1080),"embers"),((792,1070),"bootprints"),((735,1095),"wrapper")]:
                    await walk([point]); await interact(label)
                await stage(4); await record("03-ash-trail")
                ash = await save("03-ash-trail-state")
                await walk([(ash["horse"]["x"],ash["horse"]["y"])])
                await interact("Mount")
                await walk([(850,1080),(975,1100),(1040,1080)], speed=135)
                await interact("Dismount"); await interact("scrape"); await action("whistle")
                await walk([(1160,1080),(1150,975)]); await interact("hoofprints"); await stage(5)
                ford = await save("04-ford-state")
                await walk([(ford["horse"]["x"],ford["horse"]["y"])])
                await interact("Mount")
                await walk([(1280,875),(1450,750),(1550,730)], speed=135)
                await interact("Dismount"); await walk([(1550,730)]); await interact("Lark"); await choose()
                await interact("signal"); await page.wait_for_timeout(2250); await record("05-signal-answer")
                await action("whistle"); await walk([(1450,730),(1460,620)])
                await interact("Hitch"); await page.wait_for_timeout(2250); await stage(6)
                await interact("Retrieve"); await walk([(1540,590)])
                await interact("Climb"); await page.wait_for_timeout(2350)
                await use_item("warmRation")
                await interact("Climb"); await page.wait_for_timeout(2650)
                await interact("Brace"); await page.wait_for_timeout(2550)
                await interact("Crouch"); await page.wait_for_timeout(1950)
                await interact("rope")
                await walk([(1760,430)], speed=55, crouch=True)
                await interact("Climb"); await page.wait_for_timeout(2950); await stage(7)
                await walk([(1900,365)])
                # The normal context prioritizes the breathing check over optional talk.
                await interact("breathing"); await interact("Dress")
                await record("06-silas-stabilized")
                stabilized = await save("06-silas-stabilized-state")
                await interact("Lift")
                if case == "recover":
                    await walk([(1860,420)], speed=48)
                    for _ in range(60):
                        if "Lower Silas" in ((await observe())["interaction"] or ""):
                            await interact("Lower Silas")
                            lowered = await save("06-rest-pad-state")
                            if lowered["player"]["carrying"] is None:
                                break
                        await page.wait_for_timeout(180)
                    else:
                        raise AssertionError("Inez never reached the sheltered pad")
                    # The case and sheltered patient are close together; approach
                    # the case from the west outside Silas's lifting radius.
                    await walk([(1815,432)], tolerance=5)
                    if "Listen to Silas" in ((await observe())["interaction"] or ""):
                        await interact("Listen"); await choose()
                    await interact("dispatch case")
                    await record("06-secured-dispatch-case")
                    await walk([(1860,420)])
                    await interact("Lift")
                await walk([(1810,490)], speed=48)
                for number, duration in [(1,3350),(2,3150),(3,3150)]:
                    await interact("Hand Silas")
                    await page.wait_for_timeout(duration)
                    await interact("Climb down")
                    await page.wait_for_timeout(duration)
                    await interact("Receive Silas")
                    await record(f"06-handoff-{number}")
                await stage(8)
                await interact("loading spur")
                await walk([(1400,650),(1400,745),(1320,745)])
                await interact("Call the wolves")
                await walk([(1400,790),(1640,790)])
                await fight(0,"07-pack")
                loading = await save("07-loading-state")
                await near_actor(loading,"thimble"); await interact("lift Silas")
                await interact("strap"); await record("07-strapped-passenger")
                mounted = await save("07-passenger-state")
                await walk([(mounted["horse"]["x"],mounted["horse"]["y"])])
                await interact("Mount")
                await page.wait_for_timeout(150); await stage(9)
                await walk([(1380,750)], speed=135)
                await fight(1,"08-first-pursuit")
                await walk([(1240,875)], speed=135)
                await fight(2,"08-second-pursuit")
                await walk([(1150,1020),(1080,1100)], speed=120)
                await record("08-enter-return-creek")
                # Inez leads the water route; keep pace and wait at authored bends.
                for point in [(1080,1100),(925,1190),(790,1275),(650,1340)]:
                    await follow_line(point)
                    await page.wait_for_timeout(750)
                concealed = await save("08-concealed-trail-state")
                assert concealed["flags"]["creekConcealed"], concealed["tracks"]["creek"]
                assert concealed["tracks"]["creek"]["copper"]>=180 and concealed["tracks"]["creek"]["thimble"]>=180
                await record("08-both-mounts-concealed")
                await walk([(620,1380)], speed=100); await interact("left bank")
                await walk([(420,1460),(250,1560)], speed=135); await interact("Return to the kiln")
                await stage(10); await record("09-kiln-return")
                await walk([(600,970),(375,970),(375,1160)],speed=130)
                await interact("Dismount")
                await page.wait_for_timeout(1000)
                await interact("Lift Silas from Thimble")
                await walk([(380,1160)],speed=48)
                await interact("Moss and Vera")
                await walk([(380,1200),(380,1235),(365,1270)])
                await page.wait_for_timeout(3000)
                await interact("Elin and Fin"); await choose()
                home = await save("09-family-state")
                await walk([(380,1235),(380,1200),(380,1180)])
                await near_actor(home,"tomas"); await interact("Tomas"); await choose()
                home = await save("09-thanks-state")
                await near_actor(home,"della"); await interact("Della"); await choose()
                await interact("journal")
                completed = await save("10-complete-state")
                assert completed["mission"]["completed"]
                assert completed["campaign"]["missions"][OPENING]==historical_opening
                assert completed["entities"]["silas"]["attachment"]["targetId"]=="silas-bed"
                assert completed["weapons"]["coach-gun"]["owner"]=="mara"
                assert completed["weapons"]["coach-gun"]["loanMissionId"] is None
                assert completed["flags"]["caseCollected"]==(case=="recover")
                await record("10-voice-home")
                await page.reload(); await page.wait_for_function('globalThis.My3D2dge?.current?._running'); await continue_saved()
                reloaded = await save("11-reloaded-state")
                # Ordinary Resume/Continue lets the world clock advance. Verify its
                # authored bedside healing exactly, then compare all other graph
                # fields instead of treating legitimate recovery as lost state.
                elapsed = reloaded["elapsed"]-completed["elapsed"]
                assert 0<=elapsed<10, f"unexpected reload observation interval {elapsed}"
                after_campaign = copy.deepcopy(reloaded["campaign"])
                before_clinic = completed["campaign"]["missions"][RESCUE]["rescue"]["silas"]
                after_clinic = after_campaign["missions"][RESCUE]["rescue"]["silas"]
                for key,rate in [("healingHours",80),("injury",80*18)]:
                    assert abs(after_clinic[key]-max(0,before_clinic[key]-elapsed/rate))<1e-7, f"scheduled {key} changed incorrectly"
                    after_clinic[key]=before_clinic[key]
                assert after_campaign==completed["campaign"], "durable mission records changed on normal reload"
                for key in ["inventory","weapons","camp","companions","sideQuests","wanted","honor","stats","regions"]:
                    assert reloaded[key]==completed[key], f"durable {key} changed on normal reload"
                for identifier, before in completed["entities"].items():
                    after = reloaded["entities"][identifier]
                    for key in ["id","category","regionId","attachment","owned","ownerId","pack","equippedWeaponId","money","mounted","carrying","coldcoat","lantern","scars","injured","coatRepaired"]:
                        assert after.get(key)==before.get(key), f"durable {identifier}.{key} changed on reload"
                    expected_hp=min(100,before["hp"]+elapsed/160) if identifier=="silas" else before["hp"]
                    assert abs(after["hp"]-expected_hp)<1e-7, f"durable {identifier}.hp changed outside scheduled healing"
                await record("11-reloaded-home")
                await inspect_journal()
                final = await observe()
                assert not errors and not final["engineErrors"], {"errors":errors,"engineErrors":final["engineErrors"]}
                result.update({"passed":True,"final":final,"performance":completed["performance"],"stats":completed["stats"],"camp":completed["camp"],"honor":completed["honor"],"saveReloadPreserved":True,"fullRescueCompletedInThisRun":True,"inputEvidence":action_counts})
        except Exception as error:
            result["failure"]=str(error)
            try:
                result["final"]=await observe()
                await page.screenshot(path=str(output/'failure.png'))
            except Exception as observation_error:
                result["observationFailure"]=str(observation_error)
        finally:
            (output/'report.json').write_text(json.dumps(result,indent=2)+"\n")
            print(json.dumps(result),flush=True)
            await browser.close()
    return result["passed"]


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--url',default='http://127.0.0.1:4173')
    parser.add_argument('--output',type=Path,default=Path('/tmp/dust-mercy-rescue-input-playthrough'))
    parser.add_argument('--engine',choices=['chromium','firefox','webkit'],default='webkit')
    parser.add_argument('--mode',choices=['pointer','controller'],default='pointer')
    parser.add_argument('--device',default='iPhone SE (3rd gen)')
    parser.add_argument('--source-save',type=Path,required=True,help='Untouched game-generated current-v2 Save: completed opening, or completed rescue for --journal-only; imported through the visible file chooser')
    parser.add_argument('--case',choices=['recover','omit'],default='recover')
    parser.add_argument('--journal-only',action='store_true',help='Separate notebook/scroll UI check importing an untouched completed-rescue Save; does not rerun or claim full mission progression')
    args=parser.parse_args()
    raise SystemExit(0 if asyncio.run(run(args.url,args.output,args.engine,args.source_save,args.case,args.mode,args.device,args.journal_only)) else 1)
