"""Public mouse/keyboard regression using an untouched game-generated Save.

Deliberately aim at Copper to verify the protected-shot failure. Releasing a
Space focus hold must leave Retry pending, followed by one explicit Retry click.
Evaluations read projection and normal-menu Saves; none writes runtime state.
"""

from campaign_save import observed_save
import argparse,asyncio,json,os
from pathlib import Path
os.environ.setdefault('PLAYWRIGHT_HOST_PLATFORM_OVERRIDE','ubuntu24.04-x64')
from playwright.async_api import async_playwright
parser=argparse.ArgumentParser(description='Verify mouse aiming, protected-shot failure and held focus across three engines.')
parser.add_argument('--source-save',type=Path,required=True,help='Ordinary active rescue combat Save generated by rescue-playthrough.py')
parser.add_argument('--output',type=Path,default=Path('/tmp/dust-mercy-rescue-held-focus'))
parser.add_argument('--url',default='http://127.0.0.1:4173')
args=parser.parse_args()
OUT=args.output;OUT.mkdir(parents=True,exist_ok=True)
SAVE=args.source_save
async def main():
 results=[]
 async with async_playwright() as p:
  for engine in ['chromium','webkit','firefox']:
   b=await getattr(p,engine).launch();page=await b.new_page(viewport={'width':1440,'height':1000});errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
   row={'engine':engine,'passed':False,'errors':errors,'sourceSave':str(SAVE),'caveat':'Ordinary game-generated combat save imported through product UI. Mouse aims at Copper deliberately to verify protected-shot failure and held focus never activates Retry.'}
   try:
    await page.goto(args.url);await page.wait_for_function('globalThis.My3D2dge?.current?._running');await page.locator('[data-panel="menu"]').click()
    async with page.expect_file_chooser() as fc:await page.locator('[data-command="import"]').click()
    await (await fc.value).set_files(str(SAVE));await page.locator('#welcome').wait_for(state='hidden')
    await page.keyboard.press('Escape');await page.locator('[data-command="save"]').click();before=await observed_save(page);await page.locator('[data-command="resume"]').click()
    target=before['entities']['copper'];point=await page.evaluate('''a=>{const g=My3D2dge.current,r=g.r,s=g.screen,rc=s.canvas.getBoundingClientRect();const[x,y]=r.w(a.x,a.y,a.z||0);return{x:rc.left+(s.OX+(x-s.fx)*s.S)/s.dpr,y:rc.top+(s.OY+(y-22-s.fy)*s.S)/s.dpr}}''',target)
    await page.mouse.move(point['x'],point['y']);await page.keyboard.down('Space');await page.mouse.click(point['x'],point['y']);await page.wait_for_timeout(700);await page.keyboard.up('Space');await page.wait_for_timeout(200)
    row['text']=await page.locator('#dialogue-text').inner_text();row['choices']=await page.locator('[data-choice]').evaluate_all('(els)=>els.map(e=>e.dataset.choice)')
    assert await page.locator('#conversation').evaluate('(el)=>el.open'),row
    assert 'Copper' in row['text'] and 'struck by your shot' in row['text'],row
    assert row['choices']==['retry','restart'],row
    await page.screenshot(path=str(OUT/f'{engine}-held-focus-failure.png'))
    await page.locator('[data-choice="retry"]').click();await page.wait_for_timeout(100);await page.keyboard.press('Escape');await page.locator('[data-command="save"]').click();after=await observed_save(page);(OUT/f'{engine}-recovered.json').write_text(json.dumps(after,indent=2)+'\n')
    mid='snowbound-a-voice-under-ice';assert after['campaign']['missions'][mid]['retryCount']==before['campaign']['missions'][mid]['retryCount']+1,(before['campaign']['missions'][mid]['retryCount'],after['campaign']['missions'][mid]['retryCount']);assert after['failure'] is None
    assert after['stats']['deaths']==before['stats']['deaths']+1
    assert not errors;row['passed']=True
   except Exception as e:row['failure']=str(e);await page.screenshot(path=str(OUT/f'{engine}-failed.png'))
   await b.close();results.append(row);print(json.dumps(row),flush=True)
 (OUT/'report.json').write_text(json.dumps({'passed':all(r['passed']for r in results),'results':results},indent=2)+'\n')
asyncio.run(main())
raise SystemExit(0 if json.loads((OUT/'report.json').read_text())['passed'] else 1)
