/** The Names They Took: a separate quarry operation and a persistent captive. */
import {RIVAL_ID,RIVAL_CAST,RIVAL_ENEMIES,RIVAL_WORLD as W,RIVAL_STAGES,RIVAL_CARBINE,RIVAL_ITEMS} from '../content/campaign/bellwether-works.js';
import {QUARRY_POCKET_OBJECTS} from '../content/campaign/quarry-papers.js';
import {usesRivalContinuation,validateRivalContinuation,rivalHistoricalValidationState} from './rival-continuation.js';
import {blockedAt,moveActor,clearLine,followActor,insideRect} from './campaign-navigation.js';
import {createRivalQuestioning,usesQuestioningContract,getQuestioningInteractions,interactQuestioning,chooseQuestioning,advanceQuestioning,validateQuestioning,questioningVisitText,QUESTIONING_TRANSACTION_KEYS,QUESTIONING_CHOICES} from './rival-questioning.js';
import {validateRivalDialog} from './rival-dialogue-validation.js';
import {rivalSceneSpeech} from './rival-scene-speech.js';
import {createEquipmentWork,equipmentContract,ammunitionReady,carriedCarbine,initialCarbineReserve,issuedCarbineRounds,requestCartridges,stepEquipmentWork,storeCarbine,validateEquipmentWork,EQUIPMENT_TRANSACTION_KEY,CARBINE_INSPECTION_TEXT} from './rival-equipment-work.js';
import * as Narrative from './rival-narrative.js';
import {requiresReconWitness,initializeReconWitness,visibleReconActors,witnessedReconEvent,recordReconEvent,reconWitnessComplete,validateReconWitness} from './rival-recon-observation.js';
import {physicalSearchContract,requestPhysicalSearch,physicalSearchOffers,interactPhysicalSearch,stepPhysicalSearchWork,validatePhysicalSearchWork,PHYSICAL_SEARCH_TRANSACTION_KEYS} from './rival-search-work.js';
import {initializeHolding,getHoldingInteractions,interactHolding,chooseHolding,validateHolding,HOLDING_TRANSACTION_KEYS} from './rival-aftermath.js';
import {advanceWeaponCustody,getWeaponInteractions,interactWeaponCustody,validateWeaponCustody,dropOwnedWeapon,recordCustodyShot,ENGRAVED_REVOLVER_ID,WEAPON_THIEF_ID,WEAPON_CUSTODY_TRANSACTIONS} from './rival-weapon-custody.js';
import {createRivalTransport,usesRivalTransport,canInitialPassengerStrap,registerSkeinWound,recordSkeinDeath,needsSkeinFootPursuit,recordSkeinFootPursuit,transportLoaded,transportStrapped,transportUnloaded,rivalPassenger,rivalTransportPace,canReturnWithPassenger,getRivalTransportInteractions,interactRivalTransport,stepRivalTransport,validateRivalTransport} from './rival-transport.js';
export {RIVAL_ID,RIVAL_ITEMS};
export const RIVAL_ENTITY_IDS=[...RIVAL_CAST,...RIVAL_ENEMIES].map(a=>a.id);
export const RIVAL_PARTY=['tomas','inez','ruth','bastian','emmett'];
export const RIVAL_MOUNTS=['tomas-mount','thimble','plover','cinder','button'];
const HUNT='snowbound-a-quiet-table',RESCUE='snowbound-a-voice-under-ice',OPENING='snowbound-the-last-warm-light';
const clone=v=>JSON.parse(JSON.stringify(v)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),point=a=>({x:a.x,y:a.y,z:a.z||0});
const record=s=>s.campaign.missions[RIVAL_ID],active=s=>s.campaign.activeMissionId===RIVAL_ID,object=v=>v&&typeof v==='object'&&!Array.isArray(v);
const nearby=(a,b,r=55)=>a&&b&&Math.abs((a.z||0)-(b.z||0))<8&&distance(a,b)<=r;
const flags={intervened:false,ruthHeard:false,emmettHeard:false,bastianHeard:false,inezHeard:false,accepted:false,carbineGranted:false,carbineInspected:false,carbineEquipped:false,lariatGranted:false,sightglassGranted:false,entered:false,groovesRead:false,hoovesRead:false,ridgeBriefed:false,reconComplete:false,approachReady:false,focusTaught:false,yardSafe:false,pocketSearched:false,patrolWarned:false,patrolSafe:false,magazineRead:false,capWagonRead:false,weighhouseRead:false,chargeInspected:false,chargePassed:false,chargeRepacked:false,crateTaken:false,plansRead:false,plansDelivered:false,horsesRetrieved:false,convoyDeparted:false,chaseStarted:false,bound:false,loaded:false,strapped:false,campReturned:false,delivered:false,questioned:false,held:false,chargesStored:false,accounted:false};
export function createRivalRecord(){return{
  status:'locked',sourceRequirementId:'campaign-old-friends',retryCount:0,checkpointId:null,
  mission:{id:RIVAL_ID,name:'The Names They Took',stage:0,stageCount:14,completed:false,rewardPaid:false,objective:RIVAL_STAGES[0]},
  flags:{...flags},timers:{elapsed:0,abandonment:0,patrol:0,chase:0,bind:0,handoff:0,shot:0,gift:0},
  performance:{shots:0,hits:0,headshots:0,kills:0,healingUses:0,fifteenHeadshots:false,noHealingItems:true,threeFocusKills:false,quickCapture:false,underTime:false,eligible:true},
  choices:{firstShot:null,tactic:null,assurance:null,care:null,order:null},transactions:{},objects:{},
  rival:{contractVersion:2,narrativeVersion:1,narrative:Narrative.createRivalNarrative(),equipment:createEquipmentWork(),questioningVersion:1,questioning:createRivalQuestioning(),transportVersion:1,transport:createRivalTransport(),trailIndex:0,descentIndex:0,convoyIndex:0,returnIndex:0,calderIndex:0,leviIndex:0,helperIndex:0,reconEventPhase:0,reconAge:0,dismissalIndex:0,searchPhase:0,marksBelow:0,surrenderCount:0,weatherBurden:0,captiveId:'levi',operationName:'The Names They Took',pavelReturned:false,huntAtEntry:false,skeinRecovered:false,skeinLeadDistance:0,gearPending:null,weaponCustody:null,partyInjuries:{},shots:[],observations:[],loot:{},patrolRoutes:{east:0,west:0,reserve:0}},
  scope:{raised:false,zoom:1,aim:{x:0,y:0,z:0},observed:{calder:false,levi:false,magazine:false,weighhouse:false,entry:false},hold:0,target:null},
  focus:{unlocked:false,active:false,activation:0,marks:[],queue:[],killIds:[],clock:0},
  rope:{phase:'idle',x:0,y:0,z:0,vx:0,vy:0,ttl:0,targetId:null,tension:0,age:0,misses:0},
  captivity:{state:'unseen',trust:0,cruelty:0,injury:0,questions:{card:false,signatures:false},helperId:null},aftermath:null,
};}
const field=s=>s.region===W.id,WORLD=(s,ctx)=>ctx.worldFor(s);
function emit(s,ctx,kind,target,targetId,actorId='mara',from=s.entities[actorId],sourceId=from?.id||actorId){ctx.present(s,kind,target,targetId,{...point(from),facing:from.facing||0},actorId,{sourceId});}
function tx(s,key,apply){const r=record(s),id=`${RIVAL_ID}:${key}`;if(r.transactions[id])return false;if(apply()===false)return false;r.transactions[id]={completed:true};return true;}
function say(s,ctx,id,actor,text,choices=[['leave','Continue.']]){ctx.talk(s,`rival-${id}`,s.entities[actor]?.name||actor,rivalSceneSpeech(record(s),id,text),choices);}
function objective(s){const r=record(s);r.mission.objective=r.mission.completed?'Levi is held under guard, with his own name and account. The next train operation needs its own preparation.':RIVAL_STAGES[r.mission.stage];}
function advance(s,ctx,stage,key,label){const r=record(s);if(stage<=r.mission.stage)return;r.mission.stage=stage;objective(s);ctx.checkpoint(s,key,label);}
function moveRegion(s,a,regionId,position){if(a.attachment)return;for(const env of Object.values(s.regions))env.residentIds=env.residentIds.filter(id=>id!==a.id);a.regionId=regionId;s.regions[regionId].residentIds.push(a.id);Object.assign(a,point(position));a.route=[];delete a.routeTarget;delete a.goal;}
function goal(a,target){if(a.goal&&distance(a.goal,target)<1)return;a.goal=point(target);a.route=[];delete a.routeTarget;}
export function ensureRivalCast(s,ctx){
  const r=record(s);if(!r||r.status==='locked')return;
  for(const a of RIVAL_CAST)ctx.addEntity(s,a,a.regionId||(['levi','skein','calder','grout'].includes(a.id)?W.id:'snowbound'),a.kind==='horse'?'mount':'npc');
  for(const a of RIVAL_ENEMIES){const e=ctx.addEntity(s,{...a,active:false,routeIndex:0,ammo:a.ammo??7,reserve:a.reserve??28,fireTimer:1.5,looted:false},W.id,'enemy');if(!r.rival.loot[e.id])r.rival.loot[e.id]=clone(a.loot||{money:1.5,cartridges:2,keepsake:'quarry token'});}
  if(!s.companions.ruth)for(const id of ['ruth','bastian','emmett'])s.companions[id]={trust:0,requests:0};
}
function offer(list,s,id,label,target,radius=55,priority=2){if(target&&nearby(s.player,target,radius))list.push({id,label,targetId:target.id||id,x:target.x,y:target.y,z:target.z||0,distance:distance(s.player,target),priority});}
const living=e=>e&&e.hp>0&&!e.surrendered&&!e.escaped;
function yard(s){return RIVAL_ENEMIES.filter(e=>e.wave==='yard').map(e=>s.entities[e.id]).concat(record(s).rival.pavelReturned?[s.entities.pavel]:[]);}
function patrol(s){return RIVAL_ENEMIES.filter(e=>e.wave!=='yard').map(e=>s.entities[e.id]);}
function tool(s,id){return record(s).objects[id];}
function partyNear(s,radius){return RIVAL_PARTY.every(id=>s.entities[id]&&distance(s.player,s.entities[id])<radius);}
function mountsAt(s,positions,radius=30){return RIVAL_MOUNTS.every(id=>positions[id]&&nearby(s.entities[id],positions[id],radius));}
function mount(s,ctx,a,h){if(a.carrying||a.mounted||h.hp<=0||!nearby(a,h,58)||blockedAt(WORLD(s,ctx),h.x,h.y,13))return false;const from={...point(a),facing:a.facing};a.mounted=true;a.mountId=h.id;Object.assign(a,point(h));a.facing=h.facing;h.hitched=false;emit(s,ctx,'mount',{...point(h),z:(h.z||0)+23},h.id,a.id,from);return true;}
function dismount(s,ctx,a){if(!a.mounted)return true;const h=s.entities[a.mountId||s.party.mountId];for(const radius of [27,35,44])for(const angle of [Math.PI/2,-Math.PI/2,Math.PI,0]){const q={x:h.x+Math.cos((h.facing||0)+angle)*radius,y:h.y+Math.sin((h.facing||0)+angle)*radius,z:h.z||0};if(blockedAt(WORLD(s,ctx),q.x,q.y,9))continue;const from={...point(a),z:(h.z||0)+23,facing:a.facing};a.mounted=false;Object.assign(a,q);emit(s,ctx,'dismount',q,h.id,a.id,from);return true;}return false;}
export function getRivalInteractions(s,ctx){
  const r=record(s),list=[];if(!r||r.status==='locked'||s.dialog||s.failure)return list;ensureRivalCast(s,ctx);const f=r.flags,p=s.player,levi=s.entities.levi;
  list.push(...getHoldingInteractions(s));
  list.push(...getRivalTransportInteractions(s,WORLD(s,ctx)));
  if(!yardOpeningPending(s))list.push(...getWeaponInteractions(s));
  if(!active(s)){
    if(s.region==='snowbound'&&r.status==='unstarted'&&s.mission.completed)offer(list,s,'rival:briefing','Listen to the stove-room argument',W.camp.briefing,65,-2);
    if(r.mission.completed&&s.region==='snowbound')offer(list,s,'rival:visit','Visit Levi at the guarded tack room',W.camp.holding,65,1);
    return list;
  }
  for(const a of Narrative.narrativeOffers(s))offer(list,s,a.id,a.label,a.target,a.radius,-4);
  const stage=r.mission.stage;
  if(!r.mission.completed&&f.carbineInspected){if(carriedCarbine(s)&&!p.mounted&&!p.carrying)offer(list,s,'rack:store-carbine','Store the Tern on Copper’s rack',s.horse,58,5);else if(stage!==1)offer(list,s,'rack:carbine','Retrieve the Tern from Copper’s rack',s.horse,58,-3);}
  if(stage===0){for(const[id,label]of[['ruth','Hear Ruth’s account'],['emmett','Hear Emmett challenge the accusation'],['bastian','Answer Bastian’s demand'],['inez','Let Inez intervene']])if(!f[`${id}Heard`]&&Narrative.openingVoiceAvailable(s,id))offer(list,s,`talk:${id}`,label,s.entities[id],65,-2);if(f.ruthHeard&&f.emmettHeard&&f.bastianHeard&&f.inezHeard&&Narrative.openingReady(s))offer(list,s,'rival:accept','Discuss the expedition with Tomas',s.entities.tomas,65,-2);}
  if(stage===1){
    if(f.carbineGranted&&!f.carbineInspected)offer(list,s,'rack:inspect-carbine','Inspect the Tern carbine at Copper’s rack',s.horse,58,-3);
    if(f.carbineInspected&&s.weapons[RIVAL_CARBINE.id]?.location==='saddle')offer(list,s,'rack:carbine','Retrieve and equip the Tern carbine',s.horse,58,-3);
    if(equipmentContract(s)&&f.carbineGranted&&!ammunitionReady(s)&&!p.mounted&&!p.carrying)offer(list,s,'gear:cartridges','Receive Ruth’s forty-two spare cartridges',s.entities.ruth,55,-3);
    if(!f.lariatGranted)offer(list,s,'gear:lariat','Receive Inez’s working lariat',s.entities.inez,55,-3);
    if(!f.sightglassGranted)offer(list,s,'gear:sightglass','Receive the quarry sightglass',s.entities.emmett,55,-3);
    if(f.carbineEquipped&&carriedCarbine(s)&&ammunitionReady(s)&&f.lariatGranted&&f.sightglassGranted&&p.mounted&&RIVAL_PARTY.every(id=>s.entities[id].mounted))offer(list,s,'depart:bellwether','Take the south trail with all six riders',W.travelGate,65,-3);
    offer(list,s,'rival:postpone','Ask Tomas to wait before departure',s.entities.tomas,65,8);
  }
  if(stage===2){for(const id of ['wagon-grooves','patrol-hooves','wrong-fork']){const q=W.props.find(a=>a.id===id);if(id==='wrong-fork'||!f[id==='wagon-grooves'?'groovesRead':'hoovesRead'])offer(list,s,`inspect:${id}`,id==='wrong-fork'?'Check the frozen wrong fork':id==='wagon-grooves'?'Inspect the quarry wagon grooves':'Read the returning patrol hoofprints',q,55,-2);}if(f.groovesRead&&f.hoovesRead&&r.rival.trailIndex>=W.trail.length&&Narrative.trailNarrativeReady(s))offer(list,s,'lesson:ridge','Hear Tomas and Ruth at the ridge',W.observation,75,-2);}
  if(stage===3){offer(list,s,'sightglass:raise',r.scope.raised?'Lower the sightglass':'Raise the sightglass and scan the works',W.observation,60,-2);if(r.flags.reconComplete)offer(list,s,'recon:plan','Assign the flank pairs with Tomas',s.entities.tomas,75,-3);}
  if(stage===4&&f.approachReady)offer(list,s,'choose-first','Choose Mara’s first shot or Tomas’s signal',W.readyCover,60,-3);
  if(stage===6||stage===8){
    const bodies=stage===6?yard(s):[...yard(s),...patrol(s)];
    for(const e of bodies.filter(e=>!living(e)&&!e.looted&&!e.escaped))offer(list,s,`${e.surrendered?'search-surrendered':'loot'}:${e.id}`,e.surrendered?'Search the surrendered guard without killing':'Search this Claimant’s finite belongings',e,48,-3);
    if(stage===6&&f.pocketSearched&&f.patrolWarned)offer(list,s,'battle:tactics','Choose where to meet the wooded patrols',s.entities.tomas,80,-2);
  }
  if(stage===8){
    for(const[id,key,label]of[['magazine','magazine','Inspect the powder magazine'],['cap-wagon','capWagon',physicalSearchContract(s)?'Ask Ruth to search the cap wagon':'Search the cap wagon'],['weighhouse','weighhouse',physicalSearchContract(s)?'Ask Bastian to search the weighhouse desk':'Read the weighhouse account room']])if(!f[{magazine:'magazineRead',capWagon:'capWagonRead',weighhouse:'weighhouseRead'}[key]])offer(list,s,`search:${id}`,label,W.searchSites[key],55,-3);
    for(const action of physicalSearchOffers(s))offer(list,s,action.id,action.label,action.target,action.radius,-3);
    if(f.magazineRead&&!f.chargeInspected)offer(list,s,'inspect:charges','Inspect the four sealed quarry charges',W.charge,45,-3);
    if(f.chargeInspected&&!f.chargePassed&&nearby(p,W.charge,90))offer(list,s,'pass:charge','Hand one charge to Ruth for inspection',s.entities.ruth,48,-3);
    if(f.chargePassed&&!f.chargeRepacked&&tool(s,'cap-tin')?.owner==='ruth')offer(list,s,'repack:charges','Repack the four inspected charges',W.charge,48,-3);
    if(f.chargeRepacked&&!f.crateTaken)offer(list,s,'take:crate','Ask Ruth to take custody of the sealed crate',s.entities.ruth,48,-3);
    if(f.weighhouseRead&&!f.plansRead&&nearby(s.entities.bastian,W.plans,55)&&(!physicalSearchContract(s)||r.objects['route-diagram']?.owner==='bastian'&&r.objects['seizure-list']?.owner==='bastian'))offer(list,s,'read:plans','Read the route diagram and seizure list',W.plans,45,-3);
    if(f.crateTaken&&f.plansDelivered&&f.horsesRetrieved)offer(list,s,'convoy:depart','Remount and lead the recovered convoy home',s.entities.tomas,90,-2);
  }
  if(stage===10){if(r.captivity.state==='roped'&&distance(p,levi)<35&&!p.mounted)offer(list,s,'bind:levi','Bind Levi while keeping the rope taut',levi,35,-3);if(!levi.mounted&&['fleeing','tackled'].includes(r.captivity.state)&&!p.mounted)offer(list,s,r.captivity.state==='tackled'?'bind:levi':'tackle:levi',r.captivity.state==='tackled'?'Bind Levi’s hands':'Tackle and restrain the fleeing copyist',levi,26,-3);}
  if(stage===11){if(!levi.attachment&&!p.carrying&&!p.mounted)offer(list,s,'carry:levi','Lift the bound Levi',levi,38,-3);if(p.carrying==='levi')offer(list,s,'load:levi','Set Levi in Copper’s rear passenger position',s.horse,52,-3);if(levi.attachment?.type==='passenger'&&(!f.strapped||usesRivalTransport(s)&&!levi.attachment.strap)&&canInitialPassengerStrap(s,WORLD(s,ctx)))offer(list,s,'strap:levi','Secure the bound passenger with a real strap',s.horse,55,-3);if(f.strapped&&!r.choices.assurance&&(!usesRivalTransport(s)||rivalPassenger(s)))offer(list,s,'talk:levi-road','Answer Levi’s questions about the destination',{...levi,z:s.horse.z||0},65,-2);if(f.strapped&&r.choices.assurance&&p.mounted&&r.rival.returnIndex>=W.returnRoute.length&&(s.entities.skein.hp<=0||r.rival.skeinRecovered)&&partyNear(s,210)&&canReturnWithPassenger(s))offer(list,s,'return:kiln','Return the entire convoy to the kiln',W.entry,70,-3);}
  if(stage===12&&s.region==='snowbound'){list.push(...getQuestioningInteractions(s));if(p.mounted)offer(list,s,'hitch:tack','Dismount at the tack-room doorway',W.camp.arrival,65,-3);if(levi.attachment?.type==='passenger'&&!p.mounted)offer(list,s,'unload:levi','Lift Levi from Copper’s passenger seat',s.horse,52,-3);if(p.carrying==='levi')offer(list,s,'deliver:levi','Bring Levi through the tack-room doorway',W.camp.doorway,35,-3);if(!usesQuestioningContract(r)&&f.delivered&&f.held&&!f.questioned)offer(list,s,'talk:levi-evidence','Compare Levi’s debt card with the seizure list',W.camp.holding,65,-3);}
  if(stage===13&&!r.mission.completed){if(!f.chargesStored)offer(list,s,'deposit:charges','Store Ruth’s sealed charges under her custody',W.camp.charges,55,-3);if(f.chargesStored&&f.held&&nearby(s.entities.bastian,W.camp.holding,60))offer(list,s,'finish:rival','Let Della write every name and finish the account',W.camp.ledger,65,-3);}
  if(r.mission.completed)offer(list,s,'rival:visit','Visit Levi at the guarded tack room',W.camp.holding,65,1);
  if(!p.carrying){offer(list,s,p.mounted?'dismount':'mount',p.mounted?'Dismount Copper':'Mount Copper',s.horse,58,7);}
  return list.sort((a,b)=>a.priority-b.priority||a.distance-b.distance);
}
function rackStance(h){const c=Math.cos(h.facing||0),n=Math.sin(h.facing||0);return{x:h.x-26*c+12*n,y:h.y-26*n-12*c,z:h.z||0,facing:(h.facing||0)+Math.atan2(4,8)};}
function grantCarbine(s,ctx){const r=record(s);tx(s,'grant:tern',()=>{s.weapons[RIVAL_CARBINE.id]={...RIVAL_CARBINE,id:RIVAL_CARBINE.id,kind:'carbine',capacity:7,ammoType:'tern-cartridge',ammo:7,reserve:initialCarbineReserve(s),condition:1,owner:'mara',loanMissionId:null,location:'saddle',rackMountId:s.horse.id};});r.flags.carbineGranted=true;emit(s,ctx,'give-carbine',s.horse,RIVAL_CARBINE.id,'tomas',s.entities.tomas,s.horse.id);ctx.notice(s,equipmentContract(s)?'Tomas brings the loaded Tern to Copper’s rack. Ruth has the separate spare cartridges.':'Tomas brings seven loaded cartridges and forty-two spare rounds to Copper’s actual rack.');}
function equip(s,ctx,id){const r=record(s),p=s.player,w=s.weapons[id],rack=w?.rackMountId&&s.entities[w.rackMountId];if(!w||!['mara','community-rescue-chest'].includes(w.owner)||p.carrying||p.weaponAction||w.location==='dropped'||id===ENGRAVED_REVOLVER_ID&&w.owner!=='mara'||w.location==='saddle'&&!nearby(p,s.entities[w.rackMountId],58)||id===RIVAL_CARBINE.id&&!r.flags.carbineInspected)return false;p.equippedWeaponId=w.id;w.location='carried';delete w.rackMountId;p.holstered=false;p.armed=true;p.reloadTimer=0;delete p.reloadWeaponId;if(id===RIVAL_CARBINE.id)r.flags.carbineEquipped=true;cancelRivalFocus(s);emit(s,ctx,'equip',rack||p,w.id,'mara',p,rack?.id||'mara');return true;}
function yardOpeningPending(s){const r=record(s);return r.mission.stage===5&&r.rival.yardOpening?.firedAt===null;}
function releaseYard(s){for(const e of yard(s))if(e.hp>0){e.active=true;e.fireTimer=1.2;}}
function prepareBattle(s,ctx,first){
  const r=record(s);r.choices.firstShot=first;r.focus.unlocked=true;r.flags.focusTaught=true;
  ctx.log(s,'The Tern’s first automatic focus sweep is taught in the actual yard battle.');
  if(first==='player'){
    r.rival.yardOpening={schema:1,shotsBefore:r.performance.shots,shotSerial:null,startedAt:s.elapsed,firedAt:null};
    for(const e of yard(s))e.active=false;
  }else{
    const a=s.entities.tomas;
    if(a.ammo===undefined){a.ammo=7;a.reserve=21;a.weapon={id:'tomas-quarry-carbine',kind:'carbine',capacity:7,owner:'tomas'};}
    a.ammo--;a.holstered=false;a.aiming=true;a.shotTimer=.3;
    const target=yard(s).find(living);launchBullet(s,a,target,'ally',38);
    emit(s,ctx,'shoot',target,a.weapon.id,'tomas',a);releaseYard(s);
  }
  advance(s,ctx,5,'yard-battle','Concealed approach and first-shot roles established');
  ctx.notice(s,'Hold Focus and sweep the reticle over visible targets. Fire attempts the marked shots through actual cover.');
}
export function interactRival(s,requestedId,ctx){const offered=getRivalInteractions(s,ctx).find(a=>a.id===requestedId);if(!offered)return s;const r=record(s),f=r.flags,id=offered.id,p=s.player,levi=s.entities.levi;
  if(id.startsWith('transport:')){interactRivalTransport(s,id,ctx,WORLD(s,ctx));return s;}
  if(id.startsWith('holding:'))return interactHolding(s,id,ctx);
  if(usesQuestioningContract(r)&&(id==='talk:levi-evidence'||id.startsWith('care:bring:')||id.startsWith('care:unpack:'))){interactQuestioning(s,id,ctx);return s;}
  if(id.startsWith('weapon:')){interactWeaponCustody(s,id,ctx);return s;}
  if(id==='rival:briefing')Narrative.initializeUnstartedNarrative(s);
  if(Narrative.interactNarrative(s,id,ctx)){objective(s);return s;}
  if(id==='rival:briefing'){f.intervened=true;say(s,ctx,'argument','ruth','Bastian calls the careful frightened. He has just struck the shoulder that carried the powder ledger. Inez steps between us. A raid needs reasons as well as cartridges.',[['intervene','Stand beside Ruth and stop the quarrel.'],['ask-motive','Ask Tomas why this cooperative matters.'],['leave','Return when you are ready.']]);}
  else if(id.startsWith('talk:')&&['ruth','emmett','bastian','inez'].includes(id.slice(5))){const who=id.slice(5);f[`${who}Heard`]=true;const texts={ruth:'The quarry families signed for a fair settlement. Calder used their names to choose the houses his men would empty. We recover the account; we do not blame the signatories.',emmett:'Tracks tell us who has passed, not whether an accusation is true. I will keep the horses above the works until I can name a safe ramp.',bastian:'A direct blow might finally make Calder listen. I hear Ruth’s objection. I will take the western cover she chooses, and I will search the weighhouse.',inez:'I stopped the second blow. My work is the mount line: Copper, Moth, Thimble and the three new partners come home as themselves.'};say(s,ctx,who,who,texts[who]);}
  else if(id==='rival:accept')say(s,ctx,'invitation','tomas','Calder turned a settlement into a seizure list. I want the quarry papers and the sealed powder crate. Ask whether I can leave my anger here, then decide whether to come.',[['accept-rival','Take the separate quarry expedition.'],['ask-motive','Question Tomas’s motive.'],['leave','Wait at the kiln.']]);
  else if(id==='rack:inspect-carbine'){f.carbineInspected=true;emit(s,ctx,'inspect-carbine',s.horse,RIVAL_CARBINE.id);say(s,ctx,'carbine','tomas',equipmentContract(s)?CARBINE_INSPECTION_TEXT:'Seven chambers in the tube. The spare cartridges belong to this gun; a coach shell or field arrow will not fit. Bring your sidearm too. Inspect the action before you take it.');}
  else if(id==='gear:cartridges')requestCartridges(s,ctx);
  else if(id==='rack:store-carbine'){if(storeCarbine(s,ctx))cancelRivalFocus(s);}
  else if(id==='rack:carbine'){if(equip(s,ctx,RIVAL_CARBINE.id))ctx.checkpoint(s,'loadout','Inspected carbine physically retrieved');}
  else if(id==='gear:lariat'){if(s.entities.inez.mounted){dismount(s,ctx,s.entities.inez);if(!nearby(p,s.entities.inez,55)){ctx.notice(s,'Inez has stepped down to pass the rope. Move beside her.');return s;}}if(!nearby(p,s.entities.inez,22)){r.rival.gearPending='gear:lariat';goal(s.entities.inez,{x:p.x+12,y:p.y+7,z:p.z||0});ctx.notice(s,'Inez is coming close enough to pass the working rope.');return s;}r.rival.gearPending=null;s.entities.inez.actionTimer=1.1;tx(s,'grant:lariat',()=>{s.weapons['working-lariat']={id:'working-lariat',name:'Inez’s working lariat',kind:'lariat',capacity:0,ammo:0,reserve:0,ammoType:'rope',condition:1,owner:'mara',loanMissionId:null,location:'carried'};});f.lariatGranted=true;emit(s,ctx,'give-lariat',p,'working-lariat','inez',s.entities.inez);say(s,ctx,'lariat','inez','Throw across a clear lane within reach. Keep tension, dismount, approach and bind. Slack lets a frightened person regain his feet; it does not give you a second body.');}
  else if(id==='gear:sightglass'){if(s.entities.emmett.mounted){dismount(s,ctx,s.entities.emmett);if(!nearby(p,s.entities.emmett,55)){ctx.notice(s,'Emmett has stepped down with the sightglass. Move beside him.');return s;}}if(!nearby(p,s.entities.emmett,22)){r.rival.gearPending='gear:sightglass';goal(s.entities.emmett,{x:p.x+12,y:p.y+7,z:p.z||0});ctx.notice(s,'Emmett is bringing the sightglass to your hand.');return s;}r.rival.gearPending=null;s.entities.emmett.actionTimer=1.1;tx(s,'grant:sightglass',()=>{r.objects.sightglass={id:'sightglass',kind:'sightglass',owner:'mara',location:{type:'carried',targetId:'mara'}};});f.sightglassGranted=true;emit(s,ctx,'give-sightglass',p,'sightglass','emmett',s.entities.emmett);}
  else if(id==='depart:bellwether'){
    if(!partyNear(s,220)||!carriedCarbine(s)||!ammunitionReady(s))return s;const ids=['mara',s.horse.id,...RIVAL_PARTY,...RIVAL_MOUNTS],positions={mara:point(W.entry),[s.horse.id]:point(W.entry)};RIVAL_PARTY.forEach((who,i)=>{const q={x:W.entry.x+45+(i%2)*40,y:W.entry.y-40-Math.floor(i/2)*45,z:0};positions[who]=q;positions[RIVAL_MOUNTS[i]]=q;});
    if(ctx.transition(s,W.id,ids,positions)){f.entered=true;const old=s.campaign.missions[OPENING].flags;if(old.pavelChoice==='release'&&s.entities.pavel.hp>0){moveRegion(s,s.entities.pavel,W.id,{x:1805,y:1365,z:0});s.entities.pavel.active=false;s.entities.pavel.ammo=6;s.entities.pavel.reserve=18;r.rival.pavelReturned=true;r.rival.loot.pavel={money:0,cartridges:2,keepsake:'station chit'};}advance(s,ctx,2,'six-riders','Six living riders entered the separate quarry region');}
  }else if(id.startsWith('inspect:')&&['wagon-grooves','patrol-hooves','wrong-fork'].includes(id.slice(8))){const track=id.slice(8);if(track==='wrong-fork'){r.rival.marksBelow++;ctx.notice(s,'Emmett: “Ice has filled those older prints. Return to the cart grooves; the mistaken fork is recoverable.”');}else f[track==='wagon-grooves'?'groovesRead':'hoovesRead']=true;emit(s,ctx,'inspect-track',offered,track);}
  else if(id==='lesson:ridge'){dismount(s,ctx,p);for(const who of RIVAL_PARTY)dismount(s,ctx,s.entities[who]);for(const id of [...RIVAL_PARTY,...RIVAL_MOUNTS,s.horse.id]){const a=s.entities[id];delete a.goal;a.route=[];delete a.routeTarget;}for(let i=0;i<RIVAL_PARTY.length;i++)goal(s.entities[RIVAL_PARTY[i]],{x:W.observation.x-20-(i%2)*30,y:W.observation.y+15+Math.floor(i/2)*25,z:W.observation.z});f.ridgeBriefed=true;advance(s,ctx,3,'observation-ridge','All six riders reached the observation approach');say(s,ctx,'ridge','ruth','The magazine is beyond the traverser. The account room sits downhill. Watch before you choose a way through; Tomas’s failed agreement did not make every worker his enemy.');}
  else if(id==='sightglass:raise'){r.scope.raised=!r.scope.raised;r.scope.hold=0;if(r.scope.raised){initializeReconWitness(s);r.scope.camera={x:W.recon.calderStart.x,y:W.recon.calderStart.y};r.scope.aim={...W.recon.calderStart};}emit(s,ctx,'sightglass',W.observation,'sightglass');ctx.notice(s,r.scope.raised?'Aim the sightglass at Calder, Levi, the magazine, weighhouse and screened entry. Hold each view until the observation is written.':'Sightglass lowered.');}
  else if(id==='recon:plan'){r.scope.raised=false;for(const who of ['ruth','bastian'])goal(s.entities[who],W.yardCover[who]);for(const who of ['inez','emmett'])goal(s.entities[who],W.mountsPark[s.entities[who].mountId]);goal(s.entities.tomas,W.descent[0]);advance(s,ctx,4,'screened-descent','Observed works and assigned separate flank and mount roles');say(s,ctx,'descent','tomas','Ruth and Bastian take the western cover. Inez and Emmett hold the mount line. Mara, come down the screened chute with me; wait until all our positions are real before the first shot.');}
  else if(id==='choose-first')say(s,ctx,'first-shot','tomas','The cover is held. Will you make the first shot, or wait for my signal?', [['player-first','Mara opens the yard battle.'],['tomas-first','Let Tomas give the first shot.']]);
  else if(id.startsWith('loot:')||id.startsWith('search-surrendered:')){
    const e=s.entities[id.slice(id.indexOf(':')+1)],stock=r.rival.loot[e.id];
    tx(s,`loot:${e.id}`,()=>{
      p.money+=stock.money;
      const gun=s.weapons[RIVAL_CARBINE.id];gun.reserve+=(stock.cartridges||stock.ammunition?.['tern-cartridge']||0);
      const held=new Set([...(stock.objects||[]),stock.keepsake].filter(Boolean));
      stock.transferredObjectIds=[];
      for(const paper of QUARRY_POCKET_OBJECTS.filter(paper=>paper.sourceEntityId===e.id&&held.has(paper.lootId))){
        r.objects[paper.id]={id:paper.id,kind:paper.kind,sourceEntityId:e.id,owner:'mara',location:{type:'carried',targetId:'mara'}};
        stock.transferredObjectIds.push(paper.id);
      }
      stock.money=0;stock.cartridges=0;if(stock.ammunition)stock.ammunition['tern-cartridge']=0;
      stock.objects=[];stock.keepsake=null;e.looted=true;
    });
    f.pocketSearched=true;emit(s,ctx,e.surrendered?'search-surrendered':'loot',e,e.id);
    ctx.notice(s,stock.transferredObjectIds.length?'The personal belonging is now owned in your satchel. Read it there; this individual pocket cannot pay twice.':'The pocket is empty now. The individual body and its finite transfer remain recorded.');
  }
  else if(id==='battle:tactics')say(s,ctx,'tactics','tomas','The scouts are moving through both tree lanes. Hold the wheels and stop the flankers, or advance into the screen before the reserve reaches the gate?', [['hold-yard','Hold the traverser and its cover.'],['advance-trees','Advance into the two wooded approaches.']]);
  else if(id==='search:cap-self'||id==='handoff:cap-tin')interactPhysicalSearch(s,id,ctx);
  else if(id.startsWith('search:')){const site=id.slice(7);if(physicalSearchContract(s)&&['cap-wagon','weighhouse'].includes(site)){requestPhysicalSearch(s,site,ctx);}else{const key={'magazine':'magazineRead','cap-wagon':'capWagonRead','weighhouse':'weighhouseRead'}[site];f[key]=true;emit(s,ctx,'search',offered,site);if(site==='cap-wagon'){r.objects['cap-tin']={id:'cap-tin',kind:'cap-tin',owner:'ruth',location:{type:'carried',targetId:'ruth'}};goal(s.entities.ruth,W.charge);}if(site==='weighhouse'){for(const item of ['route-diagram','seizure-list'])r.objects[item]={id:item,kind:'document',owner:'bastian',location:{type:'station',targetId:W.plans.id}};goal(s.entities.bastian,W.plans);}}}
  else if(id==='inspect:charges'){f.chargeInspected=true;r.objects['charge-crate']={id:'charge-crate',kind:'sealed-quarry-charges',count:4,chargeIds:['quarry-sealed-charge-1','quarry-sealed-charge-2','quarry-sealed-charge-3','quarry-sealed-charge-4'],owner:'quarry-store',location:{type:'station',targetId:W.charge.id}};for(const id of r.objects['charge-crate'].chargeIds)r.objects[id]={id,kind:'sealed-charge',sealed:true,inspected:true,owner:'quarry-store',location:{type:'crate',targetId:'charge-crate'}};emit(s,ctx,'inspect-charge',W.charge,'charge-crate');ctx.notice(s,'Four sealed quarry charges. Their caps remain in Ruth’s separate tin; this is equipment for the later plan, not free ammunition.');}
  else if(id==='pass:charge'){f.chargePassed=true;const charge=r.objects['quarry-sealed-charge-1'];charge.owner='ruth';charge.location={type:'carried',targetId:'ruth'};emit(s,ctx,'pass-charge',s.entities.ruth,'charge-crate');say(s,ctx,'powder','ruth','The wrapper is dry and the seal is sound. Keep its cap separate until a real plan needs it. Return this one to the same crate; we count four, not five.');}
  else if(id==='repack:charges'){f.chargeRepacked=true;r.objects['quarry-sealed-charge-1'].owner='quarry-store';r.objects['quarry-sealed-charge-1'].location={type:'crate',targetId:'charge-crate'};emit(s,ctx,'repack-charge',W.charge,'charge-crate');}
  else if(id==='take:crate'){const o=tool(s,'charge-crate');o.owner='ruth';o.location={type:'carried',targetId:'ruth'};for(const id of o.chargeIds)r.objects[id].owner='ruth';f.crateTaken=true;emit(s,ctx,'carry-crate',s.entities.ruth,o.id,'ruth',W.charge);}
  else if(id==='read:plans'){f.plansRead=true;ctx.log(s,'The route diagram places the bond-and-deed train at the pulley crossing. The seizure list contains families from Tomas’s failed settlement.');say(s,ctx,'plans','emmett','The scale shows the bend at the pulley creek. Calder plans to divert a bond-and-deed train and sell the same holdings twice. This paper proves a route, not a promise that our next plan will work.');goal(s.entities.bastian,s.entities.tomas);}
  else if(id==='convoy:depart'){if(!p.mounted){mount(s,ctx,p,s.horse);return s;}if(!RIVAL_PARTY.every(who=>s.entities[who].mounted))return s;f.convoyDeparted=true;r.choices.order=r.rival.huntAtEntry?'hunt-first':'rival-first';const narrated=Narrative.startNarrativeConvoy(s,ctx);advance(s,ctx,9,'convoy-home','Actual papers, sealed charges and six mounts leave together');if(!narrated)say(s,ctx,'convoy','tomas',r.rival.huntAtEntry?'Juno’s food is counted and her hand is resting. We have recovered the quarry papers too. Della must still account for every injury.':'The quarry papers are recovered. Orla’s separate food expedition is still needed before the next train plan. We cannot eat a seizure list.');}
  else if(id==='tackle:levi'){if(levi.mounted)return s;r.captivity.state='tackled';levi.vx=0;levi.vy=0;r.timers.bind=0;emit(s,ctx,'tackle',levi,'levi');}
  else if(id==='bind:levi'){r.timers.bind=2;emit(s,ctx,'bind',levi,'levi');ctx.notice(s,'Keep close while Mara binds the moving person’s hands.');}
  else if(id==='carry:levi'){if(ctx.setAttachment(s,'levi',{type:'carried',targetId:'mara'})){r.captivity.state='carried';emit(s,ctx,'lift',p,'levi','mara',levi,'levi');}}
  else if(id==='load:levi'){const from=point(p);if(ctx.setAttachment(s,'levi',{type:'passenger',targetId:s.horse.id,strap:false})){r.captivity.state='loaded';f.loaded=true;transportLoaded(s);emit(s,ctx,'load',s.horse,'levi','mara',from,'mara');}}
  else if(id==='strap:levi'){if(!canInitialPassengerStrap(s,WORLD(s,ctx)))return s;levi.attachment.strap=true;f.strapped=true;transportStrapped(s);emit(s,ctx,'strap',levi,'levi');ctx.checkpoint(s,'bound-passenger','One living captive secured in the separate passenger seat');}
  else if(id==='talk:levi-road')say(s,ctx,'levi-road','levi','My name is Levi Senn. Calder bought my family’s arrears and made me copy the warrants. Am I being taken to a judge, or another man who wants a uniform to blame?', [['offer-assurance','Promise food and a checked account, without promising release.'],['threaten','Threaten punishment if he refuses to speak.']]);
  else if(id==='return:kiln'){const ids=['mara',s.horse.id,'levi',...RIVAL_PARTY,...RIVAL_MOUNTS,...(s.entities.skein.hp>0?['skein']:[])],positions={mara:point(W.camp.arrival),[s.horse.id]:point(W.camp.arrival)};RIVAL_PARTY.forEach((who,i)=>{positions[RIVAL_MOUNTS[i]]=W.camp.partyParking[RIVAL_MOUNTS[i]];positions[who]=positions[RIVAL_MOUNTS[i]];});if(s.entities.skein.hp>0)positions.skein=point(W.camp.partyParking.skein);if(ctx.transition(s,'snowbound',ids,positions)){s.entities.skein.leading=false;delete s.entities.skein.leaderId;for(const id of ['mara',s.horse.id,...RIVAL_PARTY,...RIVAL_MOUNTS]){const a=s.entities[id];delete a.goal;a.route=[];delete a.routeTarget;}f.campReturned=true;advance(s,ctx,12,'tack-room-return','Complete convoy returned with Levi’s actual passenger attachment');}}
  else if(id==='hitch:tack'){dismount(s,ctx,p);s.horse.following=false;for(const who of RIVAL_PARTY){dismount(s,ctx,s.entities[who]);goal(s.entities[who],W.camp.homes[who]||{x:s.entities[who].x,y:s.entities[who].y,z:0});}}
  else if(id==='unload:levi'){const from=point(s.horse);if(ctx.setAttachment(s,'levi',{type:'carried',targetId:'mara'})){r.captivity.state='carried';transportUnloaded(s);emit(s,ctx,'unload',p,'levi','mara',from,s.horse.id);}}
  else if(id==='deliver:levi'){const ruth=s.entities.ruth;goal(ruth,W.camp.doorway);if(!nearby(ruth,p,48)){ctx.notice(s,'Ruth is coming through the actual doorway to receive Levi.');return s;}if(ctx.setAttachment(s,'levi',{type:'carried',targetId:'ruth'})){f.delivered=true;r.captivity.helperId='ruth';r.rival.helperIndex=0;goal(s.entities.hob,W.camp.helpers.hob);emit(s,ctx,'handoff',ruth,'levi','mara',p,'mara');}}
  else if(id==='talk:levi-evidence'){r.captivity.questions.card=true;r.captivity.questions.signatures=true;f.questioned=true;say(s,ctx,'levi-evidence','Della Wren','His torn payment card gives Levi’s own name. The seizure list carries copied signatures; it cannot tell us whether he copied them willingly. Bastian asks for punishment. Tomas orders a guarded hold while this account is checked.', [['care-levi','Give food, a blanket and less cruel restraints from the actual camp stock.'],['deprive-levi','Withhold provisions and tighten the hold.']]);}
  else if(id==='deposit:charges'){if(tool(s,'charge-crate')?.location.type==='saddle'){if(!nearby(s.entities.ruth,s.entities.plover,55)){goal(s.entities.ruth,s.entities.plover);ctx.notice(s,'Ruth is retrieving the crate from Plover’s actual saddle.');return s;}tool(s,'charge-crate').location={type:'carried',targetId:'ruth'};emit(s,ctx,'unload-crate',s.entities.ruth,'charge-crate','ruth',s.entities.plover,'plover');}if(!nearby(s.entities.ruth,W.camp.charges,45)){goal(s.entities.ruth,W.camp.charges);ctx.notice(s,'Ruth is carrying the sealed crate to its own store.');return s;}tx(s,'deposit:charges',()=>{for(const name of ['charge-crate','cap-tin']){const o=tool(s,name);o.location={type:'station',targetId:W.camp.charges.id,regionId:'snowbound'};}f.chargesStored=true;});emit(s,ctx,'deposit',W.camp.charges,'charge-crate','ruth',s.entities.ruth);}
  else if(id==='finish:rival'){if(!partyNear(s,500))return s;tx(s,'complete:account',()=>{s.camp.morale=clamp(s.camp.morale+4,0,100);f.accounted=true;});r.performance.underTime=r.timers.elapsed<1320;r.aftermath={operationName:'The Names They Took',captiveId:'levi',care:r.choices.care,assurance:r.choices.assurance,order:r.choices.order};initializeHolding(s);ctx.complete(s,['campaign-who-the-hell-is-leviticus-cornwall']);s.campaign.unlocks['focus-auto-mark']={available:true,requirementKnown:true};objective(s);say(s,ctx,'completed','Della Wren','Every recovered pocket, document, charge and injured person is in the account. Levi’s name is written separately from Calder’s. The next train operation still requires its own authored preparation.');}
  else if(id==='rival:visit')say(s,ctx,'visit','levi',questioningVisitText(r)||(r.choices.care==='care'?'The blanket stayed, and so did the guard. I can name the copied warrants. Checking them does not make this a free room.':'I am still cold under guard. The account records what was withheld as well as what was recovered.'));
  else if(id==='rival:postpone')say(s,ctx,'postpone','tomas','We can wait at the kiln. Your issued equipment remains individually owned and counted; waiting will not issue it twice.');
  else if(id==='mount')mount(s,ctx,p,s.horse);else if(id==='dismount')dismount(s,ctx,p);
  objective(s);return s;
}
export function chooseRival(s,id,ctx){const d=s.dialog,r=record(s);if(!d||!d.id.startsWith('rival-')||!d.choices.some(c=>c.id===id))return s;
  if(d.id.startsWith('rival-holding-'))return chooseHolding(s,id,ctx);
  if(d.id.startsWith('rival-questioning-')){chooseQuestioning(s,id,ctx);return s;}
  if(Narrative.chooseNarrative(s,id,ctx))return s;
  if(id==='leave'){s.dialog=null;return s;}if(id==='intervene'){if(!active(s)&&!ctx.startMission(s,RIVAL_ID))return s;r.flags.intervened=true;s.companions.ruth.trust++;s.dialog=null;ctx.notice(s,'Hear Ruth, Emmett, Bastian and Inez individually before deciding.');}
  else if(id==='ask-motive')say(s,ctx,'motive','tomas','I trusted Calder with a quarry settlement. He turned those names into a seizure list. Anger brought me to this room; whether evidence or revenge takes us out is a question you can keep asking.');
  else if(id==='accept-rival'){if(!ctx.startMission(s,RIVAL_ID))return s;r.flags.accepted=true;r.rival.huntAtEntry=!!s.campaign.missions[HUNT].mission.completed;s.dialog=null;goal(s.entities.tomas,rackStance(s.horse));ctx.checkpoint(s,'accepted','Separate quarry expedition accepted before equipment grants');advance(s,ctx,1,'equipment-prelude','Loadout preparation at actual people and Copper’s rack');}
  else if(['player-first','tomas-first'].includes(id)){s.dialog=null;Narrative.setNarrativeFirstShot(s,id==='player-first'?'player':'tomas');prepareBattle(s,ctx,id==='player-first'?'player':'tomas');}
  else if(['hold-yard','advance-trees'].includes(id)){s.dialog=null;r.choices.tactic=id==='hold-yard'?'hold':'advance';for(const who of ['tomas','ruth','bastian'])goal(s.entities[who],r.choices.tactic==='hold'?W.yardCover[who]:{x:W.yardCover[who].x+120,y:W.yardCover[who].y-180,z:0});for(const e of patrol(s)){e.active=true;e.fireTimer=2;}r.timers.patrol=0;advance(s,ctx,7,'wooded-patrols','Two actual wooded approaches and reserve engaged under chosen tactic');}
  else if(['offer-assurance','threaten'].includes(id)){r.choices.assurance=id==='threaten'?'threaten':'assurance';if(id==='threaten'){r.captivity.cruelty++;s.honor--;}else r.captivity.trust++;s.dialog=null;}
  else if(['care-levi','deprive-levi'].includes(id)){if(id==='care-levi'&&(s.camp.food<1||(s.camp.blankets||0)<1)){ctx.notice(s,'The promise requires one actual food portion and one counted blanket. Bring supplies or change the decision.');return s;}tx(s,'care:levi',()=>{r.choices.care=id==='care-levi'?'care':'deprive';if(id==='care-levi'){s.camp.food--;s.camp.blankets--;r.captivity.trust+=2;s.honor+=2;}else{r.captivity.cruelty+=2;s.honor-=3;}return true;});r.captivity.guardId='bastian';goal(s.entities.bastian,{x:W.camp.holding.x+30,y:W.camp.holding.y,z:0});s.dialog=null;advance(s,ctx,13,'guarded-hold','Levi’s testimony, guarded place and resource-backed care recorded');}
  return s;
}
function npcWeapon(s,a){const registered=s.weapons[a.equippedWeaponId];if(registered?.owner===a.id&&registered.location==='carried')return{weapon:registered,stock:registered};return a.weapon&&!a.weapon.registryOwned&&!a.gunDisarmed?{weapon:a.weapon,stock:a}:null;}
function launchBullet(s,shooter,target,faction,damage=45,aimZ=30){if(!target)return;const weapon=shooter.id==='mara'?s.weapons[shooter.equippedWeaponId]:npcWeapon(s,shooter)?.weapon;recordCustodyShot(s,shooter.id,weapon?.id);const dx=target.x-shooter.x,dy=target.y-shooter.y,d=Math.max(1,Math.hypot(dx,dy)),height=(shooter.z||0)+(shooter.mounted?64:29);shooter.facing=Math.atan2(dy,dx);s.bullets.push({x:shooter.x+dx/d*16,y:shooter.y+dy/d*16,z:height,vx:dx/d*720,vy:dy/d*720,vz:((target.z||0)+aimZ-height)/Math.max(1,d-16)*720,ttl:(weapon?.range||(weapon?.kind==='coach-gun'?420:weapon?.kind==='revolver'?650:720))/720,damage,faction,weaponKind:weapon?.kind||'carbine',shooterId:shooter.id,shotSerial:shooter.id==='mara'?record(s).performance.shots:null,focusActivation:record(s).focus.active?record(s).focus.activation:null});}
export function cancelRivalFocus(s){const f=record(s)?.focus;if(f){if(s.player)s.player.focusActive=false;f.active=false;f.marks=[];f.queue=[];f.clock=0;}return s;}
function attemptShot(s,x,y,ctx,aim={}){const r=record(s),p=s.player,w=s.weapons[p.equippedWeaponId];if(!w||w.kind==='bow'||w.kind==='lariat'||w.location!=='carried'||w.id===ENGRAVED_REVOLVER_ID&&w.owner!=='mara'||w.ammo<1||p.shotTimer>0||p.reloadTimer>0||p.holstered||p.carrying||p.weaponAction)return false;w.ammo--;p.shotTimer=w.kind==='carbine'?.28:w.kind==='coach-gun'?.7:.4;r.performance.shots++;s.stats.shots++;r.rival.shots.push({serial:r.performance.shots,weaponId:w.id,from:point(p),aim:{x,y,z:Number.isFinite(aim.z)?aim.z:30},activation:r.focus.active?r.focus.activation:null,impact:null});launchBullet(s,p,{x,y,z:0},'player',w.kind==='coach-gun'?64:45,Number.isFinite(aim.z)?aim.z:30);if(yardOpeningPending(s)){r.rival.yardOpening.shotSerial=r.performance.shots;r.rival.yardOpening.firedAt=s.elapsed;releaseYard(s);}emit(s,ctx,'shoot',{x,y,z:aim.z||30},w.id);Narrative.narrativeShot(s,ctx);return true;}
export function shootRival(s,x,y,ctx,aim={}){if(!active(s)||s.dialog||s.failure||!Number.isFinite(x)||!Number.isFinite(y))return s;const r=record(s),w=s.weapons[s.player.equippedWeaponId];if(r.scope.raised)return s;if(w?.kind==='lariat'){throwRope(s,x,y,ctx,aim);return s;}if(r.mission.stage===3||r.mission.stage===4&&!r.flags.approachReady){ctx.fail(s,'The reconnaissance was exposed before the concealed approach was ready.');return s;}if(r.mission.stage===4){Narrative.setNarrativeFirstShot(s,'unprompted');prepareBattle(s,ctx,'player');}if(r.focus.active&&r.focus.marks.length){r.focus.queue=clone(r.focus.marks);r.focus.marks=[];r.focus.clock=0;return s;}attemptShot(s,x,y,ctx,aim);return s;}
export function reloadRival(s,ctx){const p=s.player,w=s.weapons[p.equippedWeaponId];if(!active(s)||s.failure||s.dialog||p.carrying||!w||w.location!=='carried'||['bow','lariat'].includes(w.kind)||p.reloadTimer>0||w.ammo>=w.capacity||!w.reserve)return s;cancelRivalFocus(s);p.reloadTimer=w.kind==='carbine'?2.4:w.kind==='coach-gun'?1.8:1.3;p.reloadWeaponId=w.id;emit(s,ctx,'reload',p,w.id);return s;}
function throwRope(s,x,y,ctx,aim={}){const r=record(s),p=s.player;if(r.mission.stage!==10||p.carrying||p.holstered||r.rope.phase!=='idle'||s.weapons['working-lariat']?.location!=='carried')return;const d=Math.max(1,Math.hypot(x-p.x,y-p.y));r.rope={...r.rope,phase:'flying',x:p.x,y:p.y,z:(p.z||0)+(p.mounted?64:29),vz:((aim.z||30)-((p.z||0)+(p.mounted?64:29)))/d*430,vx:(x-p.x)/d*430,vy:(y-p.y)/d*430,ttl:.38,targetId:null,tension:0,age:0};emit(s,ctx,'lariat-throw',{x,y,z:25},'working-lariat');}
function projectileStep(s,dt,ctx){const r=record(s),world=WORLD(s,ctx);for(const b of s.bullets){const start=point(b),end={x:b.x+b.vx*dt,y:b.y+b.vy*dt,z:b.z+(b.vz||0)*dt};if(!clearLine(world,start,end,1,true)){b.ttl=0;continue;}let hit=null,best=Infinity;for(const a of Object.values(s.entities)){if(a.id===b.shooterId||a.regionId!==s.region||a.hp<=0||a.hidden||a.escaped)continue;if(b.faction==='enemy'&&!['mara',s.horse.id,...RIVAL_PARTY,...RIVAL_MOUNTS].includes(a.id))continue;if(b.faction==='ally'&&![...yard(s),...patrol(s)].some(e=>e.id===a.id))continue;const dx=end.x-start.x,dy=end.y-start.y,len=dx*dx+dy*dy,u=clamp(len?((a.x-start.x)*dx+(a.y-start.y)*dy)/len:0,0,1),x=start.x+dx*u,y=start.y+dy*u,z=start.z+(end.z-start.z)*u;if(Math.hypot(x-a.x,y-a.y)<(a.kind==='horse'||a.category==='mount'?21:12)&&z>=(a.attachment?.type==='passenger'?s.entities[a.attachment.targetId]?.z||0:a.z||0)+(a.mounted||a.attachment?.type==='passenger'?40:5)&&z<=(a.attachment?.type==='passenger'?s.entities[a.attachment.targetId]?.z||0:a.z||0)+(a.kind==='horse'||a.category==='mount'?60:a.mounted||a.attachment?.type==='passenger'?88:53)&&u<best){best=u;hit={a,z};}}
    if(hit){const a=hit.a,head=a.kind!=='horse'&&a.category!=='mount'&&hit.z>(a.attachment?.type==='passenger'?s.entities[a.attachment.targetId]?.z||0:a.z||0)+(a.mounted||a.attachment?.type==='passenger'?73:39);a.hp=Math.max(0,a.hp-b.damage*(head?b.weaponKind==='carbine'?2.5:1.7:1));if(a.hp===0)dropOwnedWeapon(s,a.id,ctx);b.ttl=0;if(b.faction==='player'){const hostile=[...yard(s),...patrol(s)].some(e=>e.id===a.id);if(hostile){s.stats.hostileHits++;if(a.hp===0){s.stats.kills++;if(a.surrendered)s.honor-=3;}}const receipt=r.rival.shots.find(a=>a.serial===b.shotSerial);if(receipt)receipt.impact={targetId:a.id,head,kill:a.hp===0,activation:b.focusActivation};if(a.id==='skein')registerSkeinWound(s,ctx,b.shotSerial);r.performance.hits++;if(a.hp===0){if(head)r.performance.headshots++;r.performance.kills++;if(b.focusActivation===r.focus.activation){r.focus.killIds.push(a.id);if(new Set(r.focus.killIds).size>=3)r.performance.threeFocusKills=true;}}if(['mara','levi',...RIVAL_PARTY,...RIVAL_MOUNTS,s.horse.id].includes(a.id))ctx.fail(s,'A required person or expedition mount was deliberately shot.');if(a.id==='skein'&&a.hp===0){recordSkeinDeath(s);tx(s,'skein:killed',()=>{s.honor-=5;r.captivity.injury++;return true;});}}if([...yard(s),...patrol(s)].some(e=>e.id===a.id)&&a.hp===0){a.active=false;a.dead=true;emit(s,ctx,'collapse',a,a.id,a.id,a);}}
    Object.assign(b,end);b.ttl-=dt;}s.bullets=s.bullets.filter(b=>b.ttl>0);
}
function focusStep(s,dt,input,ctx){const r=record(s),f=r.focus,p=s.player,w=s.weapons[p.equippedWeaponId],held=!!input.focus&&f.unlocked&&p.focus>0&&!p.carrying&&!p.weaponAction&&w?.location==='carried'&&(w.id!==ENGRAVED_REVOLVER_ID||w.owner==='mara')&&!['bow','lariat'].includes(w?.kind);if(held&&!f.active){f.active=true;f.activation++;f.marks=[];f.queue=[];f.killIds=[];}if(!held&&f.active)cancelRivalFocus(s);p.focusActive=held;p.focus=clamp(p.focus+(held?-14:5)*dt,0,100);
  if(held&&!f.queue.length&&Number.isFinite(input.aimX)&&Number.isFinite(input.aimY)){const target=[...yard(s),...patrol(s)].find(e=>living(e)&&(e.active||yardOpeningPending(s)&&yard(s).includes(e))&&distance(e,{x:input.aimX,y:input.aimY})<12&&distance(e,p)<580&&clearLine(WORLD(s,ctx),{...p,z:(p.z||0)+29},{...e,z:Number.isFinite(input.aimZ)?input.aimZ:(e.z||0)+30}));if(target&&!f.marks.some(m=>m.targetId===target.id)&&f.marks.length<w.ammo){f.marks.push({targetId:target.id,x:input.aimX-target.x,y:input.aimY-target.y,z:(Number.isFinite(input.aimZ)?input.aimZ:(target.z||0)+30)-(target.z||0),weaponId:w.id,activation:f.activation});emit(s,ctx,'focus-mark',target,target.id);}}
  if(f.queue.length){f.clock-=dt;if(f.clock<=0){const mark=f.queue.shift(),target=s.entities[mark.targetId];if(target&&living(target)&&w.id===mark.weaponId){p.shotTimer=0;attemptShot(s,target.x+mark.x,target.y+mark.y,ctx,{z:(target.z||0)+mark.z});}f.clock=.28;}}
}
function scopeStep(s,dt,input,ctx){const r=record(s);if(r.mission.stage!==3||!r.scope.raised)return;const q=r.scope;if(input.scopeVisible===false){q.hold=0;q.target=null;return;}if(Number.isFinite(input.aimX)&&Number.isFinite(input.aimY)){q.aim={x:input.aimX,y:input.aimY,z:input.aimZ||0};}const targets={calder:s.entities.calder,levi:s.entities.levi,magazine:W.searchSites.magazine,weighhouse:W.searchSites.weighhouse,entry:W.readyCover},id=Object.keys(targets).filter(id=>distance(q.aim,targets[id])<70&&distance(s.player,targets[id])<1800&&(!requiresReconWitness(s)||!['calder','levi'].includes(id)||visibleReconActors(s,input,[id]))).sort((a,b)=>distance(q.aim,targets[a])-distance(q.aim,targets[b]))[0];if(id!==q.target){q.target=id||null;q.hold=0;}if(id){q.hold+=dt;if(q.hold>.65&&!q.observed[id]){q.observed[id]=true;r.rival.observations.push({id,at:s.elapsed,from:point(s.player),aim:point(q.aim)});emit(s,ctx,'observe',targets[id],id);ctx.log(s,`Sightglass observation: ${id}. ${requiresReconWitness(s)?id==='levi'?'Levi stands beside Skein with his payment card.':id==='calder'?'Calder is speaking to the younger worker; keep them in view.':'A quarry location identified.':id==='levi'?'Calder tears Levi’s payment card; Skein waits beside him.':id==='calder'?'Calder leaves on Grout after striking the indebted copyist.':'A physical quarry location identified.'}`);}}if(Object.values(q.observed).every(Boolean)){r.flags.reconComplete=reconWitnessComplete(s);if(r.flags.reconComplete&&!s.log.some(e=>e.text==='All quarry observations complete.')){ctx.log(s,'All quarry observations complete.');ctx.notice(s,'All five observations are written. Lower the glass and assign the separate routes with Tomas.');}}}
function companionsStep(s,dt,ctx){const r=record(s),world=WORLD(s,ctx),stage=r.mission.stage,p=s.player;
  for(let i=0;i<RIVAL_PARTY.length;i++){const a=s.entities[RIVAL_PARTY[i]],h=s.entities[RIVAL_MOUNTS[i]];if(!a||!h)continue;if(a.weaponAction==='grappled'){a.vx=0;a.vy=0;a.aiming=false;continue;}a.shotTimer=Math.max(0,(a.shotTimer||0)-dt);a.reloadTimer=Math.max(0,(a.reloadTimer||0)-dt);a.actionTimer=Math.max(0,(a.actionTimer||0)-dt);
    if(stage===1){if(a.actionTimer>0)continue;const pending=r.rival.gearPending,asked=pending==='gear:lariat'&&a.id==='inez'||pending==='gear:sightglass'&&a.id==='emmett';if(asked&&!p.mounted){followActor(world,a,{x:p.x+12,y:p.y+7,z:p.z||0},76,dt,3);if(nearby(a,p,22))interactRival(s,pending,ctx);continue;}if(a.id==='tomas'&&!r.flags.carbineGranted){const stance=rackStance(s.horse);goal(a,stance);followActor(world,a,stance,76,dt,1);if(nearby(a,stance,1.1)){a.facing=stance.facing;grantCarbine(s,ctx);r.timers.gift=1.25;goal(a,h);}}else if(!a.mounted&&!(a.id==='ruth'&&equipmentContract(s)&&!ammunitionReady(s))&&!(a.id==='inez'&&!r.flags.lariatGranted)&&!(a.id==='emmett'&&!r.flags.sightglassGranted)){if(a.goal)followActor(world,a,a.goal,76,dt,18);else followActor(world,a,h,76,dt,25);if(r.timers.gift===0&&nearby(a,h,50))mount(s,ctx,a,h);}}
    else if(stage===11&&a.id==='inez'&&s.entities.skein.hp>0&&!r.rival.skeinRecovered){const mare=s.entities.skein;if(distance(a,mare)>50){const walker=a.mounted?h:a;followActor(world,walker,mare,a.mounted?170:100,dt,35,a.mounted?13:9);if(a.mounted)Object.assign(a,point(h));}else{dismount(s,ctx,a);mare.leading=true;mare.leaderId='inez';r.rival.skeinLeadDistance+=followActor(world,mare,a,125,dt,30,13);followActor(world,a,{x:p.x-70,y:p.y+45,z:0},95,dt,32);followActor(world,h,{x:a.x+45,y:a.y+20,z:0},125,dt,28,13);if(r.rival.skeinLeadDistance>40&&distance(mare,p)<180)r.rival.skeinRecovered=true;}continue;}else if(usesRivalTransport(s)&&stage===11&&a.id==='inez'&&r.rival.skeinRecovered&&!a.mounted){followActor(world,h,a,125,dt,25,13);if(nearby(a,h,55))mount(s,ctx,a,h);continue;}else if([2,9,10,11].includes(stage)){if(!a.mounted&&nearby(a,h,55))mount(s,ctx,a,h);if(a.mounted){const target={x:p.x+40+(i%2)*45,y:p.y-35-Math.floor(i/2)*48,z:p.z||0};followActor(world,h,target,Math.max(170,Math.hypot(p.vx||0,p.vy||0)+20),dt,36,13);Object.assign(a,point(h));a.facing=h.facing;a.vx=h.vx;a.vy=h.vy;}}
    else if(a.goal&&!a.mounted){followActor(world,a,a.goal,stage===12&&a.carrying?48:82,dt,5);if(nearby(a,a.goal,6))delete a.goal;}
    if(stage===1&&a.mounted&&p.mounted&&r.flags.carbineEquipped&&r.flags.lariatGranted&&r.flags.sightglassGranted){const target={x:p.x+40+(i%2)*45,y:p.y-35-Math.floor(i/2)*48,z:0};followActor(world,h,target,180,dt,35,13);Object.assign(a,point(h));a.facing=h.facing;}
    if([5,7].includes(stage)&&a.ammo===undefined&&!a.gunDisarmed){const capacity=a.id==='bastian'?6:7;a.ammo=capacity;a.reserve=capacity*3;a.fireTimer=1;a.weapon={id:a.id==='bastian'?ENGRAVED_REVOLVER_ID:`${a.id}-quarry-carbine`,kind:a.id==='bastian'?'revolver':'carbine',capacity,owner:a.id};a.holstered=false;}
    if([5,7].includes(stage)&&!yardOpeningPending(s)&&['tomas','ruth','bastian'].includes(a.id)){const owned=npcWeapon(s,a);if(!owned)continue;const {weapon,stock}=owned;a.fireTimer=Math.max(0,(a.fireTimer||0)-dt);const target=(stage===5?yard(s):patrol(s)).filter(living).filter(e=>distance(a,e)<550&&clearLine(world,{...a,z:(a.z||0)+30},{...e,z:(e.z||0)+28})).sort((a,b)=>distance(p,a)-distance(p,b))[0];if(target&&a.fireTimer===0){if(stock.ammo>0){stock.ammo--;a.aiming=true;a.shotTimer=.3;launchBullet(s,a,target,'ally',22);emit(s,ctx,'shoot',target,weapon.id,a.id,a);a.fireTimer=1.2;}else if(stock.reserve>0){const n=Math.min(weapon.capacity-stock.ammo,stock.reserve);stock.ammo+=n;stock.reserve-=n;a.reloadTimer=2.6;a.fireTimer=2.6;emit(s,ctx,'reload',a,weapon.id,a.id,a);}}}
  }
}
function enemiesStep(s,dt,ctx){const r=record(s),world=WORLD(s,ctx),stage=r.mission.stage;if(yardOpeningPending(s))return;for(const e of [...yard(s),...patrol(s)]){if(!living(e))continue;e.shotTimer=Math.max(0,(e.shotTimer||0)-dt);e.reloadTimer=Math.max(0,(e.reloadTimer||0)-dt);if(e.id===WEAPON_THIEF_ID&&['disarming','pursuing','grappling','dropped'].includes(r.rival.weaponCustody?.phase))continue;
    if(e.wave==='reserve'&&stage===7&&r.timers.patrol<12)continue;if(e.wave!=='yard'&&[6,7].includes(stage)){const route=W.patrolRoutes[e.wave]||W.patrolRoutes.east,node=route[e.routeIndex||0];if(node){followActor(world,e,node,85,dt,9);if(nearby(e,node,12)){e.routeIndex=(e.routeIndex||0)+1;e.route=[];}}if(stage===6){if(distance(e,s.player)<420){r.flags.patrolWarned=true;ctx.notice(s,'Emmett: “The returning hoofprints were real. Scouts in both tree lanes are moving toward the fight.”');}continue;}}
    if(!e.active||![5,7].includes(stage))continue;const possible=[s.player,...RIVAL_PARTY.filter(id=>!['inez','emmett'].includes(id)).map(id=>s.entities[id])],target=possible.filter(a=>a.hp>0&&distance(e,a)<650).sort((a,b)=>distance(e,a)-distance(e,b))[0];if(!target)continue;
    if(e.hp<18&&['runner','surrender-capable'].includes(e.role)){e.surrendered=true;e.active=false;r.rival.surrenderCount++;continue;}
    if(['flanker','pusher','pushing-rifleman','runner','disarm-grappler'].includes(e.role)&&distance(e,target)>150){const side=e.id.length%2?1:-1;followActor(world,e,{x:target.x+side*95,y:target.y-45,z:e.z||0},e.role==='flanker'?62:38,dt,60);}
    const owned=npcWeapon(s,e);if(!owned)continue;const {weapon,stock}=owned;e.fireTimer=Math.max(0,(e.fireTimer||0)-dt);if(e.fireTimer===0&&clearLine(world,{...e,z:(e.z||0)+32},{...target,z:(target.z||0)+28})){if(stock.ammo>0){stock.ammo--;e.holstered=false;e.aiming=true;e.shotTimer=.3;launchBullet(s,e,target,'enemy',8);emit(s,ctx,'shoot',target,weapon.id,e.id,e);e.fireTimer=1.8+(e.id.length%3)*.22;}else if(stock.reserve>0){const n=Math.min(weapon.capacity-stock.ammo,stock.reserve);stock.ammo+=n;stock.reserve-=n;e.reloadTimer=3;e.fireTimer=3;emit(s,ctx,'reload',e,weapon.id,e.id,e);}}
  }}
function retrievalStep(s,dt,ctx){
  const r=record(s),f=r.flags,world=WORLD(s,ctx);
  stepPhysicalSearchWork(s,dt,ctx);
  for(let i=0;i<RIVAL_MOUNTS.length;i++){
    const h=s.entities[RIVAL_MOUNTS[i]],a=s.entities[RIVAL_PARTY[i]],index=h.rivalRampIndex||0,node=W.horseRamp[index];
    if(node){followActor(world,h,node,125,dt,8,13);if(distance(h,node)<12){h.rivalRampIndex=index+1;h.route=[];}}
    else{const parking={x:W.readyCover.x+100+(i%2)*70,y:W.readyCover.y+75+Math.floor(i/2)*65,z:0};followActor(world,h,parking,125,dt,10,13);}
    if(a.mounted){Object.assign(a,point(h));a.facing=h.facing;if(!node&&distance(h,W.readyCover)<400){dismount(s,ctx,a);goal(a,a.id==='emmett'?W.plans:{x:h.x+25,y:h.y,z:0});}}
  }
  if(!s.player.mounted){followActor(world,s.horse,W.readyCover,125,dt,15,13);}
  f.horsesRetrieved=RIVAL_MOUNTS.every(id=>(s.entities[id].rivalRampIndex||0)>=W.horseRamp.length&&distance(s.entities[id],W.readyCover)<400)&&distance(s.horse,W.readyCover)<400;
  if(!physicalSearchContract(s)&&f.plansRead&&!f.plansDelivered&&nearby(s.entities.bastian,s.entities.tomas,55)){for(const id of ['route-diagram','seizure-list']){const o=tool(s,id);o.owner='tomas';o.location={type:'carried',targetId:'tomas'};}f.plansDelivered=true;emit(s,ctx,'give-plans',s.entities.tomas,'route-diagram','bastian',s.entities.bastian);}
  if(f.crateTaken&&f.plansDelivered&&f.horsesRetrieved){for(let i=0;i<RIVAL_PARTY.length;i++){
    const a=s.entities[RIVAL_PARTY[i]],h=s.entities[RIVAL_MOUNTS[i]];
    if(a.mounted||a.actionTimer>0)continue;goal(a,h);
    if(nearby(a,h,55)){
      if(a.id==='ruth'&&tool(s,'charge-crate')?.location.type==='carried'){tool(s,'charge-crate').location={type:'saddle',targetId:'plover'};a.actionTimer=1.55;emit(s,ctx,'load-crate',h,'charge-crate','ruth',a);continue;}
      mount(s,ctx,a,h);
    }
  }}
}
function reconActorsStep(s,dt,ctx,input={}){
  const r=record(s),world=WORLD(s,ctx),calder=s.entities.calder,grout=s.entities.grout,levi=s.entities.levi,skein=s.entities.skein;
  if(!r.scope.observed.calder)return;
  if(r.rival.reconEventPhase<2){
    followActor(world,calder,{x:levi.x-16,y:levi.y,z:levi.z||0},85,dt,3);
    if(distance(calder,levi)>24)return;
    if(requiresReconWitness(s)&&!visibleReconActors(s,input,['calder','levi']))return;
    r.rival.reconAge+=dt;
    if(r.rival.reconAge>.35&&r.rival.reconEventPhase===0){r.objects['levi-debt-card']={id:'levi-debt-card',kind:'debt-card',owner:'levi',torn:true,location:{type:'carried',targetId:'levi'}};r.rival.reconEventPhase=1;emit(s,ctx,'card-tear',levi,'levi-debt-card','calder',calder);recordReconEvent(s,'card',input,ctx);}
    if(r.rival.reconAge>1.1&&r.rival.reconEventPhase===1){levi.hp=Math.max(20,levi.hp-6);levi.bruised=true;r.captivity.injury++;r.rival.reconEventPhase=2;emit(s,ctx,'strike',levi,'levi','calder',calder);recordReconEvent(s,'strike',input,ctx);}
    return;
  }
  if(!calder.departed){
    if(!calder.mounted){followActor(world,calder,grout,85,dt,25);if(nearby(calder,grout,55)&&(!requiresReconWitness(s)||visibleReconActors(s,input,['calder','grout']))){if(mount(s,ctx,calder,grout)&&requiresReconWitness(s))initializeReconWitness(s).departureOrigin=point(calder);}}
    else{
      const witnessed=!requiresReconWitness(s)||witnessedReconEvent(s,'departure');
      if(witnessed||visibleReconActors(s,input,['calder','grout'])){
        const node=W.calderEscape[r.rival.calderIndex];
        if(node){
          followActor(world,grout,node,190,dt,8,13);Object.assign(calder,point(grout));calder.vx=grout.vx;calder.vy=grout.vy;
          if(requiresReconWitness(s)&&distance(calder,initializeReconWitness(s).departureOrigin)>=40)recordReconEvent(s,'departure',input,ctx);
          if(distance(grout,node)<12){r.rival.calderIndex++;grout.route=[];}
        }else{calder.departed=true;grout.departed=true;}
      }
    }
  }
  if(!r.flags.chaseStarted&&r.rival.dismissalIndex<W.recon.leviDismissal.length){
    if(!levi.mounted){followActor(world,levi,skein,80,dt,22);if(nearby(levi,skein,55)&&(!requiresReconWitness(s)||visibleReconActors(s,input,['levi','skein']))){if(mount(s,ctx,levi,skein)&&requiresReconWitness(s))initializeReconWitness(s).dismissalOrigin=point(levi);}}
    else if(!requiresReconWitness(s)||witnessedReconEvent(s,'dismissal')||visibleReconActors(s,input,['levi','skein'])){
      const node=W.recon.leviDismissal[r.rival.dismissalIndex];followActor(world,skein,node,130,dt,8,13);Object.assign(levi,point(skein));levi.vx=skein.vx;levi.vy=skein.vy;
      if(requiresReconWitness(s)&&distance(levi,initializeReconWitness(s).dismissalOrigin)>=40)recordReconEvent(s,'dismissal',input,ctx);
      if(distance(skein,node)<12){r.rival.dismissalIndex++;skein.route=[];}
    }
  }
}
function capturedStep(s,dt,ctx){const r=record(s),levi=s.entities.levi,h=s.entities.skein,p=s.player,world=WORLD(s,ctx),stage=r.mission.stage;
  if(stage===10){r.timers.chase+=dt;const rope=r.rope;if(rope.phase==='flying'){const start=point(rope),end={x:rope.x+rope.vx*dt,y:rope.y+rope.vy*dt,z:rope.z+(rope.vz||0)*dt};if(!clearLine(world,start,end,1,true)){rope.phase='idle';rope.misses++;}else{const dx=end.x-start.x,dy=end.y-start.y,len=dx*dx+dy*dy,u=clamp(len?((levi.x-start.x)*dx+(levi.y-start.y)*dy)/len:0,0,1);if(distance(levi,{x:start.x+dx*u,y:start.y+dy*u})<18&&start.z+(end.z-start.z)*u>=(levi.z||0)+(levi.mounted?40:5)&&start.z+(end.z-start.z)*u<=(levi.z||0)+(levi.mounted?88:53)){rope.phase='taut';rope.targetId='levi';rope.tension=.5;r.captivity.state='roped';if(levi.mounted){levi.mounted=false;Object.assign(levi,{x:h.x+24,y:h.y,z:0});h.vx=0;h.vy=0;h.route=[];delete h.routeTarget;}emit(s,ctx,'lariat-catch',levi,'levi');}Object.assign(rope,end);rope.ttl-=dt;if(rope.ttl<=0&&rope.phase==='flying'){rope.phase='idle';rope.misses++;}}}
    if(rope.phase==='taut'){const length=distance(p,levi);rope.tension=clamp((length-12)/130,0,1);if(length>165||length<8||!clearLine(world,p,levi,1,false)){rope.phase='idle';rope.targetId=null;r.captivity.state='fleeing';ctx.notice(s,'The rope went slack or struck cover. Levi can run again; recover the throw.');}}
    if(usesRivalTransport(s)&&needsSkeinFootPursuit(s)){if(dismount(s,ctx,levi)){h.vx=0;h.vy=0;h.route=[];delete h.routeTarget;recordSkeinFootPursuit(s,ctx);if(h.hp<=0)r.captivity.injury++;}}else if(!usesRivalTransport(s)&&h.hp<=0&&levi.mounted){levi.mounted=false;Object.assign(levi,{x:h.x+25,y:h.y,z:0});r.captivity.injury++;}
    if(r.captivity.state==='fleeing'){const node=W.chase.route[r.rival.leviIndex];if(node){const actor=levi.mounted?h:levi;followActor(world,actor,node,levi.mounted?175:92,dt,8,levi.mounted?13:9);if(levi.mounted){Object.assign(levi,point(h));levi.vx=h.vx;levi.vy=h.vy;}if(nearby(actor,node,12)){r.rival.leviIndex++;actor.route=[];}}else ctx.fail(s,'Levi escaped beyond the two lane forks. Retry the physical pursuit.');}
    if(r.timers.bind>0){if(!nearby(p,levi,38)||p.mounted){r.timers.bind=0;ctx.notice(s,'Move beside Levi on foot before completing the binding.');}else{r.timers.bind=Math.max(0,r.timers.bind-dt);if(!r.timers.bind){levi.bound=true;levi.mounted=false;r.flags.bound=true;r.captivity.state='bound';r.performance.quickCapture=r.timers.chase<55;r.rope.phase='idle';r.rope.targetId=null;advance(s,ctx,11,'levi-bound','A living, separately identified captive physically bound');}}}}
  if(stage===12&&r.flags.delivered&&!r.flags.held){const helper=s.entities[r.captivity.helperId||'ruth'],hob=s.entities.hob,node=W.camp.helperRoute[r.rival.helperIndex];if(hob?.goal){followActor(world,hob,hob.goal,78,dt,4);if(nearby(hob,hob.goal,5))delete hob.goal;}if(r.rival.helperIndex===1&&helper.id==='ruth'){if(!nearby(hob,helper,55)){goal(hob,helper);return;}if(ctx.setAttachment(s,'levi',{type:'carried',targetId:'hob'})){r.captivity.helperId='hob';emit(s,ctx,'handoff',hob,'levi','ruth',helper,'ruth');}return;}if(node){followActor(world,helper,node,48,dt,3,11);if(nearby(helper,node,6)){r.rival.helperIndex++;helper.route=[];}}else if(ctx.setAttachment(s,'levi',{type:'rest',targetId:W.camp.holding.id,regionId:'snowbound'})){r.flags.held=true;r.captivity.state='held';r.captivity.helperId=null;emit(s,ctx,'holding-transfer',W.camp.holding,'levi',helper.id,helper);}}
  if(stage===11){if(h.hp>0&&r.rival.skeinRecovered)followActor(world,h,{x:s.entities.inez.x-55,y:s.entities.inez.y+25,z:0},(usesRivalTransport(s)&&h.hp<=65?115:185),dt,35,13);r.rival.weatherBurden+=dt*(s.weather==='snow'?1:.4);if(usesRivalTransport(s))stepRivalTransport(s,dt,ctx,world);else if(levi.attachment?.type==='passenger'&&!levi.attachment.strap&&Math.hypot(p.vx||0,p.vy||0)>190)ctx.fail(s,'The unstrapped captive was put at risk by the fast ride. Secure him before leaving.');}
}
export function stepRival(s,dt,input={},ctx){const r=record(s);if(!active(s)||!r||!Number.isFinite(dt))return s;dt=clamp(dt,0,.1);if(!dt)return s;ensureRivalCast(s,ctx);s.notices=s.notices.map(n=>({...n,time:n.time-dt})).filter(n=>n.time>0);if(s.dialog||s.failure)return s;const world=WORLD(s,ctx),p=s.player,f=r.flags,stage=r.mission.stage;
  s.elapsed+=dt;s.time+=dt/80;if(s.time>=24){s.time-=24;s.day++;}if(!r.mission.completed)r.timers.elapsed+=dt;for(const key of ['gift','shot'])r.timers[key]=Math.max(0,r.timers[key]-dt);p.shotTimer=Math.max(0,p.shotTimer-dt);p.blockTimer=Math.max(0,p.blockTimer-dt);
  if(p.reloadTimer>0){p.reloadTimer=Math.max(0,p.reloadTimer-dt);if(!p.reloadTimer){const w=s.weapons[p.reloadWeaponId||p.equippedWeaponId];if(w){const n=Math.min(w.capacity-w.ammo,w.reserve);w.ammo+=n;w.reserve-=n;}delete p.reloadWeaponId;}}
  if(r.scope.raised&&r.scope.camera){r.scope.camera.x=clamp(r.scope.camera.x+(Number(input.mx)||0)*180*dt,0,W.width);r.scope.camera.y=clamp(r.scope.camera.y+(Number(input.my)||0)*180*dt,0,W.height);}
  let mx=clamp(Number(input.mx)||0,-1,1),my=clamp(Number(input.my)||0,-1,1),len=Math.hypot(mx,my);if(r.scope.raised){mx=0;my=0;}if(len>1){mx/=len;my/=len;}if(input.crouch!==undefined)p.crouch=!!input.crouch&&!p.mounted;const sprint=!!input.sprint&&!p.carrying&&(p.mounted?s.horse.stamina:p.stamina)>1,actor=p.mounted?s.horse:p,speed=(p.mounted?sprint?230:160:p.carrying?50:p.crouch?60:sprint?160:105)*(r.scope.raised?.35:1)*(p.mounted&&(usesRivalTransport(s)?rivalPassenger(s):f.loaded)?.86:1)*rivalTransportPace(s),before=point(actor);moveActor(world,actor,mx*speed*dt,my*speed*dt,p.mounted?13:p.carrying?11:9);actor.vx=(actor.x-before.x)/dt;actor.vy=(actor.y-before.y)/dt;if(Math.hypot(actor.vx,actor.vy)>1)actor.facing=Math.atan2(my,mx);if(p.mounted){s.horse.following=false;Object.assign(p,point(actor));p.vx=actor.vx;p.vy=actor.vy;p.facing=actor.facing;}s.stats.distance+=distance(before,actor);p.stamina=clamp(p.stamina+(sprint?-8:p.carrying?-1:5)*dt,0,100);s.horse.stamina=clamp(s.horse.stamina+(p.mounted&&sprint?-8:4)*dt,0,100);
  stepEquipmentWork(s,dt,ctx);
  if(!p.mounted&&stage!==8&&s.horse.following)followActor(world,s.horse,p,155,dt,36,13);focusStep(s,dt,input,ctx);const combatDt=r.focus.active?dt*.3:dt;companionsStep(s,combatDt,ctx);Narrative.stepRivalNarrative(s,dt,ctx,world);if(!yardOpeningPending(s))advanceWeaponCustody(s,combatDt,ctx,world);if(stage===7)r.timers.patrol+=combatDt;enemiesStep(s,combatDt,ctx);projectileStep(s,combatDt,ctx);scopeStep(s,dt,input,ctx);capturedStep(s,dt,ctx);advanceQuestioning(s,dt,ctx);
  if(field(s)){const ground=W.elevationZones.find(zone=>insideRect(p,zone))?.z||0;p.z=ground;if(p.mounted)s.horse.z=ground;for(const a of [...RIVAL_PARTY,...Object.values(s.entities).filter(a=>(a.kind==='horse'||a.category==='mount')&&a.regionId===s.region).map(a=>a.id)].map(id=>s.entities[id]))if(a&&!a.attachment){a.z=W.elevationZones.find(zone=>insideRect(a,zone))?.z||0;}}
  if(stage===2){const node=W.trail[r.rival.trailIndex];if(node&&distance(p,node)<85&&partyNear(s,200))r.rival.trailIndex++;}
  if(stage>=3&&stage<=9)reconActorsStep(s,dt,ctx,input);
  if(stage===4){const node=W.descent[r.rival.descentIndex];if(node){if(distance(p,node)<65){p.z=node.z||0;r.rival.descentIndex++;goal(s.entities.tomas,W.descent[Math.min(r.rival.descentIndex,W.descent.length-1)]);}}if(r.rival.descentIndex>=W.descent.length&&nearby(p,W.readyCover,65)&&['tomas','ruth','bastian'].every(id=>nearby(s.entities[id],W.yardCover[id],110)))f.approachReady=true;for(const e of yard(s).filter(living))if(distance(p,e)<150&&(!p.crouch||sprint)&&clearLine(world,{...e,z:(e.z||0)+35},{...p,z:(p.z||0)+30}))ctx.fail(s,'A watcher saw the noisy descent before the party reached its first-shot cover.');}
  if(stage===5&&yard(s).every(e=>!living(e))){f.yardSafe=true;advance(s,ctx,6,'yard-cleared','Finite traverser defenders resolved; individual pockets remain');}
  if(stage===7&&patrol(s).every(e=>!living(e))){f.patrolSafe=true;for(const who of ['inez','emmett']){const a=s.entities[who],h=s.entities[a.mountId];delete a.goal;if(nearby(a,h,58))mount(s,ctx,a,h);}for(const who of ['inez','emmett']){const h=s.entities[s.entities[who].mountId];goal(h,W.yardCover[who]||W.readyCover);}advance(s,ctx,8,'patrols-cleared','Both wooded approaches and reserve resolved before the three searches');}
  if(stage===8)retrievalStep(s,dt,ctx);
  if(stage===9){const node=W.convoyRoute[r.rival.convoyIndex];if(node&&nearby(p,node,85)&&partyNear(s,210))r.rival.convoyIndex++;if(r.rival.convoyIndex>=W.convoyRoute.length&&nearby(p,W.chase.trigger,100)&&Narrative.convoyNarrativeReady(s)){const levi=s.entities.levi,h=s.entities.skein;levi.mounted=h.hp>0;levi.mountId='skein';moveRegion(s,h,W.id,W.chase.route[0]);moveRegion(s,levi,W.id,{x:h.x,y:h.y,z:0});r.captivity.state='fleeing';f.chaseStarted=true;advance(s,ctx,10,'pulley-creek-flight','Levi recognized the returning convoy and physically began to flee');ctx.notice(s,'Levi is running on Skein. Equip the lariat, pursue a clear lane, keep tension, then dismount and bind.');}}
  if(stage===11&&(!usesRivalTransport(s)||rivalPassenger(s)&&s.entities.levi.attachment.strap)){const node=W.returnRoute[r.rival.returnIndex];if(node&&nearby(p,node,90)&&partyNear(s,210))r.rival.returnIndex++;}
  const assignedWork=stage>=3&&stage<=8&&insideRect(p,{x:700,y:450,w:1800,h:1350});const apart=stage>=2&&stage<=11&&!assignedWork&&RIVAL_PARTY.some(id=>distance(p,s.entities[id])>720);r.timers.abandonment=apart?r.timers.abandonment+dt:0;if(r.timers.abandonment>35)ctx.fail(s,'The quarry expedition was abandoned. All six people and their mounts must return together.');
  if(['mara','levi',...RIVAL_PARTY,...RIVAL_MOUNTS,s.horse.id].some(id=>s.entities[id]?.hp<=0))ctx.fail(s,'A required person or expedition mount died during the quarry operation.');r.performance.fifteenHeadshots=r.performance.headshots>=15;r.performance.noHealingItems=r.performance.healingUses===0;objective(s);return s;
}
export function actionRival(s,id,ctx){if(!active(s)||s.dialog||s.failure)return s;const p=s.player;if(id.startsWith('equip:')){const request=id.slice(6),w=s.weapons[request]||Object.values(s.weapons).find(w=>w.kind===request);if(w)equip(s,ctx,w.id);}else if(id==='holster'){p.holstered=true;p.armed=false;cancelRivalFocus(s);emit(s,ctx,'holster',p,p.equippedWeaponId);}else if(id==='draw'){p.holstered=false;p.armed=true;emit(s,ctx,'draw',p,p.equippedWeaponId);}else if(id==='scope:zoom-in')record(s).scope.zoom=clamp(record(s).scope.zoom+.25,1,3);else if(id==='scope:zoom-out')record(s).scope.zoom=clamp(record(s).scope.zoom-.25,1,3);else if(id==='cancel-rope'){const r=record(s);if(r.mission.stage===10&&['flying','taut'].includes(r.rope.phase)&&['fleeing','roped'].includes(r.captivity.state)){r.rope.phase='idle';r.rope.targetId=null;r.captivity.state='fleeing';}}else if(id==='crouch')p.crouch=true;else if(id==='stand')p.crouch=false;else if(id==='block')p.blockTimer=.8;else{const offered=getRivalInteractions(s,ctx).find(a=>a.id===id);if(offered)interactRival(s,id,ctx);}return s;}
export function whistleRival(s,ctx){if(!active(s)||s.dialog||s.failure||s.player.mounted)return s;s.horse.hitched=false;s.horse.following=true;goal(s.horse,s.player);ctx.notice(s,'Copper is coming to the actual call.');return s;}
export function useRivalItem(s,id,ctx){
  if(s.dialog||s.failure||!s.inventory[id])return s;
  const p=s.player,r=record(s),healing=()=>{if(active(s)&&!r.mission.completed){r.performance.healingUses++;r.performance.noHealingItems=false;}};
  if(id==='tonic'){s.inventory[id]--;p.hp=Math.min(100,p.hp+55);healing();}
  else if(id==='coffee'){s.inventory[id]--;p.focus=Math.min(100,p.focus+50);}
  else if(id==='bandages'&&p.hp<100){s.inventory[id]--;p.hp=Math.min(100,p.hp+35);healing();emit(s,ctx,'bandage',p,id);}
  else if(['meat','cookedMeat','broth','tableBroth'].includes(id)){s.inventory[id]--;p.hp=Math.min(100,p.hp+20);p.stamina=Math.min(100,p.stamina+25);healing();}
  else if(id==='oats'&&nearby(p,s.horse,80)){s.inventory[id]--;s.horse.stamina=100;s.horse.bond=Math.min(4,s.horse.bond+.05);}
  return s;
}
function validateYardOpening(s){
  const r=record(s),opening=r.rival.yardOpening;
  // Earlier public v4 Saves predate this receipt and keep their existing
  // encounter history rather than acquiring an invented signal projectile.
  if(opening===undefined)return true;
  if(!object(opening)||opening.schema!==1||Object.keys(opening).length!==5||r.choices.firstShot!=='player'||r.mission.stage<5||!Number.isInteger(opening.shotsBefore)||opening.shotsBefore<0||opening.shotsBefore>r.performance.shots||!Number.isFinite(opening.startedAt)||opening.startedAt<0||opening.startedAt>s.elapsed)return false;
  if(opening.firedAt===null)return opening.shotSerial===null&&r.mission.stage===5&&r.performance.shots===opening.shotsBefore&&yard(s).every(e=>!e.active);
  return Number.isFinite(opening.firedAt)&&opening.firedAt>=opening.startedAt&&opening.firedAt<=s.elapsed&&opening.shotSerial===opening.shotsBefore+1&&r.rival.shots[opening.shotSerial-1]?.serial===opening.shotSerial;
}
export function validateRivalRecord(s){
  if(usesRivalContinuation(s)&&s.campaign.missions[RIVAL_ID].rival.continuation?.initializedAt!==null){if(!validateRivalContinuation(s))return false;s=rivalHistoricalValidationState(s);}
  const r=s?.campaign?.missions?.[RIVAL_ID];if(!object(r))return false;const template=createRivalRecord(),m=r.mission,integer=(v,max=100000)=>Number.isInteger(v)&&v>=0&&v<=max;
  if(!object(m)||m.id!==RIVAL_ID||m.name!=='The Names They Took'||m.stageCount!==14||!integer(m.stage,13)||typeof m.completed!=='boolean'||m.rewardPaid!==m.completed||!['locked','unstarted','active','completed'].includes(r.status)||m.completed!==(r.status==='completed')||r.sourceRequirementId!==template.sourceRequirementId||!integer(r.retryCount)||r.status==='active'&&!active(s)||active(s)&&!['active','completed'].includes(r.status))return false;
  if(r.status!=='locked'&&!s.campaign.missions[RESCUE].mission.completed)return false;
  for(const section of ['flags','timers','performance'])if(!object(r[section])||Object.keys(r[section]).length!==Object.keys(template[section]).length||Object.entries(template[section]).some(([key,v])=>typeof v==='boolean'?typeof r[section][key]!=='boolean':!Number.isFinite(r[section][key])||r[section][key]<0||r[section][key]>1e8))return false;
  if(!object(r.choices)||![null,'player','tomas'].includes(r.choices.firstShot)||![null,'hold','advance'].includes(r.choices.tactic)||![null,'assurance','threaten'].includes(r.choices.assurance)||![null,'care','deprive'].includes(r.choices.care)||![null,'hunt-first','rival-first'].includes(r.choices.order)||!object(r.transactions)||!object(r.objects)||!object(r.rival)||r.rival.captiveId!=='levi'||!object(r.focus)||!object(r.scope)||!object(r.captivity)||!object(r.rope))return false;
  if(Object.entries(r.transactions).some(([id,t])=>!id.startsWith(`${RIVAL_ID}:`)||!object(t)||t.completed!==true)||Object.keys(r.objects).some(id=>!['sightglass','cap-tin','charge-crate','route-diagram','seizure-list','levi-debt-card','quarry-sealed-charge-1','quarry-sealed-charge-2','quarry-sealed-charge-3','quarry-sealed-charge-4',...QUARRY_POCKET_OBJECTS.map(paper=>paper.id)].includes(id)))return false;
  for(const[id,o]of Object.entries(r.objects)){if(!object(o)||o.id!==id||!object(o.location)||!['carried','station','saddle','crate'].includes(o.location.type)||!['mara','ruth','bastian','tomas','levi','quarry-store'].includes(o.owner)||o.location.type==='carried'&&(!s.entities[o.location.targetId]||o.owner!==o.location.targetId))return false;if(o.location.type==='crate'&&(o.kind!=='sealed-charge'||o.location.targetId!=='charge-crate'||!r.objects['charge-crate']?.chargeIds.includes(id)))return false;if(o.kind==='sealed-charge'&&(o.sealed!==true||o.inspected!==true))return false;if(o.location.type==='saddle'&&o.location.targetId!=='plover')return false;if(id==='charge-crate'&&(o.count!==4||!Array.isArray(o.chargeIds)||o.chargeIds.length!==4||new Set(o.chargeIds).size!==4||o.chargeIds.some((id,n)=>id!==`quarry-sealed-charge-${n+1}`)||o.kind!=='sealed-quarry-charges'))return false;}
  for(const paper of QUARRY_POCKET_OBJECTS){
    const item=r.objects[paper.id];if(!item)continue;
    const transferred=r.rival.loot?.[paper.sourceEntityId]?.transferredObjectIds;
    if(item.kind!==paper.kind||item.sourceEntityId!==paper.sourceEntityId||item.owner!=='mara'||item.location.type!=='carried'||item.location.targetId!=='mara'||!Array.isArray(transferred)||!transferred.includes(paper.id)||!r.transactions[`${RIVAL_ID}:loot:${paper.sourceEntityId}`])return false;
  }
  for(const [sourceId,stock]of Object.entries(r.rival.loot||{})){
    if(stock.transferredObjectIds===undefined)continue; // Preserve pre-fix v4 public histories without inventing belongings.
    const expected=QUARRY_POCKET_OBJECTS.filter(paper=>paper.sourceEntityId===sourceId).map(paper=>paper.id);
    if(!Array.isArray(stock.transferredObjectIds)||stock.transferredObjectIds.length!==expected.length||new Set(stock.transferredObjectIds).size!==expected.length||stock.transferredObjectIds.some(id=>!expected.includes(id)||!r.objects[id])||!r.transactions[`${RIVAL_ID}:loot:${sourceId}`]||stock.objects?.length||stock.keepsake!==null)return false;
  }
  const f=r.flags,crate=r.objects['charge-crate'];
  if(Boolean(crate)!==f.chargeInspected||f.chargePassed&&!f.chargeInspected||f.crateTaken&&!f.chargeRepacked)return false;
  if(crate){
    if(crate.owner!==(f.crateTaken?'ruth':'quarry-store'))return false;
    for(const id of crate.chargeIds){
      const child=r.objects[id];
      if(!child||child.kind!=='sealed-charge')return false;
      const passed=id==='quarry-sealed-charge-1'&&f.chargePassed&&!f.chargeRepacked;
      if(passed){
        if(child.owner!=='ruth'||child.location.type!=='carried'||child.location.targetId!=='ruth')return false;
      }else if(child.owner!==crate.owner||child.location.type!=='crate'||child.location.targetId!==crate.id)return false;
    }
  }else if(Object.values(r.objects).some(o=>o.kind==='sealed-charge'))return false;
  const gates=[[1,f.accepted],[2,f.entered&&f.carbineInspected&&f.carbineEquipped&&f.lariatGranted&&f.sightglassGranted],[3,f.groovesRead&&f.hoovesRead&&f.ridgeBriefed],[4,f.reconComplete],[5,f.approachReady&&f.focusTaught],[6,f.yardSafe],[7,f.pocketSearched&&f.patrolWarned&&r.choices.tactic!==null],[8,f.patrolSafe],[9,f.crateTaken&&f.plansRead&&f.plansDelivered&&f.horsesRetrieved&&f.convoyDeparted],[10,f.chaseStarted],[11,f.bound],[12,f.campReturned&&f.loaded&&f.strapped],[13,f.delivered&&f.held&&f.questioned&&r.choices.care!==null]];
  if(gates.some(([stage,gate])=>m.stage>=stage&&!gate)||m.completed&&(!f.chargesStored||!f.accounted||!r.aftermath||r.aftermath.captiveId!=='levi'))return false;
  for(const[key,transaction]of[['carbineGranted','grant:tern'],['lariatGranted','grant:lariat'],['sightglassGranted','grant:sightglass'],['chargesStored','deposit:charges'],['accounted','complete:account']])if(f[key]!==!!r.transactions[`${RIVAL_ID}:${transaction}`])return false;
  if(f.chargeInspected&&(!r.objects['charge-crate']?.chargeIds.every(id=>r.objects[id]?.kind==='sealed-charge'))||f.carbineGranted&&!s.weapons[RIVAL_CARBINE.id]||f.lariatGranted&&!s.weapons['working-lariat']||f.sightglassGranted&&!r.objects.sightglass||f.chargeRepacked&&(!f.chargePassed||!f.chargeInspected)||f.bound&&!s.entities.levi.bound)return false;
  if(!Array.isArray(r.focus.marks)||!Array.isArray(r.focus.queue)||r.focus.marks.length>7||r.focus.queue.length>7||typeof r.focus.unlocked!=='boolean'||typeof r.focus.active!=='boolean'||!integer(r.focus.activation)||[...r.focus.marks,...r.focus.queue].some(a=>!s.entities[a.targetId]||!Number.isFinite(a.x+a.y+a.z)||a.weaponId!==RIVAL_CARBINE.id&&a.weaponId!=='mara-revolver'&&a.weaponId!=='coach-gun'&&a.weaponId!==ENGRAVED_REVOLVER_ID||a.weaponId===ENGRAVED_REVOLVER_ID&&(!s.weapons[ENGRAVED_REVOLVER_ID]||s.weapons[ENGRAVED_REVOLVER_ID].owner!=='mara')))return false;
  if(!['unseen','fleeing','roped','tackled','bound','carried','loaded','held'].includes(r.captivity.state)||!['idle','flying','taut'].includes(r.rope.phase)||!Number.isFinite(r.rope.x+r.rope.y+r.rope.z+r.rope.tension)||r.rope.tension<0||r.rope.tension>1)return false;
  if(r.status==='locked'&&(m.stage!==0||Object.values(f).some(Boolean)||Object.keys(r.transactions).length||Object.keys(r.objects).length))return false;
  if(!Array.isArray(r.rival.shots)||r.rival.shots.length!==r.performance.shots||r.rival.shots.length>10000||r.rival.shots.some((shot,n)=>shot.serial!==n+1||!s.weapons[shot.weaponId]&&!(shot.weaponId===ENGRAVED_REVOLVER_ID&&r.rival.weaponCustody?.createdAt!==null&&r.rival.weaponCustody?.createdAt!==undefined)||!Number.isFinite(shot.aim?.x+shot.aim?.y+shot.aim?.z)||shot.impact&&(!s.entities[shot.impact.targetId]||typeof shot.impact.head!=='boolean'||typeof shot.impact.kill!=='boolean')))return false;
  const hits=r.rival.shots.filter(shot=>shot.impact),kills=hits.filter(shot=>shot.impact.kill);
  if(r.performance.hits!==hits.length||r.performance.kills!==kills.length||r.performance.headshots!==kills.filter(shot=>shot.impact.head).length||r.performance.fifteenHeadshots!==(r.performance.headshots>=15)||r.performance.noHealingItems!==(r.performance.healingUses===0))return false;
  const activations=new Map();for(const shot of kills)if(shot.impact.activation!==null&&shot.impact.activation!==undefined){const set=activations.get(shot.impact.activation)||new Set();set.add(shot.impact.targetId);activations.set(shot.impact.activation,set);}
  if(r.performance.threeFocusKills!==[...activations.values()].some(set=>set.size>=3)||r.performance.quickCapture&&!f.bound||r.performance.underTime&&!m.completed)return false;
  if(!Array.isArray(r.rival.observations)||r.rival.observations.length>5||Object.entries(r.scope.observed).some(([id,seen])=>seen!==r.rival.observations.some(entry=>entry.id===id&&Number.isFinite(entry.at)&&entry.at<=s.elapsed)))return false;
  const stations=new Set([...W.props,...W.camp.props].map(p=>p.id));
  if(Object.values(r.objects).some(o=>o.location.type==='station'&&!stations.has(o.location.targetId)))return false;
  const validTransactions=[...HOLDING_TRANSACTION_KEYS,...QUESTIONING_TRANSACTION_KEYS,...WEAPON_CUSTODY_TRANSACTIONS.map(key=>`weapon:${key}`),...PHYSICAL_SEARCH_TRANSACTION_KEYS,EQUIPMENT_TRANSACTION_KEY,'grant:tern','grant:lariat','grant:sightglass','care:levi','deposit:charges','complete:account','skein:killed','skein:wounded',...RIVAL_ENEMIES.map(e=>`loot:${e.id}`),'loot:pavel'];
  if(Object.keys(r.transactions).some(key=>!validTransactions.includes(key.slice(RIVAL_ID.length+1))))return false;
  if(r.status==='locked'||r.status==='unstarted'){if(r.performance.shots||r.performance.hits||r.performance.kills||r.performance.headshots||r.performance.healingUses||r.focus.unlocked||r.scope.raised||r.scope.observed.calder||Object.keys(r.transactions).length)return false;}
  if(r.status!=='locked'){
    const levi=s.entities.levi;if(!levi||Boolean(levi.bound)!==f.bound||!f.bound&&levi.attachment||!f.chaseStarted&&r.captivity.state!=='unseen'||f.held&&(levi.attachment?.type!=='rest'||levi.attachment.targetId!==W.camp.holding.id))return false;
    if(r.rope.targetId!==null&&r.rope.targetId!=='levi'||r.rope.phase==='taut'&&(r.rope.targetId!=='levi'||r.captivity.state!=='roped'))return false;
    if(typeof r.scope.raised!=='boolean'||!Number.isFinite(r.scope.zoom)||r.scope.zoom<1||r.scope.zoom>3||Object.keys(r.scope.observed).length!==5||Object.values(r.scope.observed).some(v=>typeof v!=='boolean'))return false;
    const limits={trailIndex:W.trail.length,descentIndex:W.descent.length,convoyIndex:W.convoyRoute.length,returnIndex:W.returnRoute.length,leviIndex:W.chase.route.length,calderIndex:W.calderEscape.length,helperIndex:W.camp.helperRoute.length};
    if(Object.entries(limits).some(([key,max])=>!integer(r.rival[key],max)))return false;
    for(const e of RIVAL_ENEMIES){const actor=s.entities[e.id],stock=r.rival.loot[e.id];if(!actor||!object(stock)||!Number.isFinite(stock.money)||stock.money<0||stock.money>e.loot.money||Boolean(actor.looted)!==Boolean(r.transactions[`${RIVAL_ID}:loot:${e.id}`]))return false;}
    if((s.inventory.ternCartridge||0)>0||(s.inventory['tern-cartridge']||0)>0||Object.values(s.entities).some(a=>(a.pack?.['tern-cartridge']||a.pack?.ternCartridge||0)>0))return false;
    if(f.carbineGranted&&!m.completed){const w=s.weapons[RIVAL_CARBINE.id],issued=issuedCarbineRounds(s)+RIVAL_ENEMIES.filter(e=>r.transactions[`${RIVAL_ID}:loot:${e.id}`]).reduce((n,e)=>n+(e.loot.cartridges||e.loot.ammunition?.['tern-cartridge']||0),0)+(r.transactions[`${RIVAL_ID}:loot:pavel`]?2:0),spent=r.rival.shots.filter(shot=>shot.weaponId===RIVAL_CARBINE.id).length;if(w.ammo+w.reserve!==issued-spent)return false;}
    if(r.performance.quickCapture!==(f.bound&&r.timers.chase<55)||r.performance.underTime!==(m.completed&&r.timers.elapsed<1320))return false;
  }
  if(s.dialog?.id.startsWith('rival-')&&!s.dialog.id.startsWith('rival-holding-')){if(s.dialog.id==='rival-visit'?!m.completed:s.dialog.id==='rival-argument'?!['unstarted','active'].includes(r.status):!active(s))return false;const allowed=new Set([...QUESTIONING_CHOICES,'leave','intervene','ask-motive','accept-rival','player-first','tomas-first','hold-yard','advance-trees','offer-assurance','threaten','care-levi','deprive-levi','challenge-injuries','narrative-pavel-reply']);if(s.dialog.choices.some(c=>!allowed.has(c.id)))return false;}
  return validateRivalTransport(s)&&validateEquipmentWork(s)&&validateReconWitness(s)&&validateYardOpening(s)&&validateQuestioning(s)&&validateRivalDialog(s)&&validateHolding(s)&&validateWeaponCustody(s)&&validatePhysicalSearchWork(s)&&Narrative.validateRivalNarrative(s);
}
