/** Native train/world terrain queries. Geometry alone grants no mission facts. */
import {EPS,validPoint,localPoint,worldPoint,worldVector,sub,segmentBox} from './rail-foundation/rigid-frame.js';
import {TRAIN_TERRAIN_DATA} from '../content/campaign/train-terrain-data.js';
import {immutableSnapshot} from './rail-foundation/accepted-step-context.js';
import {validateBodySupport} from './rail-foundation/moving-support.js';
import {resolveStepPlatforms,acceptedStepPlatforms} from './rail-foundation/accepted-step-context.js';
import {frameAt} from './rail-foundation/moving-support.js';

/** An instantaneous POINT ray through the exact cover pose at one accepted
 * fraction. No elapsed-time sweep, dt substitution or world mutation. Closed
 * cover boundaries count as contact; a source inside cover remains blocked. */
export function raycastCoverAt(geometry,from,to,{fraction=1,mode='projectile'}={}){
 if(!validPoint(from)||!validPoint(to)||!Number.isFinite(fraction)||fraction<0||fraction>1||!['projectile','body'].includes(mode))throw new TypeError('Invalid instant cover ray');
 const records=resolveStepPlatforms(geometry),hits=[];
 for(const platform of records){if(!platform.cover.some(c=>mode==='body'?c.bodySolid:c.projectileSolid))continue;const frame=frameAt(platform,fraction),a=localPoint(frame,from),b=localPoint(frame,to);
  for(const cover of platform.cover){if(!(mode==='body'?cover.bodySolid:cover.projectileSolid))continue;const rayU=segmentBox(a,b,cover.bounds);if(rayU===null)continue;
   const local={x:a.x+(b.x-a.x)*rayU,y:a.y+(b.y-a.y)*rayU,z:a.z+(b.z-a.z)*rayU},startsInside=['x','y','z'].every(k=>a[k]>cover.bounds.min[k]+EPS&&a[k]<cover.bounds.max[k]-EPS);let normal=null;
   if(!startsInside){let distance=Infinity;for(const k of['x','y','z'])for(const sign of[-1,1]){const d=Math.abs(local[k]-(sign<0?cover.bounds.min[k]:cover.bounds.max[k]));if(d<distance){distance=d;normal={x:0,y:0,z:0,[k]:sign};}}normal=worldVector(frame,normal);}
   hits.push({carId:platform.id,volumeId:cover.id,material:cover.material||null,rayU,motionFraction:fraction,world:worldPoint(frame,local),local,normal,startsInside});
  }
 }
 return hits.sort((a,b)=>a.rayU-b.rayU||a.carId.localeCompare(b.carId)||a.volumeId.localeCompare(b.volumeId))[0]||null;
}

// Static meshes use shared world vertices. Private compiled records never
// become competing actor, inventory, mission or Save authorities.
const TERRAIN_BRAND=new WeakMap(),WORLD_BRAND=new WeakMap();
const P=(x=0,y=0,z=0)=>({x,y,z}),cross2=(a,b,p)=>(b.x-a.x)*(p.y-a.y)-(b.y-a.y)*(p.x-a.x);
const area=p=>{if(!p.length)return 0;const o=p[0];return p.reduce((s,a,i)=>{const b=p[(i+1)%p.length];return s+(a.x-o.x)*(b.y-o.y)-(a.y-o.y)*(b.x-o.x);},0)/2;};
function polygonHasInterior(poly){if(poly.length<3)return false;const a=poly[0],b=poly.reduce((best,p)=>Math.hypot(p.x-a.x,p.y-a.y)>Math.hypot(best.x-a.x,best.y-a.y)?p:best,a),n=Math.hypot(b.x-a.x,b.y-a.y);return n>EPS&&poly.some(p=>Math.abs(cross2(a,b,p))>EPS*n);}
function inside2(p,poly){if(!polygonHasInterior(poly)){return poly.some((a,i)=>{const b=poly[(i+1)%poly.length],dx=b.x-a.x,dy=b.y-a.y,n=dx*dx+dy*dy;if(n<=EPS*EPS)return Math.hypot(p.x-a.x,p.y-a.y)<=EPS;const u=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/n));return Math.hypot(p.x-a.x-dx*u,p.y-a.y-dy*u)<=EPS;});}return poly.every((a,i)=>{const b=poly[(i+1)%poly.length],n=Math.hypot(b.x-a.x,b.y-a.y);return n<=EPS||cross2(a,b,p)>=-EPS*n;});}
function clip2(poly,a,b,inside){const out=[];if(!poly.length)return out;if(Math.hypot(b.x-a.x,b.y-a.y)<=EPS)return poly;const signed=p=>cross2(a,b,p)*(inside?1:-1),limit=EPS*Math.hypot(b.x-a.x,b.y-a.y);let previous=poly.at(-1),pd=signed(previous);for(const current of poly){const cd=signed(current),pi=pd>=-limit,ci=cd>=-limit;if(pi!==ci){const t=pd/(pd-cd);out.push({x:previous.x+(current.x-previous.x)*t,y:previous.y+(current.y-previous.y)*t});}if(ci)out.push(current);previous=current;pd=cd;}const clean=[];for(const p of out)if(!clean.length||Math.hypot(p.x-clean.at(-1).x,p.y-clean.at(-1).y)>EPS)clean.push(p);if(clean.length>1&&Math.hypot(clean[0].x-clean.at(-1).x,clean[0].y-clean.at(-1).y)<=EPS)clean.pop();return clean;}
function localFloorConnected(a,b,x,y,r,step){let overlap=a.xy;for(let i=0;i<b.xy.length&&overlap.length;i++)overlap=clip2(overlap,b.xy[i],b.xy[(i+1)%b.xy.length],true);if(!overlap.length)return false;const height=p=>planeHeight(a.plane,p.x,p.y)-planeHeight(b.plane,p.x,p.y),c=height({x:0,y:0}),gx=height({x:1,y:0})-c,gy=height({x:0,y:1})-c,diff={xy:overlap,plane:{n:P(-gx,-gy,1),d:c}},negative={xy:overlap,plane:{n:P(gx,gy,1),d:-c}},high=maxFloorInDisc(diff,x,y,r),low=maxFloorInDisc(negative,x,y,r);return!!high&&!!low&&high.z>=-step-EPS&&-low.z<=step+EPS;}
function footprintCovered(x,y,r,polygons){if(!r)return polygons.some(p=>inside2({x,y},p));if(polygons.some(poly=>poly.every((a,i)=>{const b=poly[(i+1)%poly.length],n=Math.hypot(b.x-a.x,b.y-a.y);return cross2(a,b,{x,y})>=(r-EPS)*n;})))return true;const count=64,outer=r/Math.cos(Math.PI/count);let remaining=[Array.from({length:count},(_,i)=>({x:x+outer*Math.cos(i*2*Math.PI/count),y:y+outer*Math.sin(i*2*Math.PI/count)}))];for(const cover of polygons){const next=[];for(const original of remaining){let current=original;for(let i=0;i<cover.length&&current.length;i++){const a=cover[i],b=cover[(i+1)%cover.length],outside=clip2(current,a,b,false);if(polygonHasInterior(outside))next.push(outside);current=clip2(current,a,b,true);}}remaining=next;if(!remaining.length)return true;}return false;}
function planeHeight(plane,x,y){return(plane.d-plane.n.x*x-plane.n.y*y)/plane.n.z;}
function maxFloorInDisc(floor,x,y,r){const poly=floor.xy,candidates=[],addCandidate=p=>{if(inside2(p,poly)&&Math.hypot(p.x-x,p.y-y)<=r+EPS)candidates.push({...p,z:planeHeight(floor.plane,p.x,p.y)});};if(inside2({x,y},poly))addCandidate({x,y});const gx=-floor.plane.n.x/floor.plane.n.z,gy=-floor.plane.n.y/floor.plane.n.z,g=Math.hypot(gx,gy);if(r&&g)addCandidate({x:x+r*gx/g,y:y+r*gy/g});
 for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length];addCandidate(a);const dx=b.x-a.x,dy=b.y-a.y,A=dx*dx+dy*dy;if(!A)continue;const t0=-((a.x-x)*dx+(a.y-y)*dy)/A,q={x:a.x+dx*t0,y:a.y+dy*t0},distance=Math.hypot(q.x-x,q.y-y);if(distance>r+EPS)continue;
  // Work in world distances at tangent seams. The raw quadratic discriminant
  // has length^4 units and loses small contacts after translated clipping.
  const span=Math.sqrt(Math.max(0,r*r-distance*distance)/A),parameterTolerance=EPS/Math.sqrt(A);for(const u of[t0-span,t0,t0+span])if(u>=-parameterTolerance&&u<=1+parameterTolerance){const t=Math.max(0,Math.min(1,u));addCandidate({x:a.x+dx*t,y:a.y+dy*t});}
 }return candidates.length?candidates.reduce((a,b)=>a.z>=b.z?a:b):null;
}
function normalize3(v){const n=Math.hypot(v.x,v.y,v.z);if(n<EPS)throw new TypeError('Degenerate terrain face');return{x:v.x/n,y:v.y/n,z:v.z/n};}
function dot3(a,b){return a.x*b.x+a.y*b.y+a.z*b.z;}
function cross3(a,b){return{x:a.y*b.z-a.z*b.y,y:a.z*b.x-a.x*b.z,z:a.x*b.y-a.y*b.x};}
function compileMesh(mesh){if(!mesh||typeof mesh.id!=='string'||!Array.isArray(mesh.vertices)||mesh.vertices.length<6||!mesh.vertices.every(validPoint)||!Array.isArray(mesh.faces)||mesh.faces.length<4||!['bodySolid','projectileSolid'].every(k=>typeof mesh[k]==='boolean'))throw new TypeError('Invalid terrain mesh');const edgeCounts=new Map(),used=new Set();for(const face of mesh.faces){if(!Array.isArray(face))throw new TypeError('Invalid terrain face');for(let i=0;i<face.length;i++){const a=face[i],b=face[(i+1)%face.length],key=Math.min(a,b)+','+Math.max(a,b);edgeCounts.set(key,(edgeCounts.get(key)||0)+1);used.add(a);}}if(used.size!==mesh.vertices.length||[...edgeCounts.values()].some(n=>n!==2))throw new TypeError('Terrain mesh must be a closed solid');const centre=mesh.vertices.reduce((s,p)=>P(s.x+p.x/mesh.vertices.length,s.y+p.y/mesh.vertices.length,s.z+p.z/mesh.vertices.length),P()),planes=mesh.faces.map(face=>{if(!Array.isArray(face)||face.length<3||new Set(face).size!==face.length||!face.every(i=>Number.isInteger(i)&&i>=0&&i<mesh.vertices.length))throw new TypeError('Invalid terrain face');const a=mesh.vertices[face[0]],b=mesh.vertices[face[1]],c=mesh.vertices[face[2]];let n=normalize3(cross3(sub(b,a),sub(c,a))),d=dot3(n,a);if(dot3(n,centre)>d){n=P(-n.x,-n.y,-n.z);d=-d;}if(dot3(n,centre)>=d-EPS||face.some(i=>Math.abs(dot3(n,mesh.vertices[i])-d)>EPS)||mesh.vertices.some(p=>dot3(n,p)>d+EPS))throw new TypeError('Terrain solid must have planar convex faces');return{n,d};}),bounds={min:P(...['x','y','z'].map(k=>Math.min(...mesh.vertices.map(p=>p[k])))),max:P(...['x','y','z'].map(k=>Math.max(...mesh.vertices.map(p=>p[k]))))};let floor=null;if(mesh.walkableFace!==undefined){if(!Number.isInteger(mesh.walkableFace)||!planes[mesh.walkableFace]||planes[mesh.walkableFace].n.z<=EPS)throw new TypeError('Invalid walkable terrain face');let xy=mesh.faces[mesh.walkableFace].map(i=>({x:mesh.vertices[i].x,y:mesh.vertices[i].y}));if(area(xy)<0)xy=xy.reverse();floor={id:mesh.id+':floor',meshId:mesh.id,plane:planes[mesh.walkableFace],xy,bounds,slope:Math.hypot(planes[mesh.walkableFace].n.x,planes[mesh.walkableFace].n.y)/planes[mesh.walkableFace].n.z};}let prism=null;if(planes.every(p=>p.n.z===0||p.n.x===0&&p.n.y===0)){const caps=planes.map((p,i)=>p.n.z>0?i:-1).filter(i=>i>=0);if(caps.length===1){const top=caps[0];let xy=mesh.faces[top].map(i=>({x:mesh.vertices[i].x,y:mesh.vertices[i].y}));if(area(xy)<0)xy=xy.reverse();prism={xy,minZ:bounds.min.z,maxZ:bounds.max.z};}}return{source:mesh,planes,bounds,floor,prism};}
function rayMesh(mesh,from,to,{radius=0,height=0,closed=true}={}){const delta=sub(to,from);let enter=0,leave=1,normal=null,inside=true;for(const plane of mesh.planes){const pad=radius*Math.hypot(plane.n.x,plane.n.y)+height/2*Math.abs(plane.n.z),a=dot3(plane.n,from)-plane.d-pad,b=dot3(plane.n,to)-plane.d-pad;if(a>=-EPS)inside=false;if(!closed&&a>=-EPS&&b>=-EPS)return null;const v=dot3(plane.n,delta);if(Math.abs(v)<EPS){if(a>EPS)return null;continue;}const t=-a/v;if(v<0){if(t>enter){enter=t;normal=plane.n;}}else leave=Math.min(leave,t);if(enter>leave+EPS)return null;}if(leave<-EPS||enter>1+EPS)return null;return{rayU:Math.max(0,Math.min(1,enter)),normal:inside?null:normal,startsInside:inside};}
function queryBounds(a,b,r=0){return{min:P(Math.min(a.x,b.x)-r,Math.min(a.y,b.y)-r,Math.min(a.z,b.z)),max:P(Math.max(a.x,b.x)+r,Math.max(a.y,b.y)+r,Math.max(a.z,b.z))};}
function candidates(compiled,bounds){const found=new Set();for(let cy=Math.floor(bounds.min.y/128);cy<=Math.floor(bounds.max.y/128);cy++)for(let cx=Math.floor(bounds.min.x/128);cx<=Math.floor(bounds.max.x/128);cx++)for(const i of compiled.grid.get(cx+','+cy)||[])found.add(i);return[...found].map(i=>compiled.meshes[i]);}
function terrainInfo(terrain){const c=TERRAIN_BRAND.get(terrain);if(!c)throw new TypeError('A compiled real terrain provider is required');return c;}
export function createTrainTerrain(data=TRAIN_TERRAIN_DATA){const snapshot=immutableSnapshot(data);if(!snapshot||snapshot.schema!==1||snapshot.regionId!=='brass-cutting'||!snapshot.bounds||!validPoint(snapshot.bounds.min)||!validPoint(snapshot.bounds.max)||['x','y','z'].some(k=>snapshot.bounds.max[k]<=snapshot.bounds.min[k])||!Array.isArray(snapshot.meshes)||!snapshot.meshes.length||new Set(snapshot.meshes.map(m=>m?.id)).size!==snapshot.meshes.length)throw new TypeError('Incomplete train terrain');const meshes=immutableSnapshot(snapshot.meshes.map(compileMesh)),grid=new Map();for(let i=0;i<meshes.length;i++){const b=meshes[i].bounds;for(let cy=Math.floor(b.min.y/128);cy<=Math.floor(b.max.y/128);cy++)for(let cx=Math.floor(b.min.x/128);cx<=Math.floor(b.max.x/128);cx++){const key=cx+','+cy;if(!grid.has(key))grid.set(key,[]);grid.get(key).push(i);}}const compiled={data:snapshot,meshes,grid,maxSlope:Math.max(...meshes.map(m=>m.floor?.slope||0))};const terrain=Object.freeze({regionId:snapshot.regionId,bounds:snapshot.bounds,meshes:snapshot.meshes,routes:snapshot.routes,fixedContact:id=>{const p=snapshot.fixedContacts?.[id];if(!validPoint(p))throw new TypeError('Unknown fixed terrain contact');return p;},groundAt:(x,y,r=0,z,step=2)=>{if(!Number.isFinite(z))throw new TypeError('Current feet height is required');return terrainFloorAt(terrain,P(x,y,z),{radius:r,step})?.height??-Infinity;},traceGroundSegment:(from,to,options)=>traceGroundSegment(terrain,from,to,options),sweepBody:(from,to,options)=>sweepTerrainBody(terrain,from,to,options),stepBody:(body,dt,input)=>stepTerrainBody(terrain,body,dt,input),jumpBody:(body,speed)=>jumpTerrainBody(terrain,body,speed)});TERRAIN_BRAND.set(terrain,compiled);return terrain;}
export function terrainFloorAt(terrain,point,{radius=0,step=2,requireFull=true}={}){const c=terrainInfo(terrain);if(!validPoint(point)||![radius,step].every(n=>Number.isFinite(n)&&n>=0))throw new TypeError('Invalid terrain floor query');if(point.x-radius<c.data.bounds.min.x-EPS||point.y-radius<c.data.bounds.min.y-EPS||point.x+radius>c.data.bounds.max.x+EPS||point.y+radius>c.data.bounds.max.y+EPS)return null;const local=candidates(c,queryBounds(point,point,radius)).filter(m=>m.floor).map(m=>({floor:m.floor,hit:maxFloorInDisc(m.floor,point.x,point.y,radius)})).filter(q=>q.hit),selected=local.filter(q=>inside2(point,q.floor.xy)).map(q=>({...q,height:planeHeight(q.floor.plane,point.x,point.y)})).filter(q=>q.height<=point.z+step+EPS).sort((a,b)=>b.height-a.height);
 for(const root of selected){const layer=[root],seen=new Set([root.floor.id]);for(let at=0;at<layer.length;at++)for(const next of local)if(!seen.has(next.floor.id)&&localFloorConnected(layer[at].floor,next.floor,point.x,point.y,radius,step)){seen.add(next.floor.id);layer.push(next);}const fullFootprint=footprintCovered(point.x,point.y,radius,layer.map(q=>q.floor.xy));if(requireFull&&!fullFootprint)continue;return{height:root.height,contact:P(point.x,point.y,root.height),normal:root.floor.plane.n,faceId:root.floor.id,coverIds:layer.map(q=>q.floor.meshId),fullFootprint};}return null;}

function raycastTerrain(terrain,from,to,{mode='projectile',radius=0,height=0,closed=true,ignoreMesh=null}={}){const c=terrainInfo(terrain),hits=[];for(const mesh of candidates(c,queryBounds(from,to,radius))){if(!(mode==='body'?mesh.source.bodySolid:mesh.source.projectileSolid)||ignoreMesh?.(mesh))continue;const hit=rayMesh(mesh,from,to,{radius,height,closed});if(hit)hits.push({...hit,carId:terrain.regionId,volumeId:mesh.source.id,material:mesh.source.material||null,world:P(from.x+(to.x-from.x)*hit.rayU,from.y+(to.y-from.y)*hit.rayU,from.z+(to.z-from.z)*hit.rayU)});}return hits.sort((a,b)=>a.rayU-b.rayU||a.volumeId.localeCompare(b.volumeId))[0]||null;}
export function createWorldQuery(trainGeometry,terrain){const records=acceptedStepPlatforms(trainGeometry),c=terrainInfo(terrain),expected=[...(c.data.trainCarIds||[]),...(c.data.gangwayIds||[])];if(!records?.length||expected.length&&(records.length!==expected.length||expected.some(id=>!records.some(p=>p.id===id))))throw new TypeError('Complete owning train geometry is required');const world=Object.freeze({regionId:'brass-cutting',trainGeometry,terrain,fixedContact:id=>terrain.fixedContact(id)});WORLD_BRAND.set(world,true);return world;}
function worldInfo(world){if(!WORLD_BRAND.has(world))throw new TypeError('Complete compiled world/train query is required');return world;}
export function raycastWorldCoverAt(world,from,to,options={}){worldInfo(world);const train=raycastCoverAt(world.trainGeometry,from,to,options),terrain=raycastTerrain(world.terrain,from,to,options);return!train?terrain:!terrain?train:train.rayU<=terrain.rayU?train:terrain;}
export function actorWorldPoint(actor,world){worldInfo(world);if(!actor||!validPoint(actor)||actor.attachment||!validateBodySupport(actor,world.trainGeometry))throw new TypeError('Invalid current actor world/support point');return P(actor.x,actor.y,actor.z);}
function groundBreaks(c,from,to){const found=candidates(c,queryBounds(from,to)).filter(m=>m.floor).map(m=>m.floor),us=new Set([0,1]),dx=to.x-from.x,dy=to.y-from.y,len2=dx*dx+dy*dy;for(const f of found){const poly=f.xy;for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],ex=b.x-a.x,ey=b.y-a.y,den=dx*ey-dy*ex;if(Math.abs(den)>EPS){const u=((a.x-from.x)*ey-(a.y-from.y)*ex)/den,v=((a.x-from.x)*dy-(a.y-from.y)*dx)/den;if(u>EPS&&u<1-EPS&&v>=-EPS&&v<=1+EPS)us.add(u);}else if(len2&&Math.abs((a.x-from.x)*dy-(a.y-from.y)*dx)<=EPS){for(const p of[a,b]){const u=((p.x-from.x)*dx+(p.y-from.y)*dy)/len2;if(u>EPS&&u<1-EPS)us.add(u);}}}}
 for(let i=0;i<found.length;i++)for(let j=0;j<i;j++){const a=found[i],b=found[j],v0=planeHeight(a.plane,from.x,from.y)-planeHeight(b.plane,from.x,from.y),v1=planeHeight(a.plane,to.x,to.y)-planeHeight(b.plane,to.x,to.y);if(Math.abs(v0-v1)<EPS)continue;const u=v0/(v0-v1),p=P(from.x+dx*u,from.y+dy*u);if(u>EPS&&u<1-EPS&&inside2(p,a.xy)&&inside2(p,b.xy))us.add(u);}return[...us].sort((a,b)=>a-b).filter((u,i,all)=>!i||u-all[i-1]>EPS*EPS);}
export function traceGroundSegment(terrain,from,to,{radius=9,height=53,step=2,maxSpacing=4}={}){const c=terrainInfo(terrain);if(!validPoint(from)||!validPoint(to)||![radius,height,step,maxSpacing].every(n=>Number.isFinite(n)&&n>=0)||maxSpacing<=0||maxSpacing>4)throw new TypeError('Invalid carried-wire ground segment');const distance=Math.hypot(to.x-from.x,to.y-from.y,to.z-from.z),blocked=hit=>({clear:false,groundPoints:[],length3d:0,hit});if(distance<=EPS)return blocked({kind:'zero-ground-segment'});const us=groundBreaks(c,from,to),points=[],point=u=>P(from.x+(to.x-from.x)*u,from.y+(to.y-from.y)*u,from.z+(to.z-from.z)*u),append=p=>{if(!points.length||Math.hypot(p.x-points.at(-1).x,p.y-points.at(-1).y,p.z-points.at(-1).z)>EPS)points.push(p);};
 for(let k=1;k<us.length;k++){const ua=us[k-1],ub=us[k],mid=point((ua+ub)/2),floor=terrainFloorAt(terrain,mid,{radius:0,step});if(!floor)return blocked({kind:'unsupported-ground',point:mid});const mesh=c.meshes.find(m=>m.floor?.id===floor.faceId),a=point(ua),b=point(ub);a.z=planeHeight(mesh.floor.plane,a.x,a.y);b.z=planeHeight(mesh.floor.plane,b.x,b.y);if(k===1&&Math.abs(a.z-from.z)>EPS)return blocked({kind:'unsupported-ground-endpoint',point:from});if(points.length&&Math.abs(a.z-points.at(-1).z)>step+EPS)return blocked({kind:'ground-cliff',point:a});append(a);const n=Math.max(1,Math.ceil(Math.hypot(b.x-a.x,b.y-a.y,b.z-a.z)/(maxSpacing*(1-1e-10))));for(let i=1;i<=n;i++){const u=i/n,p=P(a.x+(b.x-a.x)*u,a.y+(b.y-a.y)*u,a.z+(b.z-a.z)*u);if(!terrainFloorAt(terrain,P(p.x,p.y,p.z+step),{radius,step}))return blocked({kind:'unsupported-full-footprint',point:p});append(p);}}
 if(!points.length||Math.abs(points[0].z-from.z)>EPS||Math.abs(points.at(-1).z-to.z)>EPS)return blocked({kind:'unsupported-ground-endpoint'});let total=0;for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],fa=terrainFloorAt(terrain,a,{radius,step}),fb=terrainFloorAt(terrain,b,{radius,step}),stepFloor={coverIds:[...new Set([...(fa?.coverIds||[]),...(fb?.coverIds||[])])]},hit=bodySweepInternal(terrain,a,b,{r:radius,height},stepFloor);if(hit)return blocked(hit);total+=Math.hypot(points[i].x-points[i-1].x,points[i].y-points[i-1].y,points[i].z-points[i-1].z);}points[0]=P(from.x,from.y,from.z);points[points.length-1]=P(to.x,to.y,to.z);return{clear:true,groundPoints:points,length3d:total,hit:null};}

/** Finite vertical native-body sweep against the actual static convex solids.
 * A true outgoing contact on a walkable top may depart its own floor; ceilings
 * and unrelated faces are never discarded. This query does not move a body. */
export function sweepTerrainBody(terrain,from,to,{radius=9,height=53}={}){if(!validPoint(from)||!validPoint(to)||![radius,height].every(n=>Number.isFinite(n)&&n>=0))throw new TypeError('Invalid terrain body sweep');return bodySweepInternal(terrain,from,to,{r:radius,height},null,null,false);}

const GROUND_RECEIPTS=new WeakMap();
function bodySettings(body){const values={r:body.r??9,height:body.height??53,gravity:body.gravity??700,step:body.step??2,friction:body.friction??0,bounce:body.bounce??0};if(!validPoint(body)||!Object.values(values).every(Number.isFinite)||values.r<0||values.height<0||values.gravity<0||values.step<0||body.attachment||body.support!==undefined&&body.support!==null||body.supports!==undefined||body.mounted)throw new TypeError('A free native terrain body is required');return values;}
function nativeView(body,settings){return new Proxy(body,{get:(target,key)=>target[key]===undefined&&Object.hasOwn(settings,key)?settings[key]:Reflect.get(target,key),set:(target,key,value)=>Reflect.set(target,key,value)});}
/** A downward centre-foot crossing of an actual walkable face. The complete
 * native footprint must be covered by its physically connected floor union. */
export function sweepTerrainLanding(terrain,from,to,{radius=9,ignoreInitialFloorIds=[]}={}){
 const c=terrainInfo(terrain);if(!validPoint(from)||!validPoint(to)||!Number.isFinite(radius)||radius<0||!Array.isArray(ignoreInitialFloorIds))throw new TypeError('Invalid terrain foot sweep');const hits=[];
 for(const mesh of candidates(c,queryBounds(from,to,radius))){if(!mesh.floor)continue;const plane=mesh.floor.plane,a=from.z-planeHeight(plane,from.x,from.y),b=to.z-planeHeight(plane,to.x,to.y);if(a<-EPS||b>EPS||b>=a-EPS)continue;const u=Math.max(0,Math.min(1,a/(a-b)));if(u<1e-6&&ignoreInitialFloorIds.includes(mesh.source.id))continue;
  const point=P(from.x+(to.x-from.x)*u,from.y+(to.y-from.y)*u,0);point.z=planeHeight(plane,point.x,point.y);const floor=terrainFloorAt(terrain,point,{radius,step:EPS*2});if(!floor||Math.abs(floor.height-point.z)>EPS*4||!floor.coverIds.includes(mesh.source.id))continue;
  hits.push({kind:'landing',carId:terrain.regionId,volumeId:mesh.source.id,faceId:mesh.floor.id,u,world:point,normal:plane.n,fullFootprint:true,floor});
 }return hits.sort((a,b)=>a.u-b.u||a.volumeId.localeCompare(b.volumeId))[0]||null;
}
function resolvedBodyHit(mesh,hit,from,to,settings){const centre=P(from.x+(to.x-from.x)*hit.rayU,from.y+(to.y-from.y)*hit.rayU,from.z+(to.z-from.z)*hit.rayU);let normal=hit.normal,depth=0;if(!normal){let closest=-Infinity;for(const p of mesh.planes){const pad=settings.r*Math.hypot(p.n.x,p.n.y)+settings.height/2*Math.abs(p.n.z),d=dot3(p.n,centre)-p.d-pad;if(d>closest){closest=d;normal=p.n;}}depth=Math.max(0,-closest);}return{...hit,carId:'brass-cutting',volumeId:mesh.source.id,material:mesh.source.material||null,normal,depth,u:hit.rayU,world:P(centre.x,centre.y,centre.z-settings.height/2)};}
function footOwnsTerrainTop(terrain,mesh,hit,from,to,settings,landing){if(!mesh.floor||dot3(hit.normal,mesh.floor.plane.n)<1-EPS)return false;const plane=mesh.floor.plane,z=point=>point.z-planeHeight(plane,point.x,point.y);if(z(from)<-EPS||z(hit.world)<-EPS)return false;const floor=terrainFloorAt(terrain,hit.world,{radius:settings.r,step:EPS*2});if(!floor||!floor.coverIds.includes(mesh.source.id))return false;
 // A cylinder toe can reach an inclined floor before its centre-foot plane.
 // Defer only this declared upward top; support still needs a real crossing.
 return landing?.floor.coverIds.includes(mesh.source.id)||z(to)>=-EPS;
}
function circlePolygonState(poly,point,radius){let nearest=null,distance=Infinity;for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],dx=b.x-a.x,dy=b.y-a.y,n=dx*dx+dy*dy;if(n<=EPS*EPS)continue;const u=Math.max(0,Math.min(1,((point.x-a.x)*dx+(point.y-a.y)*dy)/n)),q={x:a.x+dx*u,y:a.y+dy*u},d=Math.hypot(point.x-q.x,point.y-q.y);if(d<distance){distance=d;const len=Math.sqrt(n);nearest={q,outward:P(dy/len,-dx/len,0)};}}
 const inside=inside2(point,poly),normal=inside?nearest.outward:distance>EPS?P((point.x-nearest.q.x)/distance,(point.y-nearest.q.y)/distance,0):nearest.outward;return{overlap:inside||distance<=radius+EPS,inside,normal,depth:inside?radius+distance:Math.max(0,radius-distance)};
}
/** Exact translating vertical cylinder versus a single-cap vertical prism.
 * Edge strips and vertex circles retain the actual circular footprint; this
 * removes only the conservative halfspace outset's artificial sharp corners. */
function sweepVerticalPrism(mesh,from,to,settings){const prism=mesh.prism,poly=prism.xy,r=settings.r,dx=to.x-from.x,dy=to.y-from.y,dz=to.z-from.z,A=dx*dx+dy*dy,at=u=>P(from.x+dx*u,from.y+dy*u,from.z+dz*u),us=[];
 const initial=circlePolygonState(poly,from,r),final=circlePolygonState(poly,to,r);if(initial.overlap)us.push(0);if(final.overlap)us.push(1);
 for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],ex=b.x-a.x,ey=b.y-a.y,n=Math.hypot(ex,ey);if(n<=EPS)continue;const nx=ey/n,ny=-ex/n,v=nx*dx+ny*dy;if(Math.abs(v)>EPS){const u=(r-nx*(from.x-a.x)-ny*(from.y-a.y))/v;if(u>=0&&u<=1){const p=at(u),projection=((p.x-a.x)*ex+(p.y-a.y)*ey)/(n*n);if(projection>=-EPS/n&&projection<=1+EPS/n&&circlePolygonState(poly,p,r).overlap)us.push(u);}}
  if(A){const fx=from.x-a.x,fy=from.y-a.y,B=2*(fx*dx+fy*dy),C=fx*fx+fy*fy-r*r,disc=B*B-4*A*C;if(disc>=-EPS*A*Math.max(1,r)*8){const root=Math.sqrt(Math.max(0,disc));for(const u of[(-B-root)/(2*A),(-B+root)/(2*A)])if(u>=0&&u<=1&&circlePolygonState(poly,at(u),r).overlap)us.push(u);}}
 }
 if(!us.length)return null;const xyLo=Math.min(...us),xyHi=Math.max(...us),zMin=prism.minZ-settings.height,zMax=prism.maxZ;let zLo=0,zHi=1,zNormal=null;
 if(Math.abs(dz)<=EPS){if(from.z<=zMin+EPS||from.z>=zMax-EPS)return null;}else{let a=(zMin-from.z)/dz,b=(zMax-from.z)/dz;if(a>b){[a,b]=[b,a];zNormal=P(0,0,1);}else zNormal=P(0,0,-1);zLo=Math.max(0,a);zHi=Math.min(1,b);}
 const u=Math.max(xyLo,zLo);if(u>Math.min(xyHi,zHi)+EPS||u>1||zHi<0)return null;const world=at(u),state=circlePolygonState(poly,world,r);if(state.depth<=EPS&&initial.depth<=EPS&&final.depth<=EPS&&dot3(state.normal,P(dx,dy,0))>=-EPS)return null;const inside=initial.depth>EPS&&from.z>zMin+EPS&&from.z<zMax-EPS;let normal=zLo>xyLo+EPS?zNormal:state.normal,depth=0;
 if(inside){normal=initial.normal;depth=initial.depth;for(const [d,n]of[[zMax-from.z,P(0,0,1)],[from.z-zMin,P(0,0,-1)]])if(d<depth){depth=d;normal=n;}}
 if(!inside&&dot3(normal,P(dx,dy,dz))>=-EPS)return null;
 return{rayU:u,u,normal,depth,startsInside:inside,carId:'brass-cutting',volumeId:mesh.source.id,material:mesh.source.material||null,world};
}
function bodySweepInternal(terrain,from,to,settings,stepFloor=null,landing=null,deferFeet=true){const c=terrainInfo(terrain),delta=sub(to,from),height=settings.height,a=P(from.x,from.y,from.z+height/2),b=P(to.x,to.y,to.z+height/2),hits=[];
 for(const mesh of candidates(c,queryBounds(a,b,settings.r))){if(!mesh.source.bodySolid||mesh.bounds.max.z<=Math.min(from.z,to.z)+EPS||mesh.bounds.min.z>=Math.max(from.z,to.z)+height-EPS)continue;
  if(mesh.floor&&stepFloor?.coverIds.includes(mesh.source.id))continue;
  const raw=rayMesh(mesh,a,b,{radius:settings.r,height,closed:false});if(!raw)continue;const hit=mesh.prism?sweepVerticalPrism(mesh,from,to,settings):resolvedBodyHit(mesh,raw,a,b,settings);if(!hit)continue;
  if(mesh.floor&&dot3(hit.normal,mesh.floor.plane.n)>1-EPS&&from.z>=planeHeight(mesh.floor.plane,from.x,from.y)-EPS&&inside2(from,mesh.floor.xy)&&dot3(mesh.floor.plane.n,delta)>EPS)continue;
  if(deferFeet&&footOwnsTerrainTop(terrain,mesh,hit,from,to,settings,landing))continue;hits.push(hit);
 }return hits.sort((a,b)=>a.u-b.u||a.volumeId.localeCompare(b.volumeId))[0]||null;
}
/** Static terrain controller uses the supplied native Body integration. A real
 * floor query permits only native steps; finite solid sweeps then resolve wall,
 * floor and ceiling contact. It does not integrate an attached train body. */
export function stepTerrainBody(terrain,body,dt,{vx=body.vx??0,vy=body.vy??0}={}){
 terrainInfo(terrain);const settings=bodySettings(body);if(!Number.isFinite(dt)||dt<0||dt>.1+EPS||![vx,vy,body.vz??0].every(Number.isFinite))throw new TypeError('Invalid terrain fixed step');if(!dt)return{kind:'paused',hits:[],trajectory:[]};const native=globalThis.My3D2dge?.Body?.prototype?.update;if(!native)throw new Error('Native engine must be loaded');const original=P(body.x,body.y,body.z),hits=[],trajectory=[];let elapsed=0;body.vx=vx;body.vy=vy;body.vz??=0;body.hitCeiling=false;
 while(elapsed<dt-EPS*EPS){
  const h=Math.min(1/120,dt-elapsed),before=P(body.x,body.y,body.z),oldFloor=terrainFloorAt(terrain,before,{radius:settings.r,step:settings.step}),wasGrounded=body.onGround===true&&oldFloor&&Math.abs(before.z-oldFloor.height)<=EPS*8;if(body.onGround&&!wasGrounded)body.onGround=false;
  const target=P(before.x+body.vx*h,before.y+body.vy*h,before.z),floor=wasGrounded?terrainFloorAt(terrain,target,{radius:settings.r,step:settings.step}):null;let stepFloor=floor&&floor.height<=before.z+settings.step+EPS?{...floor,coverIds:[...new Set([...oldFloor.coverIds,...floor.coverIds])]}:null;
  const map={collide(){return false;},groundAt(x,y,r,z,step){if(!wasGrounded)return-1000000;return terrainFloorAt(terrain,P(x,y,before.z),{radius:r,step})?.height??-1000000;}};
  native.call(nativeView(body,settings),h,map);let current=P(body.x,body.y,body.z),from=before,remaining=h,phaseStart=elapsed/dt,grounded=wasGrounded&&body.onGround,ignoreInitialFloorIds=wasGrounded&&!grounded?oldFloor.coverIds:[];let contactCount=0;
  while(remaining>EPS*EPS){
   const landing=grounded?null:sweepTerrainLanding(terrain,from,current,{radius:settings.r,ignoreInitialFloorIds}),hit=bodySweepInternal(terrain,from,current,settings,grounded?stepFloor:null,landing);
   if(!hit&&!landing){trajectory.push({from,to:current,dt:remaining,phaseFrom:phaseStart,phaseTo:(elapsed+h)/dt});break;}
   if(++contactCount>32)throw new RangeError('Terrain collision sequence needs a smaller fixed step');
   const landed=landing&&(!hit||landing.u<=hit.u+EPS),contactHit=landed?landing:hit,u=contactHit.u,contact=landed?contactHit.world:addPoint(hit.world,scalePoint(hit.normal,hit.depth+EPS)),consumed=remaining*u;hits.push(contactHit);trajectory.push({from,to:contact,dt:consumed,phaseFrom:phaseStart,phaseTo:phaseStart+consumed/dt});Object.assign(body,contact);remaining-=consumed;phaseStart+=consumed/dt;
   if(landed){body.onGround=true;body.landed=true;body.vz=0;body.groundZ=landing.floor.height;grounded=true;stepFloor=landing.floor;}
   else{const velocity=P(body.vx,body.vy,body.vz),incoming=dot3(velocity,hit.normal);if(incoming<0){const resolved=sub(velocity,scalePoint(hit.normal,incoming));body.vx=resolved.x;body.vy=resolved.y;body.vz=resolved.z;}body.hitWall=true;if(hit.normal.z<-.5)body.hitCeiling=true;
    const contactFloor=grounded?terrainFloorAt(terrain,contact,{radius:settings.r,step:EPS}):null;grounded=!!contactFloor&&Math.abs(contactFloor.height-contact.z)<=EPS*8;body.onGround=grounded;if(grounded){stepFloor=contactFloor;body.vz=0;body.groundZ=contactFloor.height;}
   }
   from=P(body.x,body.y,body.z);current=P(from.x+body.vx*remaining,from.y+body.vy*remaining,from.z+body.vz*remaining);ignoreInitialFloorIds=[];
   if(grounded){const nextFloor=terrainFloorAt(terrain,P(current.x,current.y,from.z),{radius:settings.r,step:settings.step});if(nextFloor){current.z=nextFloor.height;stepFloor={...nextFloor,coverIds:[...new Set([...stepFloor.coverIds,...nextFloor.coverIds])]};}else{ignoreInitialFloorIds=stepFloor.coverIds;grounded=false;body.onGround=false;body.vz=-settings.gravity*remaining;current.z=from.z+body.vz*remaining;stepFloor=null;}}
  }
  Object.assign(body,current);const finalFloor=terrainFloorAt(terrain,current,{radius:settings.r,step:EPS});if(body.onGround&&(!finalFloor||Math.abs(current.z-finalFloor.height)>EPS*8))body.onGround=false;if(body.onGround){body.groundZ=finalFloor.height;body.vz=0;}elapsed+=h;
 }
 const after=P(body.x,body.y,body.z),observedVelocity=P((after.x-original.x)/dt,(after.y-original.y)/dt,(after.z-original.z)/dt),groundVelocity=P(body.vx,body.vy,0),speedXY=Math.hypot(groundVelocity.x,groundVelocity.y);if(body.onGround&&speedXY){const h=1e-5,p=P(after.x+groundVelocity.x*h,after.y+groundVelocity.y*h,after.z),nextFloor=terrainFloorAt(terrain,p,{radius:settings.r,step:settings.step}),limit=terrainInfo(terrain).maxSlope*speedXY*h+EPS;if(nextFloor&&Math.abs(nextFloor.height-after.z)<=limit)groundVelocity.z=(nextFloor.height-after.z)/h;}const receipt={kind:body.onGround?'ground':'air',dt,from:original,to:after,groundVelocity,observedVelocity,hits,trajectory};if(body.onGround)GROUND_RECEIPTS.set(body,{terrain,position:P(after.x,after.y,after.z),velocity:P(groundVelocity.x,groundVelocity.y,groundVelocity.z)});else GROUND_RECEIPTS.delete(body);return receipt;
}
function addPoint(a,b){return P(a.x+b.x,a.y+b.y,a.z+b.z);}
function scalePoint(a,n){return P(a.x*n,a.y*n,a.z*n);}
/** A grounded jump inherits the actual last accepted ground velocity. Restored
 * bodies must settle through an accepted step first; no past movement inferred. */
export function jumpTerrainBody(terrain,body,speed=220){terrainInfo(terrain);bodySettings(body);const receipt=GROUND_RECEIPTS.get(body),floor=terrainFloorAt(terrain,body,{radius:body.r??9,step:EPS});if(!Number.isFinite(speed)||speed<=0||body.hp<=0||body.onGround!==true||!receipt||receipt.terrain!==terrain||!floor||Math.abs(body.z-floor.height)>EPS*8||Math.hypot(body.x-receipt.position.x,body.y-receipt.position.y,body.z-receipt.position.z)>EPS)return false;const native=globalThis.My3D2dge?.Body?.prototype?.jump;if(!native)throw new Error('Native engine must be loaded');if(!native.call(body,speed))return false;body.vx=receipt.velocity.x;body.vy=receipt.velocity.y;body.vz=speed+receipt.velocity.z;GROUND_RECEIPTS.delete(body);return true;}
